### ISSUE TITLE
feat(app): link external markdown in the main one

### ISSUE THREAD

**Issue by daniele-zurico** [compodoc/compodoc#10]
I've the following structure in my code:

- README.md
```
src
  component
     component.html
     compontent.ts
     component.scss
    component.spec
    README.md
```
Now I would to point the attention on the README inside the subfolder. It explain exactly what the component does and all the properties that it use. There's any way to display it as well?

I know that is not easy but could be a workaround if I link them in the main readme.md?
Open for suggestions

**Comment by vogloblinsky** [comment]
It is in my roadmap : supply a folder of README.md files, and get them in html in a special entry in the left menu.
Your use-case is interesting. Instead of having all the md files in the same folder, they are dispatched.
I will try to provide a solution for both scenarios.
Stay tuned.

**Comment by daniele-zurico** [comment]
I think honestly that is more organised to have readme file in each folder because the people that are not interested in the doc but they want just to look on the module easily find it. Is almost the same rule that angular-cli use for a module: everything is in the same place and they are not organised by type (as was the old angular1 structure: directives, views, etc), so why not do the same for the readme file?
Hope that it make sense

**Comment by vogloblinsky** [comment]
Yep, i am 100% ok with that.
My starting idea was the scenario of a global documentation for one application, more oriented "use-cases" than "code" with components etc...

**Comment by daniele-zurico** [comment]
If you don't have time to implement it( is not you first priority) but you've some input on that I can try to help on that one otherwise I've to do something like that in my doc that is not amazing:
```
 * For more information have a look at the [readme](https://,,,,){:target="_blank"}
```

**Comment by vogloblinsky** [comment]
I am working on it.
I will implement 2 things :
- scan for README.md in each component folder, and display it in a seperate tab in the doc ( in the right side)
- use external markdown files inside a folder
I will update the todomvc-ng2 demo project after.
