### ISSUE TITLE
[BUG] : Problem using JSDoc light support - @param & @example

### ISSUE THREAD

**Issue by shiloDrot** [compodoc/compodoc#100]
##### **Overview of the issue**

I can't generate JSDoc light support tags.
I used the command compodoc -p ./src/my-project/tsconfig.json & compodoc -s

this is the source file: 
![image](https://cloud.githubusercontent.com/assets/9968573/22638427/a565ae4e-ec50-11e6-9dbb-783887a168c3.png)

this is what compodoc generated:
![image](https://cloud.githubusercontent.com/assets/9968573/22638402/8db8e2ca-ec50-11e6-8fea-0fe43b1c925a.png)

can you help me?

**Comment by vogloblinsky** [comment]
JSDoc tags for decorator comment are not supported. I will add that in next release.

**Comment by shiloDrot** [comment]
Hey, i saw you fix the example tag, but param tag is still not working :-(
Are you going to fix this?

**Comment by vogloblinsky** [comment]
It is still present with 0.0.41 ?
Do you have an example for debugging please ?
