### ISSUE TITLE
[BUG] Compodoc/Storybook. Errors during the launch of "npm run storybook"

### ISSUE THREAD

**Issue by giuliacontento** [compodoc/compodoc#1007]
Hi all,
I'm trying to install Storybook in my Angular project. 
The installation goes well but when I type "npm run storybook" the code generates these errors:

<img width="1263" alt="Screenshot 2020-11-16 at 18 56 09" src="https://user-images.githubusercontent.com/43807591/99370462-fe946480-28bd-11eb-8804-0cf4dc2cb51d.png">

I don't understand what is the real problem. I have tried a lot of changes but none seem to work.
Can someone help me?

Thanks in advance :)

**Comment by wolanskiadrian** [comment]
Having the same issue.

**Comment by Alfr3d** [comment]
Mee too. I try to generate documentation with external tsconfig.compodoc.json in project root with this command:
`npx compodoc -p ./tsconfig.compodoc.json -e json -d .`
but the file documentation.json was empty.

I use the latest version of storybookjs (v.6.0) and angularcore > 9.

**Comment by giuliacontento** [comment]
Hi all,
I finally have resolved the problems.
Premise: I was working with Angular 8.2.14, Angular CLI 8.3.29, compodoc 1.1.11, Typescript 3.5.e and Sass-loader 8.0.0.

First of all make sure that these two lines of code are present in package.json:

   "storybook": "npm run docs:json && start-storybook -p 6006",
   "build-storybook": "npm run docs:json && build-storybook"

If they aren't, it means that the installation of storybook was probably not successful.

Then I have created the file sconfig.compodoc.json by hand, putting this code in it:
   {​​​​​​​​
      "extends": "./tsconfig.json",
      "include": ["./apps/**/*.ts", "./libs/**/*.ts"],
      "exclude": ["**/*.spec.ts"]
   }​​​​​​​​

After some research I found that my version of Angular CLI didn't work with the version that I used of sass-loader, so I had to downgrade sass-loader to version 7.3.1 and it works!

If it still doesn't work, try to check that in the .storybook/main.js there are no webpack specifications that block the launch of the project in storybook.

That's it! Good luck ;)

**Comment by gcherem** [comment]
In my case (using angular 11 and vscode), problem was due the default configuration: **sb init** puts the following command in the package.json:

`"docs:json": "compodoc -p ./tsconfig.json -e json -d .",`

This make storybook to scan from the root directory, that includes ./history folder that vscode puts there and probably breaking in any corrupted file. Just replaced by

`"docs:json": "compodoc -p tsconfig.json src -e json -d .",`

making storybook scan from **src** directory instead and it fixed the problem.
