### ISSUE TITLE
[BUG] Problem trying to exclude part of the project from documentation generation

### ISSUE THREAD

**Issue by shoogsteyn** [compodoc/compodoc#102]
Hi, first of all thanks for your work. To this day compodoc's the best tool to document angular2 project !

**Overview of the issue**

The issue I have is that my project is quite massive and I would like to exclude some module from the documentation. In order to do that I have create a tsconfig.json speficique for documentation generation. In the file I exclude the module that should not be documented at the time.

_compodoc -p tsconfig.doc.json_

**In the tsconfig.doc.json :** 

"exclude": [
    "src/app/exampleModule",
  ]

I have try exclude the directory, only the exampleModule.module.ts, event a file in particular, nothing seems to work.

Is there another way to exclude module/file from documentation generation ? 
 
Thanks

**Comment by vogloblinsky** [comment]
The exclude method with tsconfig is a good one. 
Just made a test, it is the excluding stuff of Compodoc which doesn' t works well.
I will fix soon, coming in next release this week.
