### ISSUE TITLE
[BUG] Nothing rendered apart index and readme

### ISSUE THREAD

**Issue by DanielFran** [compodoc/compodoc#1024]
##### **Overview of the issue**

No issue raised during the generation of the documentation, only index and readme are generated

##### **JHipster Version(s)**

```
supportivecare@1.5.0-SNAPSHOT C:\workspace\support_care
+-- generator-jhipster@7.0.0-beta.1
`-- generator-jhipster-entity-audit@3.3.0
  `-- generator-jhipster@6.10.5

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folde
r**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "caffeine",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "withAdminUi": false,
    "baseName": "supportivecare",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "custom",
    "languages": ["pt-pt", "en"],
    "messageBroker": false,
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["cypress"],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "uc.dei.mse.supportivecare",
    "packageFolder": "uc/dei/mse/supportivecare",
    "clientPackageManager": "npm",
    "nativeLanguage": "pt-pt",
    "jhipsterVersion": "7.0.0-beta.1",
    "skipServer": false,
    "dtoSuffix": "DTO",
    "entitySuffix": "",
    "reactive": false,
    "clientTheme": "none",
    "clientThemeVariant": "",
    "entities": [
      "Administration",
      "Notice",
      "ActiveSubstance",
      "Treatment",
      "TherapeuticRegime",
      "Document",
      "Content",
      "Outcome",
      "ToxicityRate",
      "Symptom",
      "Thumb",
      "Feedback"
    ],
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "blueprints": [],
    "otherModules": [],
    "pages": [],
    "creationTimestamp": 1608470745965,
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipst
erInfoCommandForObviousSecurityReasons",
    "lastLiquibaseTimestamp": 1611596955000,
    "herokuAppName": "supportivecare",
    "herokuDeployType": "jar",
    "herokuJavaVersion": "11"
  },
  "generator-jhipster-entity-audit": {
    "auditFramework": "custom",
    "auditPage": false,
    "lastLiquibaseTimestamp": 1608471465000
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in
 the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * Administração.
 */
entity Administration {
  /**
   * Tipo de administração.
   */
  type String required maxlength(100)
}
/**
 * Observação.
 */
entity Notice {
  /**
   * Descrição.
   */
  description String required maxlength(1000)
  /**
   * Avaliação.
   */
  evaluation String required maxlength(1000)
  /**
   * Intervenção interdependente.
   */
  intervention String required maxlength(1000)
}
/**
 * Substância Ativa (ou DCI: Denominação Comum Internacional).
 */
entity ActiveSubstance {
  /**
   * Nome.
   */
  name String required maxlength(255)
  /**
   * Dosagem.
   */
  dosage String required maxlength(30)
  /**
   * Forma Farmacêutica.
   */
  form String required maxlength(255)
  /**
   * Descrição geral.
   */
  description String maxlength(1000)
}
/**
 * Tratamento.
 */
entity Treatment {
  /**
   * Tipo de tratamento.
   */
  type String required maxlength(100)
}
/**
 * Regime Terapêutico.
 */
entity TherapeuticRegime {
  /**
   * Nome.
   */
  name String required maxlength(255)
  /**
   * Acrônimo.
   */
  acronym String maxlength(50)
  /**
   * Propósito.
   */
  purpose String required maxlength(1000)
  /**
   * Condições para administração.
   */
  condition String required maxlength(1000)
  /**
   * Calendarização.
   */
  timing String maxlength(255)
  /**
   * Indicação para prescrição.
   */
  indication String required maxlength(1000)
  /**
   * Critérios de redução de dose.
   */
  criteria String required maxlength(1000)
  /**
   * Outras informações.
   */
  notice String maxlength(1000)
}
/**
 * Documento.
 */
entity Document {
  /**
   * Título.
   */
  title String required maxlength(255)
  /**
   * Tamanho.
   */
  size Long required
  /**
   * Tipo de ficheiro.
   */
  mimeType String maxlength(50)
}
/**
 * Conteúdo.
 */
entity Content {
  /**
   * Dados.
   */
  data AnyBlob required
}
/**
 * PROM.
 */
entity Outcome {
  /**
   * Nome.
   */
  name String required maxlength(255)
  /**
   * Descrição.
   */
  description String maxlength(1000)
  /**
   * Link.
   */
  link String maxlength(1000)
}
/**
 * Grau de Toxicidade.
 */
entity ToxicityRate {
  /**
   * Nome.
   */
  name String required maxlength(255)
  /**
   * Descrição.
   */
  description String maxlength(1000)
  /**
   * Informação ao doente.
   */
  notice String maxlength(1000)
  /**
   * Intervenção autónoma.
   */
  autonomousIntervention String maxlength(1000)
  /**
   * Intervenção interdependente.
   */
  interdependentIntervention String maxlength(1000)
  /**
   * Suporte para auto-gestão.
   */
  selfManagement String maxlength(1000)
}
/**
 * Sintoma (Efeito secundário).
 */
entity Symptom {
  /**
   * Nome.
   */
  name String required maxlength(255)
  /**
   * Informação ao enfermeiro.
   */
  notice String maxlength(1000)
}
/**
 * Thumb.
 */
entity Thumb {
  /**
   * Tipo da entidade.
   */
  entityType EntityFeedback required
  /**
   * Id da entidade.
   */
  entityId Long required
  /**
   * Polegar.
   */
  thumb Boolean required
}
/**
 * Feedback.
 */
entity Feedback {
  /**
   * Tipo da entidade.
   */
  entityType EntityFeedback required
  /**
   * Id da entidade.
   */
  entityId Long required
  /**
   * Nome da entidade.
   */
  entityName String maxlength(255)
  /**
   * Razão.
   */
  reason String maxlength(1000)
  /**
   * Resolvido.
   */
  solved Boolean required
  /**
   * Anónimo.
   */
  anonym Boolean required
}
enum EntityFeedback {
  ACTIVE_SUBSTANCE (active-substance),
  THERAPEUTIC_REGIME (therapeutic-regime),
  OUTCOME (outcome),
  SYMPTOM (symptom)
}

relationship OneToOne {
  Document{content} to Content{document required}
}
relationship OneToMany {
  ActiveSubstance{notice(description)} to Notice{activeSubstance(name) required}
  Administration{activeSubstance} to ActiveSubstance{administration(type)}
  Treatment{therapeuticRegime} to TherapeuticRegime{treatment(type) required}
  Outcome{document} to Document{outcome(name) required}
  Symptom{toxicityRate(name)} to ToxicityRate{symptom(name)}
}
relationship ManyToMany {
  TherapeuticRegime{activeSubstance(name)} to ActiveSubstance{therapeuticRegime(
name)}
  Symptom{therapeuticRegime(name)} to TherapeuticRegime{symptom(name)}
  Symptom{outcome(name)} to Outcome{symptom(name)}
}

dto Administration, Notice, ActiveSubstance, Treatment, TherapeuticRegime, Docum
ent, Content, Outcome, ToxicityRate, Symptom, Thumb, Feedback with mapstruct
paginate Administration, Notice, ActiveSubstance, Treatment, TherapeuticRegime,
Document, Content, Outcome, ToxicityRate, Symptom, Thumb, Feedback with infinite
-scroll
service Administration, Notice, ActiveSubstance, Treatment, TherapeuticRegime, D
ocument, Content, Outcome, ToxicityRate, Symptom, Thumb, Feedback with serviceCl
ass
filter Administration, Notice, ActiveSubstance, Treatment, TherapeuticRegime, Do
cument, Content, Outcome, ToxicityRate, Symptom, Thumb, Feedback

</pre>
</details>

##### **Environment and Tools**

java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

git version 2.24.1.windows.2

node: v14.15.4

npm: 6.14.11

yeoman: 3.1.1

Docker version 20.10.2, build 2291f61

docker-compose version 1.27.4, build 40524192

INFO! Congratulations, JHipster execution is complete!

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "supportivecare",
  "version": "1.5.0-SNAPSHOT",
  "private": true,
  "description": "Description for supportivecare",
  "license": "UNLICENSED",
  "scripts": {
    "backend:doc:test": "./mvnw -ntp javadoc:javadoc --batch-mode",
    "backend:info": "./mvnw -ntp enforcer:display-info --batch-mode",
    "backend:nohttp:test": "./mvnw -ntp checkstyle:check --batch-mode",
    "backend:unit:test": "./mvnw -ntp -P-webpack verify --batch-mode -Dlogging.level.ROOT=OFF -Dlogging.level.org.zalando=OFF -Dlogging.level.tech.jhipster=OFF -Dlogging.level.uc.dei.mse.supportivecare=OFF -Dlogging.level.org.springframework=OFF -Dlogging.level.org.springframework.web=OFF -Dlogging.level.org.springframework.security=OFF",
    "build": "npm run webpack:prod",
    "ci:backend:test": "npm run backend:info && npm run backend:doc:test && npm run backend:nohttp:test && npm run backend:unit:test",
    "ci:e2e:package": "npm run java:$npm_package_config_packaging:$npm_package_config_default_environment -- -Pe2e -Denforcer.skip=true",
    "ci:e2e:prepare": "npm run ci:e2e:prepare:docker",
    "ci:e2e:prepare:docker": "npm run docker:db:up && npm run docker:others:up && docker ps -a",
    "ci:e2e:run": "concurrently -k -s first \"npm run ci:e2e:server:start\" \"npm run e2e:headless\"",
    "preci:e2e:server:start": "npm run docker:db:await --if-present && npm run docker:others:await --if-present",
    "ci:e2e:server:start": "java -jar target/e2e.$npm_package_config_packaging --spring.profiles.active=$npm_package_config_default_environment -Dlogging.level.ROOT=OFF -Dlogging.level.org.zalando=OFF -Dlogging.level.tech.jhipster=OFF -Dlogging.level.uc.dei.mse.supportivecare=OFF -Dlogging.level.org.springframework=OFF -Dlogging.level.org.springframework.web=OFF -Dlogging.level.org.springframework.security=OFF --logging.level.org.springframework.web=ERROR",
    "ci:e2e:teardown": "npm run ci:e2e:teardown:docker",
    "ci:e2e:teardown:docker": "npm run docker:db:down --if-present && npm run docker:others:down && docker ps -a",
    "ci:frontend:build": "npm run webpack:build:$npm_package_config_default_environment",
    "ci:frontend:doc": "npx compodoc -d ./docs -p tsconfig.app.json src",
    "ci:frontend:test": "npm run ci:frontend:build && npm test",
    "ci:server:await": "echo \"Waiting for server at port $npm_package_config_backend_port to start\" && wait-on http-get://localhost:$npm_package_config_backend_port/management/health && echo \"Server at port $npm_package_config_backend_port started\"",
    "ci:server:package": "npm run java:$npm_package_config_packaging:$npm_package_config_default_environment",
    "clean-www": "rimraf target/classes/static/app/{src,target/}",
    "cleanup": "rimraf target/classes/static/",
    "cypress": "cypress open",
    "docker:db:down": "docker-compose -f src/main/docker/postgresql.yml down -v --remove-orphans",
    "docker:db:up": "docker-compose -f src/main/docker/postgresql.yml up -d",
    "docker:others:down": "",
    "predocker:others:up": "",
    "docker:others:up": "",
    "e2e": "npm run e2e:cypress",
    "e2e:cypress": "cypress run --browser chrome",
    "e2e:cypress:headless": "npm run e2e:cypress -- --headless",
    "e2e:dev": "concurrently -k -s first \"./mvnw\" \"e2e:run\"",
    "pree2e:headless": "npm run ci:server:await",
    "e2e:headless": "npm run e2e:cypress:headless",
    "java:docker": "./mvnw -ntp verify -DskipTests jib:dockerBuild",
    "java:docker:dev": "npm run java:docker -- -Pdev,webpack",
    "java:docker:prod": "npm run java:docker -- -Pprod",
    "java:jar": "./mvnw -ntp verify -DskipTests --batch-mode",
    "java:jar:dev": "npm run java:jar -- -Pdev,webpack",
    "java:jar:prod": "npm run java:jar -- -Pprod",
    "java:war": "./mvnw -ntp verify -DskipTests --batch-mode -Pwar",
    "java:war:dev": "npm run java:war -- -Pdev,webpack",
    "java:war:prod": "npm run java:war -- -Pprod",
    "jest": "jest --coverage --logHeapUsage --maxWorkers=2 --config jest.conf.js",
    "lint": "eslint . --ext .js,.ts",
    "lint:fix": "npm run lint -- --fix",
    "prettier:check": "prettier --check \"{,src/**/,webpack/}*.{md,json,yml,html,js,ts,tsx,css,scss,java}\"",
    "prettier:format": "prettier --write \"{,src/**/,webpack/}*.{md,json,yml,html,js,ts,tsx,css,scss,java}\"",
    "serve": "npm run start",
    "start": "npm run webpack:dev",
    "start-hmr": "ng serve --hmr",
    "start-tls": "npm run webpack:dev -- --env.tls",
    "pretest": "npm run lint",
    "test": "ng test --coverage --logHeapUsage -w=2",
    "test:watch": "npm run test -- --watch",
    "webpack:build": "npm run cleanup && npm run webpack:build:dev",
    "webpack:build:dev": "ng build",
    "webpack:build:prod": "ng build --prod",
    "webpack:dev": "ng serve",
    "webpack:dev-verbose": "ng serve --verbose",
    "webpack:prod": "npm run cleanup && npm run webpack:build:prod && npm run clean-www",
    "webpack:test": "npm run test"
  },
  "config": {
    "backend_port": "8080",
    "default_environment": "prod",
    "packaging": "jar"
  },
  "dependencies": {
    "@angular/common": "11.1.1",
    "@angular/compiler": "11.1.1",
    "@angular/core": "11.1.1",
    "@angular/forms": "11.1.1",
    "@angular/localize": "11.1.1",
    "@angular/platform-browser": "11.1.1",
    "@angular/platform-browser-dynamic": "11.1.1",
    "@angular/router": "11.1.1",
    "@compodoc/compodoc": "1.1.11",
    "@fortawesome/angular-fontawesome": "0.8.1",
    "@fortawesome/fontawesome-svg-core": "1.2.34",
    "@fortawesome/free-solid-svg-icons": "5.15.2",
    "@ng-bootstrap/ng-bootstrap": "9.0.2",
    "@ngx-translate/core": "13.0.0",
    "@ngx-translate/http-loader": "6.0.0",
    "bootstrap": "4.6.0",
    "dayjs": "1.10.4",
    "file-saver": "2.0.5",
    "ng-multiselect-dropdown": "0.3.1",
    "ngx-infinite-scroll": "10.0.1",
    "ngx-webstorage": "7.0.1",
    "rxjs": "6.6.3",
    "swagger-ui-dist": "3.41.1",
    "tslib": "2.1.0",
    "zone.js": "0.11.3"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "11.0.0",
    "@angular-builders/jest": "11.0.0",
    "@angular-eslint/eslint-plugin": "1.1.0",
    "@angular/cli": "11.1.2",
    "@angular/compiler-cli": "11.1.1",
    "@angular/service-worker": "11.1.1",
    "@types/file-saver": "2.0.1",
    "@types/jest": "26.0.20",
    "@types/node": "14.14.22",
    "@typescript-eslint/eslint-plugin": "4.14.1",
    "@typescript-eslint/parser": "4.14.1",
    "browser-sync": "2.26.14",
    "browser-sync-webpack-plugin": "2.3.0",
    "concurrently": "5.3.0",
    "copy-webpack-plugin": "6.4.1",
    "cypress": "6.2.1",
    "eslint": "7.18.0",
    "eslint-config-prettier": "7.2.0",
    "eslint-webpack-plugin": "2.4.3",
    "friendly-errors-webpack-plugin": "1.7.0",
    "generator-jhipster": "7.0.0-beta.1",
    "generator-jhipster-entity-audit": "3.3.0",
    "husky": "4.3.8",
    "jest": "26.6.3",
    "jest-date-mock": "1.0.8",
    "jest-junit": "12.0.0",
    "jest-sonar-reporter": "2.0.0",
    "lint-staged": "10.5.3",
    "merge-jsons-webpack-plugin": "1.0.21",
    "prettier": "2.2.1",
    "prettier-plugin-java": "1.0.1",
    "rimraf": "3.0.2",
    "simple-progress-webpack-plugin": "1.1.2",
    "typescript": "4.1.3",
    "wait-on": "5.2.1",
    "webpack": "4.46.0",
    "webpack-bundle-analyzer": "4.4.0",
    "webpack-notifier": "1.12.0"
  },
  "engines": {
    "node": ">=14.15.0"
  },
  "cacheDirectories": [
    "node_modules"
  ],
  "jestSonar": {
    "reportPath": "target/test-results/jest",
    "reportFile": "TESTS-results-sonar.xml"
  }
}

##### **Compodoc installed globally or locally ?**

Compodoc installed locally

##### **If possible sourcecode of the file where it breaks**

Nothing breaks.

##### **If possible your terminal logs before the error**

>npm run ci:frontend:doc

> supportivecare@1.5.0-SNAPSHOT ci:frontend:doc C:\workspace\support_care
> npx compodoc -d ./docs -p tsconfig.app.json src

1.1.11

TypeScript version used by Compodoc : 2.9.1

TypeScript version of current project : 4.1.3

Node.js version : v14.15.4

Operating system : Windows 10

[19:07:05] No configuration file found, switching to CLI flags.
[19:07:05] Using provided source folder
[19:07:05] Using tsconfig file : C:\workspace\support_care\tsconfig.app.json
[19:07:05] Searching package.json file
[19:07:05] package.json file found
[19:07:05] Processing package.json dependencies
[19:07:05] Searching README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.
md files
[19:07:05] README.md file found
[19:07:05] Error during C:\workspace\support_care\CHANGELOG read
[19:07:05] Continuing without CHANGELOG.md file
[19:07:05] Error during C:\workspace\support_care\CONTRIBUTING read
[19:07:05] Continuing without CONTRIBUTING.md file
[19:07:05] Error during C:\workspace\support_care\LICENSE read
[19:07:05] Continuing without LICENSE.md file
[19:07:05] Error during C:\workspace\support_care\TODO read
[19:07:05] Continuing without TODO.md file
[19:07:05] Get dependencies data
[19:07:05] parsing        : C:/workspace/support_care/src/main/webapp/main.ts
[19:07:05] parsing        : C:/workspace/support_care/src/main/webapp/polyfills.ts
[19:07:05] -------------------
[19:07:05] Project statistics 
[19:07:05] -------------------
[19:07:05] Prepare components
[19:07:05] Prepare modules
[19:07:05] Process documentation coverage report
[19:07:05] Process main graph
[19:07:05] Process pages
[19:07:05] Process page   : coverage
[19:07:05] Process page   : dependencies
[19:07:05] Process page   : index
[19:07:05] Process page   : modules
[19:07:05] Process page   : overview
[19:07:05] Process menu...
[19:07:05] Copy main resources
[19:07:06] Documentation generated in ./docs/ in 1.056 seconds using gitbook the
me

##### **Motivation for or Use Case**

Generate documentation

##### **Reproduce the error**

Just run the following command npm run ci:frontend:doc

##### **Related issues**

None

**Comment by tcoz** [comment]
I have this as well, though whether or not this is the same issue I don't know. Compodoc just stopped working, it doesn't generate any data other than the basic index page structure. 

However, I notice this: recently I had occasion to completely wipe and reinstall node. Not just an update or basic reinstall; I manually removed all traces of node from my (Mac) system and reinstalled it with the binary installer available from Node.js. 

Compodoc worked then, but only once. I rerun of the same exact command once again yielded the index shell (serving on localhost etc) but no data at all. Note that in the console I do see this (and no errors):

[10:24:46] No configuration file found, switching to CLI flags.
[10:24:46] Using tsconfig file : /Users/Consolazio/Documents/GitHub/nbcuas-ui/apps/promo/promo-ui/tsconfig.json
[10:24:46] Searching package.json file
[10:24:46] package.json file found
[10:24:46] Processing package.json dependencies
[10:24:46] Searching README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.md files
[10:24:46] README.md file found
[10:24:46] Error during /Users/Consolazio/Documents/GitHub/nbcuas-ui/CHANGELOG read
[10:24:46] Continuing without CHANGELOG.md file
[10:24:46] Error during /Users/Consolazio/Documents/GitHub/nbcuas-ui/CONTRIBUTING read
[10:24:46] Continuing without CONTRIBUTING.md file
[10:24:46] Error during /Users/Consolazio/Documents/GitHub/nbcuas-ui/LICENSE read
[10:24:46] Continuing without LICENSE.md file
[10:24:46] Error during /Users/Consolazio/Documents/GitHub/nbcuas-ui/TODO read
[10:24:46] Continuing without TODO.md file
[10:24:46] Get dependencies data
[10:24:46] -------------------
[10:24:46] Project statistics 
[10:24:46] -------------------
[10:24:46] Prepare components
[10:24:46] Prepare modules
[10:24:46] Process documentation coverage report
[10:24:46] Process main graph
[10:24:46] Process pages
[10:24:46] Process page   : coverage
[10:24:46] Process page   : dependencies
[10:24:46] Process page   : index
[10:24:46] Process page   : modules
[10:24:46] Process page   : overview
[10:24:46] Process menu...
[10:24:46] Copy main resources
[10:24:46] Documentation generated in /Users/Consolazio/Desktop/promo-docs/ in 0.443 seconds using material theme
[10:24:46] Serving documentation from /Users/Consolazio/Desktop/promo-docs/ at http://127.0.0.1:8080

You might say, "well, the missing files..." but that's never been a problem, and again, it did work once after that complete Node wipe. 

Maybe it's a cache or reference issue of some kind that could be wiped with a --force or --clear or something?

**Comment by vogloblinsky** [comment]
Please follow the updated documentation, and add a `tsconfig.doc.json`file with `"include": ["src/**/*.ts"]`
