### ISSUE TITLE
[BUG] Routes with data enum throw error

### ISSUE THREAD

**Issue by MickL** [compodoc/compodoc#1025]
##### **Overview of the issue**

Having a route with a data element that contains an enum throws an error:

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { ErrorComponent } from './error.component';
import { ErrorPage } from './error.interfaces';

const routes: Routes = [
  {
    path:        '404',
    component:   ErrorComponent,
    data: {
      errorType: ErrorPage.PageNotFound, // <--- This throws the error
    }
  },
];

@NgModule({
  imports: [
    RouterModule.forChild(routes)
  ],
  exports: [
    RouterModule
  ]
})
export class ErrorRoutingModule {
}
```

Error:

> [14:29:43] Analysing routes definitions and clean them if necessary
> Unhandled Rejection at: Promise {
>   <rejected> InvalidOperationError: Expected to find an initializer.

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: macOS 11.1
Node: v15.6.0
NPM: 7.4.0
compodoc: 1.1.11

**Comment by MickL** [comment]
Please dont close, this is a critical issue that still occurs.

**Comment by csutorasr** [comment]
The issue also happening, if you use enum as a string for the path.

**Comment by vogloblinsky** [comment]
Cannot reproduce with 1.1.14

**Comment by MickL** [comment]
I am on 1.1.14 now, shows error in console:
> [11:18:37] Error during generation of routes JSON file, maybe a trailing comma or an external variable inside one route.

Storybook is working anyway.

**Comment by schimini** [comment]
I think enums are still problematic. It doesn´t throw an unexpected error but it does log that trailing comma  issue
