### ISSUE TITLE
[BUG] UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dharsanav** [compodoc/compodoc#103]
##### **Overview of the issue**

I have a file say test.ts that contain some functions. When I try to generate documentation Iam getting the error as

>  **UnhandledPromiseRejectionWarning:Unhandled promise rejection(rejection id:1): RangeError:Invalid array length** .

I have  3 functions in test.ts. If either I commented out a particular function (out of 3) say get() or if I commented out functions other than get() , compodoc works fine. 

##### **Operating System, Node.js, npm, compodoc version(s)**
Node.js:v6.9.0
compodoc:0.0.39

##### **Compodoc installed globally or locally ?**
compodoc is installed locally and included as a dev dependency.

Any Idea why this is happening?

**Comment by vogloblinsky** [comment]
Is it possible to have the code of the blocking function ?

**Comment by dharsanav** [comment]
But I don't understand how that function works when i comment out remaining functions in that file.\

```javascript
const isEmpty = function isEmpty(...args: any[]): boolean {
    const len: number = args.length;
    for (let i: number = 0; i < len; i++) {
        if (args[i] == null) {
            return true;
        }
    }
    return false;
};`

**Comment by vogloblinsky** [comment]
I think it is the rest parameter that breaks the things.

**Comment by dharsanav** [comment]
But I do have other files having functions with rest parameters.
If rest parameter breaks things, then how does this function work when i comment out the remaining functions in the file

**Comment by vogloblinsky** [comment]
Strange it doesn't break on the demo project (https://github.com/compodoc/compodoc-demo-todomvc-angular) copying-pasting your code in https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/master/src/app/shared/miscellaneous/miscellaneous.ts
Using compodoc locally.

**Comment by dharsanav** [comment]
Iam using compodoc locally.
Yeah It is ineed strange that this particular function works well when other functions in file are commented.

**Comment by dharsanav** [comment]
Is there any way to identify which promise has thrown this error? Any piece of debugging info?

**Comment by vogloblinsky** [comment]
Can you try the last version 0.0.40 ?
I fixed a bug with TypeScript v2.2.0

**Comment by dharsanav** [comment]
No I tried but same error

**Comment by mattlewis92** [comment]
I'm seeing this as well, the stack trace is (super busy atm so don't have the time to send a PR to debug further):
```
RangeError: Invalid array length
    at pad (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/compodoc/src/logger.ts:49:15)
    at Logger.format (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/compodoc/src/logger.ts:54:14)
    at Logger.error (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/compodoc/src/logger.ts:35:15)
    at /Users/mattlewis/Code/open-source/angular-calendar/node_modules/compodoc/src/app/compiler/dependencies.ts:137:32
    at Array.map (native)
    at Dependencies.getDependencies (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/compodoc/src/app/compiler/dependencies.ts:124:21)
    at CliApplication.Application.getDependenciesData (/Users/mattlewis/Code/open-source/angular-calendar/node_modules/compodoc/src/app/application.ts:123:40)
    at /Users/mattlewis/Code/open-source/angular-calendar/node_modules/compodoc/src/app/application.ts:102:18
```

If you need a project to test it on: https://github.com/mattlewis92/angular-calendar (`yarn && yarn run compodoc`)

**Comment by vogloblinsky** [comment]
Fixed in 0.0.41
For angular-calendar it is working fine now. i hope for @dharsanav too

**Comment by dharsanav** [comment]
Thanks. Now it's working fine.It would be better if u could address  #101 in further release.

**Comment by mattlewis92** [comment]
Works great for me as well, thanks for the quick turnaround @vogloblinsky 👍

**Comment by mattlewis92** [comment]
Ah getting the same error (and stacktrace) on a different project now: https://github.com/mattlewis92/angular-resizable-element

Steps to reproduce:
```
yarn
yarn add --dev compodoc@0.0.41
// remove this bit from package.json:  -b /angular-resizable-element/docs/
yarn run compodoc
```

**Comment by vogloblinsky** [comment]
Ok, related to return type TypeScript analysis for one function of the directive.
