### ISSUE TITLE
[BUG] Dependency Update- Security

### ISSUE THREAD

**Issue by ewok-janitor** [compodoc/compodoc#1033]
Compodoc relies on several vulnerable libraries:
https://app.snyk.io/test/npm/@compodoc/compodoc/1.1.11

<copy/paste>
Authentication Bypass
Vulnerable module: http-auth
Introduced through: live-server@1.2.1
Detailed paths
Introduced through: @compodoc/compodoc@1.1.11 › live-server@1.2.1 › http-auth@3.1.3

Prototype Pollution
Vulnerable module: i18next
Introduced through: i18next@17.3.1
Detailed paths
Introduced through: @compodoc/compodoc@1.1.11 › i18next@17.3.1

...
<copy/paste>

There are more references in the snyk report.

Can we get a new release without the vulnerable libs?

**Comment by tomascubeek** [comment]
That would be really helpful!

**Comment by Akkora** [comment]
We are waiting for it aswell.

For us it is the package marked in version 0.7.0
Full report can be viewed here:  https://snyk.io/vuln/npm:marked@0.7.0

It is fixed in develop already, but not merged and released yet.

**Comment by vogloblinsky** [comment]
Will be fixed in 1.1.12 coming this week.

**Comment by GuessWhoSamFoo** [comment]
Any updates on this release? Using resolutions is generally not a preferred way of fixing this as it might cause problems with other dependencies.
