### ISSUE TITLE
[BUG] Dynamic type crashes compodoc

### ISSUE THREAD

**Issue by 8thblock** [compodoc/compodoc#1038]
The type below causes compodoc to crash

```
export type ClaimState = "draft" | "open" | "closed" | "archived";
export type ClaimStateTranslationKey =`claims.status.${Lowercase<ClaimState>}`;
```

Error given:
**"Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'text' of undefined"**

Environment:
Angular: 11.2.3
TS: 4.1.5
Node: 14.15.4
OS: MacOS Big Sur

Command ran: `compodoc -p ./tsconfig.json -e json -d .`

A project to reproduce the issue is attached

[my-app.zip](https://github.com/compodoc/compodoc/files/6075391/my-app.zip)

**Comment by 8thblock** [comment]
any at all who could take a look? @vogloblinsky may be?

**Comment by vogloblinsky** [comment]
fixed by https://github.com/compodoc/compodoc/commit/c7cd839107b929b5993086bcf413c9571f80a908
