### ISSUE TITLE
[BUG] No Documentation Generated (with workaround)

### ISSUE THREAD

**Issue by tcoz** [compodoc/compodoc#1039]
Running Angular 11.x, Compodoc 1.11.x, in an NRWL nx workspace. 

Compodoc stopped working, no documentation generated, no errors. Just an index page serving on localhost with no project detail at all. 

Here's what's happening. I ran into references to this, which pointed me in the right direction, but the below works around the problem. 

There's two tsconfig files to deal with: tsconfig, and tsconfig.app

The issue is, there is a files array in these files (added in a prior version of angular). 

That array breaks compodoc in the manner described (nothing generated). 

Removing the array in tsconfig.app will not work, as it inherits from tsconfig (which also has the array). And of course, removing it from tsconfig means that it's still in tsconfig.app. 

**So the workaround is** (and it's not a fix, we need to be able to keep that files array); either remove all files arrays from the entire inheritance chain of tsconfig files (e.g. if your workspace-base tsconfig has a files array), or failing that (which in my situation is the case) modify/create a tsconfig file that you can point the compodoc command at.

**Comment by lucini** [comment]
@tcoz same problem here... can you post an example of your workaround?

**Comment by lorencho** [comment]
What I did:
**tsconfig.doc.json**
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "include": ["src/**/*.ts"]
}

in **package.json**
{
  "name": "HTools",
  "version": "0.1.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "npx compodoc -p tsconfig.doc.json -d docs"
  },....................

**Comment by vogloblinsky** [comment]
Yes this workaround has been added in the official documentation.
I will try to handle that easily in the next versions.
