### ISSUE TITLE
[FEATURE] Create documentation for personalized file components's names

### ISSUE THREAD

**Issue by alexcarrasco93** [compodoc/compodoc#1043]
##### **Overview of the feature**

I want compodoc to generate documentation for components which the file's name is not component but for example _home.page.ts_.

##### **Motivation for or Use Case**

I have modules which I separate components between pages and components. The components in the pages folder are named _[name of the component].page.ts_ and the compodoc doesn't see it as a component so it doesn't generate documentation.

**Comment by vogloblinsky** [comment]
Can you share the folder/files structure ?

**Comment by alexcarrasco93** [comment]
I realised that the problem is that when you go to the documentation of a module and click on a component which has a different name or is located in other folder then the route to that component is incorrect but it exists in the documentation.
![image](https://user-images.githubusercontent.com/22663646/114836224-baf14880-9dd2-11eb-960f-1e1c65d0bf00.png)
In the pages folder I have components which are declared in the module. When I go to the module documentation and click on a component located in the pages folder, for example the SummaryPage, compodoc try to go to the following link: http://127.0.0.1:8080/s/SummaryPage.html
So I finally realised that the components located in these folders the link created for them instead of **_components/MyComponent.html_** is **_s/MyComponent.html_**
