### ISSUE TITLE
[BUG] Error during documentation generation

### ISSUE THREAD

**Issue by mkarpovets** [compodoc/compodoc#1044]
Error during documentation generation

Ooops error during main graph generation, moving on next part with main graph disabled : : Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/local/lib/node_modules/@compodoc/compodoc/node_modules/@aduh95/viz.js/sync/index.js
require() of ES modules is not supported.
require() of /usr/local/lib/node_modules/@compodoc/compodoc/node_modules/@aduh95/viz.js/sync/index.js from /usr/local/lib/node_modules/@compodoc/compodoc/node_modules/@compodoc/ngd-transformer/dist/engines/dot/dot.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/local/lib/node_modules/@compodoc/compodoc/node_modules/@aduh95/viz.js/package.json.

**Comment by mkarpovets** [comment]
@vogloblinsky do you know, how couldd I fix this?

**Comment by ALapaque** [comment]
Hi @mkarpovets as we need a fix from the compodoc team I did add --disableGraph to my command line in order to remove the generation of the graph and remove the error

**Comment by josielh12** [comment]
> Hi @mkarpovets as we need a fix from the compodoc team I did add --disableGraph to my command line in order to remove the generation of the graph and remove the error

do you have other fix from this bug ?

**Comment by vogloblinsky** [comment]
@mkarpovets what the technical context ? Node.js version ?

**Comment by ALapaque** [comment]
@vogloblinsky personnaly, I've the same issue and I'm using v12.16.3

**Comment by ALapaque** [comment]
@mkarpovets I did solve this issue by updating my nodeJs version I was in v12.16.3 and I move to v14.16.1 and it's working :D

**Comment by JamboBuenna** [comment]
Unfortunately, the fixes are either move dependencies to an unstable version or disable key features on compodoc 👎

**Comment by JamboBuenna** [comment]
Apologies for not being clear @vogloblinsky 

NodeJs versions recommended with latest stable angular is 12.x.
However the known fix for this is either, turn on graph generation (disabling the compodoc feature) or move to nodeJs 14+ (currently not supported by Angular stable)

**Comment by JamboBuenna** [comment]
However, I may be out of date, as 14 is now LTS... checking.
