### ISSUE TITLE
[FEATURE] Support ... and dynamic in Type declaration

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#1053]

**Comment by rabraghib** [comment]
When will this come ??

**Comment by bcakmakoglu** [comment]
I'd really appreciate it if this got published in the near future 👍

**Comment by 8thblock** [comment]
Any idea if this is going to get published soon?

**Comment by vogloblinsky** [comment]
@bcakmakoglu @8thblock Did you have examples ?

**Comment by vogloblinsky** [comment]
@bcakmakoglu @8thblock Did you have examples ?

**Comment by bcakmakoglu** [comment]
@vogloblinsky 
Sorry I didn't see the notification.
Well I don't have an example right now, the relevant Code was sort of trashed for completely different reasons but it was something like this
```ts
type Foo = '320' | '360' | '1440';

type Bar = `(min-width: ${Foo}px)`
```

The type "Bar" would have caused compodoc to complain.

**Comment by vogloblinsky** [comment]
Semi-support for Type Reference, the TypeScript version used in 1.1.14, 3.9.10, doesn't give more information with this syntax ``` `(min-width: ${Foo}px)` ```

**Comment by vogloblinsky** [comment]
Finally fixed with migration from ts-simple-ast to ts-morph. Coming in 1.1.14
