### ISSUE TITLE
Hi I have added comments for all functions and global variable but the code coverage not showing 100%. I am not able to find out which parts are missing.

### ISSUE THREAD

**Issue by shindekaps** [compodoc/compodoc#106]

**Comment by shindekaps** [comment]
I am not able to understand how code coverage calculated?

**Comment by vogloblinsky** [comment]
The code is here :

https://github.com/compodoc/compodoc/blob/master/src/app/application.ts#L379

Could you provide a screenshot of your coverage report ?

**Comment by shindekaps** [comment]
![screen shot 2017-02-09 at 3 57 29 pm](https://cloud.githubusercontent.com/assets/6639215/22779430/cdc3d5cc-eee0-11e6-94fc-820b3c0185d1.png)
![screen shot 2017-02-09 at 3 57 55 pm](https://cloud.githubusercontent.com/assets/6639215/22779449/da931d26-eee0-11e6-95c4-9035a72601fd.png)

**Comment by shindekaps** [comment]
For datastorage.service.ts I have added comment for each parts but still showing 36%
Below is code for this
`import { Injectable } from '@angular/core';
import { Storage } from '@ionic/storage';
import { Events } from 'ionic-angular';

import { AppConfiguration } from './app-configuration.service';
/**
 * DatastorageService provider
 * This provider is used to handle all local db transactions like storing data in localStorage as well as sqlite db. 
 */
@Injectable()
export class DatastorageService {
  /**
   * Local reference for localStorage object
   */
  local: any;
  /**
  * Local reference for user details
  */
  userDetails: any;
  /**
  * Local reference to store some data in cache. 
  */
  static cacheData: any;
  /**
  * The "constructor"
  *
  * @param {Storage} storage A Storage
  * @param {Events} pubsub A Events
  */
  constructor(
    private storage: Storage,
    private pubsub: Events
  ) {
    this.local = localStorage;
    DatastorageService.cacheData = {};
  }
  /**
  * @param {string} key 
  * Pass key for the local storage
  *  @param {string} value 
  * Pass value that we need to store in local storage
  * @example
  * This method is used to store data in local storage
  * setLocalStorageData("user","{name:'abc',email:'xyz@abc.com'}")
  * @returns  {void}  nothing to return
  */
  setLocalStorageData(key: string, data: string) {
    this.local.setItem(key, data);
  }
  /**
  * @param {string} key 
  * Pass key for the local storage
  * @example
  * This method is used to get particular data from the local storage
  * getLocalStorageData("user")
  * @returns  {string} It get the data from local storage and return.
  */
  getLocalStorageData(key: string) {
    let data = this.local.getItem(key);
    if (!data) {
      return null;
    }
    return (data);
  }
  /**
  * @param {string} key 
  * Pass key for sqlite db
  *  @param {object} value 
  * Pass value that we need to store in sqlite db
  * @example
  * This method is used to store data in sqlite db
  * setDataInDb("user",{name:'abc',email:'xyz@abc.com'})
  * @returns  {void}  nothing to return
  */
  setDataInDb(key: string, value: any) {
    this.storage.set(key, value).then(success => {
      this.pubsub.publish(AppConfiguration.customEvents.dbUpdated);
      console.log("offline db updated");
    });
  }
  /**
  * @param {string} key 
  * Pass key for sqlite db
  * @example
  * This method is used to get particular data from sqlite db
  * getDbData("user")
  * @returns  {Promise} It return promise with value
  */
  getDbData(key: string): Promise<any> {
    return new Promise((resolve, reject) => {
      this.storage.get(key).then((val) => {
        resolve(val);
      }, err => {
        reject(err);
      })
    })
  }
  /**
  * @param {string} key 
  * Pass key for sqlite db
  * @example
  * This method is used to delete particular data from sqlite db
  * deleteDbData("user")
  * @returns  {Promise} It return promise with deletion status
  */
  deleteDbData(key: string): Promise<any> {
    return new Promise((resolve, reject) => {
      this.storage.remove(key).then((val) => {
        resolve(val);
      }, err => {
        reject(err);
      })
    })
  }
  /**
  * @param {void} 
  * no param required
  * @example
  * This method is used to to fetch all keys of data from sqlite db
  * getKeysInDb()
  * @returns  {Promise} It return promise with list of keys.
  */
  getKeysInDb(): any {
    return new Promise((resolve, reject) => {
      this.storage.keys().then((val) => {
        console.log(val);
        resolve(val);
      }, err => {
        console.log(err);
        reject(err);
      });
    })
  }
  /**
  * @param {string} key 
  * Pass key for sqlite db
  *  @param {object} value 
  * Pass value that we need to store in cache.
  * @example
  * This method is used to store data in cache
  * setCacheData("user",{name:'abc',email:'xyz@abc.com'})
  * @returns  {void}  nothing to return
  */
  setCacheData(key, value) {
    this.setLocalStorageData(key, JSON.stringify(value));
  }
  /**
  * @param {string} key 
  * Pass key for cache
  * @example
  * This method is used to get particular data from cache
  * getCacheData("user")
  * @returns  {Promise} It returns JSON object
  */
  getCacheData(key) {
     /**
     * variable details used to store cache data
     * @type Object
     */
    let details = this.getLocalStorageData(key);
    if (details) {
      details = JSON.parse(details);
    }
    return details;
  }
}
`

**Comment by vogloblinsky** [comment]
For each method, the main comment is not at the top of the comment paragraph. Compodoc calculate coverage with that.

```
/**
  * This method is used to get particular data from cache
  * @param {string} key
  * Pass key for cache
  * @example
  * getCacheData("user")
  * @returns  {Promise} It returns JSON object
  */
  getCacheData(key) {
     /**
     * variable details used to store cache data
     * @type Object
     */
    let details = this.getLocalStorageData(key);
    if (details) {
      details = JSON.parse(details);
    }
    return details;
  }
```

**Comment by shindekaps** [comment]
Thanks for your quick response. Now it is working fine.
