### ISSUE TITLE
[BUG] Dependencies with security issues

### ISSUE THREAD

**Issue by OxyFlax** [compodoc/compodoc#1060]
##### **Overview of the issue**

With last package version, yarn audit is giving security issues:
Critical vulnerabilities:
- handlebars (fix 4.7.7)

High vulnerabilities:
- lodash (fix 4.17.21)

Low vulnerabilities:
- lodash (fix 4.17.19)

<img width="1273" alt="compodoc yarn audit report" src="https://user-images.githubusercontent.com/14943003/117622421-e9b0d380-b172-11eb-9d47-4d08c99603aa.png">

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc version: 1.1.11

##### **Reproduce the error**

Run `yarn audit` in an application with compodoc dependency.

##### **Suggest a Fix**

The current code on develop branch has updated packages with the vulnerability packages fixed. 
Creating another build should fix the issue.

**Comment by OxyFlax** [comment]
If package is in devDependencies, which is were it belongs, yarn audit is not raising it :)
Still, would be good to have an updated package whenever you have time ;)

**Comment by vogloblinsky** [comment]
Fixed, coming with 1.1.12
