### ISSUE TITLE
[BUG] component metadata provider displays incorrectly in docs

### ISSUE THREAD

**Issue by Alegiter** [compodoc/compodoc#1074]
Hi, first of all thank you for super tool!)

But
I\`m using transloco library and it\`s provider doesn`t display properly:
There are no values for scope and alias properties...
![Снимок экрана от 2021-06-24 14-15-14](https://user-images.githubusercontent.com/24659873/123255141-29036b80-d4f8-11eb-9b6e-0b590a4af1df.png)

Maybe this doesn\`t really relate to transloco`s provider
I tried to set simple string to useValue instead of object, but got useValue without value

Ask me for reproduction repo if you really need

**Comment by vogloblinsky** [comment]
@Alegiter I just need the file with the provider. Thanks

**Comment by vogloblinsky** [comment]
Internal printer of TypeScript is used for this providers syntax. I keep that for another big release, where i will upgrade TypeScript dependency used by ts-simple-ast, and i think the issue will be fixed.

**Comment by Alegiter** [comment]
OK. Thanks for reply. I`m looking forward to 1.2.0 :)
