### ISSUE TITLE
[BUG] Component Inheritance not merged if Ivy is enabled

### ISSUE THREAD

**Issue by pburgmer** [compodoc/compodoc#1075]
##### **Overview of the issue**

In Angular 11 and with Ivy enabled I have to mark the base class a component as directive, otherwise the Angular compiler complains about the base class using Angular features but not being decorated.

Marking the base class as directive prevents inclusion of inherited inputs in the generated documentation.

I saw [b94e9c759267425809edce52dc843e06fbff16a9](https://github.com/compodoc/compodoc/commit/b94e9c759267425809edce52dc843e06fbff16a9) and as far as I understand the merger excludes this kind of inheritance.

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10 64 bit
NodeJS 14.17.0
npm 6.14.7
compodoc 1.1.11
Angular 11.2.14

##### **Angular configuration, a `package.json` file in the root folder**

Please take a look at the example repo I prepared:
https://github.com/pburgmer/compodoc-inheritance-ivy-bug

##### **Compodoc installed globally or locally ?**

Compodoc is installed locally as dev dependency

##### **If possible sourcecode of the file where it breaks**

https://github.com/pburgmer/compodoc-inheritance-ivy-bug/blob/master/src/app/child.component.ts

##### **Motivation for or Use Case**

Without Ivy it works as expected. The inherited input is included in the documentation. With Ivy enabled it's not.

##### **Reproduce the error**

* Take a look at the example code in `scr/app/child.component.ts`
* Run `npm run compodoc` to generate the documentation to `dist/doc/documentation.json`
* Inheritance is mentioned for `ChildComponent` but neither `ParentComponent` got documented nor is the input of `ParentComponent` included in the documentation of `ChildComponent`
* Remove decorator on `ParentComponent` and run `npm run compodoc` again
* Now the input is included
* Run `npm run start` to see Angular complaining about the missing decorator
  `@Injectable` and `@Component` also don't work. Only `@Directive` satisfies Angular

##### **Related issues**

nothing found

##### **Suggest a Fix**

Include a base classes in the merge of depenencies

**Comment by vogloblinsky** [comment]
Fixed in 1.1.12
