### ISSUE TITLE
[FEATURE] Nested Component Structure

### ISSUE THREAD

**Issue by mikerhyssmith** [compodoc/compodoc#108]
Hi Vincent,

I wondered about the possibility of documenting the structure of components based on their templates.
Working with a lot of nested components, it would nice to be able to visualise the structure of these components based on the further components they contain.  What would be really great would be a graph similar to those produced from the modules in Compodoc currently. I'm not sure on the feasibility or best approach of doing this ?

Thanks,
Mike

**Comment by vogloblinsky** [comment]
Yep, nice idea. I have the same need on one project. 
Will add that in the roadmap.

**Comment by mikerhyssmith** [comment]
Have you got any thoughts on how best to implement this ? I'd be happy to have a look at working on a PR for it!

**Comment by vogloblinsky** [comment]
Not right now ;)
I think it is a mix of : 
- scanning all sources, and all components with their selector
- scanning all templates of components for searching for all previous selectors
- building a tree with that
- creating a static graph or dynamic (d3.js) using the tree

**Comment by DmitryEfimenko** [comment]
How come this is closed? If this is implemented, a link to the docs showing how to turn it on would be nice
