### ISSUE TITLE
Is compodoc dead?

### ISSUE THREAD

**Issue by ManuelRauber** [compodoc/compodoc#1084]
Hi @vogloblinsky 

Is your project dead? According to insights, there was no progress for a long time: https://github.com/compodoc/compodoc/graphs/commit-activity

Last release was end of 2019, so almost two years ago.

Other projects like Storybook rely on your project and they start to break because compodoc does not support all latest features, like TypeScript Template Literal Types. 

It would wish for some more communication from your side, if the project is dead/deprecated, if you look out for a new maintainer etc. 

Thanks!

**Comment by vogloblinsky** [comment]
Hi @ManuelRauber 
No it is not dead, i will try to find some time this week.
Do you have the issues related to Storybook you mentionned ?
Regards
