### ISSUE TITLE
[BUG] Dependency Update- Security

### ISSUE THREAD

**Issue by ewok-janitor** [compodoc/compodoc#1086]
Resubmission of https://github.com/compodoc/compodoc/issues/1033

Compodoc relies on several vulnerable libraries:
https://app.snyk.io/test/npm/@compodoc/compodoc/1.1.11

<copy/paste>
Authentication Bypass
Vulnerable module: http-auth
Introduced through: live-server@1.2.1
Detailed paths
Introduced through: @compodoc/compodoc@1.1.11 › live-server@1.2.1 › http-auth@3.1.3

Prototype Pollution
Vulnerable module: i18next
Introduced through: i18next@17.3.1
Detailed paths
Introduced through: @compodoc/compodoc@1.1.11 › i18next@17.3.1

...
<copy/paste>

There are more references in the snyk report.

Can we get a new release without the vulnerable libs?

**Comment by vogloblinsky** [comment]
Fixes with development version, next version coming this afternoon

**Comment by Blakesalot** [comment]
Hi, @vogloblinsky. How is progress going on the release?
