### ISSUE TITLE
[BUG] compodoc 1.1.12 doesn't install correctly : pb with sleep@6.3.0

### ISSUE THREAD

**Issue by turbo-xav** [compodoc/compodoc#1093]
##### **Overview of the issue**

When i intall compodoc "npm i @compodoc/compodoc@1.1.12 --verbose"
I have this error message :
gyp http GET https://nodejs.org/download/release/v14.17.1/node-v14.17.1-headers.tar.gz
...
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT 104.20.22.46:443
...
npm ERR! errno 1
npm ERR! sleep@6.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1

It seems that "https://nodejs.org/download/release/v14.17.1/node-v14.17.1-headers.tar.gz" fails
**I use an internal repo "nexus 3".**

##### **Operating System, Node.js, npm, compodoc version(s)**

nodejs 14.17.1
npm 6.14.13
anhular 12.1.1

##### **Compodoc installed locally ?**
- Compodoc 1.1.12

##### **If possible sourcecode of the file where it breaks**
N/A
##### **Motivation for or Use Case**
Use last version of compodoc 1.1.12

Cannot use last version of compodoc
##### **Reproduce the error**
npm i @compodoc/compodoc@1.1.12 --verbose
it is reproduced when i install "sleep" only
npm i sleep@6.3.0 --verbose
##### **Related issues**
N/A
##### **Suggest a Fix**
- Replace sleep@6.3.0 by another which doesn't download  https://nodejs.org/download/release/v14.17.1/node-v14.17.1-headers.tar.gz ?

**Comment by vogloblinsky** [comment]
Fixed by a1d5a1a, i will release a quick 1.1.13 this afternoon.

**Comment by turbo-xav** [comment]
Thanks
