### ISSUE TITLE
[BUG] @Input added to inputsClass and propertiesClass

### ISSUE THREAD

**Issue by dexster** [compodoc/compodoc#1095]
### **Overview of the issue**

Since v1.1.12 @Input generates in both inputsClass array and propertiesClass array. Is this duplication expected?

Generated docs JSON

v1.1.11
 ```
 "components": [
        {
            "name": "ButtonComponent",
            ...
            "inputsClass": [
                {
                    "name": "label",
                    "defaultValue": "'Button'",
                    "line": 13
                }
            ],
            "outputsClass": [],
            "propertiesClass": [],
            "methodsClass": [],
            "hostBindings": [],
            "hostListeners": [],
```

v1.1.12 and v1.1.13
```
 "components": [
        {
            "name": "ButtonComponent",
            ...
            "inputsClass": [
                {
                    "name": "label",
                    "defaultValue": "'Button'",
                    "deprecated": false,
                    "deprecationMessage": "",
                    "line": 13,
                    "type": "string"
                }
            ],
            "outputsClass": [],
            "propertiesClass": [
                {
                    "name": "label",
                    "defaultValue": "'Button'",
                    "deprecated": false,
                    "deprecationMessage": "",
                    "type": "string",
                    "optional": false,
                    "description": "",
                    "line": 13,
                    "decorators": [
                        {
                            "name": "Input",
                            "stringifiedArguments": ""
                        }
                    ]
                }
            ],
            "methodsClass": [],
            "deprecated": false,
            "deprecationMessage": "",
            "hostBindings": [],
```

### **Operating System, Node.js, npm, compodoc version(s)**

node 14.15.5
Mac Big Sur
Compodoc 1.1.11 (working)
Compodoc 1.1.12 (bug)

### **Angular configuration, a `package.json` file in the root folder**

"dependencies": {
    "@angular/animations": "~12.0.2",
    "@angular/common": "~12.0.2",
    "@angular/compiler": "~12.0.2",
    "@angular/core": "~12.0.2",
    "@angular/forms": "~12.0.2",
    "@angular/platform-browser": "~12.0.2",
    "@angular/platform-browser-dynamic": "~12.0.2",
    "@angular/router": "~12.0.2",
    "@compodoc/compodoc": "^1.1.11",
    "rxjs": "~6.6.0",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
 "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.2",
    "@angular/cli": "~12.0.2",
    "@angular/compiler-cli": "~12.0.2",
    "@angular/elements": "^12.1.1",
    "@babel/core": "^7.14.6",
    "@storybook/addon-actions": "^6.3.4",
    "@storybook/addon-essentials": "^6.3.4",
    "@storybook/addon-links": "^6.3.4",
    "@storybook/angular": "^6.3.4",
    "@storybook/builder-webpack5": "^6.3.4",
    "@storybook/manager-webpack5": "^6.3.4",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "@webcomponents/custom-elements": "^1.4.3",
    "babel-loader": "^8.2.2",
    "jasmine-core": "~3.7.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "typescript": "~4.2.3"
  }
### **Compodoc installed globally or locally ?**

locally

### **Motivation for or Use Case**

Storybook generates controls based on docs which allows Inputs to be modified dynamically. Controls are now breaking as storybook is reading Inputs as properties and not inputs.

### **Reproduce the error**

Create a component like this and run compodocs `compodoc -p ./tsconfig.json -e json -d .`: 

```
@Component({
  selector: 'storybook-button',
  template: ` <button
    type="button"
  >
    {{ label }}
  </button>`
})
export default class ButtonComponent {
  @Input()
  label = 'Button';
}
```

👉  https://opencollective.com/compodoc/donate -->

**Comment by vogloblinsky** [comment]
No, it seems to be a regression. I fix that asap.
