### ISSUE TITLE
[BUG] Route Parser: Transform Angular Import does not support return type

### ISSUE THREAD

**Issue by nabihnadhif** [compodoc/compodoc#1097]
##### **Overview of the issue**

Route parser does not support lazy loaded callback with return type. 
The regex responsible of the transformation of angular import syntax does not include the return type.

```typescript
private transformAngular8ImportSyntax = /(['"]loadChildren['"]:)\(\)=>"import\((\\'|'|")([^'"]+?)(\\'|'|")\)\.then\(\w+?=>\S+?\.([^)]+?)\)(\\'|'|")/g;
```

##### **Reproduce the error**

```typescript
{
    path: 'dashboard',
    loadChildren: (): Promise<DashboardModule> =>
       import('../dashboard/dashboard.module').then(m => m.DashboardModule)
}
```

##### **Suggest a Fix**

1. Update the regex

```typescript
this.transformAngular8ImportSyntax =
    /(['"]loadChildren['"]:)\(\)(:[^)]+?)?=>(\\'|'|")import\((\\'|'|")([^'"]+?)(\\'|'|")\)\.then\(\w+?=>\S+?\.([^)]+?)\)(\\'|'|")/g;
```

2. Update the replace pattern (lines 72 and 87)

```typescript
routesWithoutSpaces = routesWithoutSpaces.replace(this.transformAngular8ImportSyntax, '$1"$5#$7"');
```

**Comment by vogloblinsky** [comment]
Thanks @nabihnadhif for the trick !
There was just a typo, it is ```'$1"$4#$6"'```and not ```'$1"$5#$7"'```

**Comment by nabihnadhif** [comment]
Thank you @vogloblinsky
That's because I have replaced `"import` by `(\\'|'|")import`

**Comment by vogloblinsky** [comment]
Yes i have used your regex 😄
