### ISSUE TITLE
[BUG] 1.1.11 to 1.1.12 error generating docs /* your preset */

### ISSUE THREAD

**Issue by rickvandermey** [compodoc/compodoc#1100]
After updating from `1.1.11` to`1.1.12` an error occured during the build process of compodoc

```
[14:39:08] Error during ./documentation//js/menu-wc_es5.js page generation
[14:39:08] Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,

babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });

See https://babeljs.io/docs/en/options#filename for more information.
```

.compodocrc
```
disableRoutesGraph: true
hideGenerator: true
name: RVDM Angular Starterkit
output: ./documentation
tsconfig: ./src/tsconfig.compodoc.json
unitTestCoverage: ./coverage/coverage-summary.json
```

scripts:
```
"doc": "compodoc --coverageTestThresholdFail=false",
"doc:full": "npm run test:ci && npm run test:e2e && npm run wpo:stats && npm run wpo:lighthouse && npm run doc:reports && npm run doc -- --includes compodoc-additional-doc",
"doc:reports": "npx mkdirp documentation/additional-documentation && npx ncp reports documentation/additional-documentation",
```

a reproduction can be found at https://github.com/rickvandermey/angular-starterkit

**Comment by vogloblinsky** [comment]
can you test by doing
- rm -rf node_modules
- npm i
run your doc command

**Comment by rickvandermey** [comment]
Still returning the same error

if i just run compodoc i already got the error

**Comment by vogloblinsky** [comment]
I just cloned your repository.
Running ```./node_modules/.bin/compodoc``` works fine and use 1.1.11 version.
You can uograde to 1.1.14, now Compodoc will not fail with this issue. I will investigate because using the same command ```./node_modules/.bin/compodoc``` with 1.1.14 show the Babel error.
