### ISSUE TITLE
[BUG] Multilevel `@Directive` inheritance only includes properties of last parent

### ISSUE THREAD

**Issue by stefan-schweiger** [compodoc/compodoc#1105]
**Overview of the issue**

If you have multi level inheritance with directives only the properties of the "last" parent show up in the generated `documentation.json`.

For example `ChildComponent <- DirectParentDirective <- GrandParentDirective`. Only properties of `DirectParentDirective` show up in `ChildComponent`.

But if you do something like this `ChildComponent <- DirectParentComponent <- GrandParentDirective` the properties get inherited as expected to `ChildComponent`.

**Reproduction of the issue**
https://github.com/stefan-schweiger/compodoc-repro/tree/double-directive-inheritance

**Comment by stefan-schweiger** [comment]
Still a problem

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/3814299a0f707116254deb6ea24b563eceed96b2
