### ISSUE TITLE
[FEATURE] Replace generic in class methods

### ISSUE THREAD

**Issue by Granipouss** [compodoc/compodoc#1106]
##### **Overview of the feature**

Basically it would take 

```ts
class A<T> {
  getData(value: T): void {}
}

class B extends A<string> {}
```

and type `B.getData` as `(value: string) => void` instead of `(value: T) => void`

##### **Motivation for or Use Case**

A way to acheive the proper documentation would be to redeclare the method

```ts
class B extends A<string> {
  getData(value: string): void {
    super.getData(value);
  }
}
```

but it seems like a very poor pattern to me. Additionnally documentating a method as `(value: T) => void` when the documentation of `B` makes no reference to `T` isn't very informative.

##### **Related issues**

I haven't found any.

**Comment by ssams** [comment]
would also love to see this, please also extend it to properties as the same issues also applies to them!

Example: 

```typescript
class A<T> {
  /** test */
  dummy: T;
}

class B extends A<string> {}
```

Currently documentation will show `dummy` as having type `T` although it should be `string`, so generated docs are also incorrect in this case.

Had a quick look if this can be fixed easily, but it seems to be related to #555  - in this example generated JSON docs for `A` only list `"extends": "A"`, generic type information from the base is not available for implementing this at the moment?

**Comment by ssams** [comment]
What would be also nice is if there'd be a way to overwrite the documentation from the base without redeclaring the method or property (e.g. in the above example where the docs in `A` generate the description "test" -> set the description to "something else" in B only). Would be useful to be able to add a generic default description in the base type but add more details in the subclass. However this might be out of scope of this issue, maybe should be handled in a separate one?

**Comment by ssams** [comment]
issue/request still applies (commenting to avoid automatic closure)
