### ISSUE TITLE
[BUG] components don't have the correct data depth 

### ISSUE THREAD

**Issue by elasticrash** [compodoc/compodoc#111]
##### **Overview of the issue**

It seems that for the components the 
{{relativeURL data.depth data.pageType 'root'}} in the template is generated wrong
specifically I get in all urls ./styles/style.css instead of ../styles/style.css same goes for js files

##### **Operating System, Node.js, npm, compodoc version(s)**

OS X. node 6.7 npm 3.10.3 compodoc 0.0.41

##### **Compodoc installed globally or locally ?**

globally

##### **Motivation for or Use Case**
web page is not served correctly

**Comment by vogloblinsky** [comment]
Fixed. Coming in next release very soon ;)
