### ISSUE TITLE
[FEATURE] - Support adding unit test code to documentation

### ISSUE THREAD

**Issue by RomanKisilenko** [compodoc/compodoc#112]
esdoc has a nice feature which allows you to attach unit tests code to documentation so that readers can use it as usage samples. https://esdoc.org/manual/usage/feature.html#integration-test-codes

It would be nice to have a similar feature in compodoc.

**Comment by vogloblinsky** [comment]
Yes, it can be a great feature.
I will take a look at esdoc implementation.
Could be added in v1.1 next month, v1.0 is coming soon first ;)

**Comment by michael-letcher** [comment]
Updated link: https://esdoc.org/manual/feature.html#integration-test-codes

I love the documentation coverage, getting one that shows the unit test coverage would be fantastic!

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/pull/594
