### ISSUE TITLE
[BUG] Babel unknown: Preset

### ISSUE THREAD

**Issue by andreasciamanna** [compodoc/compodoc#1122]
This issue is identical to #1100.

The differences are:
- I'm already using the latest version of compodoc: `"@compodoc/compodoc": "^1.1.14"`
- It happens with both the script (`"doc:generate": "compodoc src -p tsconfig.doc.json"`) and a direct all to `./node_modules/.bin/compodoc src -p tsconfig.doc.json`
- The repo is a React Native app built with Expo (I hope the fact that it's not an Angular project won't be an issue: after all, compodoc works just fine with React JS apps that use TypeScript).

This is the content of `tsconfig.doc.json`:

```json
{
  "include": ["src/**/*.ts"],
  "exclude": ["src/test.ts", "src/**/*.spec.ts", "src/database/migrations"]
}
```

This works just fine with another React JS app I've used to try out compodoc.

However, looking at #1100, I've also tried this approach, but I saw no differences:

tsconfig.doc.json`:
```json
{
  "extends": "tsconfig.json",
  "include": ["src/**/*.ts"],
  "exclude": ["src/test.ts", "src/**/*.spec.ts", "src/database/migrations"]
}
```

tsconfig.json`:
```json
{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "types": ["codeceptjs"]
  },
  "ts-node": {
    "files": true
  },
}
```

These are the last entries of the output log:

```
[08:39:30] Process menu...
[08:39:30] Error during ./documentation//js/menu-wc_es5.js page generation
[08:39:30] Error: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
'''
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
'''
See https://babeljs.io/docs/en/options#filename for more information.
[08:39:30] 
[08:39:30] Copy main resources
[08:39:30] Documentation generated in ./documentation/ in 1.464 seconds using gitbook theme
```

It's worth noting that the documentation gets generated, and I could see no errors when browsing it.

Another thing I noticed is that if I run `which compodoc`, the path returned is the one of another project (always a React Native one, where I was doing the same testing, and where there is the same version installed).

Compodoc is not installed globally, but I find it odd that, when installed locally, the command is still available globally, pointing, I guess, to the first or last place where npm installed it.

Unfortunately, I can't share the original repo because this is a private project, but I could replicate the issue with [this simple Expo app](https://github.com/andreasciamanna/compodoc-test).

I hope I've provided all the information you need.

**Comment by vogloblinsky** [comment]
Ok. Fixed by https://github.com/compodoc/compodoc/commit/10f73a546773a328b3d8fb9d3a4684add7a8e61e
I added another babel config param to be sure @babel/preset-env is correctly resolved.
