### ISSUE TITLE
[BUG] SyntaxError: JSON5: invalid character '.' at 1:470

### ISSUE THREAD

**Issue by taras-kravets-ua** [compodoc/compodoc#1124]
**Error during generation of routes JSON file, maybe a trailing comma or an external variable inside one route.**

Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '.' at 1:470
      at syntaxError (/Users/project/node_modules/json5/lib/parse.js:1083:17)
      at invalidChar (/Users/project/node_modules/json5/lib/parse.js:1028:12)
      at Object.afterArrayValue (/Users/project/node_modules/json5/lib/parse.js:672:15)
      at Object.default (/Users/project/node_modules/json5/lib/parse.js:146:37)
      at lex (/Users/project/node_modules/json5/lib/parse.js:78:42)
      at Object.parse (/Users/project/node_modules/json5/lib/parse.js:25:17)
      at loopModulesParser (/Users/project/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:5711:51)
      at RouterParserUtil.constructRoutesTree (/Users/project/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:5736:13)
      at AngularDependencies.getDependencies (/Users/project/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:8673:50)
      at CliApplication.Application.getDependenciesData (/Users/project/node_modules/@compodoc/compodoc/dist/index-cli-32a621dc.js:10227:40) {
    lineNumber: 1,
    columnNumber: 470
  }
}

Angular CLI: 12.1.2
Node: 14.17.6
Package Manager: npm 6.14.15
OS: darwin x64
Compodoc: 1.1.14

**Comment by MysticBlaze085** [comment]
I am currently running into this error which is keeping me from using storybook

**Comment by luizfernando1996** [comment]
+1

**Comment by raghav-kanwal** [comment]
+1. Getting this issue which is blocking me from using Storybook with Angular as well.

**Comment by AliF50** [comment]
How I unblocked myself with regards to this error:

I clicked on the `parse.js:1083:17` error in the terminal (in VS Code, it should open up the file) and I was presented with a function that's similar to this:

![parse js](https://user-images.githubusercontent.com/22825890/155194259-27bb1048-69f2-410c-8451-8da505727db2.png)

I added the `console.log` (shown in picture) of line, column, parseState, stack, pos, token, key and root, saved the file, and re-ran the command. For me the `root` property gave me a hint as to which one of my files was causing the issue. It turns out I was using spread syntax (...) in route configuration file and although Angular was not complaining about it, compodoc did not like it. I rewrote the spread syntax into something else and compodoc was satisfied with that and the error did not appear anymore.

**Comment by vogloblinsky** [comment]
@AliF50 Do you have an example of your spread syntax please ?

**Comment by AliF50** [comment]
I think it was something like this:

`
const routes = [{
  path: 'abc',
  component: ComponentA,
}, {
  path: 'def',
  loadChildren: async () => (await import('./path/componentB')).ComponentBModule,
}].map(route => ({
   ...route,
   ...(route.component && canActivate: [FeatureGuard]),
   ...(route.loadChildren && canLoad: [FeatureGuard]),
}));
`

I am going off of memory but I am pretty sure it was like so. I just attached the respective canActivate and canLoad for every entry and removed the map to fix it.

**Comment by rasmus-e-christensen** [comment]
It seems to be something to do with the "..." notation that is causing trouble, in my case at least :) I want to use on a big project and can only use the minimal use of compodoc, which is helpful but not that much.

**Comment by syndesis** [comment]
I'm seeing it break in a similar way on a route like this:

```javascript
          {
            path: 'foo',
            canActivate: [AuthenticationGuard, FeatureFlagGuard],
            loadChildren: (): Promise<RouterModule> =>
              import('foo').then((m) => m.FeatureFooModule),
            data: {
              title: { name: 'Foo' },
              preload: true,
              featureFlagKey: FeatureFlags.FOO_FLAG,
              relativePathToRedirect: '..',
            },
          },
```

it dies on the `.` in `FeatureFlags.FOO_FLAG`

This may be related to https://github.com/json5/json5/issues/249

**Comment by admir86** [comment]
same problem when using `TimeUserEntry.JOB_DESIGNATION` direct in the `userEntries`. Using `TimeUserEntry.JOB_DESIGNATION` via a const works
```ts
const JD = TimeUserEntry.JOB_DESIGNATION;
const routes: Routes = [
  {
    path: '',
    component: TimeComponent,
    children: [
      {
        path: ROUTES.EMPLOYMENTS,
        loadChildren: () => import('@inova/basiskomponenten').then((m) => m.UserEntryModule),
        data: {
          userEntries: [JD],
        },
      },
      { path: ROUTES.CONFIGURATION, loadChildren: () => import('@inova/basiskomponenten').then((m) => m.DomainConfigurationModule) },
    ],
  },
];
```

**Comment by ghost** [comment]
I had a similar problem, my issue happens when using an enum value inside the paths of an angular routing module.
```ts
// enums.ts
export enum View {
  Main,
  Secondary,
  Critical
}

// routing.module.ts
import { Routes } from "@angular/router";
import { View } from "./enums";

export const routes: Routes = [
  {
    path: '',
    redirectTo: 'index',
    pathMatch: 'full'
  },
  {
    path: 'index',
    component: IndexComponent,
    canActivate: [AuthGuard],
    children: [
      {
        path: '',
        redirectTo: 'main',
        pathMatch: 'full'
      },
      {
        path: 'main',
        loadChildren: () =>
          import('./components/main.module').then(
            (m) => m.MainModule
          ),
        data: {
          tabState: View.Main // this kills the compodoc
        }
      },
      {
        path: 'secondary',
        loadChildren: () =>
          import('./components/secondary.module').then(
            (m) => m.SecondaryModule
          ),
        data: {
          tabState: View.Secondary // this kills the compodoc if the previous one didn't kill it already
        }
      },
    ]
  }
];
```

The issue is that the JSON the compodoc generates does not resolve the enum value and takes the literal value (here it puts the value as `View.Main` or `View.Secondary`, the dot accordingly causes the problem.

@admir86's solution worked in that case

**Comment by divyeshjethwa** [comment]
> How I unblocked myself with regards to this error:
> 
> I ctrl + clicked on the `parse.js:1083:17` error in the terminal (in VS Code, it should open up the file) and I was presented with a function that's similar to this:
> 
> ![parse js](https://user-images.githubusercontent.com/22825890/155194259-27bb1048-69f2-410c-8451-8da505727db2.png)
> 
> I added the `console.log` (shown in picture) of line, column, parseState, stack, pos, token, key and root, saved the file, and re-ran the command. For me the `root` property gave me a hint as to which one of my files was causing the issue. It turns out I was using spread syntax (...) in route configuration file and although Angular was not complaining about it, compodoc did not like it. I rewrote the spread syntax into something else and compodoc was satisfied with that and the error did not appear anymore.
> 
> Unless if I missed it, I think it would be good if Compodoc can show in red bold text which file was scanned and caused the error.

I followed your steps the same way. Added console.log in the parse.js and it pointed out what was causing the problem
You rock

**Comment by spyro2000** [comment]
Still same problem with 1.1.19.

In routes:

Explodes:
```typescript
{
        path: 'my-component',
        component: MyComponent,
        data: { propertyName: MyEnum.myValue},
 },
````

Runs:
```typescript
{
        path: 'my-component',
        component: MyComponent,
        data: { propertyName: 'myValue'},
 },
````

Did only find that out by debugging the json builder.

**Comment by ElfenB** [comment]
This is also an issue for me. I can temporarily fix it by removing the '.' within the require statement but I wouldn't consider this a fix because of course I have to change it after every new npm install ...

`parse.js`
``` javascript
// before
const util = require('./util')
// after
const util = require('util')
```

`terminal output (excerpt)`
``` shell
reason: SyntaxError: JSON5: invalid character '.' at 1:40
    at syntaxError (C:\_projects\my-project\node_modules\json5\lib\parse.js:1083:17)
```

**Comment by Nathanrs15** [comment]
> How I unblocked myself with regards to this error:
> 
> I ctrl + clicked on the `parse.js:1083:17` error in the terminal (in VS Code, it should open up the file) and I was presented with a function that's similar to this:
> 
> ![parse js](https://user-images.githubusercontent.com/22825890/155194259-27bb1048-69f2-410c-8451-8da505727db2.png)
> 
> I added the `console.log` (shown in picture) of line, column, parseState, stack, pos, token, key and root, saved the file, and re-ran the command. For me the `root` property gave me a hint as to which one of my files was causing the issue. It turns out I was using spread syntax (...) in route configuration file and although Angular was not complaining about it, compodoc did not like it. I rewrote the spread syntax into something else and compodoc was satisfied with that and the error did not appear anymore.
> 
> Unless if I missed it, I think it would be good if Compodoc can show in red bold text which file was scanned and caused the error.

This worked for me.  I found that it complains about a resolver class: 

❌ Bad:

`{path: 'some-path', resolver: { ResolverClass } ...}`

👍 Good:

`{path: 'some-path', resolver: { name: ResolverClass } ...}`

**Comment by ivanFlor3s** [comment]
> This is also an issue for me. I can temporarily fix it by removing the '.' within the require statement but I wouldn't consider this a fix because of course I have to change it after every new npm install ...
> 
> `parse.js`
> 
> ```js
> // before
> const util = require('./util')
> // after
> const util = require('util')
> ```
> 
> `terminal output (excerpt)`
> 
> ```shell
> reason: SyntaxError: JSON5: invalid character '.' at 1:40
>     at syntaxError (C:\_projects\my-project\node_modules\json5\lib\parse.js:1083:17)
> ```

It solved my problem when generating documentation

**Comment by enrosales** [comment]
<img width="783" alt="error in compodoc" src="https://github.com/compodoc/compodoc/assets/24546669/bddfee86-2343-474f-939c-f6fffd117368">

in my case doing this and setting clg() in the syntaxError function fix the problem

**Comment by markwhitfeld** [comment]
@AliF50's [approach of adding the console log](https://github.com/compodoc/compodoc/issues/1124#issuecomment-1048083430) helped me identify the issue.
For anyone that would like to copy paste the console log, here it is:
```ts
console.log({line, column, parseState, stack, pos, token, key, root})
```
