### ISSUE TITLE
[FEATURE] Support add Promise return

### ISSUE THREAD

**Issue by JuraAkaGosha** [compodoc/compodoc#113]
Can you add that feature:
if i write in typescript:
`public signIn(): Promise<string>`
in compodoc i have: `Returns: Promise<string>`?
Thank you, compodoc!

**Comment by vogloblinsky** [comment]
Hi @JuraAkaGosha seems to be ok in last version : https://github.com/compodoc/compodoc/releases/tag/1.0.0-beta.4
