### ISSUE TITLE
[FEATURE] Recognize ngOnInit() as a method

### ISSUE THREAD

**Issue by jhkeung** [compodoc/compodoc#114]
##### **Overview of the issue**

I noticed that the ngOnInit() method is not present in the generated documentation. I would expect it to be listed under the 'Methods' section on the page of the component that implements the OnInit interface. If the method is listed elsewhere, I have been unable to locate it. Other component methods and properties, along with descriptions, are visible so I do not believe this is a configuration error.

Thanks for your hard work on compodoc! 

##### **Operating System, Node.js, npm, compodoc version(s)**

MacOS Sierra 10.12.3, compodoc 0.0.41, Node.js 7.5.0, npm 4.1.2

**Comment by vogloblinsky** [comment]
Thanks for the feedback.
Yes it is clear that it need to be displayed. I have fixed that. It will come in the next big release (1.0.0) next week.
