### ISSUE TITLE
[FEATURE] When component has a setter as input parameter type is not populated in inputClass structure

### ISSUE THREAD

**Issue by dimitriliberman** [compodoc/compodoc#1142]
##### **Overview of the feature**
I am trying to use compdoc with storybook. After json file generated and i try to use it with storybook - it does not render parameters datatype or allows to enter values for story in argument section of storybook.

I have the following input parameter that defined as a setter

`
  @Input()
  set config(config: DataTableConfig) {
      this.config$.next(config);
  }
`

After processing with compdoc and generating json file, that parameter defined without type:

            "inputsClass": [
                {
                    "name": "config",
                    "deprecated": false,
                    "deprecationMessage": "",
                    "line": 69,
                    "type": ""
                },

It would be nice if compdoc would pickup type for setter like that:

            "inputsClass": [
                {
                    "name": "config",
                    "deprecated": false,
                    "deprecationMessage": "",
                    "line": 69,
                    **"type": "DataTableConfig"**
                },

##### **Motivation for or Use Case**
If i update type manually parameters get picked up by story book.
Not sure if that is compdoc issue or storybooks. But I figured will start with the source that is used to generate storybook - compdoc.

**Comment by vogloblinsky** [comment]
Seems to be fixed with my last test

<img width="294" alt="image" src="https://user-images.githubusercontent.com/2841805/153293252-3cb5ae30-6384-4d04-b59c-2d44e519a2b3.png">
