### ISSUE TITLE
[BUG] Unhandled Rejection at: Promise (  rejected» TypeError: type.toLowerCase is not a function

### ISSUE THREAD

**Issue by Prasanth-FrontEnd** [compodoc/compodoc#1152]
While running npm run build-storybook, it throws error like:

Unhandled Rejection at: Promise (

rejected» TypeError: type.toLowerCase is not a function

at BasicTypeutil. isJavascriptType (C: \Users \folder \project name\node modules (@compodoc \ compodoc \distlindex-cli.js:1626:2

5)

**Comment by vogloblinsky** [comment]
Which version did you use ?

**Comment by Prasanth-FrontEnd** [comment]
1.1.8

**Comment by vogloblinsky** [comment]
Could you upgrade to last version please and said if the bug is still here ?

**Comment by Prasanth-FrontEnd** [comment]
After upgrading to the latest version, it's working fine.

**Comment by vogloblinsky** [comment]
Thanks for the feedback
