### ISSUE TITLE
[QUESTION] Roboto License missing?

### ISSUE THREAD

**Issue by tunessofia** [compodoc/compodoc#1154]
For Roboto usage:

The Apache License Version 2.0 requires that on redistribution we must give a copy of the license.

(a) You must give any other recipients of the Work or Derivative Works a copy of this License; and

Isn't this repo missing a license for this? I'm having this doubt, because in my project we are using compodoc and blackduck is accusing a missing license, since compodoc redistributes the font.

**Comment by vogloblinsky** [comment]
Ok, so what do you mean, i have to copy this file (https://github.com/googlefonts/roboto/blob/main/LICENSE) in compodoc repository ?
