### ISSUE TITLE
[FEATURE] ng add support

### ISSUE THREAD

**Issue by doggy8088** [compodoc/compodoc#1155]
##### **Overview of the feature**

```sh
ng add @compodoc/compodoc
```

1. Add default `tsconfig.doc.json` for normal Angular project.

2. Add `scripts` section for `package.json`

##### **Motivation for or Use Case**

Good for Angular beginner.

##### **Related issues**

N/A

**Comment by vogloblinsky** [comment]
Is these scripts ok for you ?
```
'compodoc:build': 'compodoc -p tsconfig.doc.json',
'compodoc:build-and-serve': 'compodoc -p tsconfig.doc.json -s',
'compodoc:serve': 'compodoc -s'
```
