### ISSUE TITLE
[BUG] imported types are not included in the generated documentation

### ISSUE THREAD

**Issue by NausheenAkhter** [compodoc/compodoc#1162]
Not able to get metadata of the imported types or enums

I am able to get datatypes which is there in the file but not the imported ones.

I am working on versions:
Node: v14.18.1
npm: 6.14.15
compodoc: 1.1.16

##### **Angular configuration, a `package.json` file in the root folder**
    "docs:json": "compodoc -p ./tsconfig.doc.json -e json --minimal"
this is script I am running from package.json file

##### **Motivation for or Use Case**

 not able to give the users detailed information about the custom types

**Comment by vogloblinsky** [comment]
Could you provide an example please ?

**Comment by NausheenAkhter** [comment]
let's say, there is one file where we are keeping all our custom types:

types.ts

```
export type Sizes =
  | 'small'
  | 'medium'
  | 'large'
```
  
  Now we are importing this file into our component file:
  app.component.ts
  
```
  import { Sizes } from '../../types';
export class App extends BaseComponent {
  /**
   * Determines the view sizes
   */
  @Input() size?:Sizes = 'small';
  // here goes the render part
}
```
In the above case, I am not getting type of size as  'small'
  | 'medium'
  | 'large'
  
  instead what I am getting is text 'Sizes'.

**Comment by vogloblinsky** [comment]
Sorry, just tested, you got for me enough information with this : 
![image](https://user-images.githubusercontent.com/2841805/145392171-9ab71220-f4b8-424e-960a-8c19a9426ea3.png)

**Comment by NausheenAkhter** [comment]
How would I get the detailed types of type "`Sizes`"? 
I am trying to get all the types as 'small' | 'medium' | 'large' but I am unsuccessful on doing that.

**Comment by vogloblinsky** [comment]
No sorry, but for me, the user could click on `Sizes`link to get information about this Type alias.

Typedoc does the same thing :

![image](https://user-images.githubusercontent.com/2841805/145584728-97714d35-c1a7-4a8e-aa78-29f9378901ac.png)

**Comment by NausheenAkhter** [comment]
I am not able to get it in the json file created using exportFormat like `-e json`.

**Comment by vogloblinsky** [comment]
What did you miss ?

**Comment by NausheenAkhter** [comment]
For my use case, I am having 4 different custom types stored in the different directories with the same type name. When I was going through the `typealiases.html`, I found that the href for all 4 types are same as `#TYPE_NAME`, How would I differentiate that what is there for which component?

**Comment by NausheenAkhter** [comment]
<img width="1457" alt="Screenshot 2021-12-16 at 4 06 08 PM" src="https://user-images.githubusercontent.com/30772381/146355966-3511e325-36ff-4c6e-b14c-bd4815da69ef.png">


I want to see what is the exact type of the input I clicked rather it is showing me all available types with that name

**Comment by vogloblinsky** [comment]
I don't think it'is possible, Compodoc does a static analysis of the source code.
