### ISSUE TITLE
[FEATURE] Versioning support

### ISSUE THREAD

**Issue by wlucha** [compodoc/compodoc#1163]
##### **Overview of the feature**

Versioning functionality for compodoc generated documentation (similar to Docusaurus: https://docusaurus.io/docs/versioning)

##### **Motivation for or Use Case**

Currently documentation generated by compodoc doesn't support history versioning which is needed for Angular libraries.

##### **Related issues**

https://github.com/compodoc/compodoc/issues/40

**Comment by vogloblinsky** [comment]
Can you explain a little more what could be the role of compodoc for this feature ?
Handling versions for Compodoc can be quickly a nightmare (diff, etc).

**Comment by relliv** [comment]
> Can you explain a little more what could be the role of compodoc for this feature ? Handling versions for Compodoc can be quickly a nightmare (diff, etc).

It can be manual or depends on the version number in package.json. Actually, I want to see a version list in UI. Otherwise, I have to create subfolders for versioning manually.

**Comment by voelkerb** [comment]
Would love to have such a feature as well. Creating subfolders is my current way to go too but having a dropdown in the docs to quickly select the version would be nice. Maybe using an additional manually updated config file in the root folder.
