### ISSUE TITLE
[BUG] issue with story book

### ISSUE THREAD

**Issue by GestHairHome** [compodoc/compodoc#1166]
when running following npm run storybook following appear :

> Unhandled Rejection at: Promise {
>   <rejected> SyntaxError: JSON5: invalid character '.' at 1:187
>       at syntaxError (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:1083:17)
>       at invalidChar (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:1028:12)
>       at Object.afterArrayValue (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:672:15)
>       at Object.default (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:146:37)
>       at lex (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:78:42)
>       at Object.parse (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:25:17)
>       at loopInsideModule (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/@compodoc/compodoc/dist/index-cli-298ea115.js:6103:63)
>       at loopRoutesParser (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/@compodoc/compodoc/dist/index-cli-298ea115.js:6136:29)
>       at loopRoutesParser (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/@compodoc/compodoc/dist/index-cli-298ea115.js:6141:21)
>       at loopRoutesParser (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/@compodoc/compodoc/dist/index-cli-298ea115.js:6141:21) {
>     lineNumber: 1,
>     columnNumber: 187
>   }
> } reason: SyntaxError: JSON5: invalid character '.' at 1:187
>     at syntaxError (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:1083:17)
>     at invalidChar (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:1028:12)
>     at Object.afterArrayValue (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:672:15)
>     at Object.default (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:146:37)
>     at lex (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:78:42)
>     at Object.parse (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/json5/lib/parse.js:25:17)
>     at loopInsideModule (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/@compodoc/compodoc/dist/index-cli-298ea115.js:6103:63)
>     at loopRoutesParser (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/@compodoc/compodoc/dist/index-cli-298ea115.js:6136:29)
>     at loopRoutesParser (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/@compodoc/compodoc/dist/index-cli-298ea115.js:6141:21)
>     at loopRoutesParser (/Users/gesthairhome/Applis/my-promantis/my-promantis-app/node_modules/@compodoc/compodoc/dist/index-cli-298ea115.js:6141:21) {
>   lineNumber: 1,
>   columnNumber: 187
> }
> [11:24:16] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
>

**Comment by vogloblinsky** [comment]
Can i have the use-case of storybook for reproduce this bug please ?

**Comment by rasmus-e-christensen** [comment]
There are some examples of this bug in #1124 but whether they are used with Storybook is a good question.
