### ISSUE TITLE
[BUG] >1.1.7 isn't able to read `package.json` (REGRESSION)

### ISSUE THREAD

**Issue by stefan-schweiger** [compodoc/compodoc#1174]
##### **Overview of the issue**

I've updated from 1.1.4 to 1.1.8 (everything else stayed the same) and got this error message:

```
[16:56:55] Error during C:\<workspace root>\libs\shared\ui\storybook\package.json read

[16:56:55] 
Continuing without package.json file
```

I've tried to go trough all versions between 1.1.4 and 1.1.8 and the issue only appears in 1.1.7 and 1.1.8.

From the error message I'm guessing that compodoc tries to find the `package.json` file in the directory of the nx project I'm running and not in the workspace root where it is actually located (`C:\<workspace root>\package.json`).

##### **Operating System, Node.js, npm, compodoc version(s)**

```
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (97.0.1072.55)
  npmPackages:
    @nrwl/nx: 13.3.6
    @angular: 13.0.9
    @storybook: 6.4.9
    @compodoc: 1.1.8
```

##### **Angular configuration, a `package.json` file in the root folder**

To be honest I don't understand what exactly you want?

##### **Compodoc installed globally or locally ?**

Locally

##### **Reproduce the error**

I will try to create a reproduction tomorrow, if this is still relevant by then. But for now updating compodoc in my angular/nx project to 1.1.7/1.1.8 was enough to get this error.

**Comment by stefan-schweiger** [comment]
@vogloblinsky here is my repro https://github.com/stefan-schweiger/compodoc-1.1.8-package-bug

To run it use

```
yarn install
nx run nx13-app:compodoc
```

Works perfectly fine with 1.1.6. but breaks with 1.1.7. and 1.1.8

**Comment by vogloblinsky** [comment]
I have tested your repro. What is the problem ?
The file in the log doesn't exist, and compodoc generate the doc correctly.

**Comment by stefan-schweiger** [comment]
@vogloblinsky that it prints this error right at the beginning. It still "works" in the sense that it generates output, but it doesn't use the `package.json`.

```
[16:56:55] Error during C:\<workspace root>\libs\shared\ui\storybook\package.json read
[16:56:55] Continuing without package.json file
```

**Comment by stefan-schweiger** [comment]
@vogloblinsky before 1.1.7 it didn't print this error, so I'm assuming it tries to resolve the wrong `package.json` instead of the one in the workspace root.

**Comment by stefan-schweiger** [comment]
@vogloblinsky I've now tried to debug compodoc myself and I can't find anything obviously wrong because it just uses `process.cwd()`. But I still can't figure out why updating from 1.1.6 to 1.1.7 would change any behavior of where the process working directory is located. I don't see any changed which could cause this except for updated packages maybe https://github.com/compodoc/compodoc/compare/1.1.16...1.1.17

@twittwer could this be in any way related to the implementation in `@twittwer/compodoc`?

**Comment by twittwer** [comment]
The executor uses the project's root (except when running in workspaceDocs mode). [Code](https://github.com/twittwer/nx-tools/blob/9b3add3526bad0cdf568d37982b1ff0ed94a9b5b/packages/compodoc/src/executors/build/executor.ts#L29-L31)

**Comment by stefan-schweiger** [comment]
@vogloblinsky I finally had time to look into this again, and it seems like the error was always there when using it for `nx` projects, but it just wasn't printed in silent mode (default for nx). I'm guessing some lib updated changed this behavior. Probably the upgrade from `fancy-log@^1.3.3` to `fancy-log@^2.0.0`.

@twittwer the cwd which compodoc gets when running with `nx`/`@twittwer/compodoc` is the app/lib folder. Therefore the error message is correct.

## What to do next?

What are the implications of not being able to use `package.json`? Should we try to fix it?

If we try to fix it I could see 3 options:

- Make compodoc traverse the tree up to look for `package.json`
- Try if we can influence the cwd in `@twittwer/compodoc`
- Add an option to compodoc to specify the `package.json` location

Any opinions?

**Comment by twittwer** [comment]
@stefan-schweiger @jogelin
Like I said, by default the library is used as working directory and in case of the [workspaceDocs mode](https://github.com/twittwer/nx-tools/tree/main/packages/compodoc#workspace-docs) the workspace root.

I don't know what the package.json is used for. In case of dependency analysis, it seems correct to use the library and not the workspace as buildable libraries have their own package.json.

**Comment by jogelin** [comment]
@twittwer maybe we could just have a fallback? If the library package.json doesn't exist, then we use the workspace one?
