### ISSUE TITLE
[BUG] Compodoc tsconfig path resolution is broken on windows machines

### ISSUE THREAD

**Issue by kroeder** [compodoc/compodoc#1195]
##### **Overview of the issue**

If you run Compodoc with the `-p` flag and pass in an absolute path on windows machines, it results in an error

Storybook passes in an absolute path like this 

```
-p D:\Development\storybook-example\.storybook\tsconfig.json
```

and the result is 

```
Error: error TS5083: Cannot read file 'D:\Development\storybook-example\D:\Development\storybook-example\.storybook\tsconfig.json'.
```

It seems like it adds `process.cwd()` to the already absolut path and causes a duplication

We figured out that this might be the line where things go wrong for windows users 

https://github.com/compodoc/compodoc/blob/develop/src/index-cli.ts#L708

We worked around this by always passing in a relative path
https://github.com/storybookjs/storybook/pull/17334/files

##### **Operating System, Node.js, npm, compodoc version(s)**

```
Windows
node v16.13.1
@compodoc/compodoc: 1.1.18
```

##### **If possible sourcecode of the file where it breaks**

[](https://github.com/compodoc/compodoc/blob/develop/src/index-cli.ts#L708)

##### **If possible your terminal logs before the error**

```
compodoc -p D:\Development\storybook-example\.storybook\tsconfig.json -d D:\Development\storybook-example -e json

1.1.18

TypeScript version used by Compodoc : 4.5.5

TypeScript version of current project : 4.5.2

Node.js version : v16.13.1


Operating system : Windows 10



[09:28:06] 
No configuration file found, switching to CLI flags.

[09:28:06]
Using tsconfig file : D:\Development\storybook-example\D:\Development\storybook-example\.storybook\tsconfig.json

D:\Development\storybook-example\node_modules\@compodoc\compodoc\dist\index-cli-a4b7f403.js:1016
        throw new Error(message);
        ^

Error: error TS5083: Cannot read file 'D:\Development\storybook-example\D:\Development\storybook-example\.storybook\tsconfig.json'.

    at readConfig (D:\Development\storybook-example\node_modules\@compodoc\compodoc\dist\index-cli-a4b7f403.js:1016:15)
    at CliApplication.start (D:\Development\storybook-example\node_modules\@compodoc\compodoc\dist\index-cli-a4b7f403.js:13690:40)
    at Object.<anonymous> (D:\Development\storybook-example\node_modules\@compodoc\compodoc\bin\index-cli.js:6:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

An unexpected error occurred: undefined
```

##### **Reproduce the error**

Use absolute path for `-p` flag on windows machines

##### **Suggest a Fix**

Probably add another `else if` or update

```
                    let _file = path.join(
                        path.join(process.cwd(), path.dirname(Configuration.mainData.tsconfig)),
                        path.basename(Configuration.mainData.tsconfig)
                    );
```

As said, in Storybook we fixed it using this code: 

```
const toRelativePath = (pathToTsConfig: string) => {
  return path.isAbsolute(pathToTsConfig) ? path.relative('.', pathToTsConfig) : pathToTsConfig;
};
```

**Comment by vogloblinsky** [comment]
@kroeder Cannot reproduce the bug with the demo project (https://github.com/compodoc/compodoc-demo-todomvc-angular) on Windows.
Could you make one with storybook installed ? thanks

**Comment by kroeder** [comment]
I can do that! It will take a bit of time, though. I don't have much time for OSS for the next 1-2 weeks
I'll give you feedback here as soon as I have a reproduction!

**Comment by BirgitNoegel** [comment]
Hello,
maybe I have the similar problem in the uploaded project. The base path is: c:\projekte\. 
On calling 'npm run storybook-build' everything is ok - on calling 'npm  run storybook-watch' I get the following error:

The storybook can be opened, but is does not contains the Docs.

Here are some details about my windows-machine:
Edition	Windows 10 Enterprise
Version	21H2
Betriebssystembuild	19044.1586
Leistung	Windows Feature Experience Pack 120.2212.4170.0

          _**_PS C:\Projekte\product-apps> npm run storybook-watch
          
          > product-apps@0.0.0 storybook-watch
          > nx run workspace:storybook-watch
           
          > nx run workspace:storybook-watch
                  
          > nx run workspace:compodoc:json --watch
                   
          > nx run workspace:storybook
         
           info => Loading presets
          [nodemon] 2.0.15
          
          [nodemon] to restart at any time, enter `rs`
          [nodemon] watching path(s): *.*
          [nodemon] watching extensions: ts
          
          [nodemon] starting `node_modules\\.bin\\compodoc --tsconfig=C:\\Projekte\\product-apps\\libs\\workspace\\tsconfig.compodoc.json --output=C:\\Projekte\\product-apps\\dist\\compodoc\\wor
          kspace --exportFormat=json --minimal --name=product-apps --includes=..\\..\\Temp\\compodoc-includes-muQkIN --includesName=Projects --disableCoverage --disablePrivate --disableInternal 
          --disableLifeCycleHooks --language=en-US --theme=gitbook --serve`
          
          1.1.19
          
          
          TypeScript version used by Compodoc : 4.5.5
          
          
          TypeScript version of current project : 4.5.2
          
          
          Node.js version : v16.13.2
          
          
          info => Using implicit CSS loaders
          info => Loading angular-cli config for angular >= 13.0.0
          info => Using angular browser target options from "workspace:build-storybook"
          info => Using angular project with "tsConfig:C:\Projekte\product-apps\libs\workspace\.storybook\tsconfig.json"
          Operating system : Windows 10
          
          
          
          [18:27:48] 
          No configuration file found, switching to CLI flags.
          
          **[18:27:49]
          Using tsconfig file : C:\Projekte\product-apps\C:\Projekte\product-apps\libs\workspace\tsconfig.compodoc.json
          
          C:\Projekte\product-apps\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:1034
                  throw new Error(message);
                  ^
          
          Error: error TS5083: Cannot read file 'C:\Projekte\product-apps\C:\Projekte\product-apps\libs\workspace\tsconfig.compodoc.json'.
          
              at readConfig (C:\Projekte\product-apps\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:1034:15)
              at CliApplication.start (C:\Projekte\product-apps\node_modules\@compodoc\compodoc\dist\index-cli-f7393cac.js:13827:40)
              at Object.<anonymous> (C:\Projekte\product-apps\node_modules\@compodoc\compodoc\bin\index-cli.js:6:5)
              at Module._compile (node:internal/modules/cjs/loader:1101:14)
              at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
              at Module.load (node:internal/modules/cjs/loader:981:32)
              at Function.Module._load (node:internal/modules/cjs/loader:822:12)
              at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
              at node:internal/main/run_main_module:17:47
          
          [nodemon] app crashed - waiting for file changes before starting..._****_
          

[product-apps.zip](https://github.com/compodoc/compodoc/files/8391328/product-apps.zip)
