### ISSUE TITLE
Error when semi-colon after class function

### ISSUE THREAD

**Issue by isaacplmann** [compodoc/compodoc#12]
I get an error `RangeError: Invalid array length` when there is a semi-colon after a class function.

e.g.
```js
@Component({...})
export class SomeComponent {
  testFunction(): void {
  };
}
```

It's not really a problem to delete the extraneous semi-colons, but the error message could be a little more helpful.  It took me a while to find the problem.

**Comment by vogloblinsky** [comment]
Fixed in next release.
