### ISSUE TITLE
[FEATURE] - Ability to set RawTypes from dynamic custom typescript types

### ISSUE THREAD

**Issue by sir-captainmorgan21** [compodoc/compodoc#1216]
##### **Overview of the feature**

Hi. I am looking for the ability to set RawTypes from dynamic custom typescript types.

##### **Motivation for or Use Case**

I have the following type defined

```
import SAJ_COLORS from '../../../style/src/lib/style-dictionary-build/json/_colors.json';

type SAJIconColors = keyof typeof SAJ_COLORS;
```

I am using Storybook. When defining types explicitly like `type MyType = 'test' | 'test1' | 'test2';` it makes a `rawType` property in the output for any properties that use that type. Storybook then displays that as radio button options. However, with the dynamic types, it doesn't create a rawtype property, so the argtable value changer is just freeform text. The user isn't aware of the options. The location of the object that we are deriving the keys from is available. Can that be used?

##### **Related issues**
None that I could find.

**Comment by sir-captainmorgan21** [comment]
Bumping

**Comment by sir-captainmorgan21** [comment]
bumping

**Comment by sir-captainmorgan21** [comment]
bumping

**Comment by sir-captainmorgan21** [comment]
bumping

**Comment by sir-captainmorgan21** [comment]
@vogloblinsky can we get a look at this?

**Comment by ptu14** [comment]
Same issue with `as const`.

e.g. 

```typescript
const LETTERS = ['a', 'b', 'c'] as const;
type Letter = (typeof LETTERS)[number];
```

then in Angular 

```typescript
@Input() letter: Letter = 'a';
```

or

```typescript
@Input() letter: (typeof LETTERS)[number] = 'a';
```

Compodoc generete blank `rawtype`
