### ISSUE TITLE
[BUG] @internal JSDoc not getting captured

### ISSUE THREAD

**Issue by TheColorRed** [compodoc/compodoc#1221]
##### **Overview of the issue**

Methods are not picking up the `@internal` JSDoc

```typescript
  /** @internal */
  setClasses(): void {
  }
```
![image](https://user-images.githubusercontent.com/1571806/155167482-77ade2f1-8282-453f-975b-7ae0d8a9a7f7.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

* Compodoc: 1.1.18
* Mac: 10.15.7
* Node: 16.13.2
* NPM: 8.1.2

##### **Compodoc installed globally or locally ?**

Locally

**Comment by vogloblinsky** [comment]
Did you use the option `--disableInternal`?

**Comment by TheColorRed** [comment]
No I didn't:

package.json:

```
"docs:json": "compodoc -p ./tsconfig.json -t -e json -d .",
```

**Comment by vogloblinsky** [comment]
Ok so this should works : `compodoc -p ./tsconfig.json --disableInternal -t -e json -d .`

**Comment by TheColorRed** [comment]
That does work for my current case, however, if I did want that generated, it wouldn't be there.
