### ISSUE TITLE
[FEATURE] Can we have an option to specify the code syntax color?

### ISSUE THREAD

**Issue by shane-abbas** [compodoc/compodoc#123]
There are two reasons for needing this. One, the monokai theme looks good always. Two, there is coloring issue when I use the readthedocs theme with parameters appearing transparent in arrow functions.

I think it would be ideal if we can specify the syntax color, or always have it be monokai. Thanks for this tool though, we are currently using it in our project and loving it. Any news on version 1 that was supposed to come out?

**Comment by vogloblinsky** [comment]
I have fixed right now all design issues with themes & monokai syntax color.
Yes it could be added in version 1, i add this in requested features list.
I still have two bugs to fix for new features of version, and release will coming soon next week.
