### ISSUE TITLE
[BUG] Missing jsdoctags for a component

### ISSUE THREAD

**Issue by okadurin** [compodoc/compodoc#1233]
##### **Compodoc installed locally**

When running `compodoc -p ./tsconfig.base.json --disableTemplateTab --disableGraph --disablePrivate --disableInternal --disableLifeCycleHooks --disableRoutesGraph --disableSearch --exportFormat json`

the `documentation.json` doesn't contain `jsdoctags` for a component itself. The error is present in compodoc 1.1.15 and 1.1.19. But `jsdoctags` is displayed in compodoc 1.1.11. The expectation is that `jsdoctags` should be preset in the `documentation.json` for the latest version of compodoc.

**Comment by MikeMatusz** [comment]
@vogloblinsky should this be reopened? I'm on 1.1.19 and I don't see `jsdoctags` generated for any top-level entity (e.g. components, pipes, injectables, etc.)
