### ISSUE TITLE
[BUG] Issue with type being `Subscription | Promise<any>`

### ISSUE THREAD

**Issue by superKalo** [compodoc/compodoc#124]
##### **Operating System, Node.js, npm, compodoc version(s)**

- Operating System: MacOS Sierra
- Node.js: 7.4.0
- NPM: 4.0.5
- compodoc: 0.0.41

##### **Angular configuration, a `package.json` file in the root folder**

```json
{
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "rxjs": "^5.1.0",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.1",
    "@angular/compiler-cli": "^2.4.0",
    "@types/jasmine": "2.5.38",
    "@types/lodash": "^4.14.54",
    "@types/node": "^6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typescript": "~2.0.0"
  }
}
```

##### **Compodoc installed globally or locally ?**

Globally

##### **Motivation for or Use Case**

I just want to see the types of my class properties.

##### **Reproduce the error**

I have the following component:

```typescript
import { Component } from '@angular/core';

@Component({
  selector: 'random-component',
  template: `
    <h1>Bla bla</h1>
  `
})
export class RandomComponent {
  prop: Subscription | Promise<any>;

  constructor() { }

}
```

In the generated documentation for this component, the property `prop` type is `any`, which is wrong. The type should be `Subscription | Promise<any>`.

<img width="228" alt="screen shot 2017-03-20 at 13 02 23" src="https://cloud.githubusercontent.com/assets/2548061/24097202/a6dd2db8-0d6d-11e7-87d8-4a3316a2de7f.png">

If I change the property `prop` type to `string | number` in my Angular 2 Component (just for the sake of testing), the `prop` type is now displayed correctly.

<img width="217" alt="screen shot 2017-03-20 at 13 05 50" src="https://cloud.githubusercontent.com/assets/2548061/24097328/f8f35abe-0d6d-11e7-8e83-a85b74ab4d9c.png">

##### **Related issues**

I don't find any.

##### **Suggest a Fix**

Unfortunately, I am not being able to help by a fix suggestion :-)

**Comment by vogloblinsky** [comment]
Hi @superKalo 

Just made a test with the [demo project](https://github.com/compodoc/compodoc-demo-todomvc-angular)

```
import { Component } from '@angular/core';
import { Todo } from './shared/models/todo.model';

/**
 * The main component
 */
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    prop: Todo | Promise<any>;

    constructor() { }
}
```

gives me `prop: Todo | Promise<any>`in Compodoc

```
import { Component } from '@angular/core';

/**
 * The main component
 */
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.css']
})
export class AppComponent {
    prop: Todo | Promise<any>;

    constructor() { }
}
```

Gives me like you `prop: any`

So you maybe miss to import `Subscription` in your file.
