### ISSUE TITLE
[FEATURE] Ability to adjust the order in which method calls appear

### ISSUE THREAD

**Issue by haleysulcer** [compodoc/compodoc#1249]
##### **Overview of the feature**

Currently, the component and service methods appear in alphabetical order. I want the ability to have the method calls appear in the order in which they appear in the code.

##### **Motivation for or Use Case**

I organize them in a particular way from the top, and I'd want the documentation to reflect that. 

Because they're being shown in alphabetical order, the lifecycle hooks (including `ngOnInit()` and `ngOnChanges()`) are in the middle of the page, but ideally they should appear at the top since they're called in the beginning.

##### **Related issues**

I did not see any similar issues in GitHub, nor via a Google search.

**Comment by rojasjandro89** [comment]
+1
I would love to be able to do this... alphabetical order is just not good enough.
