### ISSUE TITLE
[FEATURE] Embed Documentation Coverage Report as a Badge

### ISSUE THREAD

**Issue by superKalo** [compodoc/compodoc#125]
##### **Overview of the issue**

I can't seem to find info how I can embed the Documentation Coverage report badge in my project main README.MD file.

<img width="308" alt="screen shot 2017-03-20 at 19 26 04" src="https://cloud.githubusercontent.com/assets/2548061/24112954/d8ea9850-0da3-11e7-9e4c-864a34773d91.png">

##### **Motivation for or Use Case**

I would love to show the Documentation Coverage report badge in my project main README.MD file. Any general guidelines how to do that would be great :-)

**Comment by vogloblinsky** [comment]
Hi,
It is not a badge like those available on https://shields.io.
It is just a badge available in code of your generated doc.
I could generate a svg rather than html code, but you will have to had your generated doc available online.

README.md <->  http://MY-DOC-ONLINE/documentation-coverage.svg

**Comment by superKalo** [comment]
That would do the trick I guess 👍

**Comment by superKalo** [comment]
@vogloblinsky that's great! Thank you! :)

I am looking forward to the next [version bump](https://github.com/compodoc/compodoc/releases), so I can grab this new feature 🌻

**Comment by vogloblinsky** [comment]
Here is the last, i miss to publish the tag and update github.

https://github.com/compodoc/compodoc/releases/tag/1.0.0-beta.1

**Comment by superKalo** [comment]
Thanks!! 👍

**Comment by superKalo** [comment]
Hm, @vogloblinsky , could you please update the NPM registry too. When I do:

```
npm install compodoc@latest --save
```

I still receive version `0.0.41`. See: https://www.npmjs.com/package/compodoc

**Comment by vogloblinsky** [comment]
Extract from changelog and official doc

# Breaking changes

@compodoc/compodoc : compodoc has moved to @compodoc/compodoc

**Comment by superKalo** [comment]
Oh, sorry about that, my bad :)
