### ISSUE TITLE
Handlebar Template Overrides

### ISSUE THREAD

**Issue by janstadt** [compodoc/compodoc#1253]
##### **Overview of the issue**
Im not seeing the pages.hbs file getting overridden when i use the `--templates` argument via the CLI or the `templates` property in the compodocrc.json file. 

Have a `pages.hbs` file in a folder titled `templates`. 

`npx @compodoc/compodoc -d ./docs/.debug -p ./docs/tsconfig.doc.json --templates ./docs/templates`

##### **Operating System, Node.js, npm, compodoc version(s)**
OS: Windows 10 and Mac Monterey. 
Node: v16.15.0
npm: 8.5.5
compodoc: 1.1.19

##### **Angular configuration, a `package.json` file in the root folder**
Unrelated to angular.

##### **Compodoc installed globally or locally ?**
Locally installed as a dev dep.

##### **If possible sourcecode of the file where it breaks**

Following this test as an example: 
https://github.com/compodoc/compodoc/blob/18be3504a858b7d45f11e2106b6cda224e6925e8/test/src/cli/cli-templates.spec.ts

Looking through the source i dont see how the .templates override ever gets to the pages when using the default `html` output:
https://github.com/compodoc/compodoc/blob/18be3504a858b7d45f11e2106b6cda224e6925e8/src/app/application.ts#L115-L119

Some other spots where i see the templates override but doesnt seem to be honored for actual pages: 
https://github.com/compodoc/compodoc/blob/18be3504a858b7d45f11e2106b6cda224e6925e8/src/app/application.ts#L2391

##### **If possible your terminal logs before the error**
None

**Comment by janstadt** [comment]
Slightly unrelated, but i see there is a reference to bootstrap-native and its like 4 years old. Any chance that could be updated? Im trying to render some example pages using existing libs in the `js/libs` directory and am getting an error with tabs not firing. If i replace the reference to `js/libs/bootstrap-native.js` with `https://cdn.jsdelivr.net/npm/bootstrap.native@3.0.15/dist/bootstrap-native-v4.min.js` the tabs function as expected.

**Comment by Voo2** [comment]
I have the same problem. For me, this feature is incredibly important, which is why I'm also very interested in seeing that there is a solution.

**Comment by Voo2** [comment]
btw: menu.hbs and other files don't works either

**Comment by cicarulez** [comment]
Interesting functionality, too bad it is not even documented.

It would be useful to be able to use it.

**Comment by janstadt** [comment]
@vogloblinsky can you provide an update here? stalebot marked it as `wontfix` but i see its on your milestone for 1.1.20.

**Comment by Voo2** [comment]
still waiting.

**Comment by vogloblinsky** [comment]
@janstadt 
This file https://github.com/compodoc/compodoc/blob/develop/src/app/engines/html.engine.ts handle the fact that if you put any templates in a folder, the HTML engine will use it instead of default one.

For libraries used inside the generated documentation, this commit has some updates on them : https://github.com/compodoc/compodoc/commit/c8f45185b89eee064cd4e494c95aa5ee6fbfa71f
