### ISSUE TITLE
[QUESTION] Multiple Documentations in Mono Repo

### ISSUE THREAD

**Issue by mbeckenbach** [compodoc/compodoc#1254]
Hey,

i have seen your advice on how to use compodoc in NX Workspace and I was wondering how to build the docs into separate directories per app / lib. 

The goal is to have a publishable docs folder per tsconfig. 

Like

/docs/apps/my-app
/docs/apps/foo-app
/docs/libs/some-lib

this would fit perfectly into the Nx workflows

**Comment by teslaji** [comment]
@mbeckenbach can you point me to his comments where he has advice for nx workflow. I am struggling to set up compodoc for the individual angular projects within the nx workspace.

**Comment by maxbebaasuro** [comment]
@teslaji In the meanwhile i figured out that this is actually supported for a while. Not 100% as it generates one for all projects like that but very useful. In the compodoc docs you actually find a hint on nx workspace. Its mentioned only once, you will find it.

https://www.npmjs.com/package/@twittwer/compodoc#workspace-docs

**Comment by teslaji** [comment]
@maxbebaasuro Yes, just came across this npm package, implementation is pretty straightforward. if you run the generator for the app name with `workspaceDocs` flag it generates tsconfig.compodoc.json for each project/app root. I am really hesitant to use this npm dep. maybe compodoc should collaborate with NX to create the nx-plugin. I've made a request for the enhancement but not sure if @vogloblinsky is keen on doing it.

**Comment by mbeckenbach** [comment]
@teslaji what are your concerns about this npm package? I had a look at the sources and didn’t find anything unusual.

**Comment by teslaji** [comment]
@mbeckenbach Nothing in terms of security but IMO repo with a single contributor could be a significant downside. Just hesitant to use this in any prod env. I wish compodoc adopt him with PRs or an official nx-plugin.

**Comment by maxbebaasuro** [comment]
@teslaji I know what you mean. But have a look at the repo. It is no rocket science, so even if that guy gives up you can fork it easily.

**Comment by vogloblinsky** [comment]
@teslaji Is it possible to have a link to a repo with a simple codebase where nx workspace is implemented ?
I will try to create a demo repo and add support for that easily in compodoc
Thanks

**Comment by teslaji** [comment]
@vogloblinsky  @nrwl has shared demo monorepo with angular and react apps using nx workspace. They keep this repo updated with new versions of nx and nx cli.

[https://github.com/nrwl/nx-examples.git](https://github.com/nrwl/nx-examples.git)
/apps/cart ----- react app
/apps/product --- angular app
