### ISSUE TITLE
[FEATURE] Add @see tag to link on class and its methods and properties

### ISSUE THREAD

**Issue by EugeneSnihovsky** [compodoc/compodoc#126]
##### **Overview of the issue**

This is standard feature of other doc tools. For example: I have **AuthApiService** with **signIn** method. I created **AuthApiServiceMock** for tests. To avoid copy-paste of documentation I can use
```javascript
import { AuthApiService } from './auth-api.service';

/**
 *  AuthApiService mock class. See {@see AuthApiService}
 */
export class AuthApiServiceMock {

    /**
     * See [signIn]{@see AuthApiService#signIn}
     */
    public signIn(): Promise<void> {
        return Promise.resolve();
    }
}
```

I know that for now I can use _{@link AuthApiService}_, but it's not working for methods and properties. And more semantic to use @link with url and @see with application instances (IMHO). If we can use _@link_ with properties and methods - it will be great too.

**Comment by vogloblinsky** [comment]
@see is not supported by typeScript compiler : https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript
