### ISSUE TITLE
[BUG] - Types are not supported in documentation. 

### ISSUE THREAD

**Issue by officialbidisha** [compodoc/compodoc#1267]
##### **Overview of the issue**
On clicking on the type of a varible in Typescript, it is not redirecting to the type rather it is redirecting to some other random class definition

An image

##### **Compodoc installed globally or locally ?**

locally

![opt](https://user-images.githubusercontent.com/49115207/171132052-bdfd2f79-0f93-4ed1-9fc2-018f18d19c9d.PNG)

On Clicking the above image, the page gets redirected to the bottom image. 

![Screenshot (557)](https://user-images.githubusercontent.com/49115207/171132161-d93d358e-e87d-4b5b-82ba-c15c0cb97629.png)

**Comment by vogloblinsky** [comment]
Hi, so if i understand well, you click on DataGridConfigOptions and you go to Option.html page ?

**Comment by officialbidisha** [comment]
Yes, that's right @vogloblinsky

**Comment by vogloblinsky** [comment]
DataGridConfigOptions is also a class ?

**Comment by officialbidisha** [comment]
It's a type @vogloblinsky

**Comment by officialbidisha** [comment]
Please have a look at this @vogloblinsky .

`
export type DataGridConfigOptions = {
  bordered?: boolean;
  uniqueField?: string;
  sortMode?: string;
  customSort?: boolean;
  lazy?: boolean;
  rowsPerPage?: number;
  autoLayout?: boolean;
  paginator?: boolean;
  alwaysShowPaginator?: boolean;
  showCurrentPageReport?: boolean;
};`
