### ISSUE TITLE
[BUG] Issues with stand alone components

### ISSUE THREAD

**Issue by paolo-e** [compodoc/compodoc#1268]
Angular 14 is brand new, so it is expected and I don't know if this is a bug or a feature request, but there are issues when loading a module with `loadComponent', with the new stand alone components feature.

Compodoc is installed locally and worked fine until the new feature was introduced.

This is reproducible by creating an angular 14 project, adding a stand alone component and loading it in a module:

```
loadComponent: ()=> import('...').then(c=>c.Component)
```

When compodoc is parsing the project, an error is thrown:

```
Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '(' at 1:494

```

Versions:
* Angular CLI: 14.0.0
* Node: 16.15.0
* Package Manager: npm 8.10.0 
* OS: linux x64
* Angular: 14.0.0
* compodoc: 1.1.15

**Comment by vogloblinsky** [comment]
Can you explain a little more how you load it in your module ?

**Comment by vogloblinsky** [comment]
Ok reproduced with lazy-loading.

**Comment by vogloblinsky** [comment]
First support coded, need to add unit tests later this week
