### ISSUE TITLE
[BUG] Compodoc generate link with "s" folder,  but dont generate folder 

### ISSUE THREAD

**Issue by maxbronnikov10** [compodoc/compodoc#1292]
##### **Operating System, Node.js, npm, compodoc version(s)**

ubuntu, node 16.17.0, npm 8.15.0, compodoc 1.1.19

##### **Compodoc installed globally or locally ?**

globally

### my source code 
project on nets js

```ts
@Global()
@Module({
  providers: [HelpersService],
  exports: [HelpersService],
})
export class HelpersModule {}

```

##### **If possible sourcecode of the file where it breaks**
code in my html: 

```html
<div class="col-sm-3">
                    <h3>Exports<a href="https://angular.io/api/core/NgModule#exports" target="_blank" title="Official documentation about module exports"><span
                                class="icon ion-ios-information-circle-outline"></a></h3>
                    <ul class="list-group">
                        <li class="list-group-item">
                            <a href="../s/HelpersService.html">HelpersService</a> <!-- s folder?  -->
                        </li>
                    </ul>
                </div>
```

i think error in this:

https://github.com/compodoc/compodoc/blame/c8379e04d71409ba147be2aeb018f38b8e4715db/src/templates/partials/module.hbs#L162

or

https://github.com/compodoc/compodoc/blame/c8379e04d71409ba147be2aeb018f38b8e4715db/src/templates/partials/module.hbs#L176

i dont have this "s" folder and i cant go to link

### image
![Screenshot from 2022-10-11 11-04-12](https://user-images.githubusercontent.com/33382129/195033738-3722fdc2-3144-4172-9f81-ddb9feaf56d9.png)

**Comment by vogloblinsky** [comment]
Cannot reproduce with current dev version.
Can you do a test by installing Compodoc like this ? `npm i -D https://github.com/compodoc/compodoc/`
