### ISSUE TITLE
[BUG] Folder name prevented compodoc run

### ISSUE THREAD

**Issue by raquel-f** [compodoc/compodoc#1297]
##### **Overview of the issue**
I was just starting to use Compodoc in my Angular project. I followed all the instructions in the installation page but running the actual script inserted in the `package.json` file was not working. 

1.  I ran the command `ng add @compodoc/compodoc` for easier installation and it functioned properly.
2. Verified that scripts added to `package.json` were correct (they were) and verified that `tsconfig.doc.json` was added and configured correctly (it was).
3. In the terminal, above the src folder, ran the following command `npm run compodoc:build`. This is where the problems began.

The stack trace showed something similar to this (removed PII for safety):

```
'[non-existent directory name here]\node_modules\.bin\' is not recognized as an internal or external command,
operable program or batch file.
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '[existent directory name here]\@compodoc\compodoc\bin\index-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)        
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [project name here]@0.0.0 compodoc:build: `compodoc -p tsconfig.doc.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the [project name here]@0.0.0 compodoc:build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    [existent directory name here]\npm-cache\_logs\2022-10-23T20_21_45_545Z-debug.log
```

##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc version: 1.1.19
TypeScript version used by Compodoc : 4.5.5
TypeScript version of current project : 4.0.2
Node.js version : v14.17.0
NPM version: 6.14.13
Operating system : Windows 10

##### **Angular configuration, a `package.json` file in the root folder**

```
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc:build": "compodoc -p tsconfig.doc.json",
    "compodoc:build-and-serve": "compodoc -p tsconfig.doc.json -s",
    "compodoc:serve": "compodoc -s"
  }
```

##### **Compodoc installed globally or locally ?**
Compodoc was installed locally in the Angular project with `ng add @compodoc/compodoc`.

##### **If possible sourcecode of the file where it breaks**
Not an issue related to a file.

##### **If possible your terminal logs before the error**
Log just outputs the command from script before the error stack trace is shown.

##### **Motivation for or Use Case**
I was just starting to use the tool to help document my Angular project.

##### **Reproduce the error**

The installation steps mentioned in the beginning. Angular project folder inside a folder with name formatted as `[word] & [other-word]`

##### **Related issues**

I tried to search if there was another similar issue reported but couldn't find anything similar.

##### **Suggest a Fix**
After trying to fix the scripts inside the `package.json`, I realized my folder above the Angular project contained a space and the character `&`. Formatting similar to `[name] & [name]`. Removing the space and & seemed to solve the issue. I removed both but I'm not certain which character was causing the issue, my guess is the spaces inside the folder name were causing issues running Compodoc.

Filled this bug report to make devs aware of this issue and maybe add a feature to include more possible file names so other people just starting to use this tool don't get frustrated at the beginning like I have. Otherwise this tool seems great so far.

**Comment by vogloblinsky** [comment]
Cannot reproduce...
