### ISSUE TITLE
logo is overlaying menu

### ISSUE THREAD

**Issue by c1rus** [compodoc/compodoc#13]
example project: https://github.com/c1rus/event-view

![overlay](https://cloud.githubusercontent.com/assets/11233730/20237087/d47500fc-a8c8-11e6-8d2d-b167d0ce470f.PNG)

**Comment by vogloblinsky** [comment]
what is the size of the window ?

**Comment by c1rus** [comment]
1440 x 770, height below 800 doesnt look good.
