### ISSUE TITLE
[BUG] Documentation coverage 'Type' for class is misspelt

### ISSUE THREAD

**Issue by pconnell99** [compodoc/compodoc#130]
##### **Overview of the issue**

When the Documentation coverage  page is displayed,the type column contains a misspelt 'classe' instead of 'class'.

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows, Node 6.10.0, compodoc 0.0.41

##### **Angular configuration, a `package.json` file in the root folder**

Likely not required as this seems to be a typo.

##### **Compodoc installed globally or locally ?**

Globally

##### **Reproduce the error**

Generate documentation and view coverage page type column.

##### **Suggest a Fix**

Find the mistype and fix it -  code that may be related found in html.engine.ts (result.type = 'classe';)

**Comment by vogloblinsky** [comment]
thanks for the report, already fixed on develop branch 😉
