### ISSUE TITLE
Veracode security scan flags dot library vulnerability

### ISSUE THREAD

**Issue by dberthia** [compodoc/compodoc#1311]
Our Veracode security scanner has flagged the "dot" library v1 as having a vulnerability. It was fixed in 2.0.0-beta 1. Would like to see the compodoc dependency updated to this version.

**Comment by vogloblinsky** [comment]
Ok, will try to update https://github.com/compodoc/ngd dependency first, and after compodoc

**Comment by dberthia** [comment]
Great- thanks!

**Comment by dberthia** [comment]
Same issue with your version of the "debug" library. Please update from 2.6.9 to 3.1 or later.
