### ISSUE TITLE
[BUG] Horizontal rules (hr tags) are zero pixels in width

### ISSUE THREAD

**Issue by marie-dk** [compodoc/compodoc#1315]
##### **Overview of the issue**

The horizontal rule `<hr>` is invisible

##### **Operating System, Node.js, npm, compodoc version(s)**

windows: 10
node: 18.13.0
npm: 8.19.3
compodoc: 1.1.19

##### **Angular configuration, a `package.json` file in the root folder**

<details><summary>package.json</summary>
<p>

```
{
  "name": "sdk",
  "version": "0.2.44",
  "scripts": {
    "ng": "ng",
    "start": "run-p lib:watch showcase:waiton",
    "lib:build": "ng build hms-ui",
    "lib:watch": "ng build hms-ui --watch --configuration development",
    "showcase:waiton": "wait-on -d 5000 dist/hms-ui/package.json && npm run showcase:start",
    "showcase:start": "ng serve showcase",
    "showcase:build": "ng build showcase",
    "showcase:build-prod": "ng build showcase --configuration production",
    "showcase:watch": "ng build showcase --watch --configuration development",
    "compodoc:build": "compodoc -p tsconfig.doc.json  --includes=readme --includesName=\"Examples of usage\" --name=\"sdk docs\"",
    "compodoc:start": "compodoc -s "
  },
  "private": false,
  "files": [
    "dist",
    "documentation"
  ],
  "dependencies": {
    "@angular/animations": "^14.2.0",
    "@angular/common": "^14.2.0",
    "@angular/compiler": "^14.2.0",
    "@angular/core": "^14.2.0",
    "@angular/forms": "^14.2.0",
    "@angular/platform-browser": "^14.2.0",
    "@angular/platform-browser-dynamic": "^14.2.0",
    "@angular/router": "^14.2.0",
    "@fortawesome/fontawesome-free": "^6.2.1",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.10",
    "@angular/cli": "~14.2.7",
    "@angular/compiler-cli": "^14.2.0",
    "@types/jasmine": "~4.0.0",
    "azure-devops-npm-auth": "^1.1.1",
    "jasmine-core": "~4.3.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "ng-packagr": "^14.2.0",
    "npm-run-all": "^4.1.5",
    "typescript": "~4.7.2",
    "wait-on": "^6.0.1"
  }
}
```
</p>
</details>

##### **Compodoc installed globally or locally ?**

Globally

##### **Motivation for or Use Case**

I use `<hr>` tags to separate sections of content in README.md files

##### **Reproduce the error**

Add a folder with readme files containing `<hr>` tags (or markdown for hr). Put a summary.json in the folder and generate documentation.
Serve the documentation and go to the "Additional documentation" section. Notice that the `<hr>` tags have a width of 0.

##### **Related issues**

I was not able to find any related issues

##### **Suggest a Fix**

The reason that `<hr>` tags have a width of 0 is that the parent `.content-data` is a flexbox. The following added to `compodoc.css` will fix the issue:

```
.content-data hr {
    width: 100%;
}
```

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/c8f45185b89eee064cd4e494c95aa5ee6fbfa71f
