### ISSUE TITLE
[Question] How to expose only @Input and @Output in documentation

### ISSUE THREAD

**Issue by iNath** [compodoc/compodoc#1316]
Hello,

I would like to know if it's possible to expose only the @Input and @Ouput fields/methods in generated documentation.

The question was previously posted here: https://github.com/compodoc/compodoc/issues/764
But the answer is not clear, I don't understand how to do.

Thank you :)

**Comment by vogloblinsky** [comment]
Yes, add a jsdoc tag on them, watch the example project : https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/master/src/app/list/todo/todo.component.ts
Also add @internal JSDoc tag, and use --disableInternal flag
