### ISSUE TITLE
[BUG] search results don't respect base path

### ISSUE THREAD

**Issue by mattlewis92** [compodoc/compodoc#132]
##### **Overview of the issue**

The search results page prefixes all links with `/`, so if the documentation is outputted in a non root folder the links don't work

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc `0.0.41`

##### **Angular configuration, a `package.json` file in the root folder**

https://github.com/mattlewis92/angular-calendar

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

A user of my project raised the issue: https://github.com/mattlewis92/angular-calendar/issues/167

##### **Reproduce the error**

Go to here: https://mattlewis92.github.io/angular-calendar/docs/?q=mon and click on a search result

##### **Related issues**

https://github.com/mattlewis92/angular-calendar/issues/167

##### **Suggest a Fix**

The search results links just don't need the leading slash in the url which should fix it. I couldn't see where in the source they get generated though, the [template](https://github.com/compodoc/compodoc/blob/develop/src/templates/partials/search-results.hbs#L4) didn't seem to have any content? Happy to send a PR with a fix if you can guide me where the links are generated. Thanks! 😃

**Comment by vogloblinsky** [comment]
The links are displayed in JS in this file 

https://github.com/compodoc/compodoc/blob/master/src/resources/js/search/search.js#L52

But the links come from Lunr.js store scan.

**Comment by mattlewis92** [comment]
Opened a PR for discussion, I guess it would be a better fix to fix the links in the index itself thats passed to the lunr search
