### ISSUE TITLE
[BUG] EOL libraries referenced by the latest version 1.1.19

### ISSUE THREAD

**Issue by SuperHappyJanet** [compodoc/compodoc#1321]
Here are 2 deprecated libraries are referenced by the latest version of compodoc. Would you please fix it in the next version? Thank you very much.

sourcemap-codec
![image](https://user-images.githubusercontent.com/130619984/231636757-62194a89-9508-4d23-8e8f-778753a93ded.png)
dommatrix
![image](https://user-images.githubusercontent.com/130619984/231636790-90d49350-7d94-46df-908c-6fa95cee6752.png)

**Comment by kushpra8005** [comment]
Hi @SuperHappyJanet and @vogloblinsky :
Even we are facing sonar scans issue (vulnerabilities) in our project for few libraries which was installed as compodoc dependent libraries 

- static-eval 2.1.0	
- es5-ext 0.10.61	
- Dot 1.1.3
- static-module 3.0.4
- Lunr 2.3.9

any future plan to upgrade the version and ETA for the same ?
thank you so much.

![image](https://user-images.githubusercontent.com/20460891/236993694-a777014c-6dbc-492f-b8bd-52cc7455951e.png)

**Comment by vogloblinsky** [comment]
Fixed by [#56d06514564d8b15228513759f5d7d6fab488347](https://github.com/compodoc/compodoc/commit/56d06514564d8b15228513759f5d7d6fab488347)
