### ISSUE TITLE
[BUG] Angular 16: Support object expressions as input for Input Decorators

### ISSUE THREAD

**Issue by valentinpalkovic** [compodoc/compodoc#1327]
##### **Overview of the issue**

In Angular 16, you can pass an object expression as an argument for the Input decorator.

```jsx
@Input({ required: <true|false> })
requiredInput: any;

@Input({ alias: 'some-alias' })
aliasedInput: any;

@Input({ required: <true|false>, alias: 'some-alias' })
requiredAndAliased: any;
```

Angular 16 has added the possibility to mark an input as required. This information is also not reflected in the compodoc output. In general, as soon as an object expression is passed to the input decorator, the `name` property is empty because the [current logic](https://github.com/compodoc/compodoc/blob/develop/src/app/compiler/angular/deps/helpers/class-helper.ts#L1450) assumes to get always a `StringLiteral`. Now, an ObjectExpression can be passed to the Input Decorator as well

##### **Operating System, Node.js, npm, compodoc version(s)**

- @compodoc/compodoc: v1.1.19

##### **Angular configuration, a `package.json` file in the root folder**

- Angular 16 (RC)

##### **Compodoc installed globally or locally ?**

- does not matter

##### **If possible sourcecode of the file where it breaks**

```jsx
import { Component, Input } from '@angular/core';

@Component({
    selector: 'app-foo',
    template: `<div>... </div>
    `
})
export class FooComponent {
    /**
     * An example required input
     */
    @Input({ required: true }) 
     requiredInput: string;

    /**
     * An example aliased input (already supported)
     */
    @Input('aliasedInput') 
     aliasedInput: string;

    /**
     * An example aliased input using the object syntax
     */
    @Input({ alias: 'aliasedInput' }) 
    objectAliasedInput: string;

    /**
     * An example aliased required input using the object syntax
     */
    @Input({ alias: 'aliasedInput' }) 
    aliasedAndRequired: string;
}
```

##### **Motivation for or Use Case**

Hi! I am a [Storybook](https://storybook.js.org/) maintainer, and currently, we evaluate Angular 16 support in Storybook, which will be released in the first week of May. Now, Storybook relies heavily on Compodoc to extract type information. Passing an object expression to the Input decorator currently breaks completely because compodoc a) wrongly extracts the name property of the input (it always assumes that a StringLiteral is passed in as the only valid argument) and b) cannot handle object expressions as valid decorator arguments.

##### **Reproduce the error**

Use the above sample component and try to generate compodoc upon it. The `name` is not extracted properly, also the `optional` information is missing.

##### **Suggest a Fix**

See:
https://github.com/compodoc/compodoc/pull/1326

**Comment by byjokese** [comment]
No news on this?

Thanks @valentinpalkovic for the quick PR.
