### ISSUE TITLE
fs-extra@11.1.1 node incompatible version

### ISSUE THREAD

**Issue by jromerob** [compodoc/compodoc#1336]
Hi, we have a project that uses Node 10 and we've been using Compodoc 1.1.7 for a while. Today, when reinstalling dependencies with "npm install", we encountered the following error: fs-extra@11.1.1: The engine "node" is incompatible with this module. Expected version ">=14.14". Got "10.21.0".

We haven't changed any dependencies and all of them have strict versions. Upon checking Compodoc 1.1.7, I see that it uses fs-extra@^7.0.1, which works with Node 10.

Has there been any changes that we should be aware of? Has the compatibility of Compodoc 1.1.7 with Node 10 been broken?

Thanks in advance

**Comment by vogloblinsky** [comment]
Hi,
Sorry but Compodoc now only support Node.js LTS versions : https://compodoc.app/guides/installation.html
