### ISSUE TITLE
[FEATURE] Specify the logo parameter

### ISSUE THREAD

**Issue by daniele-zurico** [compodoc/compodoc#134]
I was suggesting if it's possible to override the default logo generated.
My proposal is something like that:
```
./node_modules/.bin/compodoc --theme readthedocs -p ./tsconfig.aot.json -s --logo 'vincent.jpg'
```
if --logo is not passed it mantain the same behaviour as it is now

**Comment by YoussefTaghlabi** [comment]
Actually it might make more sense to have the logo added on top of the search input field:
![image](https://user-images.githubusercontent.com/1639024/44630976-969b8180-a933-11e8-8cc2-71a4a8fbf125.png)
