### ISSUE TITLE
[BUG] Deprecated inside@1.0.0: Package no longer supported

### ISSUE THREAD

**Issue by muuvmuuv** [compodoc/compodoc#1355]
##### **Overview of the issue**

Getting this warning and this seems warning:

```
 WARN  deprecated inside@1.0.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
```

##### **Operating System, Node.js, npm, compodoc version(s)**

latest macOS, Node, pnpm and compodoc.

##### **Compodoc installed globally or locally ?**

locally

**Comment by vogloblinsky** [comment]
Thanks for the issue.

**Comment by thepema** [comment]
Hello! I see that it is merged but a new version has not yet been released to solve it in npm

**Comment by vogloblinsky** [comment]
@thepema Just released https://github.com/compodoc/compodoc/releases/tag/1.1.22
