### ISSUE TITLE
[FEATURE] Simple Login to Access

### ISSUE THREAD

**Issue by ialex90** [compodoc/compodoc#136]
Hi there,

First, thanks for this tool which is amazing.

Secondly, I would like to suggest to add some kind of login, something simple just for internal restrictions to the projects and not to expose to everyone else.

I think with a simple login would be enough as this shouldn't be deployed to production but it might be required to be exposed to the right group/department of ppl instead to everyone.

What do you think?

Thanks!

**Comment by vogloblinsky** [comment]
Authentication is a big/complex feature for just a simple documentation tool.
Did a simple http basic authentication could do the job for you ?

**Comment by ialex90** [comment]
Well that's what I meant. You don't need a complex/secure/well performanced login access as it's not the goal of this and it shouldn't be exposed to production, but I think it is a great idea to have a really simple login to avoid everyone get into it as the documentation might expose sensitive data that you don't wanna shared with others teams/departments within the company.

I think a simple login cookie based is more than enough, it doesn't have to support multiple users or compare against the database on the cloud, just something simple.

Don't you think could be great?

**Comment by vogloblinsky** [comment]
You have the source code of the documentation available after generation.

You can easily configure the authentication on your server after that : https://httpd.apache.org/docs/2.4/howto/auth.html

I am not sure it is the goal of compodoc to provide that feature.

**Comment by ialex90** [comment]
Well, I need that functionality actually, because the power of this library for me is, the documentation might be generated on the server (VSTS) I have no access to modify that code then.

It does not have to be something that everyone has to set up, by default without login and if you explicitly want it, just set it up.

I still think is a benefit to have, but it's your library, up to you, I will do my workflow, but I think more ppl could need that functionally as well.

**Comment by vogloblinsky** [comment]
I reopen the issue, if others people need this feature, i will try to handle that.

**Comment by AilisObrian** [comment]
Please check out https://github.com/bitly/oauth2_proxy

**Comment by vogloblinsky** [comment]
Closing it, for me this issue has not to be handled by Compodoc
