### ISSUE TITLE
[BUG] NPM lib version angular is not link with @angular-devkit/schematics node version

### ISSUE THREAD

**Issue by Jasperfr74** [compodoc/compodoc#1362]
##### **Overview of the issue**

Hi, I just want to mention that you have an issue on your package lib version 1.1.20, which is not compatible with node version 14.x.
Because, I'm using angular 14.3 version with node version 14.17.0 but on your verison 1.1.20 you have a depency of "@angular-devkit/schematics": "^16.0.1", version.

https://www.npmjs.com/package/@compodoc/compodoc/v/1.1.20?activeTab=code

This won't work because @angular-devkit/schematics/v/16.1.0 required node version `"node": "^16.14.0 || >=18.10.0",` but I'm using 14.17.0.

https://www.npmjs.com/package/@angular-devkit/schematics/v/16.1.0?activeTab=code

When i delete my node_modules and my yarn.lock I can't install yarn back without an issue: 

`error @angular-devkit/schematics@16.1.4: The engine "node" is incompatible with this module. Expected version "^16.14.0 || >=18.10.0". Got "14.17.0"
error Found incompatible module.`

##### **Operating System, Node.js, npm, compodoc version(s)**

Bug found on the compodoc version 1.1.20

##### **Angular configuration, a `package.json` file in the root folder**
`
    "@angular-devkit/build-angular": "14.2.12",
    "@angular/animations": "^14.3.0",
    "@angular/cdk": "^14.2.7",
    "@angular/cli": "14.2.12",
    "@angular/common": "^14.3.0",
    "@angular/compiler": "^14.3.0",
    "@angular/compiler-cli": "^14.3.0",
    "@angular/core": "^14.3.0",
    "@angular/forms": "^14.3.0",
   "@compodoc/compodoc": "^1.1.19"`

##### **Compodoc installed globally or locally ?**

Locally

##### **Suggest a Fix**

You need to set the @angular-devkit/schematics/ version to match the current angular version (example: angular 14.3 ->  @angular-devkit/schematics 14.2.7) to be able to use the same node version ^14.x

Your range of node version is not good  "node": ">= 14.0.0" to match the "@angular-devkit/schematics": "^16.0.1", withe the angular version 14.

**Comment by MikeMatusz** [comment]
@vogloblinsky Won't this fix cause problems for anyone using newer versions of Angular?  I'm updating to Angular 17, and if I update @compodoc to ^1.1.22, this will cause Angular 14.x schematics to be installed alongside 17.x.  I'm not saying it's feasible for every version of compodoc to work with any version of Angular, but locking the dependency down to a version of Angular that's already out of support doesn't seem like the correct solution here.
