### ISSUE TITLE
[FEATURE] custom treatment of the metadata field `template`

### ISSUE THREAD

**Issue by sclausen** [compodoc/compodoc#137]
##### **Overview of the issue**

the metadata field `template` is treated as every other metadata field and is not syntax highlighted

##### **Motivation for or Use Case**

It would be clearer, if the `template` field would be syntax highlighted, like source or example.

##### **Suggest a Fix**

introduce special treatment for the metadata field `template` and add syntax highlighting to it.

**Comment by vogloblinsky** [comment]
Ok i will fix that.

There will be a template tab in v1.0.0 for better reading.

![localhost-8080-components-homecomponent html ipad 1](https://cloud.githubusercontent.com/assets/2841805/24442577/0d88f4e6-145f-11e7-9496-2ccb083e624b.png)

**Comment by sclausen** [comment]
Really nice! Do you have a (approx) schedule for v1.0.0?

**Comment by vogloblinsky** [comment]
End of this week, or at the beginning of next week ;)

**Comment by sclausen** [comment]
Wow, many many thanks!

**Comment by dharsanav** [comment]
Thanks. Waiting for the new release :)

**Comment by vogloblinsky** [comment]
Available in beta.3

**Comment by sclausen** [comment]
I've got beta.4 and it just doesn't work. Am I missing something?

**Comment by vogloblinsky** [comment]
@sclausen what is wrong for you ? you do not have a template tab ?

**Comment by sclausen** [comment]
Yes, its just as if this feature is not in beta.4 :confused:

**Comment by vogloblinsky** [comment]
This link for the official demo works fine : 
https://compodoc.github.io/compodoc-demo-todomvc-angular/components/AboutComponent.html#template

The repo used beta.4

**Comment by sclausen** [comment]
Oh I see. You have a `templateUrl` field, and see the template tab, but my issue above is about the `template` field.

**Comment by vogloblinsky** [comment]
Ok sorry, i was thinking i had merge templateUrl or template metadata in this tab. I have just tested locally, and i am wrong.
I fix that asap.
Regards

**Comment by vogloblinsky** [comment]
Example here: https://compodoc.github.io/compodoc-demo-todomvc-angular/components/FooterComponent.html
