### ISSUE TITLE
[BUG] Empty metadatas, trying to find it with imports.

### ISSUE THREAD

**Issue by pratikkajare** [compodoc/compodoc#1377]
<rejected> TypeError: Cannot read properties of undefined (reading 'text')
      at C:\Users\prati\OneDrive\Documents\Office\witsby\whole-learning-service\node_modules\@compodoc\compodoc\dist\index.js:8741:64
      
      i have getting this error when using nestjs

**Comment by vogloblinsky** [comment]
@pratikkajare Can i have source code of the file ? or an anonymous one
thanks

**Comment by pratikkajare** [comment]
thanks for your support. in entity from nestjs graphql  there is a decorator of @Directive('@key(fields: "id")') which i am using imported from '@nestjs/graphql'. compodoc not supports to graphql package. to resolve that essue i have to commit this line for minute to generate documentation.

**Comment by pratikkajare** [comment]
thanks for your support. in entity from nestjs graphql there is a decorator of @directive('@key(fields: "id")') which i am using imported from '@nestjs/graphql'. compodoc not supports to graphql package. to resolve that essue i have to commit this line for minute to generate documentation.

**Comment by coler-j** [comment]
Also ran into the same issue; any better solution?
