### ISSUE TITLE
[BUG] Search term

### ISSUE THREAD

**Issue by OrgestB** [compodoc/compodoc#1381]
##### **Overview of the issue**

I have an angular app and Im using compodoc, but the search feature doesnt work right. I search for a word, it only finds it only in a service. The word is also in a components but the search doesn't find it.
##### **Operating System, Node.js, npm, compodoc version(s)**

Angular CLI: 14.2.10
Node: 18.16.0 (Unsupported)
Package Manager: npm 9.8.0
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.7
@angular/cli                    14.2.10
@angular/flex-layout            14.0.0-beta.41
@angular/material               14.2.7
@schematics/angular             14.2.10
rxjs                            7.5.7
typescript                      4.7.4

##### **Compodoc installed globally or locally ?**

Both

**Comment by vogloblinsky** [comment]
Hi,
Where does the word is in a source code's component ?

**Comment by OrgestB** [comment]
Hi, under src/app/components/ 
The word is part of the comment /** The word ... */

**Comment by vogloblinsky** [comment]
Ok, where is this comment in the component ?
On the demo app, https://compodoc.github.io/compodoc-demo-todomvc-angular/components/EmptyComponent.html#source if you search "inheritance", it works fine.

**Comment by OrgestB** [comment]
`Yes,` I have the same scenario.
Im  looking for the word  Pattern in 


`  /**
   * PATTERN: Form Generator
   * Generates the forms according to the item in emma.
   * @param communication 
   * @param backend 
   * @param router 
   * @param routers 
   * @param _snackBar 
   * @param dialog 
   * @param datePipe 
   * @param changeDetection 
   * @param storage 
   * @param logger 
   * @param renderMarkupToHTML 
   * @param renderer 
   */`


This is above the constructor

**Comment by vogloblinsky** [comment]
Inside a component ?
Could you do an anonymous example failing file please ? I am not able to reproduce the bug inside the demo app.

**Comment by OrgestB** [comment]
Yes it is a normal component. I'm sorry I dont know how to do that. Can you explain please?
![image](https://github.com/compodoc/compodoc/assets/42538790/fe9f01dc-d1ef-4079-a989-90436b3c5609)
Im looking for the word pattern, but the search doesnt find it.

**Comment by vogloblinsky** [comment]
Could you try 5' to clone this demo repository, and reproduce the bug in it ?
https://github.com/compodoc/compodoc-demo-todomvc-angular
Thanks

**Comment by OrgestB** [comment]
How can I reproduce this on it? Should I generate compodoc on it?
if i try to run npm run doc i get this 
npm run doc

> compodoc-demo-todomvc-angular@0.0.0 doc
> ./node_modules/.bin/compodoc -p tsconfig.doc.json -a screenshots -n "TodoMVC Angular documentation" --includes additional-doc

'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by OrgestB** [comment]
Hi again, I think I found the issue. The search does not work when the components are inside one foleder.
Ex:
![image](https://github.com/compodoc/compodoc/assets/42538790/2f49df3b-e805-4a1a-8433-0fcfbea1ec21)

**Comment by vogloblinsky** [comment]
Ok cool we have a line of inquiry. Strange because in the demo project, there are also inside many folders.
May be the naming ?
For reproducing this inside the demo project, run compodoc as you do in your project. I think you have this error because you are on Windows ?

**Comment by OrgestB** [comment]
In the demo projects it works fine, I removed my components from the folder. It looks like for this two components the search doesn't work. I don't understand why. Is there anything that could interfere?

**Comment by OrgestB** [comment]
I think it is affected by the size of the typescript file, when I remove half of the code it works. Do you know anything about this?

**Comment by vogloblinsky** [comment]
No strange. I will try in the demo app.

**Comment by OrgestB** [comment]
It turned out I had an older version somehow, upgraded to a newest one and it works fine. Thank you!
