### ISSUE TITLE
[BUG] Cannot find module 'functions-have-names'

### ISSUE THREAD

**Issue by DimTheo** [compodoc/compodoc#1383]
Error: Cannot find module 'functions-have-names'
Require stack:
- /root/.npm/_npx/c70f4346bae91056/node_modules/set-function-name/index.js

Root issue [ljharb/set-function-name/issues/1]([https://github.com/ljharb/set-function-name/issues/1](https://github.com/compodoc/compodoc/issues/url))

**Comment by praveena23** [comment]
We are facing this issue from today(13-sep-23) for "@compodoc/compodoc": "1.1.19", and even for latest version 1.1.21.

**Comment by vogloblinsky** [comment]
I didn't see the package "set-function-name" in package-lock.json's compodoc file.
Could you check in your project ?

**Comment by DimTheo** [comment]
`regexp.prototype.flags ` is the culprit in your package-lock 
https://github.com/compodoc/compodoc/blob/229f4073ae38be007bf458945e57f4145959e1be/package-lock.json#L8392

**Comment by vogloblinsky** [comment]
Seems related to two main packages, pdfmake and @wdio/cli

```
@foliojs-fork/fontkit -> @foliojs-fork/pdfkit -> pdfmake
aria-query -> @wdio/cli/node_modules/webdriverio

deep-equal 2.2.1
    -> regexp.prototype.flags 1.5.0
        -> "functions-have-names": "^1.2.3"
deep-equal 1.1.1
    -> regexp.prototype.flags 1.2.0
```

I have done an update of dependencies, will release that in next version this week, say to me if it is fixed then.

**Comment by vogloblinsky** [comment]
May be fixed in last version https://github.com/compodoc/compodoc/releases/tag/1.1.22
