### ISSUE TITLE
[BUG] Using deprecated package @babel/plugin-proposal-private-methods

### ISSUE THREAD

**Issue by klub-chetanya** [compodoc/compodoc#1387]
##### **Overview of the issue**

Compodoc is using package @babel/plugin-proposal-private-methods which has been deprecated from @babel/preset-env.

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@babel/plugin-proposal-private-methods' imported from /Users/admin/Documents/node_modules/@compodoc/compodoc/dist/babel-virtual-resolve-base.js

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: mac 13.4.1 (22F82)
npm: v8.19.2
node: v18.12.1
compodoc: v1.1.21

##### **Compodoc installed globally or locally ?**

locally

##### **Suggest a Fix**

Use package @babel/plugin-transform-private-methods.

**Comment by hoangvutruong513** [comment]
Facing the same issue on

OS: MacOS 13.4.1
Node: 16.20.0
npm: 8.19.4
Angular: 16.2.5
Compodoc: 1.1.21

please update the breaking dependency @babel/plugin-proposal-private-methods

**Comment by vogloblinsky** [comment]
Fixed in https://github.com/compodoc/compodoc/commit/ecb08ef47e0f860d10636b03d2c3bd88801a1dba

**Comment by temush** [comment]
> Fixed in [ecb08ef](https://github.com/compodoc/compodoc/commit/ecb08ef47e0f860d10636b03d2c3bd88801a1dba)

Could you please release a new version? Thank you

**Comment by vogloblinsky** [comment]
@temush Yes just release https://github.com/compodoc/compodoc/releases/tag/1.1.22
