### ISSUE TITLE
[FEATURE] Add dependabot alerts to this project for security notifications

### ISSUE THREAD

**Issue by Austinb** [compodoc/compodoc#1399]
##### **Overview of the feature**

Enable dependabot alerts for this project in GitHub.  Project > Settings > Code security and analysis

##### **Motivation for or Use Case**

Enabling will let you know sooner that there is a vulernable package being used well before someone has to create an issue or PR

##### **Related issues**

N/A

**Comment by vogloblinsky** [comment]
Done ✅
