### ISSUE TITLE
module dependencies graphs not generated

### ISSUE THREAD

**Issue by c1rus** [compodoc/compodoc#14]
The overview graph is generated, but module section looks like below. I dont see any error, when docs are generating.

example project: https://github.com/c1rus/event-view

![dependencies](https://cloud.githubusercontent.com/assets/11233730/20237107/69532d7a-a8c9-11e6-9950-8545fc88a306.PNG)

**Comment by vogloblinsky** [comment]
Cannot reproduce. I got all the graph.
What is your environment ? OS, node, npm version
Thanks

**Comment by c1rus** [comment]
node - v7.0.0
npm - 3.10.8
os - windows 10
