### ISSUE TITLE
[BUG] Watch mode not working properly.

### ISSUE THREAD

**Issue by dharsanav** [compodoc/compodoc#141]
Thanks for such a wonderful tool.

##### **Overview of the issue**
Miscellaneous  section contains some documentation.But when I updated the comments,compodoc detects that change and rebuilds, but now nothing is shown in the documentation.I think this is a problem only in miscellaneous section.

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc:1.0.0-beta.1
node:v6.9.1

##### **Compodoc installed globally or locally ?**

compodoc is installed locally and included as a dev dependency.

**Comment by csentis** [comment]
Kindly let me add that this also seems to affect the section "documentation coverage":

after increasing the documentation on a specific class, the related file's documentation coverage does not get updated - although `coverage.html` receives a new time stamp).

**Comment by csentis** [comment]
Fix confirmed to work as intended.

@vogloblinsky Thank you so much for all this good work you are doing here, Vincent!

**Comment by vogloblinsky** [comment]
You are welcome @csentis

**Comment by PCASME** [comment]
Watch mode doesn't works for me.
I have installed compodoc globally and adding the flag **-w** or **--watch** doesn't seems to work.

**My call**:
`compodoc src/app/<subfolder> -p tsconfig.json --serve --watch --open`

Maybe specifying a subfolder is the cause?

**My environment**:
Windows 10
Node 9.8.0
npm 5.6.0
Angular 5.2.9
Compodoc 1.1.7

Am I doing something wrong or is something leaking?

Thanks in advance.

**Comment by vogloblinsky** [comment]
@PCASME and with that ?
`
compodoc -p tsconfig.json --serve --watch --open
`

**Comment by PCASME** [comment]
Same behavior.
I was try specifying a subfolder, as I mentioned in my previous comment, and also without it as in your comment and the watch mode doesn't works either.

Also I tried with the short and long name of the parameters and does not work either.

I don't know what can cause this about my environment.

**Comment by vogloblinsky** [comment]
Ok @PCASME reproduced with a fresh Virtal Machine and your environment + https://github.com/compodoc/compodoc-demo-todomvc-angular

This works
```
compodoc -p src/tsconfig.app.json --serve --watch --open
```

This not
```
compodoc -p tsconfig.json --serve --watch --open
```

**Comment by PCASME** [comment]
Thanks for the tip but I need to generate documentation only for a subfolder inside the `src/` and in this case doesn't works.
The use case is that we are working in a huge project for a company and there are different providers working each in its own isolated app within the whole project.
e.g.:

`src/app/isolated-apps/app-one`

Following your suggest, if I go to the `app-one` subfolder and from there launch `compodoc` referencing `tsconfig.app.json` and indicating the output folder with relative paths, it works as expected. Its a little bit verbose but it works and it's fine for now.
e.g.:

`compodoc -p ../../../tsconfig.app.json -s -w -o -d ../../../../documentation`

I will looking forward for the final solution in the next patch version.

Thanks.
