### ISSUE TITLE
[BUG] Tools directory not available in compodoc

### ISSUE THREAD

**Issue by darkmoonbzh** [compodoc/compodoc#1422]
##### **Hi, when i launch npm i with 1.11.23 of compodoc i have this error : **

node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module '/home/vagrant/workspaceAngular/DemandePrestationsAppli/node_modules/@compodoc/compodoc/tools/copy-libs.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

With version 1.11.22 there is no problem.
I see in a commit that tools directory was added but i did not see this directory in my project compodoc in my node_modules.
I try with different version of node and same problem.

Thank you

**Comment by kevinsar** [comment]
Was able to consistently reproduce this issue when running clean install `npm ci`. Looks like a recent defect, the copy-libs.js file does not exist prior to 1.11.22.

**Comment by SebastianW-OneIdentity** [comment]
I have the same issue with v1.1.25, but I could not use an older release because of the fix of #1478 in v1.1.25

So please fix this issue

**Comment by siddjellali** [comment]
no update here ?
Rollback in version 1.1.22 seems solved the issue

**Comment by landon-buttars-wgu** [comment]
Still present using compodoc v1.1.25 with pnpm on node 20. Inspecting the node_modules shows the tools directory is missing.

```
.../node_modules/@compodoc/compodoc postinstall: > @compodoc/compodoc@1.1.25 copy-libs
.../node_modules/@compodoc/compodoc postinstall: > node tools/copy-libs.js
.../node_modules/@compodoc/compodoc postinstall: node:internal/modules/cjs/loader:1228
.../node_modules/@compodoc/compodoc postinstall:   throw err;
.../node_modules/@compodoc/compodoc postinstall:   ^
.../node_modules/@compodoc/compodoc postinstall: Error: Cannot find module '/home/runner/work/wgu-web/wgu-web/node_modules/.pnpm/@compodoc+compodoc@1.1.25_typescript@5.5.4/node_modules/@compodoc/compodoc/tools/copy-libs.js'
.../node_modules/@compodoc/compodoc postinstall:     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
.../node_modules/@compodoc/compodoc postinstall:     at Module._load (node:internal/modules/cjs/loader:1051:27)
.../node_modules/@compodoc/compodoc postinstall:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
.../node_modules/@compodoc/compodoc postinstall:     at node:internal/main/run_main_module:28:49 {
.../node_modules/@compodoc/compodoc postinstall:   code: 'MODULE_NOT_FOUND',
.../node_modules/@compodoc/compodoc postinstall:   requireStack: []
.../node_modules/@compodoc/compodoc postinstall: }
.../node_modules/@compodoc/compodoc postinstall: Node.js v20.17.0
.../node_modules/@compodoc/compodoc postinstall: Done
```

**Comment by landon-buttars-wgu** [comment]
> no update here ? Rollback in version 1.1.22 seems solved the issue

In version 1.1.22 prior to 1.2.23 the tools directory did not exist and the `post-install` call to `node tools/copy-libs.js` did not exist. The issue seems to be the version published to npm is missing the tools directory.
