### ISSUE TITLE
[BUG] Unable to view DOMTree nodes image correctly.

### ISSUE THREAD

**Issue by dharsanav** [compodoc/compodoc#143]
DOM Tree option provided is really nice.But the problem is , image is too small that it is not possible to read the contents(labels of node).Even zooming has no effect.

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc:1.0.0-beta.1
node:v6.9.1

##### **Compodoc installed globally or locally ?**

compodoc is installed locally and included as a dev dependency.

**Comment by vogloblinsky** [comment]
Do you have a screenshot please ?

**Comment by dharsanav** [comment]
Yes.
![image](https://cloud.githubusercontent.com/assets/23713118/24640477/d8530a68-1914-11e7-8a60-5c65bcf8ec36.png)

The problem is when the number of nodes are high. For templates with smaller number of nodes,the DOM Tree looks fine.
