### ISSUE TITLE
[FEATURE] Support 17.1 input signals

### ISSUE THREAD

**Issue by pascal-puetz** [compodoc/compodoc#1434]
##### **Overview of the feature**

Angular 17.1 introduced the new Input Signal API which uses the `input()` or `input.required()` function to expose inputs to the component as an `InputSignal` instead of a plain value. Currently, these are shown in the documentation as properties and not as inputs, which differs from how inputs accessed using `@Input()` are represented in the documentation.

##### **Motivation for or Use Case**

`InputSignal`s are a comfortable way to get your inputs as a signal and will see widespread adoption in the near future. We are using compodoc in our company to generate documentation, not only as a standalone documentation but also for storybook. Since `InputSignal`s are currently not correctly represented in the documentation (which a lot of users rely on), this prevents us from switching to the new API. 

##### **Related issues**

Not that I am aware of.

**Comment by astrutz** [comment]
Hallo @pascal-puetz,

just to get this right before I start digging into this. `input()` should work in the same way as `@Input()` does at the moment with the corresponding `InputSignal<string>` type set (depending on the underlying generic type). Is that correct?

**Comment by attilacsanyi** [comment]
When the [`v1.1.24` milestone](https://github.com/compodoc/compodoc/milestone/39?closed=1) will be released @vogloblinsky ? Thank you so much.

**Comment by attilacsanyi** [comment]
> When the [`v1.1.24` milestone](https://github.com/compodoc/compodoc/milestone/39?closed=1) will be released @vogloblinsky ? Thank you so much.

Any update on this please?

**Comment by vogloblinsky** [comment]
Just released ;)

**Comment by attilacsanyi** [comment]
Thank you so much @vogloblinsky 👏 :)
