### ISSUE TITLE
[QUESTION] Using compodoc for Angular project without Typescript 

### ISSUE THREAD

**Issue by Lowfly** [compodoc/compodoc#144]
First off, excellent plugin! Thank you so much for sharing it! 

I started a new Angular project in pure Javascript (ES6 with decorators, no TS).

Is there any way, options or tricks to use Compodoc with my Angular project without TS?

**Comment by vogloblinsky** [comment]
Hi,

Thanks for the feedback.

It is in the roadmap, but only with TS, sorry. I use TS ast parsing, and mixing with ES6 will be complicated. I want to first focus on TS, may be later managing ES6 too. But the Angular projects with ES6 are less regular than TS projects.

**Comment by vogloblinsky** [comment]
I close this issue.

Esdoc could be an option for you : https://esdoc.org/

or dgeni : https://toddmotto.com/documenting-angular-dgeni

Regards
