### ISSUE TITLE
[FEATURE] Grouping components based on module

### ISSUE THREAD

**Issue by dharsanav** [compodoc/compodoc#145]
Hi,

I would like to suggest that it would be better to have grouping of components according to their modules.Currently components are listed under the **COMPONENTS** section in alphabetical order.It would be useful particularly for larger projects(having lots of components) if the components are grouped together based on their modules.(Just like it's being shown in Modules under Declarations).

For eg:
If componentA and componentB are part of moduleA and componentC part of ModuleB,
then in generated documentation under **COMPONENTS** section
```
ModuleA
componentA
componentB

ModuleB
componentC
```

**Comment by jaufgang** [comment]
I agree. Components, directives, providers, pipes, etc should also all be nested under the modules in which they are declared.  

If possible, it might be nice to have an option in the web UI so that the reader could choose to view the components etc, nested under module or not.  Leaving them un-nested may sometimes be preferred in order to help find a component where the reader doesn't know what module it is in.

**Comment by vogloblinsky** [comment]
Ok, the idea of an web UI option could be fine too.
I thought providing an option for the command-line, but it is too restrictive. 
Typedoc has these kinds of options : http://typedoc.org/api/classes/application.html

**Comment by larsduelfer** [comment]
Hi all,

in addition to this really useful feature, I would suggest to also support nested modules. In larger projects it is beneficial to have modules defined in other modules. This should be reflected in the documentation as well (maybe optional). 

This would help making this great documentation tool working better for larger projects as well!

Regards, Lars

**Comment by vogloblinsky** [comment]
@larsduelfer Yes. I need to really think about a way to manage very deep level of nested modules.
For now it is just a falt list by types.
After you could have :
- module 1
    - module 2
        etc....

**Comment by vogloblinsky** [comment]
@larsduelfer @jaufgang @dharsanav 
Here is a gif of a first design test of a possible implementation of a drilldown menu for modules. Hope it will fix nested modules support and duplicate names too...

![etude-new-menu-gif](https://user-images.githubusercontent.com/2841805/28504163-2250e96a-7012-11e7-9ed8-2066fb50f7c0.gif)

**Comment by larsduelfer** [comment]
@vogloblinsky That looks good! Would it be possible to have the Component, Directive etc. entries then also below the nested modules to be able to see the components for a specific module only? That would be the ideal solution from my perspective.

**Comment by vogloblinsky** [comment]
@larsduelfer 
>Would it be possible to have the Component, Directive etc. entries then also below the nested modules to be able to see the components for a specific module only
What do you mean ?
Did yu have a little example ?

**Comment by larsduelfer** [comment]
- Module A
-- Component
-- Directives 
-- ...
- Module B
-- Component
-- Directives 
-- ...
--- Module B1.1
---- Component
---- Directives 
---- ...
--- Module B1.2
---- Component
---- Directives 
---- ...

**Comment by vogloblinsky** [comment]
Ok, that's the idea of the gif and drilldown menu.
Display list of module by hierarchy.
In the gif, you have AppModule, which contains HomeModule, which contains ListModule, which himself has components, but also directives etc....

**Comment by larsduelfer** [comment]
Ok, than we are on the same page :-) I just wanted to make sure we are, since the gif currently only shows one single Component in the tree. Thanks a lot for the clarification!

**Comment by dharsanav** [comment]
This looks great. Waiting for the feature :)

**Comment by vogloblinsky** [comment]
Links for future dev : 
https://blog.patternfly.org/going-vertical-a-look-at-multi-level-vertical-navigation-for-enterprise-applications/
https://github.com/mewsoft/Bootstrap-DrillDownMenu
https://github.com/ozerk/Foundation5-DrillDownMenu
https://foundation.zurb.com/sites/docs/drilldown-menu.html#Item-1B

**Comment by alan-agius4** [comment]
This feature would also be great in case one i using this inside a mono repo.

**Comment by vogloblinsky** [comment]
I have finally simplify the UI for modules and children :
Here is an example with ngx-admin project :

- before

![localhost_8080_modules_buttonsmodule html](https://user-images.githubusercontent.com/2841805/37263521-debfa996-25a8-11e8-9568-caca44139cc1.png)

- after

![localhost_8080_modules_buttonsmodule html 1](https://user-images.githubusercontent.com/2841805/37263579-0d79643e-25a9-11e8-9d64-ca47885e1ca8.png)

All the components, directives, pipes and injectables of a module are now listed directly inside the concerned module.
