### ISSUE TITLE
[BUG] Search links are broken.

### ISSUE THREAD

**Issue by dharsanav** [compodoc/compodoc#146]
When I search for a particular component say componentA , search results are being displayed,but when I click on these results ,the following message is displayed.

> Cannot GET /interfaces/classes/componentA.html .

I think the search result's link is broken.

When I take componentA from sidebar, the url shown is 

**http://127.0.0.1:5555/components/componentA.html**

but on clicking the search results,the url shown is

**http://127.0.0.1:5555/components/components/componentA.html**

For a directive, the search link shown is 

**http://127.0.0.1:5555/components/directives/directiveA.html**

Compodoc installed locally.

Version :1.0.0-beta.2

**Comment by vogloblinsky** [comment]
Ok reproduced too here, https://compodoc.github.io/compodoc-demo-todomvc-angular/

I miss to handle correctly the search part yesterday when I had fixed https://github.com/compodoc/compodoc/issues/140

**Comment by dharsanav** [comment]
This issue is fixed in 1.0.0-beta.3
