### ISSUE TITLE
[BUG] Input Signals implementation is excluding valid cases

### ISSUE THREAD

**Issue by mridderikhoff** [compodoc/compodoc#1474]
##### **Overview of the issue**

Recently added support for Signal inputs exclude valid cases. [model](https://angular.io/guide/model-inputs) is also a valid Signal input.

The following cases fail the Regex test `/input(?:\.(required))?(?:<([\w-]+)>)?\(([\w-]+)?\)/`. 
```
inputName = input('');
readonly = input(false, { transform: booleanAttribute });
labelPosition = input<SwitchLabelPosition>(SwitchLabelPositions.after);
checked = model(false); 
```

##### **Operating System, Node.js, npm, compodoc version(s)**
`"@compodoc/compodoc": "1.1.24"`

##### **Motivation for or Use Case**
Same motiviation as the [original issue](https://github.com/compodoc/compodoc/issues/1434). Signals are a powerful pattern and the new norm for Angular developers.

##### **Suggest a Fix**
Update the checks in `src/app/compiler/angular/deps/helpers/component-helper.ts` to account for:
- `input` with `''` default value
- `input` with transformers
- `input` with complex type parameters
- `model` inputs

**Comment by angelaman** [comment]
Sorry, I don't think this bug is fixed yet. I just tried it, and many cases listed above are still not supported. I tried to ask AI to write a regex, hope that may help?

```typescript
/input(\.required)?(<([a-zA-Z_$][\w$]*(\s*<\s*[a-zA-Z_$][\w$]*(\s*,\s*[a-zA-Z_$][\w$]*)*\s*>)?(\[\])?)>)?\(([^)]*)\)/
```

matches
![image](https://github.com/compodoc/compodoc/assets/35471671/76f2435b-02bd-44d9-b673-2a67bc5d6ccb)
