### ISSUE TITLE
[BUG] Documentation coverage issue

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#148]
##### **Overview of the issue**

File with 100% documentation coverage got a red line in the report.

**Comment by dwulfde** [comment]
just had a look: everything above 75% is red.

**Comment by vogloblinsky** [comment]
@dwulfde Did you have more info ?

Demo project seems ok for me : https://compodoc.github.io/compodoc-demo-todomvc-angular/coverage.html

**Comment by dwulfde** [comment]
I think 1.0.0-beta3 fixed the problem. Just had a look and it was fine.

**Comment by vogloblinsky** [comment]
Cool, have fun ;)

**Comment by dwulfde** [comment]
Thanks ;) Great job!
