### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by sebastiangarcia-elucid** [compodoc/compodoc#1482]
##### **Overview of the issue**

Impact
If pdf.js is used to load a malicious PDF, and PDF.js is configured with isEvalSupported set to true (which is the default value), unrestricted attacker-controlled JavaScript will be executed in the context of the hosting domain.

Patches
The patch removes the use of eval:
[https://github.com/mozilla/pdf.js/pull/18015](https://github.com/mozilla/pdf.js/pull/18015)

Workarounds
Set the option isEvalSupported to false.

References
[(https://bugzilla.mozilla.org/show_bug.cgi?id=1893645)](https://bugzilla.mozilla.org/show_bug.cgi?id=1893645)

##### **Operating System, Node.js, npm, compodoc version(s)**

MacOs and NodeJS 18 LTS
@compodoc/compodoc": "1.1.23"

##### **Angular configuration, a `package.json` file in the root folder**

@compodoc/compodoc": "1.1.23"

##### **Compodoc installed globally or locally ?**

globally

##### **If possible sourcecode of the file where it breaks**

It's just updating the dependency of pdf.js

##### **Suggest a Fix**

It's just updating the dependency of pdf.js, they already fixed the issue

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/ca5089ba794328306ea5ecdae43b435eaa86018c
