### ISSUE TITLE
[FEATURE] Maintain relative markdown links

### ISSUE THREAD

**Issue by jlutz777** [compodoc/compodoc#149]
##### **Overview of the issue**
We use markdown files to document much of our code and use relative links to link between the markdown files. These relative links work great in bitbucket or github, but after documentation generation the links are broken due to .md files now being .html files. It would be great to change these relative links during generation.

##### **Motivation for or Use Case**
Without this, we have to decide if we want links to work in the documentation generation or when viewing from the repository, but we can't get both without an additional processing step outside of compodoc.

##### **Reproduce the error**
Include additional documentation with relative links, generate the code, and note that the links do not work.

**Comment by jlutz777** [comment]
One idea I have for allowing this is that if a relative-style link is used, you could replace the href with title in the markdown engine renderer.

Something like this:
```
renderer.link = function (href, title, text) {
            let out = '';

            if (href.indexOf('.md') === -1 || !title || title.indexOf('.html') === -1) {
                out = '<a href="' + href + '"';
                if (title) {
                    out += ' title="' + title + '"';
                }
                out += '>' + text + '</a>';
            } else {
                out = '<a href="' + title + '">' + text + '</a>';
            }

            return out;
        };
```

Then in the markdown you could do this:
```
[Link to something][0]
[0]: ../original_file.md (../additional-documentation/generated.html)
```

I'm curious if others have a thought around this. It could be too tailored to my use case, but it seems like others would need this.

**Comment by robertomatute** [comment]
Hi, I am in the same situation.

We want to share same markdown files for our repositorio (gitlab) and to use inside `assets` folder.  But I cannot find a way to link them.
