### ISSUE TITLE
[BUG] : passing declarations as array

### ISSUE THREAD

**Issue by c1rus** [compodoc/compodoc#15]
passing declarations as array generates this.

![declarations](https://cloud.githubusercontent.com/assets/11233730/20237129/1ead9c6e-a8ca-11e6-9c23-08698317aa96.PNG)

and when i click on 'routedComponents', i get:
![cannot](https://cloud.githubusercontent.com/assets/11233730/20237141/67dcaede-a8ca-11e6-83e6-5c27a5663d25.PNG)

example project: https://github.com/c1rus/event-view

**Comment by vogloblinsky** [comment]
compodoc doesn't link files like this issue currently.
`routedComponents` is an import of an array of components from `dashboard-routing.module`
I take your project as test case for future debugging.
