### ISSUE TITLE
[FEATURE] Migrate from traverse to neotraverse 

### ISSUE THREAD

**Issue by trivikr** [compodoc/compodoc#1503]
##### **Overview of the feature**

Migrate from traverse to neotraverse
https://github.com/compodoc/compodoc/blob/da5211f979fedc8a3b000d958c766d4cc85516cc/package.json#L125

There's a codemod available in https://github.com/es-tooling/module-replacements-codemods to migrate from traverse to neotraverse

##### **Motivation for or Use Case**

The [Ecosystem Performance](https://e18e.dev/) was formed in July 2024 to cleanup, speedup, levelup the JavaScript Ecosystem.
Socket Security team wrote a blog post about it https://socket.dev/blog/javascript-community-launches-e18e-initiative-to-improve-ecosystem-performance

On the e18e cleanup channel on Discord, multiple solutions are being discussed. One of them is to replace `traverse` with `neotraverse`, which reduces install size by around 3.5 MB and number of dependencies by 65.
For details, check blog post https://puruvj.dev/blog/forking-and-fixing-traverse

##### **Related issues**

N/A

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/52833690645bc1096510eafad4015a4d33459280
