### ISSUE TITLE
[BUG] Please pin or release a new version of compodoc for cheerio.

### ISSUE THREAD

**Issue by sofisl** [compodoc/compodoc#1504]
Cheerio just released a breaking change in 1.0.0:  https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0

This is stalling all of our repos that depend on compodoc. Would you mind pinning and/or releasing a new version of cheerio?

https://github.com/compodoc/compodoc/blob/da5211f979fedc8a3b000d958c766d4cc85516cc/package.json#L97

See affected PRs: 
- https://github.com/googleapis/google-auth-library-nodejs/actions/runs/10388837570/job/28765406656?pr=1845
- https://github.com/googleapis/google-api-nodejs-client/pull/3525

**Comment by sofisl** [comment]
Bump, we can't release as this is currently breaking all of our tests.

**Comment by cjdreiss** [comment]
Just ran into this issue as well, Cheerio has a library undici which is now at v6 in their release which does not support Node 16.  This is breaking our builds.

**Comment by cjdreiss** [comment]
Related bug for undici, confirming they no longer support node 16 https://github.com/nodejs/undici/issues/3501

**Comment by vogloblinsky** [comment]
Cheerio 1.1.0 don't seem to be very stable : https://github.com/cheeriojs/cheerio/issues
Will try to just pin it to 1.0.0-rc.12

**Comment by cjdreiss** [comment]
I always get burned by ^ and ~ in version numbers, with libraries not following proper sem ver.  Might be worth fixing all the versions of packages while you're at it.

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/d8ff27edf45be74f9855a5a1ef6c583bb6af07cc
