### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sumanalapati** [compodoc/compodoc#151]
##### **Overview of the issue**
Compodoc is running until Process Pages , step, after continuing serveral pages, it stops by throwing **TypeError: Cannot read property 'map' of undefined** error. We have angular2 app with rxjs and ngrx.

##### **Operating System, Node.js, npm, compodoc version(s)**
Mac Os, Node 6.0.4, compodoc 0.40

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "Test,
  "version": "0.0.2",
  "description": "Test",
  "scripts": {
    "ng": "ng",
    "watch": "ng serve -prod -sm -oh none --port 3001 --w=true",
    "build": "ng build -prod -aot -oh none",
    "test": "ng test -sm -sr -cc",
    "posttest": "npm run build",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postbuild": "cp -R deploy/* dist/ && npm run install-server",
    "install-server": "cd dist && npm install",
    "start": "npm run build && node dist/server",
    "compodoc": "./node_modules/.bin/compodoc -p ./tsconfig.json"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",
    "@angular/platform-browser": "^2.4.0",
    "@angular/platform-browser-dynamic": "^2.4.0",
    "@angular/router": "^3.4.0",
    "@ngrx/core": "^1.2.0",
    "@ngrx/store": "^2.2.1",
    "core-js": "^2.4.1",
    "d3": "^4.7.0",
    "intl": "1.2.4",
    "moment": "^2.17.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.7.6"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.1",
    "@angular/compiler-cli": "^2.4.0",
    "@types/d3": "^4.5.0",
    "@types/faker": "^3.1.32",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "angular2-dependencies-graph": "^1.0.0-alpha.12",
    "codelyzer": "~2.0.0",
    "faker": "^4.1.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-spec-reporter": "0.0.30",
    "phantomjs-prebuilt": "^2.1.14",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.4.2",
    "typedoc": "^0.5.10",
    "typescript": "~2.0.0"
  }
}

##### **Compodoc installed globally or locally ?**

Installed both globally and locally and tested with both

**Comment by vogloblinsky** [comment]
@sumanalapati 

Can i have an extract of your terminal log ?
On which file does it break ?

**Comment by dharsanav** [comment]
@sumanalapati Did you try with @compodoc/compodoc - 1.0.0-beta.3 ? Does this error appears in latest version too? I have also encountered same error with earlier versions of compodoc,but now it works fine.

**Comment by sumanalapati** [comment]
@vogloblinsky  PFA
<img width="1440" alt="screen shot 2017-04-11 at 8 27 40 am" src="https://cloud.githubusercontent.com/assets/4342169/24917044/c4922d02-1e90-11e7-9771-c6562016e255.png">

**Comment by vogloblinsky** [comment]
Ok thanks, and code of AccountNumberformatterPipe, is it possible ?

**Comment by sumanalapati** [comment]
@dharsanav 
That actually worked , Thanks. @vogloblinsky  I am closing the defect.


Thanks

**Comment by vogloblinsky** [comment]
Ok fine ! Have fun ! :smile:
