### ISSUE TITLE
[FEATURE] Why does `Documentation Coverage` not account for types/type aliases?

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#1517]
### Discussed in https://github.com/compodoc/compodoc/discussions/1516

<div type='discussions-op-text'>

<sup>Originally posted by **edumserrano** September 27, 2024</sup>
When looking at the `Documentation Coverage` for my library it shows:

- function
- variable
- injectable
- class
- interface
- directive

But I have many types under the `Miscellaneous -> Type Aliases` section that aren't checked for documentation coverage. 

Are types not supported for `Documentation Coverage` or am I doing something wrong?

</div>

**Comment by edumserrano** [comment]
Thank you for the quick fix @vogloblinsky 👏 

Any clue when there will be a release with this fix?

**EDIT: I can see this was recently released with [version 1.1.26](https://github.com/compodoc/compodoc/releases/tag/1.1.26). I've tested and can confirm this is working as expected. Thank you 🥇**
