### ISSUE TITLE
[BUG] Unable to zoom in/out on Modules overview or any other component diagrams

### ISSUE THREAD

**Issue by HLayton** [compodoc/compodoc#153]
I'd like to start by saying that this tool is really useful and you guys have done a great job. This one bug is really causing me problems though.

##### **Overview of the issue**

After generating the compodoc documentation, I cannot zoom in or out of the diagrams for showing component relationships. The graphs generate okay, but the zoom functionality just simply does not work.

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Debian
Node.js: 7.6.0
npm: 4.1.2
@compodoc/compodoc: 1.0.0-beta.3

Tested with:
**Linux**
 - Firefox: 43.0

**Windows**
 - Chrome: 57.0.2987.133 (64-bit)
 - Firefox 52.0 (32-bit)

##### **Angular configuration, a `package.json` file in the root folder**

.angular-cli.json
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": <name>
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [ <styles> ],
      "scripts": [ <scripts> ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json"
    },
    {
      "project": "src/tsconfig.spec.json"
    },
    {
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}`

package.json
`{
  "name": <name>,
  "version": <version>,
  "license": "MIT",
  "scripts": { <scripts> },
  "jshintConfig": {
    "esversion": 6
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.4.10",
    "@angular/core": "^2.4.10",
    "@angular/forms": "^2.4.10",
    "@angular/http": "^2.4.10",
    "@angular/platform-browser": "^2.4.10",
    "@angular/platform-browser-dynamic": "^2.4.10",
    "@angular/platform-server": "^4.0.1",
    "@angular/router": "^3.4.10",
    "@types/leaflet": "^1.0.57",
    "angular2-onsenui": "^1.0.0-rc.6",
    "body-parser": "^1.17.1",
    "chart.js": "^2.5.0",
    "chart.piecelabel.js": "^0.1.0",
    "connect-flash": "^0.1.1",
    "connect-gzip-static": "^2.0.1",
    "connect-pg-simple": "^3.1.2",
    "cookie-parser": "^1.4.3",
    "core-js": "^2.4.1",
    "express": "^4.15.2",
    "express-session": "^1.15.1",
    "http2": "^3.3.6",
    "leaflet": "^1.0.3",
    "md5": "^2.2.1",
    "moment": "latest",
    "needle": "^1.5.2",
    "ng2-bootstrap": "^1.4.1",
    "ng2-charts": "^1.5.0",
    "onsenui": "^2.2.0",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "pg": "^6.1.4",
    "rxjs": "^5.2.0",
    "spdy": "^3.4.4",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0-rc.2",
    "@angular/compiler-cli": "^2.4.10",
    "@angular/compiler": "^2.4.10",
    "@types/jasmine": "2.5.46",
    "@types/node": "~7.0.8",
    "async": "^2.3.0",
    "codelyzer": "~3.0.0-beta.3",
    "gulp": "^3.9.1",
    "gulp-cheerio": "^0.6.2",
    "gulp-modify-file": "^0.1.0",
    "gulp-remove-empty-lines": "0.0.8",
    "gulp-rename": "^1.2.2",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.5.0",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "pretty-data": "^0.40.0",
    "protractor": "~5.1.1",
    "ts-node": "~2.1.0",
    "tslint": "~4.5.1",
    "typescript": "^2.2.1"
  }
}`

##### **Compodoc installed globally or locally ?**

Installed globally using @compodoc/compodoc@latest

##### **Motivation for or Use Case**

This is a bug as there is functionality which simply doesn't work. This is really important functionality as the size of the diagrams makes them hard to use without the ability to zoom in closer.

##### **Reproduce the error**

It happens every time I create the compodoc, regardless of arguments passed.

**Comment by vogloblinsky** [comment]
@HLayton Do you serve the documentation with compodoc or just opening it directly in Chrome ?

**Comment by HLayton** [comment]
I was just opening it directly without serving it. Serving the documentation does seem to solve the problem, although even then it doesn't work all of the time. Sometimes I have to refresh the page to get the controls working.

Are these controls supposed to work only when serving the documentation?

**Comment by vogloblinsky** [comment]
No it is an issue with svg zoom library used: https://github.com/compodoc/compodoc/issues/159
