### ISSUE TITLE
[FEATURE] Link directly to the README of a component

### ISSUE THREAD

**Issue by jlutz777** [compodoc/compodoc#154]
##### **Overview of the issue**
I would like to be able to use a url to get directly to the README of a component and maintain the README in the browser history so the back and forward buttons work.

##### **Motivation for or Use Case**
I would like a route or equivalent for the README because I would like to link directly to the README of a component from other areas of documentation. I also wish that hitting the back button after visiting the README would go back to it. It currently always lands on the Infos tab and then the user has to click on the README tab.

##### **Reproduce the error**
This is an enhancement, not a bug.

**Comment by vogloblinsky** [comment]
For sure, no problem. Just few lines of JavaScript.
I will add in next beta release.
