### ISSUE TITLE
[FEATURE] Coverage test command

### ISSUE THREAD

**Issue by dbartholomae** [compodoc/compodoc#156]
##### **Overview of the issue**

It would be great if I could call compodoc to test for documentation coverage with a certain threshold, e. g. calling `compodoc --coverage-test 90` should return truthy if the project has least 90% documentation coverage and throw an error otherwise.

##### **Motivation for or Use Case**

This would allow to use compodoc for checking documentation coverage on a CI server.

**Comment by vogloblinsky** [comment]
How do you want the return, process exit with 1 if ok or 0 if not ?

**Comment by dbartholomae** [comment]
Basiscally: 0 if coverage is above threshold and 1 if it isn't. The command should fail if the coverage test doesn't succeed.

**Comment by dharsanav** [comment]
Currently if I give the coverage test command along with document generation,it stops as the coverage test command fails.Is this the expected behavior or should it complete documentation generation and then show coverage test failed error??

**Comment by vogloblinsky** [comment]
Yes, it is the expected behavior. Just parse the file, compute coverage, and stop with exit code 0 or 1.
