### ISSUE TITLE
[BUG] Interface Linking is wrong

### ISSUE THREAD

**Issue by felixroos** [compodoc/compodoc#157]
##### **Overview of the issue**

When Using an Interface as return type or parameter type, the linking does not work like expected.
If the interface has an arbitrary name, no linking is done at all.
If the interface contains a name of a class, the class is linked instead:
type "TestInterface" links to class "Test".

##### **Operating System, Node.js, npm, compodoc version(s)**
node v7.5.0, npm 3.10.10, compodoc 1.0.0-beta.3

##### **Angular configuration, a `package.json` file in the root folder**

```json
{
  "name": "ec-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "docs": "npm run typedoc",
    "typedoc": "typedoc --options typedoc.json --exclude '**/*.spec.ts' ./src/",
    "sloc": "sloc src/app --format json > sloc.json",
    "compodoc": "compodoc -p tsconfig.json --includes tutorial --includesName Tutorial"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "ec.datamanager": "^0.11.11",
    "rxjs": "^5.1.0",
    "xlcss": "^2.1.10",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typedoc": "^0.5.10",
    "typescript": "~2.2.0"
  }
}
```

##### **Compodoc installed globally or locally ?**
globally

##### **Motivation for or Use Case**
I use the interface pattern for all configuration objects. It would be nice to have the link to the interface page to see which properties are allowed. Without link, I would be forced to document the properties in the comments which would be redundant.

##### **Reproduce the error**
Example:

```typescript
interface TestInterface {
  name: string
}

class Test {
  test: TestInterface //This type links to Test class, but should link to TestInterface
}

interface AnotherInterface {
  name: string
}

class Foo {
  test: AnotherInterface //This type links to nothing, (but would link if "Another" was an existing class)
}
```

##### **Suggest a Fix**

I did not have a chance to look into the code.

##### **Thank**

Anyway, this tool is killer! Thanks

**Comment by vogloblinsky** [comment]
Example here with oneProperty property : https://compodoc.github.io/compodoc-demo-todomvc-angular/classes/Todo.html
