### ISSUE TITLE
[FEATURE] Add npm dist-tag for 1.0-betas

### ISSUE THREAD

**Issue by PhilippSoehnlein** [compodoc/compodoc#162]
##### **Overview of the issue**

I'd like to test the current compodoc beta version with our CI process, which currently isn't possible because these versions aren't on npm.

##### **Suggest a Fix**

Release the beta versions on npm and hide them into a dist-tag, so they can be installed with something like `npm install compodoc@next`.

**Comment by PhilippSoehnlein** [comment]
I'm sorry, please ignore this issue, I didn't get the memo about the new package name. 
Using `@compodoc/compodoc` now…

**Comment by vogloblinsky** [comment]
No problem, happy documentation !
