### ISSUE TITLE
[BUG] UTF-8 BOM support

### ISSUE THREAD

**Issue by kirkerafael** [compodoc/compodoc#170]
##### **Overview of the issue**
None of my additional classes (not components, directives or such) is documented. All of my models and tools look like this: http://imgur.com/a/0POen (notice well-formatted comments in source view).

Do I miss something important?

Windows 10, node.js v6.8.0, npm 2.10.8, compodoc 1.0.0-beta.7 installed globally

**Comment by vogloblinsky** [comment]
Cannot reproduce it in the demo project, on Windows Y, node.js v6.8.0, npm 3.10.6, compodoc 1.0.0-beta.7 installed globally

Is you have your project in a source management, can you remove all files and not the lontlat.ts, and retest ?

**Comment by kirkerafael** [comment]
Literally the same result with only one file: http://i.imgur.com/3EoS4TP.png. No package.json and no node_modules, empty tsconfig.json, one source file in source directory. UTF-8 Signature encoded. To download if necessary: https://github.com/kirkerafael/bugreports/blob/Compodoc/compodoc%20test%20case.zip

**Comment by vogloblinsky** [comment]
Ok thanks, reproduced.

**Comment by vogloblinsky** [comment]
Strange.

Using one default comment from another file seems to work.

The only difference i have : my file is LF and your is CRLF

**Comment by kirkerafael** [comment]
Nope, just tried converting only line ends and didn't work. What did work was converting file to ANSI. Not viable for me because of non-english comments.

**Comment by vogloblinsky** [comment]
Here is mine test which works :

[compodoc-test-case-vog.zip](https://github.com/compodoc/compodoc/files/961161/compodoc-test-case-vog.zip)

**Comment by kirkerafael** [comment]
Yours - UTF-8 (works) vs mine - UTF-8 Signature (doesn't work).

**Comment by kirkerafael** [comment]
Just downloaded current version to see if it's fixed and its not. So UTF-8 BOM is just not supported?
