### ISSUE TITLE
[BUG] Markdown with html code

### ISSUE THREAD

**Issue by R0muald** [compodoc/compodoc#172]
##### **Overview of the issue**

Part of the description of components, I'm trying to add some code that defines how the component should be used. It's working fine with `js` but I'm not able to get the `html` working properly.
The code definition :
```
/**
 * **HTML**
 *
 * ```html
 * <se-table
 *    [rows]="rows"
 *    [columns]="columns"
 *    [selected]="selected"
 *    [selectable]="selectable">
 * </se-table>
 * ```
 */
```

The result I get:
<img width="620" alt="screen shot 2017-04-26 at 1 34 18 pm" src="https://cloud.githubusercontent.com/assets/1919134/25447998/2305105c-2a85-11e7-8ced-cc7f951d8981.png">

##### **Operating System, Node.js, npm, compodoc version(s)**

@compodoc/compodoc@1.0.0-beta.5

##### **Compodoc installed globally or locally ?**

Compodoc is installed locally

**Comment by vogloblinsky** [comment]
Use @example instead of markdown.

```
/**
 * **HTML**
 *
 * @example
 * <se-table
 *    [rows]="rows"
 *    [columns]="columns"
 *    [selected]="selected"
 *    [selectable]="selectable">
 * </se-table>
 */
```

There is an issue about indentation https://github.com/compodoc/compodoc/issues/138

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/pull/179
