### ISSUE TITLE
[FEATURE] Wildcards in tsconfig excludes

### ISSUE THREAD

**Issue by Zyzle** [compodoc/compodoc#174]
##### **Overview of the issue**
Right now compodoc only excludes files specifically listed in tsconfig, it should also allow wildcard strings

##### **Motivation for or Use Case**
 In my project I usually have a `<service>.mock.ts` file containing the mock version of services for testing, listing these individually becomes difficult in large projects.

It would be good if compodoc allowed the use of wildcards for this such as the one seen for `spec` files: 
```json
"exclude": [
  "**/*.spec.ts",
  "**/*.mock.ts"
]
```

**Comment by csentis** [comment]
Doc composition stops silently at the step "Using tsconfig: ...".

My tsconfig.json contains: `"exclude": [ ...,  "**/*.spec.ts" ]` - with the glob as the last item in the array. Even when putting this to the very beginning of the array, behavior does not change (still a silent stop).

When commenting out the glob pattern line and the comma in the line before, composition runs smoothly.

**Comment by csentis** [comment]
Just wanted to supply more info re beta.10:

with a script in `package.json` reading:

`"doc": "yarn run rimraf -- doc && yarn run compodoc -- --tsconfig tsconfig.json --toggleMenuItems all --output doc --serve --watch",`

... and running `yarn run doc`, I must clarify that the compodoc _does not stop silently but rather runs for a very long time_:

```
1.0.0-beta.10

Node.js version : v8.1.0

Operating system : Windows 10

[22:32:40] Using tsconfig : C:\Users\ ... \tsconfig.json
[22:32:40] Excluding      : C:\Users\ ... \.chrome
[03:11:32] Excluding      : C:\Users\ ... \.gitlab
[03:11:42] Excluding      : C:\Users\ ... \.vscode
[03:11:42] Excluding      : C:\Users\ ... \archive
[03:13:52] Excluding      : C:\Users\ ... \dist
[03:14:18] Excluding      : C:\Users\ ... \node_modules
[03:15:42] Including      : C:\Users\ ... \src\app\account\account-routing.module.ts
[03:15:57] Including      : C:\Users\ ... \src\app\account\account.component.ts

[...]

[03:46:23] Process page   : coverage
[03:46:24] Copy main resources
[03:46:24] Documentation generated in doc in 18823.553 seconds using gitbook theme
[03:46:24] Serving documentation from doc at http://127.0.0.1:8080
[03:46:24] Watching sources in src folder
```

After having run through the excludes, it still needs approx. half an hour to finish.

For the sake of completeness, my `tsconfig.json` reads:

```
{
    "awesomeTypescriptLoaderOptions": {
        "forkChecker": false,
        "useWebpackText": true // allows other loaders to be chained to awesome-typescript-loader
    },
    "buildOnSave": false,
    "compileOnSave": true,
    "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "allowUnusedLabels": false,
        "baseUrl": ".",
        // "checkJs": true,
        "declaration": false,
        "diagnostics": true,
        "disableSizeLimit": true,
        "emitDecoratorMetadata": true,
        // "enableAutoDiscoveryDefinition": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "lib": [
            "es6",
            "dom"
        ],
        "listEmittedFiles": true,
        "listFiles": true,
        "module": "es6",
        "moduleResolution": "node",
        // "noEmit": true,
        "noEmitHelpers": false,
        "noImplicitAny": true,
        // "outDir": "dist/jit",
        "pretty": true,
        "removeComments": false,
        // "skipLibCheck": true,
        "sourceMap": true,
        // "sourceRoot": "./src",
        "strictNullChecks": false,
        "stripInternal": true,
        "suppressImplicitAnyIndexErrors": true,
        "target": "es5",
        "types": [
            // "core-js",
            "node",
            "jasmine",
            "googlemaps"
            // "protractor",
            // "selenium-webdriver"
        ],
        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "exclude": [
        "_reports",
        ".chrome",
        ".gitlab",
        ".vscode",
        "archive",
        "node_modules",
        "dist",
        "src/main.browser.ts",
        "src/main.server.ts",
        "src/express-engine.ts",
        "**/*.spec.ts",
        "**/*.e2e.ts"
    ]
}
```

**Comment by vogloblinsky** [comment]
@csentis 
Can you provide a pastebin with your terminal logs ? or just including/excluding lines.
How many files do you have in your project ?

**Comment by csentis** [comment]
@vogloblinsky Can do. Will let that run and revert here once it's done.

**Comment by vogloblinsky** [comment]
Thanks

**Comment by csentis** [comment]
@voglobinsky [here](https://pastebin.com/zyqy7BkC) you are (the pastebin is due to expire within a month).

Re file count: Included files amount up to 336 in 68 folders. I have noticed that the `.chrome` has a subfolder `cache` which might contribute to a large number of files being parsed - although that `.chrome` directory is listed as an exclude in `tsconfig.json`.

Just for completeness, I have removed the directories starting with a dot from the exclude array in `tsconfig.json` - behaviour stays the same.

Thank you for looking into this.

**Comment by csentis** [comment]
@vogloblinsky Huge step forward:

I had not thought of adding my `.git` directory to the exclude section in `tsconfig.json`. That directory comes right after the `.chrome` directory - which was always the last one mentioned in the terminal log before it took hours until the next exclude showed up.

I have explicitly mentioned the `.git` directory to be excluded in `tsconfig.json` - this is what the terminal log looks like now:
```
[12:07:02] Using tsconfig : C:\Users\cse\Documents\...\tsconfig.json
[12:07:02] Excluding      : C:\Users\cse\Documents\...\.chrome
[12:07:07] Excluding      : C:\Users\cse\Documents\...\.git
[12:07:12] Excluding      : C:\Users\cse\Documents\...\.gitlab
[12:07:23] Excluding      : C:\Users\cse\Documents\...\.vscode
[12:07:23] Excluding      : C:\Users\cse\Documents\...\archive
[12:09:38] Excluding      : C:\Users\cse\Documents\...\dist
[12:10:04] Excluding      : C:\Users\cse\Documents\...\node_modules
[12:11:26] Including      : C:\Users\cse\Documents\...\src\app\account\account-routing.module.ts
```
Although `archive` and `dist` still seem to be parsed (both are excluded in `tsconfig.json`) from here on it runs just fine. _If you have a hint how to speed things up in these excludes, I would be grateful!_

Could be worth mentioning in the docs that properly configured includes and excludes in `tsconfig.json` -
 i.e. completely covering the file+directory structure - can speed things up tremendously. Or, the other way round: can be the cause for unforeseen slowness.

Thank you for being persistent with this one. Keep up the great work!

**Comment by vogloblinsky** [comment]
@csentis 
Cool if the situation has moved in the right path.

I will add remarks in the documentation. I have noticed the "sourceRoot" setting, will add support too.

Your initial problem is still here ? https://github.com/compodoc/compodoc/issues/174#issuecomment-300936876

**Comment by csentis** [comment]
@vogloblinsky Sorry it took me so long. compodoc starts executing at 22:49:26 and finishes at 23:36:03. Takes a while (three quarters of an hour), but does what it is expected to do.

From my point of view this one can be closed.

**Comment by vogloblinsky** [comment]
Ok thanks.

**Comment by junedansari** [comment]
Hi everyone,
i am still facing the same problem.
It is not reading my tsconfig.json for exclude but i am not sure how it is excluding files with extension  spec.ts.

Kindly help if there is anything i am missing.
here is tsconfig.json
"exclude": [
    "./testing/*.ts",
    "test.ts",
    "./src/app/**/*.spec.ts", 
  ]

**Comment by vogloblinsky** [comment]
@junedansari Related to : https://github.com/compodoc/compodoc/issues/243
