### ISSUE TITLE
[BUG] Not able to exclude files from documentation

### ISSUE THREAD

**Issue by liuxinhu** [compodoc/compodoc#175]
##### **Overview of the issue**

I've added files that I want to exclude in "exclude" option in tsconfig.json, but excluded files are still used to generate documentation.

##### **Operating System, Node.js, npm, compodoc version(s)**

macOS, node 6.10.1, npm 4.4.4, compodoc 1.0.0-beta.8

##### **Compodoc installed globally or locally ?**

Locally

##### **Reproduce the error**

I ran: compodoc src -p tsconfig.compodoc.json -sw -disableGraph
with tsconfig.compodoc.json: exclude: [ "**/nodoc/*.ts" ] (I have also tried "src/**/nodoc/*.ts")
After generating documentation, files that should be excluded are still used to generate documentation.

**Comment by Zyzle** [comment]
I think this may be related to #174 it looks like a fix has already been committed.

**Comment by vogloblinsky** [comment]
Yes will coming soon in next beta release this week.

**Comment by liuxinhu** [comment]
Thanks very much! 
I also want to say, not only wildcard doesn't work for me. Even if I specify a concrete file, it doesn't work as well. Maybe I did something wrong?

**Comment by Zyzle** [comment]
@liuxinhu Hmmn, I've been able to exclude files by explicitly giving their path in tsconfig. The path should be relative to the tsconfig file compodoc looks at. So for an angular cli generated project this would be something like:

```json
  "exclude": [
    "test.ts",
    "app/your-module/excluded.ts",
    "**/*.spec.ts",
  ]
```
When using the generated `tsconfig.app.json` file

**Comment by liuxinhu** [comment]
@Zyzle Thanks for your reply. 

I am using another json for compodoc, and my `tsconfig.compodoc.json` looks like this:
```
{
  "exclude": [
    "components/some-component/some-component.ts"
  ]
}
```

However, this doesn't work. After generating, I still see some-component in the documentation.

By the way, I found if I give a non-existed json file, like `compodoc src -p non-exist.json`, I don't see any errors. Is this intended?

**Comment by vogloblinsky** [comment]
@liuxinhu Could you made a test with last release, 1.0.0-beta.9 ?

**Comment by liuxinhu** [comment]
@vogloblinsky 
Hi, thanks for your ask.
I finally found why. It works if I use `compodoc -p src/tsconfig.json`, but doesn't work for `compodoc src -p src/tsconfig.json`. 
I think this is still a bug. I would like to do a fix if it's okay :-)

**Comment by vogloblinsky** [comment]
You are welcome ;)
