### ISSUE TITLE
[BUG] Allow for comments in tsconfig.json

### ISSUE THREAD

**Issue by csentis** [compodoc/compodoc#177]
##### **Overview of the issue**
Currently, compodoc throws in case of comments present in tsconfig.json supplied via `--tsconfig` or `p` stating `Unexpected token / in JSON at position 123`.

##### **Operating System, Node.js, npm, compodoc version(s)**
Win10, node v7.5.0, compodoc v1.0.0-beta.8

##### **Angular configuration, a `package.json` file in the root folder**
`"scripts": { "doc": "rimraf doc && cross-env compodoc --tsconfig tsconfig_wo_comments.json --output ./doc" }`

##### **Compodoc installed globally or locally ?**
local dev dependency

##### **Motivation for or Use Case**
Microsoft allows for comments in tsconfig.json. With this being a used feature, compodoc asks for the developer to deviate from the standard reached before using compodoc.

##### **Reproduce the error**
execute compodoc by supplying a tsconfig with comments starting with `//`

##### **Related issues**
unknown

##### **Suggest a Fix**
angular/angular-cli team already had positively reacted upon a [comparable angular-cli issue #5216](https://github.com/angular/angular-cli/issues/5216)

**Comment by csentis** [comment]
Wow, that was quick! Thank you!

**Comment by vogloblinsky** [comment]
Thanks for the reference of angular-cli issue ;)
