### ISSUE TITLE
bug: node 7?

### ISSUE THREAD

**Issue by wallymathieu** [compodoc/compodoc#18]
Hi! I'm wondering what features in node 7 breaks compodoc? Noticed it when I tried out angular-seed.
```
error compodoc@0.0.8: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 < 7".
error Found incompatible module
```

**Comment by c1rus** [comment]
i have same issue when installing with yarn, npm works.

**Comment by vogloblinsky** [comment]
angular2-dependencies-graph which is the main dependency of compodoc is not compatible with node > 7
https://github.com/manekinekko/angular2-dependencies-graph/blob/master/package.json
I will check that with the owner.

**Comment by wallymathieu** [comment]
npm works by ignoring the package json, where it's clearly says what node versions it expects.

**Comment by vogloblinsky** [comment]
@wallymathieu just tested with nvm and node 7.0.0

I get this npm error :

```
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ENOTSUP

npm ERR! notsup Unsupported engine for compodoc@0.0.13: wanted: {"node":">= 5.4.1 < 7"} (current: {"node":"7.0.0","npm":"3.10.8"})
npm ERR! notsup Not compatible with your version of node/npm: compodoc@0.0.13
npm ERR! notsup Not compatible with your version of node/npm: compodoc@0.0.13
npm ERR! notsup Required: {"node":">= 5.4.1 < 7"}
npm ERR! notsup Actual:   {"npm":"3.10.8","node":"7.0.0"}
```

Just asked the question in angular2-dependencies-graph repository

**Comment by wallymathieu** [comment]
Someone created an issue on https://github.com/manekinekko/angular2-dependencies-graph/issues/40

**Comment by cojack** [comment]
Co, could we now solve this dependency @vogloblinsky as it's already fixed in manekinekko/angular2-dependencies-graph#40 ? :)

**Comment by vogloblinsky** [comment]
yep, @manekinekko has just published a new version on npm

**Comment by cojack** [comment]
@vogloblinsky but here https://github.com/compodoc/compodoc/blob/master/package.json there is still <7
how about this requirements?

**Comment by vogloblinsky** [comment]
Yep, give me 5 min to push a new version 😉

**Comment by vogloblinsky** [comment]
@cojack 0.0.17 pushed
