### ISSUE TITLE
[FEATURE] Detect angular version and link to the correct version of the documentation

### ISSUE THREAD

**Issue by frederikschubert** [compodoc/compodoc#180]
##### **Overview of the issue**

Currently types coming from Angular are linked to their latest documentation. However projects depending on older versions should be linked to the documentation for that version.

##### **Motivation for or Use Case**

Because Angular releases are coming quiet frequently from an enterprise perspective, it is not always possible to keep all projects on the latest release. But to benefit from improvements made at this project we still want to generate the documentation for these project with the newest compodoc version.

##### **Suggest a Fix**

The simplest solution would be to check the `package.json` for the used Angular version and create the links to the correct version of the documentation.

**Comment by vogloblinsky** [comment]
Do you have an example of an Angular API you use ?

**Comment by frederikschubert** [comment]
`IterableDifferFactory` is one example:

Current Documentation: https://angular.io/docs/ts/latest/api/core/index/IterableDifferFactory-interface.html

V2 Documentation: https://v2.angular.io/docs/ts/latest/api/core/index/IterableDifferFactory-interface.html
