### ISSUE TITLE
[BUG/FEATURE] Set marked break option to false 

### ISSUE THREAD

**Issue by tmair** [compodoc/compodoc#181]
##### **Overview of the issue**

Currently the marked.option.break is set to `true`. This causes problems, when compodoc is used in combination with a tslint rule that sets a maximum line length. The consequence is that the documentation has line breaks in illogical places.

Is there a particular reason that line breaks are set to `true`?
Would it be possible to set the setting to `false` or provide a possibility to do so?

**Comment by vogloblinsky** [comment]
It was for converting \n to <br/> using internal Marked code inside comments.
I have reverted to false, and done the transformation inside Compodoc code.
Keep in touch after 1.0.0-beta.9 release today.
