### ISSUE TITLE
[BUG] HTML code in markdown files are not properly escaped

### ISSUE THREAD

**Issue by jlutz777** [compodoc/compodoc#182]
##### **Overview of the issue**
I have markdown files with example HTML snippets in them, in code blocks. The text is not rendered properly. Here is an example md snippet:

Here's a code example:

    ``` html
    <button type="submit" color="primary">Login</button>
    ```

This renders simply as "Login", and I cannot see the code.

##### **Operating System, Node.js, npm, compodoc version(s)**
Windows 7 OS, compodoc 1.0.0-beta.8

##### **Angular configuration, a `package.json` file in the root folder**
"@angular/animations": "4.0.0",
    "@angular/common": "4.0.0",
    "@angular/compiler": "4.0.0",
    "@angular/core": "4.0.0",
    "@angular/flex-layout": "2.0.0-beta.7",
    "@angular/forms": "4.0.0",
    "@angular/http": "4.0.0",
    "@angular/material": "2.0.0-beta.3",
    "@angular/platform-browser": "4.0.0",
    "@angular/platform-browser-dynamic": "4.0.0",
    "@angular/platform-server": "4.0.0",
    "@angular/router": "4.0.0"

##### **Compodoc installed globally or locally ?**
Locally

##### **Motivation for or Use Case**
I have to manually escape the HTML as a workaround right now.

##### **Reproduce the error**
Put a code block with html in a markdown file and run it through compodoc. I did this as an additional md file, not a component README.

**Comment by vogloblinsky** [comment]
How did you write it ? with 3 backtick ?

```
` ` ` // Remove spaces, added for breaking github markdown parsing
<button type="submit" color="primary">Login</button>
` ` `
```

**Comment by jlutz777** [comment]
Sorry, I updated my comment above. Hopefully that is clearer. I use the 3 backtick with html.

**Comment by vogloblinsky** [comment]
Can you provide an example markdown file ?
Just made a test and works well here :

![selection_065](https://cloud.githubusercontent.com/assets/2841805/25906602/668c5c88-35a5-11e7-96a2-21c8e66f9cc1.png)

**Comment by jlutz777** [comment]
I put a gist here:
https://gist.github.com/jlutz777/1851368fd03c265c723bf8d138e7b5d8

**Comment by vogloblinsky** [comment]
Could you provide a screenshot please ?

**Comment by jlutz777** [comment]
Hi Vincent. Are you using the master branch or develop branch? I tried to debug this a bit myself and noticed the develop branch has an escape that isn't there in master. That will likely fix my problem.

**Comment by vogloblinsky** [comment]
Yes i work on develop branch.
I better understand why i didn't found the same error than you.
Next release coming tomorrow.
