### ISSUE TITLE
[QUESTION] Please Support @private JSDoc.

### ISSUE THREAD

**Issue by cipchk** [compodoc/compodoc#183]

**Comment by vogloblinsky** [comment]
Could you describe your use-case ?

`private` keyword directly in TypeScript work fine : https://compodoc.github.io/compodoc-demo-todomvc-angular/classes/Todo.html

**Comment by Chippi** [comment]
I need this too! I'd like to hide Angular method interfaces with the --disablePrivateOrInternalSupport property.

![image](https://cloud.githubusercontent.com/assets/6388933/25941382/8d0bb090-3639-11e7-972b-259da8e004ff.png)

**Comment by vogloblinsky** [comment]
@cipchk Please test  --disablePrivateOrInternalSupport flag, it may help you
@Chippi Feature listed.

**Comment by cipchk** [comment]
@vogloblinsky thank you. i need terseness or succinctness of style or expression. so, i hope `ngOnInit` `onTouchStart` `onTouchMove` etc no longer displayed.

[docs demo](https://cipchk.github.io/ngx-weui/docs/directives/SwipeDirective.html)

**Comment by cipchk** [comment]
thank you again.
