### ISSUE TITLE
[FEATURE] Hide Dom Tree Tab

### ISSUE THREAD

**Issue by Neill83** [compodoc/compodoc#184]
##### **Overview of the issue**

Could it be possible to hide the "Dom Tree" Tab?

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

I just don't need this tab and it's empty always.

Regards

**Comment by RajendrasinhParmar** [comment]
Hello,

I'm generating docs for my project and Dom tree and template both tabs are not shown in generated documentation.

Can anyone help me with this issue?

Thank you

**Comment by vogloblinsky** [comment]
@RajendrasinhParmar which version of compodoc / Node.js / npm did you use please ?

**Comment by RajendrasinhParmar** [comment]
i'm using version "compodoc": "0.0.41", and NodeJs version 6.9.2.

i just installed compodoc using following command.
`npm i --save-dev -E compodoc`

**Comment by vogloblinsky** [comment]
Compodoc has lover from compodoc to @compodoc/compodoc scope in npm 
Just install it with npm i @compodoc/compodoc
