### ISSUE TITLE
[FEATURE] Add an interactive examples tab

### ISSUE THREAD

**Issue by YoussefTaghlabi** [compodoc/compodoc#188]
##### **Overview of the issue**

Looking to add an "Example" `Tab` that displays Component/Directive interactive examples

##### **Motivation for or Use Case**
Compodoc is a great tool to generate static documentation. But there is a need for an interactive example to show the documented Component/Directive/Class in play, similar to what Angular material 2 has.

![image](https://cloud.githubusercontent.com/assets/1639024/26407179/61705b14-4068-11e7-8f03-f0cb8503b58e.png)

##### **Related issues**
None

##### **Suggest a Fix**
I can submit a PR. The implementation is pretty straight forward:
- Search for **xxx.component.example.html**, if it exists, create a new "Examples" Tab, and use the path to the example html file as a src value to an iframe.

![image](https://cloud.githubusercontent.com/assets/1639024/26406990/d6f3478a-4067-11e7-9acc-3c70d18f4e7c.png)

**Comment by vogloblinsky** [comment]
Yes, thanks, it is a good idea.
The problem for me is where do the developer will store the example page ?
Angular material doc is a big Angular app, and the example tab is also a component inside this big dynamic context.

**Comment by YoussefTaghlabi** [comment]
I was thinking to have it under the Same location as the component files;
```
└── my-component/
    ├── my.component.example.html
    ├── my.component.ts
    ├── my.component.spec.ts
    ├── my.component.scss|css
    ├── my.component.html
    └── my.component.md OR README.md
```
Also, this will work in conjunction with `--assetsFolder` to make sure all the `**.example.html` assets fils are available. (I haven't used --assetsFolder option but I assume it just copies a static folder to the folder that has the generated documentation)

**Comment by frederikschubert** [comment]
I would love this feature! Though I would rather have the example contained in an extra folder next to the component code:

```
└── my-component/
    ├── example/
           ├── example.module.ts
           └── example.component.ts
    ├── my.component.ts
    ├── my.component.spec.ts
    ├── my.component.scss|css
    ├── my.component.html
    └── my.component.md OR README.md
```

This way compodoc could itself include an Angular application which loads the example module and instantiates the example component in the example tab.

**Comment by YoussefTaghlabi** [comment]
@frederikschubert That will be ideal but compodoc doesn't know much about the user's environment and it shouldn't; It will be extremely difficult to handle all use cases. 
Angular version, vendors, polyfills...etc all these vary from one user to another.

**Comment by vogloblinsky** [comment]
@frederikschubert
I confirm @YoussefTaghlabi says. Compodoc pages are just html pages, with a little of JavaScript code, but for internal stuff of Compodoc.
This structure seems ok for me :
```
└── my-component/
    ├── example/
           ├── example.my.component.js
           └── example.my.component.html
    ├── my.component.ts
    ├── my.component.spec.ts
    ├── my.component.scss|css
    └── my.component.md OR README.md
```
The `example/example.component.html` could be loaded with an iframe.

**Comment by YoussefTaghlabi** [comment]
@vogloblinsky What will `example -> example.my.component.js` be used for?

**Comment by vogloblinsky** [comment]
@YoussefTaghlabi  
The compiled example app for the component. The maintainer of the documented application needs to manage that during the documentation task, for example launch compodoc + build examples.
This scenario makes me doubt about the advantages of this feature...

**Comment by rprotsyk** [comment]
@vogloblinsky
Can such approach be used as a solution for this feature request?
Please see the attached patch 
[[FEATURE] Add an interactive examples tab.zip](https://github.com/compodoc/compodoc/files/1138582/FEATURE.Add.an.interactive.examples.tab.zip)

Example of usage:
/**
 * Examples: <example-url>/examples/mycomponent.html</example-url>
 *	            <example-url>http://localhost/demo/mysample.component.html</example-url>
 */

**Comment by vogloblinsky** [comment]
@rprotsyk Yes ! thanks, that's the idea. PR welcome :smile:

**Comment by YoussefTaghlabi** [comment]
Well done!

**Comment by seaBubble** [comment]
Is there any best practice regarding where the examples should be saved? I assume under src/docs/examples or similar?

**Comment by vogloblinsky** [comment]
@seaBubble you have to manage yourself the copy of your external examples accross the documentation folder
Compodoc tries to stay as simple as possible on this part of examples tab.
A simple folders examples inside the documentation folder generated by Compodoc is a good starting point.
