### ISSUE TITLE
bug: marked ignore syntax highlighting

### ISSUE THREAD

**Issue by daniele-zurico** [compodoc/compodoc#19]
when in the readme file you try to specify the language to use it's ignored.
example:
html
should produce something like that:
```html
<h1>
  <a name="heading-" class="anchor" href="#heading-">
    <span class="header-link"></span>
  </a>
  heading+
</h1>
```

instead it produce:

```
<h1>
  <a name="heading-" class="anchor" href="#heading-">
    <span class="header-link"></span>
  </a>
  heading+
</h1>
```

reference: https://github.com/chjj/marked#highlight

**Comment by daniele-zurico** [comment]
Looks like that the internal .md still doesn't recognise it

**Comment by vogloblinsky** [comment]
I just updated the ng2 demo app with two code block in main README and todoComponent README file.
https://compodoc.github.io/compodoc-demo-todomvc-angular2/components/TodoComponent.html
Is your issue different ?
