### ISSUE TITLE
[FEATURE] PDF Export support

### ISSUE THREAD

**Issue by carlobonamico** [compodoc/compodoc#190]
##### **Overview of the issue**
In many context there are requests for also producing PDF documentation. Currenlty, compodoc only generates html documentation.

This could be implemented with three levels of integration: 
1) adding some javascript code to integrate with tools such as https://github.com/melix/deck2pdf or https://wkhtmltopdf.org/
2) generating a single html page which then can be feed to https://wkhtmltopdf.org/ or headless chrome for conversion
3) direct PDF export from the compodoc generation

##### **Operating System, Node.js, npm, compodoc version(s)**
n/a for now, to be refined

##### **Compodoc installed globally or locally ?**
n/a

##### **Motivation for or Use Case**
Support for printing the documentation, or distributing it offline to an ebook reader

##### **Reproduce the error**
n/a

##### **Related issues**
n/a

##### **Suggest a Fix**
n/a

**Comment by vogloblinsky** [comment]
Hi,
Yes it could be a cool feature.
After some researches on npm, the strategy could be to specify the output type --pdf, rendering in memory all the html, and generate the main pdf at the end.

**Comment by carlobonamico** [comment]
Tools such as headless chrome
https://developers.google.com/web/updates/2017/04/headless-chrome#create_a_pdf_dom

And phantom Js
http://phantomjs.org/screen-capture.html

Already support PDF generation from a single html page.

Maybe a first step could be that of supporting the generation of the
documentation in a single HTML file, which can then be converted to PDF
more easily.

**Comment by vogloblinsky** [comment]
@carlobonamico 
Yes, that will be the strategy. Build only one page during generation, and at the end launch such a tool, phantomjs for example to build the pdf.

**Comment by DrMabuse23** [comment]
Hi there iam also interested about this feature. I can help anywhere ? to get a little bit faster ?

**Comment by vogloblinsky** [comment]
@DrMabuse23 
We are working on JSON export feature, PDF will follow just after that.
To be more independant of rigid solution like phantomjs or wkhtmltopdf, i think we will use libraries like pdfmake http://pdfmake.org/playground.html

**Comment by jdmichaud** [comment]
Is this feature still planned?

**Comment by vogloblinsky** [comment]
@jdmichaud Yes, work in progress on this feature branch : https://github.com/compodoc/compodoc/tree/feature/pdf-export

**Comment by hiteshkumar04** [comment]
Is there any export functionality provided with it?

**Comment by Sofiane000** [comment]
Any idea when will this be ready? Thanks

**Comment by sgarelle** [comment]
Any plan to implement this feature?

**Comment by vogloblinsky** [comment]
Just restarted the work. Coming soon.

**Comment by Sofiane000** [comment]
@vogloblinsky , any progress on this please ?
Thanks

**Comment by gtamas** [comment]
What's up with this? When can we expect this feature to be released?

**Comment by goseeya** [comment]
@vogloblinsky any update please?

**Comment by SWGeekPD** [comment]
Any update on this feature...

**Comment by WyRe** [comment]
I'm also interested on updates about this feature :-)

**Comment by radarsu** [comment]
Any update on that?

**Comment by csasfr** [comment]
Updates ?

**Comment by haexyh** [comment]
huh?

**Comment by kenanaReda** [comment]
so it seems this feature hasn't been released yet?

**Comment by Botrap** [comment]
Any update on this?

**Comment by eddytnk** [comment]
Is this still a plan or not?

**Comment by vogloblinsky** [comment]
Yes, planned for 1.2.0

**Comment by ALapaque** [comment]
@vogloblinsky Hi there, do you have any news on this features and the release date of the 1.2.0 ?

**Comment by matusko89** [comment]
@vogloblinsky any update on this? Thank you

**Comment by stefan-de** [comment]
When does the PDF export feature comes?
