### ISSUE TITLE
[BUG] package.json * version results in npm update not working

### ISSUE THREAD

**Issue by CanadianEngineer** [compodoc/compodoc#191]
I recently discovered an issue this morning regarding compodoc.
**Issue**
If you have `@compodoc/compodoc` version set to be `*` in your `package.json` file, running `npm update` will result in a `cb() not being called` error.

**Fix**
Set the version to be a specific string. I've set mine to be `"@compodoc/compodoc": "^1.0.0-beta.9"` which seems to fix the issue.

**Comment by vogloblinsky** [comment]
Just tested, seems to be an npm bug.

```
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vincent/.npm/_logs/2017-06-09T22_56_18_860Z-debug.log
```
