### ISSUE TITLE
[BUG] Trailing commas throw error when parsing routes

### ISSUE THREAD

**Issue by benjamincharity** [compodoc/compodoc#192]
##### **Overview of the issue**

If there are trailing commas in the routes definition, `compodoc` throws an error:

> Routes parsing error, maybe a trailing comma or an external variable, trying to fix that later after sources scanning.

##### **Operating System, Node.js, npm, compodoc version(s)**

```
OS X 10.12.5
yarn: 0.24.6
npm: 5.0.1
@angular/cli: 1.1.0
node: 8.0.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
@angular/language-service: 4.1.3
```

##### **Angular configuration, a `package.json` file in the root folder**

```json
{
  "name": "components-test",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json --theme stripe --hideGenerator --coverageTest"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.3",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/material": "^2.0.0-beta.6",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-ladda": "^1.2.1",
    "core-js": "^2.4.1",
    "ngx-messages": "^0.2.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.1.0",
    "@angular/compiler-cli": "^4.0.0",
    "@angular/language-service": "^4.0.0",
    "@compodoc/compodoc": "^1.0.0-beta.9",
    "@types/jasmine": "2.5.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "sass-material-colors": "^0.0.5",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  }
}
```

##### **Compodoc installed globally or locally ?**

Globally

##### **Motivation for or Use Case**

The project I am working on is using `tslint` to enforce styles. Part of the styleguide requires trailing commas. Changing the rule and entire repo is not possible at this time, so the only way to solve the error is to disable `tslint` around each of the routing declarations.

##### **Reproduce the error**

1. Use trailing commas in your route declarations:

```
const INVENTORY_ROUTES: Routes = [
  {
    path: 'inventory',
    component: InventoryComponent,
  },
];
```

2. Run `compodoc`: `./node_modules/.bin/compodoc -p src/tsconfig.app.json`

**Comment by maxencefrenette** [comment]
The issue seems to be fixed in the newest beta. Just install version 1.0.0-beta.9 (or newer) from @compodoc/compodoc and you should be alright.

**Comment by benjamincharity** [comment]
Hmm.. I'm currently on `1.0.0.0-beta.9` and seeing this error.

- `rm -rf node_modules/`
- `yarn install`

Looking into the actual files downloaded to `node_modules` shows the correct version:
![screen shot 2017-06-05 at 12 20 34 pm](https://cloud.githubusercontent.com/assets/270193/26792752/761b7b4a-49e9-11e7-8b4b-992395588125.png)

### Code causing error

```typescript
const INVENTORY_ROUTES: Routes = [
  {
    path: 'inventory',
    component: InventoryComponent, // adding this comment throws error
  }, // adding this comment throws error
];

```

### Error

![screen shot 2017-06-05 at 12 22 15 pm](https://cloud.githubusercontent.com/assets/270193/26792812/a558b7d8-49e9-11e7-94ab-23be1cde5afb.png)

**Comment by maxencefrenette** [comment]
I was completely wrong, sorry. I edited my comment above.

**Comment by vogloblinsky** [comment]
@maxencefrenette 
Thanks for JSON5 link. Works fine with route parser.
Bug fixed, coming in next release soon.
