### ISSUE TITLE
[BUG] Modifier kind and icon are incorrect with TypeScript 2.3

### ISSUE THREAD

**Issue by Swiftwork** [compodoc/compodoc#197]
##### **Overview of the issue**

The modifKind and modifIcon methods rely on id's to determine what to map against. Seems as if these id's have changed causing e.g. public to be considered as static.

##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc: 1.0.0-beta.9
Node.js version : v7.5.0
Operating system : Windows 8.1

##### **Angular configuration, a `package.json` file in the root folder**

Occurs in the live demo as well

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

Misinformation

##### **Reproduce the error**

Check the live demo under the _title property
https://compodoc.github.io/compodoc-demo-todomvc-angular/classes/Todo.html#source

##### **Related issues**

Not that I can determine.

##### **Suggest a Fix**

These should be the offending lines. The id's I get for modifKind are 112, 113, 114, 115, 117 in my project
https://github.com/compodoc/compodoc/blob/aee4a243993f5578ab8909e1c24640a65cd8b42b/src/app/engines/html.engine.helpers.ts#L103-L140

**Comment by vogloblinsky** [comment]
Thanks, already fixed few days ago, it will coming soon in next release this week :smiley:

**Comment by Swiftwork** [comment]
Great work @vogloblinsky!

**Comment by vogloblinsky** [comment]
Fixed with 1.0.0-beta.12
