### ISSUE TITLE
[FEATURE] Add CLI option to ignore paths of files

### ISSUE THREAD

**Issue by steveblue** [compodoc/compodoc#199]
##### **Overview of the issue**

There is at least one folder of TS that we do not want to be documented, it would be nice to exclude folders or files in the CLI options.

##### **Angular configuration, a `package.json` file in the root folder**

4.2.0

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

We have several files that serve as templates that are copied into actual Components using a custom CLI. We do not want the folder of these template documented. We also compile AOT to a folder we do not want to be scanned, as well as a build folder.

##### **Related issues**

?

##### **Suggest a Fix**

--exclude /path/to/folder /path/to/file.ts

**Comment by vogloblinsky** [comment]
Did you try to use the exclude property of tsconfig which is supported by Compodoc ?
You can exclude one file or a group with a pattern.

**Comment by steveblue** [comment]
That worked! We have a couple missing folders in the exclude Array. TY.

**Comment by vogloblinsky** [comment]
👍🏻
