### ISSUE TITLE
[BUG] Documentation coverage badge size should match common badges

### ISSUE THREAD

**Issue by benjamincharity** [compodoc/compodoc#200]
##### **Overview of the issue**

Most badges seem to follow common dimensions which makes the badge generated by compodoc seem out of place:

![screen shot 2017-06-13 at 8 23 32 am](https://user-images.githubusercontent.com/270193/27082406-90ebbdc0-5012-11e7-9d05-1e0ccaa48916.png)

##### **Motivation for or Use Case**

I like pretty things and my OCD is yelling at me..

##### **Reproduce the error**

- Add the generated docs badge to your readme
- Add a badge from shields.io, circleci (or almost any other)

##### **Suggest a Fix**

Change sizing:
- The standard size seems to be `20px` tall (width is determined by content).
- Double bonus: Set the width according to how many characters are needed in the number (ie 1% needs less horizontal space than 100%. [`data.count.length`?](https://github.com/compodoc/compodoc/blob/bd6d7700eeaec832c0f5c7f2ae8d9d72faabde3c/src/templates/partials/coverage-badge.hbs))

Change case:
- It seems that most badges I've found are all lowercase.

**Comment by vogloblinsky** [comment]
Maybe renaming it to : "documentation coverage"

**Comment by Swiftwork** [comment]
Either that or just "documentation", I find that to be descriptive enough, especially with the percentage.

**Comment by vogloblinsky** [comment]
Ok i leave "documentation"
