### ISSUE TITLE
[BUG] Can't install compodoc : Unrecognized token in source text

### ISSUE THREAD

**Issue by Robouste** [compodoc/compodoc#202]
##### **Overview of the issue**

Can't install compodoc via npm

`npm install -g @compodoc/compodoc`

![image](https://user-images.githubusercontent.com/5463032/27282014-8dd1ffe2-54ee-11e7-8eef-a6a6aa4c2258.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 7
Node 6.10.2
NPM 3.10.10

##### **Reproduce the error**

`npm install -g @compodoc/compodoc` 

Other npm install commands work fine

**Comment by vogloblinsky** [comment]
https://stackoverflow.com/questions/38040479/trying-to-install-angular-2-material-from-npm-unrecognized-token-in-source-tex/43533031

- try with quotes : `npm install -g "@compodoc/compodoc"`
- use cmd instead of PS

**Comment by Robouste** [comment]
Using quotes with PS works !

Thank you :)

**Comment by vogloblinsky** [comment]
I will update the doc.
