### ISSUE TITLE
[BUG] Syntax highlighting for TypeScript/JavaScript/JSON missing in 1.0.0-beta.10

### ISSUE THREAD

**Issue by Swiftwork** [compodoc/compodoc#203]
##### **Overview of the issue**

Cannot generate code blocks for typescript using neither `@example` nor ` ```typescript `. Currently running update 1.0.0-beta.10. Great work otherwise btw!

##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc: 1.0.0-beta.10
Node.js version : v7.5.0
Operating system : Windows 8.1

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

Either the live demo isn't updated to 1.0.0-beta.10, or there is something missing in my environment, but examples are a big part of my documentation. I personally need support for TypecScript, Javascript, JSON, CSS (Less/SaSS/PostCSS) and HTML (Angular templates).

##### **Reproduce the error**

```typescript
/**
 * Abstract view data service which must be extended to facilitate fetching of JSON data
 * from a specific content management systems (see {@link EpiViewDataService}).
 * 
 * Bootstraping example (DtmService is optional):
 * 
 * ```typescript
 * @NgModule({
 *   providers: {
 *     provide: ViewDataService,
 *     useClass: EpiViewDataService,
 *     deps: [Http, Router, Logger, DtmService],
 *   },
 * })
 * export class AppModule { }
 * ```
 */
@Injectable()
export abstract class ViewDataService<T> { }
```

##### **Related issues**

Could not find any.

##### **Suggest fixes**

Add to documentation which syntaxes are supported / system used.

**Comment by vogloblinsky** [comment]
The bug seems related to TypeScript parsing JSDoc comment and @NgModule decorator.

This comment works fine :
```
/**
 * Abstract view data service which must be extended to facilitate fetching of JSON data
 * from a specific content management systems (see {@link EpiViewDataService}).
 * 
 * Bootstraping example (DtmService is optional):
 * 
 * ```typescript
 * export class AppModule { }
 * ```
 */
```

Need to investigate deeper.

**Comment by dotansimha** [comment]
Same here. any `@` on the example causes it to break when generated.

**Comment by vogloblinsky** [comment]
Related to https://github.com/compodoc/compodoc/issues/304
304 will be the main issue for this @ TypeScript parsing problem
