### ISSUE TITLE
[FEATURE] Markdown file support for modules, services, etc

### ISSUE THREAD

**Issue by jaufgang** [compodoc/compodoc#204]
Currently, compodoc supports adding a README documentation tab for components using markdown files:

> Documentation of each component
>
> A comment description in xxx.component.ts file, between JSDoc comments can be a little short.
>
> Compodoc search for a default xxx.component.md or README.md file inside the root folder of each component, and add it inside a tab in the component page.

This is a great feature,  and it would be even better if it worked the same way for modules, services, directives, pipes, etc.   There are lots of good reasons to add documentation this way.  

Also, the current implementation only works for components using the file naming convention `xxx.component.ts`.  In my Ionic project I have "page" components which use a similar but different convention `aaa.page.ts` and I would like to be able to name my  markdown file using a parallel naming scheme `aaa.page.md`.  Currently, this does not work.  The angular style guide does allow for this in [style-02-02](https://angular.io/guide/styleguide#style-02-02)

>Do use conventional type names including .service, .component, .pipe, .module, and .directive. Invent additional type names if you must but take care not to create too many.

I think it would be preferable for compodoc to recognize any .md file with the same file name prefix as any component/module/service/ etc and attatch that to the documentation, regardless of other file naming conventions.

**Comment by vogloblinsky** [comment]
Hi,
Yes i have to add this feature for others types (modules etc...)
I will follow your suggestion about file naming, better than just searching for README.md or my.component.md
