### ISSUE TITLE
Error when setting title as multiple words

### ISSUE THREAD

**Issue by jasedwards** [compodoc/compodoc#207]
##### **Overview of the issue**

when setting the title (-n) to multiple words an error is thrown.  So if I do -n 'My App' you get an error stating "Provided source folder App was not found in the current directory".  It basically thinks the 2nd word is the source directory even if I put it in single or double quotes.

##### **Operating System, Node.js, npm, compodoc version(s)**

Win 7, Node 6.9.x , Compodoc version 1.0.0-beta.10
##### **Angular configuration, a `package.json` file in the root folder**

App built using angular cli

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

I would like multiple words in the title

##### **Reproduce the error**

run it with this as the script in package.json:
"./node_modules/.bin/compodoc -p src/tsconfig.app.json -a screenshots -n 'My App' --toggleMenuItems 'all'",

**Comment by vogloblinsky** [comment]
Try escaping with double quotes :

```
{
   ... 
   "doc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json -a screenshots -n \"My App\" --toggleMenuItems \"all\""
   ...
}
```
