### ISSUE TITLE
bug: Are JSDoc comments required to generate doc entries?

### ISSUE THREAD

**Issue by brian428** [compodoc/compodoc#21]
It appears that doc entries for properties and methods are only created if a code element has a JSDoc comment on it. Is that right, and if so, is that deliberate? I haven't looked into how the app code is parsed, but if the TS compiler is used then it seems like that would supply sufficient information to create prop/method entries with name, params, types, etc. Everything beyond an actual text description.

Thoughts?

And thanks for the work on this. Something like this was sorely needed!

**Comment by vogloblinsky** [comment]
Hi,
Just tested, it is a bug. You are right, it is the TS parser that is used.
I will fix that, in order to always have properties or methods, even they have or not JSDoc comments.

**Comment by brian428** [comment]
Great, thanks for the quick reply and great work!

**Comment by brian428** [comment]
0.0.14 seems to fix a lot of this, so thanks for that. However, for some reason it seems that classes listed in the "Classes" section are still missing props and methods.

Also, in the "unrelated but would be nice" category:
- It seems that static members aren't being included.
- Standalone files that only export functions also don't seem to be included. I'm not really sure what the best way to include those would be, but obviously it would be nice to fit them in somewhere if possible.

**Comment by vogloblinsky** [comment]
Just published 0.0.15 version
Static functions are supported
https://compodoc.github.io/compodoc-demo-todomvc-angular2/classes/Todo.html
https://github.com/compodoc/compodoc-demo-todomvc-angular2/blob/master/src/app/shared/models/todo.model.ts
I add the standalone exporter files in the todo list.
