### ISSUE TITLE
[FEATURE] Resolve array declaration in modules

### ISSUE THREAD

**Issue by Robouste** [compodoc/compodoc#210]
##### **Overview of the issue**

I like to use a shared module through my application. Since each module/component/pipes etc need to be written twice (in declaration/import and in export), I classify them with arrays.

Example

```JS
const MODULES = [
    // modules
];

const COMPONENTS = [
    // components
];

const PIPES = [
    // pipes
];

@NgModule({
    imports: [
        MODULES
    ],
    exports: [
        MODULES,
        COMPONENTS,
        PIPES
    ],
    declarations: [
        COMPONENTS,
        PIPES
    ],
    providers: [],
})
export class SharedModule { }
```

But when doc is generated, it doesn't resolve arrays and output something like this : 

![image](https://user-images.githubusercontent.com/5463032/27477506-c43af004-580c-11e7-9362-606fbf3d8150.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc 1.0.0-beta.10

##### **Compodoc installed globally or locally ?**

globally

##### **Motivation for or Use Case**

Being able to see which components/modules etc are actually in the module

**Comment by vogloblinsky** [comment]
Related to #15
