### ISSUE TITLE
[FEATURE] Support for link to sub object within documents

### ISSUE THREAD

**Issue by petemcwilliams** [compodoc/compodoc#211]
##### **Overview of the issue**
Add an Id or Name tag to sub objects within documents, such as a link to the name of a method.  which can be accessed with markdown syntax from outside the document.

`[link]('./file#method-name')`

##### **Operating System, Node.js, npm, compodoc version(s)**

node -v
v6.9.4
npm -v
3.10.10

"@compodoc/compodoc": "^1.0.0-beta.10",

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

Main reason is trying to find a simple solution to avoid duplication of documentation between abstract methods and their implementation.  I would like to link the implementation description to the abstract declaration.

Could also be used to generate a table of contents of methods for example.

##### **Suggest a Fix**

Add `<a name="{{name}}"></a>`to lines such as 
`<b>{{#if modifierKind}}<span class="modifier">{{modifKind modifierKind}}</span>{{/if}} <a name="{{name}}"></a>{{name}}</b>`
in block-method.hbs

**Comment by petemcwilliams** [comment]
Looks like this is already fixed and released?

1.0.0-beta.14
@vogloblinsky vogloblinsky released this 27 days ago · 30 commits to master since this release
Changes
index for functions, variables, inputs etc

**Comment by vogloblinsky** [comment]
@petemcwilliams i don't think it is ok for first main subject of the issue. the second one is fixed and available.

Do you have a simple example of what you want to do with "link the implementation description to the abstract declaration." Thanks

**Comment by petemcwilliams** [comment]
The fact you have provided a method to link into the documentation was all I needed, I was only thinking about manually linking to the abstract class documentation

```
export abstract class AbstractAuthService {
    /**
     * Check if the user email in the request exists on the server, controls the flow of login to existing or new user
     *
     * @abstract
     * @param {AuthEmailUserExistsRequestModel} request
     * @returns {Promise<AuthEmailUserExistsResponseModel>}
     * @memberof AbstractAuthService
     */
    public abstract checkIfUserExists(request: AuthEmailUserExistsRequestModel):
        Promise<AuthEmailUserExistsResponseModel>;
}

@Injectable()
export class AuthService extends AbstractAuthService {

    /**
     * See [AbstractAuthService](./../classes/AbstractAuthService.html#checkIfUserExists) for details
     *
     * @param {AuthEmailUserExistsRequestModel} request
     * @returns {Promise<AuthEmailUserExistsResponseModel>}
     *
     * @memberOf AuthService
     */
    public checkIfUserExists(request: AuthEmailUserExistsRequestModel): Promise<AuthEmailUserExistsResponseModel> {
        <snip>
    }
}
```

**Comment by vogloblinsky** [comment]
@petemcwilliams this should work now with 1.0.1
```
[AbstractAuthService]{@link AbstractAuthService#checkIfUserExists}
```

**Comment by petemcwilliams** [comment]
Thanks for your help confirmed working as expected version 1.0.1.

Really like the tool.
