### ISSUE TITLE
[FEATURE] @default support

### ISSUE THREAD

**Issue by artemsky** [compodoc/compodoc#212]
##### **Overview of the issue**

[@default at JSDoc](http://usejsdoc.org/tags-default.html)

It would be great to implement this feature because all of us have default values in our code.

**NOW**

![alt text](http://i.imgur.com/HnNT3Pn.png "NOW")

**FUTURE**

![alt text](http://i.imgur.com/PFyNAz4.png "NOW")

##### **Motivation for or Use Case**

70% of my code has default values. So it would be great to display them in the documentation.

**Comment by vogloblinsky** [comment]
@artemsky showProgressBar is not instanciated with true in your code ?

```
...
    showProgressBar:boolean = true;
...
```

The demo project is a good example : https://compodoc.github.io/compodoc-demo-todomvc-angular/components/HeaderComponent.html#infos 
Watch title property.

As descrive in Compodoc documentation (https://compodoc.github.io/website/guides/comments.html), TypeScript doesn't handle all JSDoc tags, so Compodoc too.

**Comment by artemsky** [comment]
@vogloblinsky unfortunately i can't assign a default value because its a part of my interface.

```
export interface SnotifyConfig {
  /**
   * Enable/Disable progress bar. Disabled if timeout is 0.
   * Default: true
   *
   * @type {boolean}
   */
  showProgressBar?: boolean;
  /**
   * Type of toast, affects toast style.
   * It's not recommended to change it.
   * Default: Depends on toast type - success | async | error | etc...
   */
  type?: SnotifyType;
  /**
   * Enable/Disable toast close by clicking on it
   * Default: true
   * @type {boolean}
   */
  closeOnClick?: boolean;
}
```

**Comment by artemsky** [comment]
@vogloblinsky So, you reopened this issue. Have a hope that it would be implemented in future?)

**Comment by vogloblinsky** [comment]
Yes, just tested, works fine. I add that in next release.
Regards
