### ISSUE TITLE
[FEATURE] support to display the changelog.md

### ISSUE THREAD

**Issue by wittemann** [compodoc/compodoc#215]
##### **Overview of the issue**
Some project do have a CHANGELOG.md file which might be handy to read for people scrolling trough the docs. The best option could be in the top level structure next to the readme file. Ofc, this file is optional as not every project has it but a build in support might help some people.

##### **Compodoc installed globally or locally ?**
locally

##### **Suggest a Fix**
It could be treated like a second readme file as its a markdown file anyway.

**Comment by vogloblinsky** [comment]
Related to #221
