### ISSUE TITLE
[BUG] Route parsing error

### ISSUE THREAD

**Issue by Stalyon** [compodoc/compodoc#216]
##### **Overview of the issue**

I have the following issue:

> [08:45:30] parsing        : D:/xxx/xxx-xx-routing.module.ts
> [08:45:30] Routes parsing error, maybe a trailing comma or an external variable, trying to fix that later after sources scanning.

My routing module is:

```
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { AuthGuardService } from '../common/services/auth-guard.service';
import { AComponent} from './a.component';
import { Role } from '../common/model/enum/role.enum';

const routes: Routes = [
    {
        path: 'a-path',
        component: AComponent,
        data: { requiresLoggedIn: true, requiresRole: [ Role.ROLE_XXX ] },
        canActivate: [ AuthGuardService ]
    }
];

@NgModule({
    imports: [
        RouterModule.forChild(routes)
    ],
    exports: [
        RouterModule
    ]
})
export class XXXRoutingModule { }
```

And my command in package.json is:

> "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json -n 'Documentation-Angular' --theme readthedocs -s

The issue is not a comma. 
The problem seems to be there:
```
        data: { requiresLoggedIn: true, requiresRole: [ Role.ROLE_XXX ] },
        canActivate: [ AuthGuardService ]
```
When I remove this part of code, there is no problem.

What could be the solution ?

##### **Compodoc installed globally or locally ?**
locally

##### **Versions**
compodoc: 1.0.0-beta.10
npm: 5.0.4
node: 8.0.0
Windows 10

**Comment by vogloblinsky** [comment]
Related to #51

**Comment by szendo** [comment]
Not work for me.

```
const APP_ROUTES: Routes = [
  {
    path: '',
    redirectTo: '/app/abc',
    pathMatch: 'full'
  },
  {
    path: '**',
    redirectTo: '/app/error'
  }
];
```

Compodoc installed globally or locally ?
locally

Versions

compodoc: 1.2.0
node: 6.0.88
Windows  7

**Comment by vogloblinsky** [comment]
Bug fixed for dynamic path and pathMatch for route definition.
Need to work on other parts of route description : https://angular.io/api/router/Routes#description

**Comment by Gruwa** [comment]
Same problem

following issue:

```
[01:28:22] found          : AppComponent
[01:28:22] parsing        : /Users/aleks/Projects/mentarea-front/src/app/app.module.ts
[01:28:22] Analysing routes definitions and clean them if necessary
[01:28:22] Routes parsing error, maybe a trailing comma or an external variable, trying to fix that later after sources scanning.
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'kind' of undefined ....
```

routing module is:

```
const appRoutes: Routes = [
  {
    path: 'calendar',
    component: CalendarComponent
  },
  {
    path: 'auth',
    component: LoginComponent
  },
  {
    path: '',
    redirectTo: 'auth',
    pathMatch: 'full'
  },
  {
    path: '**',
    redirectTo: 'auth'
  }
];

```
Compodoc installed globally or locally ?
locally

Versions

compodoc: 1.0.9
node: 8.9.4
Mac OS X version 10.11.6

**Comment by gangfang** [comment]
@Gruwa Please update compodoc from 1.0.9 to 1.1.1 (latest). 

Just tried it, the problem is resolved.
