### ISSUE TITLE
[BUG] Unhandled promise rejection (rejection id: 1): RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by tonystark404** [compodoc/compodoc#217]
##### **Overview of the issue**
Getting `Maximum Call stack size exceeded` Error. The parsing was done successfully but the it's throwing this error it's Processing Pages.

`[18:47:15] Process page   : ShiftService
(node:24036) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): RangeError: Maximum call stack size exceeded
(node:24036) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

##### **Operating System, Node.js, npm, compodoc version(s)**
OS: Win10
Node: Tried with both 7.9.0 and 8.1.3
compodoc: 1.0.0-beta.9

 The project is a very big one with more than 100 components, 10 lazy loaded modules. 

##### **Compodoc installed globally or locally ?**
global

**Comment by vogloblinsky** [comment]
Do you have ShiftService code available ?

**Comment by tonystark404** [comment]
ShiftService Code - https://pastebin.com/LDG1DXvv

Might it be because of the large JSON data in constructor?

**Comment by tonystark404** [comment]
Removing everything in the constructor fixed it
