### ISSUE TITLE
[BUG] : Routes parsing error when use "System.import('')"

### ISSUE THREAD

**Issue by jpcode** [compodoc/compodoc#22]
```javascript
import { Routes, RouterModule }  from '@angular/router';
import { Layout } from './layout.component';
const routes: Routes = [
  { 
    path: '', component: Layout, children: [
      { path: '', redirectTo: 'home', pathMatch: 'full' },
      { path: 'home', loadChildren: () => System.import('../home/home.module') }
    ]
  }
];

export const ROUTES = RouterModule.forChild(routes);

```
![image](https://cloud.githubusercontent.com/assets/1307833/20360911/9e832d8c-ac03-11e6-8b4c-76fda27b50e7.png)

**Comment by jpcode** [comment]
Extra information:

![image](https://cloud.githubusercontent.com/assets/1307833/20365692/e2407cde-ac15-11e6-826e-66d0eb8ea693.png)

[{  "path" : "", "loadChildren" : () => "System"."import"("./layout/layout.module"), "resolve" : {  "testing" : "DataResolver"}}, {  "path" : "login", "loadChildren" : () => "System"."import"("./login/login.module")}, {  "path" : "error", "component" : "ErrorComponent"}, {  "path" : "unauthorized", "component" : "UnauthorizedComponent"}, {  "path" : "**", "component" : "ErrorComponent"}]:
[16:02:08] SyntaxError: Unexpected token ( in JSON at position 27

IO.router is returning a bad json.

**Comment by vogloblinsky** [comment]
I just support for the moment routes with simple key/value, and not the entire Routing APIs.
I will investigate that asap.

**Comment by jpcode** [comment]
Thanks!!

As workaround i added the files to the  exclude part.

![image](https://cloud.githubusercontent.com/assets/1307833/20367184/6a7ab942-ac1c-11e6-8781-e0849ff36fcf.png)

**Comment by tsifuentes** [comment]
+1

**Comment by vogloblinsky** [comment]
I close this bug.
Routes pages will be updated very soon with new design.
As system.js is not the default module loader for Angular, i focus the debugging on webpack `require(...`instead.
