### ISSUE TITLE
[BUG] Source code not rendered

### ISSUE THREAD

**Issue by ghillert** [compodoc/compodoc#223]
Go to the sample page, and you will see that the source code for components is not visible:

https://compodoc.github.io/compodoc-demo-todomvc-angular/components/AboutComponent.html#source

![image](https://user-images.githubusercontent.com/685363/28128427-ab244566-66fd-11e7-9527-7073bb433ef9.png)

We noticed the issue in our own project as well (Only for components). It seems to be related to how files are named. The source code for components named `*.component.ts` does not show up. However, if we name the component like `*-component.ts` the source code does show up.

**Comment by vogloblinsky** [comment]
Fixed this afternoon. Coming in next release, 1.0.0-beta.13 this week.

**Comment by ghillert** [comment]
@vogloblinsky THX!!! Impressive!
