### ISSUE TITLE
[BUG] Type in "Infos" tab - should be "Info"

### ISSUE THREAD

**Issue by BasyaLipman** [compodoc/compodoc#224]
##### **Overview of the issue**

The tab named "Infos" should be named "Info", as the plural of the word "information" is still "information" and the plural of "Info" is "Info".

##### **Suggest a Fix**

It seems to appear in multiple places in the code, but for example, here: https://github.com/compodoc/compodoc/blob/ab6120e630cef3cffb7db6a966b7048508bb0252/src/templates/partials/injectable.hbs#L9

**Comment by vogloblinsky** [comment]
Fixed, thanks for the information ;)
Coming in next release, 1.0.0-beta.13
