### ISSUE TITLE
[BUG] Compodoc not getting installed

### ISSUE THREAD

**Issue by Rishabhjainbvp** [compodoc/compodoc#227]
‘compodoc’ is not recognized as
operable program or batch file.
Please help.

**Comment by vogloblinsky** [comment]
Can you describe your environment ?
OS ? Node.js ?

**Comment by vogloblinsky** [comment]
From Medium original question :
"It is MS 2007 and Node version 6.10.0 , npm version is 3.10.0"

**Comment by vogloblinsky** [comment]
Closing this issue, no feedback since 25 days.
@Rishabhjainbvp if you have more information, could you please fill it here ?
Thanks
