### ISSUE TITLE
[BUG] incorrect filenames for html files in additional-documentation folder

### ISSUE THREAD

**Issue by jaufgang** [compodoc/compodoc#228]
Say I have a documentation folder with the following summary.json file:

``` json
{
    "title": "A TITLE",
    "file": "a-file.md"
}
```

This results in an output of a file `A TITLE.html` in the additional-documentation folder instead of `a-file.html`  (i.e. it uses the `title` field from the .json file as the html  filename prefix instead of  the file name prefix for the original .md file.    However, the links in the TOC point to `a-file.html`, resulting in broken links.   

I experienced this bug using  1.0.0-beta.13

**Comment by vogloblinsky** [comment]
Ok fixed, coming in next beta 1.0.0-beta.14
