### ISSUE TITLE
[BUG] Comments ignored

### ISSUE THREAD

**Issue by shwedberlin** [compodoc/compodoc#230]
##### **Overview of the issue**

Documentation generated, but documentation coverage is 0%. 
Comments in code are ignored (but some parameter descriptions are used in generated documentation). I have just started, only few modules/components are commented, but nothing is used in generated documentation.
See [this project](https://github.com/shwedberlin/AngularWebApi): AngularWebApi/Angular2webapp/Angular2webapp/app/core/logger.service.ts:

    /**
      * Logger Service
      */
    @Injectable()
    export class LoggerService {
        private defaultName: string = "NG_Client";
        private internalName: string = "NG_LoggerSrvc";
        private internalLogger: JL.JSNLogLogger;
    
    /**
     * ajax Logger appender
     */
    private ajaxAppender = JL.createAjaxAppender('ajaxAppender');
    /**
     * console Logger appender
     */
    private consoleAppender = JL.createConsoleAppender('consoleAppender');

And result without description block:
![image](https://raw.githubusercontent.com/shwedberlin/MiscFiles/master/NoDescription.PNG)

##### **Operating System, Node.js, npm, compodoc version(s)**
OS: Windows 10
Node: 6.10.3
compodoc: 1.0.0-beta 13

##### **Angular configuration, a `package.json` file in the root folder**

Angular 4, tsconfig.json and package.json in root folder of project.

##### **Compodoc installed globally or locally ?**

Both: globally and locally

##### **Related issues**

Routes graph missing completely, not sure if this issues caused by same bug

**Comment by vogloblinsky** [comment]
Ok seems related again to file encoding : your file is UTF-8 with BOM.
Compodoc should support it, i will investigate deeper on this side.

**Comment by vogloblinsky** [comment]
Ok fixed, coming in next beta 1.0.0-beta.14
