### ISSUE TITLE
[BUG] Two entity with same name

### ISSUE THREAD

**Issue by istiti** [compodoc/compodoc#233]
I'm under cli project.

##### **Operating System, Node.js, npm, compodoc version(s)**
```
@angular/cli: 1.2.1
node: 6.11.0 (npm 5.2.0)
os: win32 x64
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/core: 4.2.6
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.1
@angular/compiler-cli: 4.2.6
@angular/language-service: 4.2.6

```

##### **Angular configuration, a `package.json` file in the root folder**

https://gist.github.com/istiti/e750a414dfad559e8aba603527895e13

##### **Compodoc installed globally or locally ?**
globally version 1.0.0-beta.13

I want tell that I tried to my tsconfig.ts at root and now at src/tsconfig.app.ts and same error. My windows path have no space.

### ERROR IS: 
After all "process module graph"  OK but  juste this one get 
`Error: ENOENT: no such file or directory, unlink C:\Users\....\documentation\modules\ImpressionModule\dependencies.dot`

And this is correct because in /documentation/modules/ImpressionModule I don't have dependencies.**dot**, I only have dependencies.**svg**.

**Comment by istiti** [comment]
It's because I exported two class with same name ImpressionModule{} of course not at same place and not in same imports but compodoc get me error, unable to success to build with : ` no such file or directory, unlink C:\Users\....\ documentation\modules \ImpressionModule\dependencies.dot`

instead this error will be nice to tell to user that there is two same class name, temporarly rename it durning process OR force to have unique class name but maybe not cool to force this ...

**Comment by lucasvst** [comment]
I'm having this issue too  :// ...

There's a workaround until it's been fixed? I really cannot rename my classes...

**Comment by vogloblinsky** [comment]
@lucasvst Yes i understand.
I have an enhancement in the pipe about grouping things about where they are : https://github.com/compodoc/compodoc/issues/145
This should solve this problem at the same time.
Coming soon in 1.0.0-beta.14
