### ISSUE TITLE
 [BUG] Routing file missing

### ISSUE THREAD

**Issue by krischandra** [compodoc/compodoc#239]
##### **Operating System, Node.js, npm, compodoc version(s)**
Node 6.10.1
compodoc: *** 13

##### **Compodoc installed globally or locally ?**
Both

##### **Motivation for or Use Case**

I moved and renamed app.route.ts file to one folder.(root/root.rout.ts). From here i will bootstrap the app depending up on command
Document was generated but i cant able to find routing.

**Comment by krischandra** [comment]
![capture](https://user-images.githubusercontent.com/23637750/28493409-52d0634c-6ecb-11e7-9784-3fe57e32b337.PNG)

**Comment by vogloblinsky** [comment]
Routes page is missed if there is a problem during modules and routes linking.
How many routes do you have ?
Is there dynamic values inside them ?

**Comment by krischandra** [comment]
I have 18 routs in total. But i don't have any dynamic values.
How do i solve this issue.

**Comment by vogloblinsky** [comment]
@krischandra Is it possible to have an example ?

**Comment by krischandra** [comment]
I didn't get you exactly. Hope this will be good enough  My project structure as follows:
app --> src --> main (I have root module module here,[main.component.ts, main.root.ts, app.config.ts ] )
Main Module: These Modules are modules are the entry point of the application. They are responsible for pulling together an entire application for a particular environment whether that is mobile, or desktop or tab.
