### ISSUE TITLE
[BUG] JS stack trace

### ISSUE THREAD

**Issue by krischandra** [compodoc/compodoc#240]
##### **Overview of the issue**
<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x2a01cd9cfb51 <JS Object>
    1: exec [native regexp.js:~116] [pc=0x30011d0db2a7] (this=0x103702728e79 <JS RegExp>,D=0x28565e8ef5b9 <String[19]: simple menu-toggler>)
    2: test [native regexp.js:~260] [pc=0x30011ae8f641] (this=0x103702728e79 <JS RegExp>,D=0x28565e8ef5b9 <String[19]: simple menu-toggler>)
    3: element [/Users/krishnachandra/Downloads/retail/ng-ui/node_modules/css-select/lib/attributes.js:73] [pc=0x30...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::RegExpImpl::IrregexpPrepare(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>) [/usr/local/bin/node]
 7: v8::internal::RegExpImpl::IrregexpExec(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, v8::internal::Handle<v8::internal::JSArray>) [/usr/local/bin/node]
 8: v8::internal::RegExpImpl::Exec(v8::internal::Handle<v8::internal::JSRegExp>, v8::internal::Handle<v8::internal::String>, int, v8::internal::Handle<v8::internal::JSArray>) [/usr/local/bin/node]
 9: v8::internal::Runtime_RegExpExec(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
10: 0x3001192092a7

##### **Suggest a Fix**
I think it is okay for small projects. But for realtime projects (huge projects) Its throwing error. 
I installed increase memory package in my project and its worked fine. But by installing increase memory package it effected my project.

**Comment by vogloblinsky** [comment]
@krischandra 
Can i have more details ? context ? terminal logs ? OS & Node.js versions ?
Thanks

**Comment by krischandra** [comment]
OS: OSX 10.12.5
Node version: 6.10.0
I am trying to implement for real time project. Since its a huge project, When run npm run compodoc result as follows
<img width="1680" alt="screen shot 2017-07-25 at 7 26 56 am" src="https://user-images.githubusercontent.com/23637750/28577197-f0c37e5e-710a-11e7-8206-3a3113a7664f.png">

**Comment by vogloblinsky** [comment]
@krischandra What did you mean by huge ?
How many components ? modules ?
Regards

**Comment by vogloblinsky** [comment]
@krischandra 
Could you please install locally the development version of compodoc ?

```
npm i --save-dev https://github.com/compodoc/compodoc#develop
node_modules/bin/compodoc -p src/tsconfig.json
```

I have added a project statistics report in the logs during generation.

![capture d ecran 2017-07-26 a 00 58 35](https://user-images.githubusercontent.com/2841805/28597337-a575b8de-719d-11e7-91ad-d8a3c84ff8c0.png)

and give me your stats

Thanks

**Comment by krischandra** [comment]
Hello, I tried, But i am getting error.

Till now we have almost 90 components. Expecting more than 180.
<img width="817" alt="screen shot 2017-07-25 at 10 37 18 pm" src="https://user-images.githubusercontent.com/23637750/28606074-fd336dc8-7189-11e7-8e61-15b2ed848bbe.png">

**Comment by krischandra** [comment]
Let me know if you need more details.
Thanks

**Comment by vogloblinsky** [comment]
@krischandra
Could you please retry to install locally the development version of compodoc ?

```
npm i --save-dev https://github.com/compodoc/compodoc#develop
node_modules/.bin/compodoc -p src/tsconfig.json
```

I have fixed issue with very large project parsing.

**Comment by krischandra** [comment]
Getting error

![capture](https://user-images.githubusercontent.com/23637750/28992378-f3d6872a-794e-11e7-97d7-3c55f4aea92b.PNG)

**Comment by krischandra** [comment]
Getting the same error.

**Comment by krischandra** [comment]
Please let me know how to resolve this issue.
![capture](https://user-images.githubusercontent.com/23637750/28992502-ed502d44-7952-11e7-88fc-c7c4f52868fd.PNG)

**Comment by vogloblinsky** [comment]
I close this issue, 1.0.0-beta.14 works better with huge projects.

**Comment by UlricW** [comment]
I've the same issue with a huge project. the version is: 1.0.6

Security context: 00000200921CFB61 <JS Object>
    1: charCodeAt [native string.js:~50] [pc=000003479D8072D9] (this=000002D592496BD1 <Very long string[607842]>,t=0)
    2: advance [C:\j\w\i\fbranch2\fbranch-gui-webapp-axa\node_modules\parse5\lib\tokenizer\preprocessor.js:116] [pc=000003479DAC43D3] (this=000002D592492C01 <JS Object>)
    3: _consume [C:\j\w\i\fbranch2\fbranch-gui-webapp-axa\node_modules\parse5\lib\tokenizer\index.js:274] [...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

I tried to install and run the cmd with development version but it crashed.

**Comment by pantonis** [comment]
I am having this issue. How can I resolve it?

**Comment by Suazodev** [comment]
one more

**Comment by SergeyMell** [comment]
Same issue for me compodoc 1.1.9, npm 5.5.1, macOS 10.14.4
