### ISSUE TITLE
[FEATURE] Possibility of including public and protected properties/methods, but not private

### ISSUE THREAD

**Issue by kajnelissen** [compodoc/compodoc#241]
##### **Overview of the issue**

If I use the `--disablePrivateOrInternalSupport` flag, only public properties and methods show up in the generated documentation. It would be nice to have more granular control over this and be able to include any combination of `public`, `protected` and `private` in the documentation.

##### **Motivation for or Use Case**

Right now, I am documenting the API of a package for Angular 4. I don't want to show `private` stuff, but I actually do want to include `protected` properties and methods in the generated documentation so package users know what they can override if they want to.

##### **Suggest a Fix**

Maybe give developers the possibility to include specific access modifiers by providing specific flags for them on the command line. Something like `--private`, `--protected`, `--public` for example.

**Comment by vogloblinsky** [comment]
@kajnelissen Yes, you are right. I will split disablePrivateOrInternalSupport flag.

**Comment by tommueller** [comment]
:+1: for this
