### ISSUE TITLE
[BUG] Not able to exclude files for documentations

### ISSUE THREAD

**Issue by junedansari** [compodoc/compodoc#243]
Hi, 
I wanted to exclude some the files with extension .stub.ts under some folder .

here is my tsconfig.json
 "exclude": [
    "./testing/*.stub.ts"
  ]

and
compodoc version:  0.0.41

Please help here to fix this

**Comment by vogloblinsky** [comment]
Please use the last version.

```
npm i @compodoc/compodoc --save-dev
```

**Comment by junedansari** [comment]
Thank you for your reply.
I have done same as you suggested, now its taking so much time to generate documentation. i have a very big project and there are so many files.

Thanks

**Comment by vogloblinsky** [comment]
Could you please make a test with development version, there is a big enhancement on very large project parsing : 

```
npm i --save-dev https://github.com/compodoc/compodoc#develop
node_modules/bin/compodoc -p src/tsconfig.json
```

**Comment by vogloblinsky** [comment]
I close this issue, 1.0.0-beta.14 works better with huge projects.
