### ISSUE TITLE
[QUESTION] Make it not just for Angular applications, but any TS project?

### ISSUE THREAD

**Issue by benlesh** [compodoc/compodoc#249]
We're currently looking for ways to improve the documentation for [RxJS](https://github.com/reactivex/rxjs). This tool is interesting to me, but I haven't tried it because it appears to be only for Angular applications. Have you considered making it also support more general TypeScript use cases?

**Comment by vogloblinsky** [comment]
Hi Ben,

Thanks for taking in consideration this tool. The starting goal was to support Angular and AngularJS applications written in TypeScript.

Many features of Angular that Compodoc cannot detect during generation are not displayed, for example modules, modules graph, directives, etc..

I have juste made a quick test, and it works fine : 

![capture d ecran 2017-07-29 a 08 44 12](https://user-images.githubusercontent.com/2841805/28742812-2abbcddc-743a-11e7-87ab-01df2396409d.png)

![capture d ecran 2017-07-29 a 08 44 19](https://user-images.githubusercontent.com/2841805/28742813-2f2002da-743a-11e7-8190-539993ae368b.png)


But my first question is : what did you have to improve in the documentation of RxJS ? Esdoc is a great tool. DId you take a look at TypeDoc, which also works fine ?

**Comment by odin3** [comment]
@benlesh, maybe [TypeDoc](http://typedoc.com) is the solution for you.

**Comment by vogloblinsky** [comment]
Closing this for cleaning issues list. 
@benlesh no problem if you want to continue the discussion here. Regards
