### ISSUE TITLE
Error on Global Installation - Unexpected Token

### ISSUE THREAD

**Issue by dsoldera** [compodoc/compodoc#25]
Hello,

I´ve installed the compodoc globally but I´m having issue on Windows 10. Please check the error below:

![error-unexpected_token](https://cloud.githubusercontent.com/assets/11474555/20675259/d1c384bc-b572-11e6-9024-7192c781b069.png)

**Comment by vogloblinsky** [comment]
I use spread operator, that is just supported on Node.js 5.11.0.
I will update "engines" attribute in package.json with next release.

**Comment by dsoldera** [comment]
Hi @vogloblinsky.

I´m using Node v **4.4.5** and NPM **3.10.9**.

Do you think is really necessary to update my Node.js?? Because I had a lot of project running and it could broken a few of them.

Thanks for your help.

**Comment by vogloblinsky** [comment]
ok i will add a Babel task during build for supporting old Node.js versions.
The issue will be closed during the next release tomorrow.

**Comment by dsoldera** [comment]
ok. thanks @vogloblinsky  =)

**Comment by vogloblinsky** [comment]
Just published v0.0.16 which is transpiled in ES5 using Babel.
I have tested on a Linux VM with your Node.js version, you will get warnings on install, but the tool will now works fine.

**Comment by dsoldera** [comment]
ok. Let me test on Windows.

**Comment by dsoldera** [comment]
Hello @vogloblinsky .

I´ve updated the comodoc globally and tried to install on my Angular2 project. I get this errors.  I would like to know if I really need to update the version that the NPM requires?

![error-installing-new-version-compodoc](https://cloud.githubusercontent.com/assets/11474555/20750877/2690c3c4-b6e0-11e6-8968-e29d3c55fe15.png)

**Comment by vogloblinsky** [comment]
Eperm seems to be a permission issue with npm
This link can help : https://github.com/npm/npm/wiki/Troubleshooting

**Comment by dsoldera** [comment]
Works now. Thanks @vogloblinsky  =)
