### ISSUE TITLE
[FEATURE] add an option to make compodoc to generate html fragment of doc

### ISSUE THREAD

**Issue by rdkmaster** [compodoc/compodoc#252]
##### **Overview of the issue**

compodoc produces full, amazing HTML doc for components, modules, classes and everything else in my project. but i have a well Ux designed website, i find the full HTML files are hard to integrate into my site,

1. first of all, my site is built with Angular, so, a normal HTML doc is quite not easy to use under Anuglar.
2. my site is SPA (single page application), i am using routes of Angular. i do not want to use iframe to display the doc, because iframes make the url hard to control. ( i DO want to make the url change while my uses are browsing the doc)
3. I don't want everything in the generated html doc, I just want particular part of the generated doc, and make it as part of my site

I am doing the additional thing as following after each time compodoc generates the html docs
1. parse the source of the html docs as a string, and slice the substring i want.
2. transform the a tag, remove the href attribute, add a routerLink attribute
3. save the substring as a html fragment.

while the uses are browsing the doc, i use Http module to load the fragment i sliced from the full html doc as a html string, and bind the string to a innerHtml attribute of a div of a doc component. it's looking good so far, but i think it is not a good way to use compodc. It's great if compodoc can do this for me.

btw, i create my own doc category, and a search form as well, by the guide line of Ux design of my site.

**Comment by vogloblinsky** [comment]
@rdkmaster 
Did this feature may be more easiest for you to integrate ?
JSON export : https://github.com/compodoc/compodoc/issues/196

**Comment by rdkmaster** [comment]
@vogloblinsky a JSON export make it easier to rearrange the doc, but this brings another problem: it is hard to apply the css while using the json to generate my own html files.

maybe compodoc can provide a set of css classes which names have no conflict in the global scope, and add a css class name to the corresponding json value node. by doing this, i can easyly rearrange the doc and also apply the css.

however, i prefer a well formatted html fragment, with css class in it, and i can use the fragment anywhere i like

**Comment by rdkmaster** [comment]
we just decided make compodoc as the doc generator of [Jigsaw](https://github.com/rdkmaster/jigsaw), will you please raise the priority of this feature?

considering that compodoc is still in beta, some breaking changes should be added to compodoc, so, we are worrying about that we need to change our re-generating-doc script a lot in the near future.

**Comment by rdkmaster** [comment]
closing this issue because that exporting with type == json is good enough for us,
