### ISSUE TITLE
[BUG] @example : the generated code block of the doc gets unexpected spaces

### ISSUE THREAD

**Issue by rdkmaster** [compodoc/compodoc#253]
##### **Overview of the issue**
the generated code block of the doc gets unexpected spaces, see the image below

##### **Operating System, Node.js, npm, compodoc version(s)**

win10 64, node6.10, npm 3.10

##### **Angular configuration, a `package.json` file in the root folder**

yes

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

the generated code block of the doc gets unexpected spaces

##### **Reproduce the error**

use the comment:

```
    /**
     * Shows all events on a given day. Example usage:
     *
     * ```html
     * <mwl-calendar-day-view
     *             [viewDate]="viewDate"
     *             [events]="events">
     * </mwl-calendar-day-view>
     * ```
     */
```

##### **Related issues**

no

**Comment by rdkmaster** [comment]
![default](https://user-images.githubusercontent.com/16191626/28753949-540739c6-756e-11e7-8180-21b944cd8a64.png)

**Comment by Kapulara** [comment]
It's because you are using the ```html tag as you would in markdown.

Please supply it like this:

   ```typescript
 /**
     * Shows all events on a given day. Example usage:
     *
     * @example
     * <mwl-calendar-day-view
     *             [viewDate]="viewDate"
     *             [events]="events">
     * </mwl-calendar-day-view>
     */
```

**Comment by rdkmaster** [comment]
I tried `@example` seconds ago, and the example is gone!

![default](https://user-images.githubusercontent.com/16191626/28754082-2d43d3d2-7571-11e7-9927-dcca82cfb919.png)

**Comment by Kapulara** [comment]
@rdkmaster Where did you place the @example comment?

It should be at root level for example:

```typescript
/**
 * The datagrid component for displaying lists of data.
 *
 * @example
 * <sr-datagrid
 *               [datagridFormat]="datagridFormat"
 *               [loading]="loading"
 *               [(rows)]="rows">
 *               <sr-datagrid-search
 *                 (onSearch)="onSearch($event)"></sr-datagrid-search>
 *               <sr-datagrid-button
 *                 [textTranslationKey]="'GRID.ADD_USER'"
 *                 (onClick)="onClick($event)"></sr-datagrid-button>
 *               <sr-datagrid-toggle
 *                 (onSwitch)="onSwitch($event)"></sr-datagrid-toggle>
 * </sr-datagrid>
 */
@Component({
  selector: 'sr-datagrid',
  templateUrl: './datagrid.component.html',
  styleUrls: []
})
export class DatagridComponent implements OnInit {}
```

**Comment by rdkmaster** [comment]
I copy the example from [here](https://compodoc.github.io/website/guides/comments.html), and here is my code
```
    /**
     * Shows all events on a given day. Example usage:
     *
     * @example
     * <mwl-calendar-day-view
     *             [viewDate]="viewDate"
     *             [events]="events">
     * </mwl-calendar-day-view>
     */
    test2() {

    }
```

**Comment by Kapulara** [comment]
@rdkmaster That's not on the root level. You are giving an example to a function called test. Look at my example 😄

**Comment by rdkmaster** [comment]
what do you mean by root level? Are u saying that the `@example` can be only used outter of the class which means "the root level"?

**Comment by Kapulara** [comment]
@rdkmaster Outer class level indeed.

**Comment by rdkmaster** [comment]
ok thanks, outter of the class seems to be quite a limit.

Is that any way to use the markdown style code block and avoid the unexpected spaces?

**Comment by vogloblinsky** [comment]
I confirm this is not normal to doesn't support @example for inner function or properties of class.
Working on that tomorrow.

**Comment by Kapulara** [comment]
@vogloblinsky Sorry, Didn't know this was actually not expected behaviour ☹️

**Comment by vogloblinsky** [comment]
@Kapulara 
It should be but i miss to test it everywhere (outter class and inside for functions etc).
