### ISSUE TITLE
[FEATURE] Group injectables, interfaces and components by modules

### ISSUE THREAD

**Issue by x1unix** [compodoc/compodoc#258]
##### **Operating System, Node.js, npm, compodoc version(s)**
1.0.0-beta.13

Node.js version : v6.10.2

Operating system : macOS Sierra

##### **Compodoc installed globally or locally ?**
* Globally

##### **Motivation for or Use Case**
Current navigation is good for small projects, but for big multi-modular projects, it will be hard to understand what component belongs to a specific module.

##### **Suggest a Fix**
Separate items by module ([example screenshot](http://prntscr.com/g3cuol))

**Comment by vogloblinsky** [comment]
Duplicated of https://github.com/compodoc/compodoc/issues/145
