### ISSUE TITLE
[BUG] Coverage of public params in constructor

### ISSUE THREAD

**Issue by EugeneSnihovsky** [compodoc/compodoc#259]
##### **Overview of the issue**

I have simple component
```typescript
'use strict';

import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

/**
 * This class represents the terms and conditions component
 */
@Component({
    selector: 'al-tos',
    styleUrls: ['../../../customisations/sign-up/tos/tos.component.scss'],
    templateUrl: '../../../customisations/sign-up/tos/tos.component.html'
})
export class TOSComponent {

    /**
     * Terms of license constructor
     * @param {NgbActiveModal} activeModal Bootstrap service to work with modal instances
     */
    public constructor(
        public activeModal: NgbActiveModal
    ) {}

}
```

And when I generate docs, I have **66% (2/3)** coverage. I also tried to add docs to `activeModal`
```typescript
    /**
     * Terms of license constructor
     * @param {NgbActiveModal} activeModal Bootstrap service to work with modal instances
     */
    public constructor(

        /*
         * {NgbActiveModal} activeModal Modal instance
         */
        public activeModal: NgbActiveModal
    ) {}
```

or

```typescript
    /**
     * Terms of license constructor
     * @param {NgbActiveModal} activeModal Bootstrap service to work with modal instances
     */
    public constructor(

        /*
         * Modal instance
         */
        public activeModal: NgbActiveModal
    ) {}
```
But it didn't help. Did I missed something ?

##### **Operating System, Node.js, npm, compodoc version(s)**

- Node.js : 6.9.5
- npm: 3.10.10
- compodoc: 1.0.0.beta-13

##### **Compodoc installed globally or locally ?**
Compodoc installed locally

**Comment by vogloblinsky** [comment]
That's a bug, i will fix it for 1.0.0-beta.14

**Comment by stijnbollen** [comment]
Will the first example work after the fix, or should it still be written like the second or third?

**Comment by vogloblinsky** [comment]
First i think.

**Comment by eXXeption** [comment]
Doesn't seem fixed to me, having beta.14 with the same problem.

writing it like 
```
service: Service;
/** 
* constructor
* @param {Service} serivce
**/
constructor(service: Service)...
```
has 100% coverage. just writing ```public service:Service```in constructor is missing one coverage

**Comment by vogloblinsky** [comment]
@eXXeption 
You remove the first declaration of service variable if you write ```public service:Service``` in constructor ?

**Comment by eXXeption** [comment]
yes, i only added it in the example to get 100% coverage

 

Von: Vincent Ogloblinsky [mailto:notifications@github.com] 
Gesendet: Dienstag, 29. August 2017 07:06
An: compodoc/compodoc <compodoc@noreply.github.com>
Cc: eXXeption <stefan.sparmann@gmx.net>; Mention <mention@noreply.github.com>
Betreff: Re: [compodoc/compodoc] [BUG] Coverage of public params in constructor (#259)

 

@eXXeption <https://github.com/exxeption> 
You remove the first declaration of service variable if you write public service:Service in constructor ?

**Comment by vogloblinsky** [comment]
@eXXeption 
Just to be clear, for me, with 1.0.0-bet&.14 : 

```
/**
 * The about component
 */
@Component({
    selector: 'about',
    templateUrl: './about.component.html'
})
export class AboutComponent {

    /**
     * constructor description
     * @param {string} service A service
     */
    constructor(public service: string) {}
}
```
gives 100% code coverage

```
/**
 * The about component
 */
@Component({
    selector: 'about',
    templateUrl: './about.component.html'
})
export class AboutComponent {

    service: string;

    /**
     * constructor description
     * @param {string} service A service
     */
    constructor(service: string) {}
}
```
also gives 100%

Can i have a example of what breaks on your project ?

**Comment by eXXeption** [comment]
```
/**
* Constructor
* @param {TickersService} tickerService
*/
constructor(public tickerService: TickersService) {
}
```
does end up with one missing comment. as soon as i delete the tickerService it has 100%.

```
/**
* Constructor
* @param {TickersService} tickerService
*/
constructor(private tickerService: TickersService) {
}
```
this does give 100%, its only public which fails for me

**Comment by vogloblinsky** [comment]
@eXXeption 

Your comment ```* @param {TickersService} tickerService``` miss the text description :
```* @param {TickersService} tickerService MY DESCRIPTION```

**Comment by eXXeption** [comment]
If that is the case, why does a private DI does not need a discription, only a public one?

**Comment by vogloblinsky** [comment]
For Compodoc private properties or functions are not used during coverage calculation.
Your problem is that even you put a JSDoc tag with @param, it is the last information, the main text comment of the line which is used during calculation.
