### ISSUE TITLE
Routes parsing error, maybe a trailing comma ?

### ISSUE THREAD

**Issue by jongunter** [compodoc/compodoc#26]
I do not have trailing comma in my routes definition. However, I still get this error and my documentation doesn't generate.

Honestly, I don't even care if my routes are documented. It would be nice if this wouldn't fail the entire documentation generation process because of one syntax error.  Seems like a pretty common problem with these documentation generators.

**Comment by vogloblinsky** [comment]
Can i have a screenshot of your terminal logs ?

I notice your remark on failing generation, a wrapper with a simple try catch for each operation will be better.

**Comment by sebazburgos** [comment]
I had the same problem with the site routing:

```
const deviceRoutes: Routes = [
    {
    path: '',
    redirectTo: '/devices',
    pathMatch: 'full'
  },
    {
        path: 'devices',
        children: [
            {
                path: '',
                component: DeviceListComponent
            },
        ]
    }
];
```

and I solved it erasing the comma that was after the brace: DeviceListComponent ** } ,** 

```
const deviceRoutes: Routes = [
    {
    path: '',
    redirectTo: '/devices',
    pathMatch: 'full'
  },
    {
        path: 'devices',
        children: [
            {
                path: '',
                component: DeviceListComponent
            }
        ]
    }
];
```

I hope this works for you.

**Comment by vogloblinsky** [comment]
Yep, the AST parsing of $.ts file is used by compodoc for reconstruct the Routes array (for your example). If there is a trailing comma, the reconstruction failed.
I will add a try/catch in order to not stopping the generation process and warn the user.

**Comment by vogloblinsky** [comment]
@jongunter 0.0.19 available with no crashing issue for routes trailing comma

**Comment by jongunter** [comment]
Thanks! I'll take a look. Appreciate the quick response.

**Comment by marcelnem** [comment]
Version 1.1.3, installed locally


it does not work when we use `fromComponents.PortalLayoutRootComponent` :

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import * as fromComponents from './components';

const routes: Routes = [
  {
    path: 's',
    component: fromComponents.PortalLayoutRootComponent,
    children: [
      {
        path: 'account-management',
        loadChildren: '../../app/account-management/account-management.module#AccountManagementModule'
      }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class PortalLayoutRoutingModule {}

```

it works only like this:

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { PortalLayoutRootComponent } from '@app/portal-layout/components';

const routes: Routes = [
  {
    path: '',
    component: PortalLayoutRootComponent,
    children: [
      {
        path: 'account-management',
        loadChildren: '../../app/account-management/account-management.module#AccountManagementModule'
      }
    ]
  }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class PortalLayoutRoutingModule {}
```

**Comment by phutaneVinayak** [comment]
i fix this issue following :-1: 

first -:
   resolve: { CountryCodeResolver }
but this is giving above error to me .

solutions -:
resolve: CountryCodeResolver
this resolve my problem .

thanks
