### ISSUE TITLE
[BUG] Directives not showing up on "Documentation coverage" page

### ISSUE THREAD

**Issue by kajnelissen** [compodoc/compodoc#260]
##### **Overview of the issue**

The project I'm currently working on contains a couple of directives. The separate pages for all these directives get generated. However, the directives do not show up on the page containing information about the documentation coverage.

##### **Operating System, Node.js, npm, compodoc version(s)**

* **OS:** Windows 10
* **Node:** version 6.10.2
* **NPM:** version 4.4.4
* **Compodoc:** version 1.0.0-beta.13

##### **Angular configuration, a `package.json` file in the root folder**

See [this repository](https://github.com/kajnelissen/compodoc-interface-issue) to reproduce. Run `npm run docs:build` and check the generated docs in the `generated-docs` folder.

##### **Suggest a Fix**

Add directive coverage to documentation coverage page.

**Comment by vogloblinsky** [comment]
Supported see : https://compodoc.github.io/compodoc-demo-todomvc-angular/coverage.html
