### ISSUE TITLE
[BUG] @internal is not respected when the class is @Injectable

### ISSUE THREAD

**Issue by shlomiassaf** [compodoc/compodoc#262]
version 1.0.0-beta.13

```ts
/**
 * @internal
 */
@Injectable()
export class SomeClass {
}
```

The class will appear in the `Injectables` list but it shouldn't

**Comment by vogloblinsky** [comment]
@shlomiassaf 
I suppose you use this @internal with --disablePrivateOrInternalSupport ?

**Comment by shlomiassaf** [comment]
Yes,of course (:
