### ISSUE TITLE
[BUG] generation fails with RangeError: : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jaamofi** [compodoc/compodoc#263]
##### **Overview of the issue**

When attempting to generate the documentation with command "./node_modules/.bin/compodoc -p ./src/tsconfig.json -d ./build/compodoc/" the process fails after the files have been parsed and just before normally would start "Prepare modules, Prepare components".

The problem surfaced when we added new lazy loaded feature modules. Our tools are roughly:
- Angular 4.3.2, angular-route-loader 0.6.0, angular-redux 6.5.7
- Webpack 2.3.3
- Typescript 2.2.2

We have one main / root module that is initially loaded, it fetches a configuration file (ajax) and dynamically creates the routes based on that. Compodoc worked nicely with a setup consisting of the main module + one certain lazy loaded feature module, but after we added another feature module an error occurs. I have also tried with another very simple "dummy" modules that don't really import or do anything special, the same error remains.

I have checked for possible infinite loop scenarios (due to the error description) multiple times but haven't found any. The feature module can be as stripped down as possible, for example only importing NgModule, one component with empty stylesheet and only with html "hello world".

The route syntax for feature module load is:
`
    const route: Route = {
        path: "module-url",
        loadChildren: () => require("../modules-folder/module-directory/moduleclass.module")[ModuleClass]
      };
`

The error on console:
> ...
> [13:59:38] parsing        : C:/.../last-file.ts
> [13:59:39] RangeError: Maximum call stack size exceeded
> [13:59:39] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! our-package@0.0.1 compodoc: "compodoc -p ./src/tsconfig.json -d ./build/compodoc/"
> npm ERR! Exit status 1

Debug log file:

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\...\\nodejs\\node.exe',
> 1 verbose cli   'C:\\...\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'compodoc' ]
> 2 info using npm@5.3.0
> 3 info using node@v6.11.0
> 4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
> 5 info lifecycle our-package@0.0.1\~precompodoc: our-package@0.0.1
> 6 info lifecycle our-package@0.0.1\~compodoc: our-package@0.0.1
> 7 verbose lifecycle our-package@0.0.1\~compodoc: unsafe-perm in lifecycle true
> 8 verbose lifecycle our-package@0.0.1\~compodoc: PATH: C:\...path-stuff
> 9 verbose lifecycle our-package@0.0.1\~compodoc: CWD: C:\...\app-folder
> 10 silly lifecycle our-package@0.0.1\~compodoc: Args: [ '/d /s /c',
> 10 silly lifecycle   'compodoc -p ./src/tsconfig.json -d ./build/compodoc/' ]
> 11 silly lifecycle our-package@0.0.1\~compodoc: Returned: code: 1  signal: null
> 12 info lifecycle our-package@0.0.1\~compodoc: Failed to exec compodoc script
> 13 verbose stack Error: our-package@0.0.1 compodoc: `compodoc -p ./src/tsconfig.json -d ./build/compodoc/`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:289:16)
> 13 verbose stack     at emitTwo (events.js:106:13)
> 13 verbose stack     at EventEmitter.emit (events.js:191:7)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
> 13 verbose stack     at emitTwo (events.js:106:13)
> 13 verbose stack     at ChildProcess.emit (events.js:191:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:891:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 14 verbose pkgid our-package@0.0.1
> 15 verbose cwd C:\...\app-folder
> 16 verbose Windows_NT 10.0.15063
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "compodoc"
> 18 verbose node v6.11.0
> 19 verbose npm  v5.3.0
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error our-package@0.0.1 compodoc: `compodoc -p ./src/tsconfig.json -d ./build/compodoc/`
> 22 error Exit status 1
> 23 error Failed at the our-package@0.0.1 compodoc script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

I cleaned up the outputs a bit (directories, package name...)

I'm afraid I can't reveal source code to you, as this is a client project.

##### **Operating System, Node.js, npm, compodoc version(s)**

- OS: Windows 10
- Node: 6.11.0
- npm: 5.3.0
- CompoDoc: 1.0.0-beta.13

##### **Angular configuration, a `package.json` file in the root folder**

I'm not sure if I can provide even this.

##### **Compodoc installed globally or locally ?**

Locally.

##### **Motivation for or Use Case**

For some reason the documentation does not generate at all with different lazy loaded feature modules.

##### **Reproduce the error**

Create a main / root module that attempts to generate a navigation for feature modules. Feature modules are lazy loaded with angular-router. CompoDoc generation works with one lazy loaded feature module, fails if we try to add one or several more. It doesn't seem to matter what the feature modules consist of.

**Comment by vogloblinsky** [comment]
Fixed with 1.0.0-beta.14

**Comment by YoeriVD** [comment]
@vogloblinsky is there public access to this beta?

**Comment by vogloblinsky** [comment]
@YoeriVD Last public release version is 1.0.3 : https://www.npmjs.com/package/@compodoc/compodoc
