### ISSUE TITLE
[BUG] Wrong URL generated for inline {@link} doc

### ISSUE THREAD

**Issue by kajnelissen** [compodoc/compodoc#264]
##### **Overview of the issue**

I used an inline {@link} doc in one of my classes which links to a class definition. Both class definitions are located in the _same_ source file. See the code below for an example.

```typescript
export class LoggerOptions {
    level: string;
}

/**
 *
 */
@Injectable()
export class LoggerService {

    /**
     * Instantiates new Logger instance. By default a logger is instantiated with a set of default options.
     * Override these options by passing a {@link LoggerOptions} object to the constructor.
     *
     * @param {LoggerOptions} options
     */
    public constructor( @Optional() options?: LoggerOptions) { 
        // some code
    }
}
```

When I generate the documentation with Compodoc, the links for the parameters get generated correctly. The generated link for the inline comment is wrong however. Because it's missing a `/`, it appends the URL to the URL path of the current page. See the image below (red is wrong, green is correct):

![Example](http://i.imgur.com/JbBIE2L.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

* **OS:** Windows 10
* **Node:** version 6.10.2
* **NPM:** version 4.4.4
* **Compodoc:** version 1.0.0-beta.13

**Comment by Zyzle** [comment]
@vogloblinsky  I think this may need to be re-opened as this still seems to be an issue in beta-14 for me when an `{@link ...} is used on a function that will later be placed in the "miscellaneous/` folder. The link generated from them lacks the leading `../`

**Comment by benjamincharity** [comment]
I'm seeing this also. When linking from a type definition to a component, the generated URL doesn't take into account the new nesting of the type inside miscellaneous.

![screen shot 2017-08-29 at 9 43 57 am](https://user-images.githubusercontent.com/270193/29824193-cbf33006-8c9e-11e7-8e00-c5dbe2a4e5c1.png)


- Generated link: `components/TsInputComponent.html`
- Correct link: `../components/TsInputComponent.html`

---

- OS: OS X Sierra
- Node: 8.0.0
- NPM: 5.3.0
- Compodoc: 1.0.0-beta.14
