### ISSUE TITLE
[FEATURE] need to support enum type

### ISSUE THREAD

**Issue by rdkmaster** [compodoc/compodoc#266]
##### **Overview of the issue**

take a look at the following picture, 

![default](https://user-images.githubusercontent.com/16191626/28994358-b1492dda-79fe-11e7-9b45-ac7d54351616.png)

`PopupEffect` is an enum type:

```
export enum PopupEffect {
    fadeIn, fadeOut, bubbleIn, bubbleOut
}
```

the source is [here](https://github.com/rdkmaster/jigsaw/blob/master/src/jigsaw/service/popup.service.ts#L22)

compodoc do not create a link to it

##### **Suggest a Fix**

it it great to create a link to enum type

**Comment by eitanfr** [comment]
+ 1
also in my case, I have an enum in a sperate file and the documentation file isn't generated for it.

**Comment by kajnelissen** [comment]
Enumerations are listed on the `Miscellaneous` page @eitanfr . They do not have their own separate files like components et cetera.

**Comment by rdkmaster** [comment]
@kajnelissen that's great, but it's much better if compodoc create a link ref to it

**Comment by eitanfr** [comment]
@kajnelissen thx.
Is it possible to configure compodoc to create a separate page for enums? (or should I open another issue)
For example, I want to have the ability to search the enum docs by the enum name..

**Comment by vogloblinsky** [comment]
@eitanfr
I have fixed this feature yesterday :
- fixing the @link with enums, type aliases, variables and functions.
- splitting the misc page in 4 pages : one for each : enums, type aliases, variables and functions.
Coming very soon this week

**Comment by rdkmaster** [comment]
@vogloblinsky thanks, I can't wait any longer for the next version
