### ISSUE TITLE
[FEATURE] need to support self-defined type

### ISSUE THREAD

**Issue by rdkmaster** [compodoc/compodoc#267]
##### **Overview of the issue**

![default](https://user-images.githubusercontent.com/16191626/28994379-6db952d8-79ff-11e7-89e5-64c65b4e2acb.png)

`PopupPosition` is a self-defined type look like this

```
export type PopupPosition = PopupPoint | ElementRef | HTMLElement;
```

compodoc should create a link to this type or use `PopupPoint | ElementRef | HTMLElement` to replace `PopupPosition` in the generated doc.

this source is [here](https://github.com/rdkmaster/jigsaw/blob/master/src/jigsaw/service/popup.service.ts#L86)

**Comment by benjamincharity** [comment]
I am also hitting this issue.

[TsVerticalSpacingDirective](https://github.com/GetTerminus/terminus-ui/blob/master/src/lib/src/spacing/vertical-spacing.directive.ts) uses [TsVerticalSpacingTypes](https://github.com/GetTerminus/terminus-ui/blob/master/src/lib/src/spacing/vertical-spacing.type.ts) so it would be great for those types to appear in the documentation.
