### ISSUE TITLE
[BUG] Cant able to generate document due to memory size issue

### ISSUE THREAD

**Issue by krischandra** [compodoc/compodoc#272]
##### **Operating System, Node.js, npm, compodoc version(s)**
Node.js 
OS: OSX 10.12.5
Node version: 6.10.0
I tried in another laptop
OS: Windows 10, 16GB Ram, i7 processor

##### **Compodoc installed globally or locally ?**
locally
![28992502-ed502d44-7952-11e7-88fc-c7c4f52868fd](https://user-images.githubusercontent.com/23637750/29083619-30d0281c-7c1e-11e7-83ff-f41079d39c2f.PNG)

**Comment by vogloblinsky** [comment]
I close this issue, 1.0.0-beta.14 works better with huge projects.
