### ISSUE TITLE
[BUG] -n / --name arg not properly parsed. "Provided source folder ____ was not found in the current directory"

### ISSUE THREAD

**Issue by mattezell** [compodoc/compodoc#273]
##### **Overview of the issue**

When providing the -n/--name argument, compodoc fails with "Provided source folder ____ was not found in the current directory" error.  Easily reproduced by pulling down the official todo demo (https://github.com/compodoc/compodoc-demo-todomvc-angular) and running "npm run docs"

Specific error message: "Provided source folder Angular was not found in the current directory"

Removing -n attribute allows doc generation to complete as expected.

##### **Operating System, Node.js, npm, compodoc version(s)**
Node: 6.11.2
npm: 3.10.10
Compodoc: 1.0.0-beta.13

##### **Angular configuration, a `package.json` file in the root folder**

See project package.json

##### **Compodoc installed globally or locally ?**

Installed locally

##### **Motivation for or Use Case**

Running the official demo?

##### **Reproduce the error**

- Clone https://github.com/compodoc/compodoc-demo-todomvc-angular
- Run "npm install" from project root
- run "npm run docs"

**Comment by vogloblinsky** [comment]
@mattezell 
On which platform did you have this issue ? Mac ? Windows ? Linux ?

**Comment by mattezell** [comment]
Sorry about that, @vogloblinsky .

I'm on Windows 7...

In further researching this, it appears to be how process.argv is coming in via node and then is subsequently parsed using Commander...

If I set a log in index-cli before program.parse is called (console.log(JSON.stringify(process.argv))), I can see that the name string has been split (as expected)... 

So, "-n 'My Angular App'" comes in as:
"-n","'My","Angular","App'"

Continuing to dig in - will report back as I find anything of value...

Thanks!

**Comment by vogloblinsky** [comment]
using npm scripts, on Windows you need to escape quotes like \"
https://compodoc.github.io/website/guides/usage.html

**Comment by mattezell** [comment]
Ugh.. Thank you so much, @vogloblinsky ... 

I actually just realized the err of my way and was coming back here to disclose my stupidity on this when I noticed your update... 

I should have known better - been playing in the warm and fuzzy *nix world with this stuff for too long.

Thanks for leading an old horse to water... Now let's see if I can avoid thirsting and drowning :D

-Matt
