### ISSUE TITLE
[BUG] html tag bcode not balanced

### ISSUE THREAD

**Issue by rdkmaster** [compodoc/compodoc#276]
##### **Overview of the issue**

in the generated html sources, some unbalanced `bcode` tag found, e.g. try investigate the source of [this file](http://rdkmaster.com/jigsaw/doc/components/JigsawTable.html), search `bcode` in the source tag of chrome. 3 unstarted `bcode` tag will be found

![image](https://user-images.githubusercontent.com/16191626/29159031-c833851a-7ddf-11e7-97a8-9f6ec8f8b79e.png)
 the cresponding source file of this html doc is [here](https://github.com/rdkmaster/jigsaw/blob/master/src/jigsaw/component/table/table.ts).

##### **Operating System, Node.js, npm, compodoc version(s)**

win7 x64, node 6.10, npm 3.10

##### **Angular configuration, a `package.json` file in the root folder**

yes

##### **Compodoc installed globally or locally ?**

both globally and locally produces the same result

##### **Motivation for or Use Case**

see #252, i have to transform the generated html doc to html fragment for my website, this issue make my transforming script do not work correctly, the script can find a correct end tag because of this unexpected `bcode` tag

##### **Reproduce the error**

try to generate html doc by using [this source file](https://github.com/rdkmaster/jigsaw/blob/master/src/jigsaw/component/table/table.ts)

##### **Related issues**

#252

##### **Suggest a Fix**

it is quite obviously that the `bcode` tag is unneccessary.

**Comment by vogloblinsky** [comment]
Ok found three typo in handlebars templates, fixed.
Coming in 1.0.0-beta.14 very soon.

**Comment by rdkmaster** [comment]
thanks @vogloblinsky
