### ISSUE TITLE
[FEATURE] Linking directly to correct enumeration

### ISSUE THREAD

**Issue by kajnelissen** [compodoc/compodoc#278]
##### **Overview of the issue**

Just installed beta 14 and generated the docs again. Happy to see that enums now link to the enumeration page. However, the project I'm currently working on has tons of enums, Every enum links to the enumerations page right now and then you have to scroll and find the enum you were looking for.

##### **Operating System, Node.js, npm, compodoc version(s)**

* **OS:** Windows 10
* **Node:** version 6.10.2
* **NPM:** version 4.4.4
* **Compodoc:** version 1.0.0-beta.14, installed locally

##### **Suggest a Fix**

One possibility would be to add an ID to the `h3` headers based on the enumeration name. Then the links can be changed to `/miscellaneous/enumerations.html#<NameOfEnumeration>`. That way, the browser scrolls to the enum you clicked on automatically.

**Comment by vogloblinsky** [comment]
Yes, i just added this morning index table, and anchors for functions, properties etc of class, components, directives etc..; and miss to add links between enums links and enum page.
Will add soon.
