### ISSUE TITLE
missing some generated pages

### ISSUE THREAD

**Issue by trickpattyFH20** [compodoc/compodoc#28]
after upgrading from .17 to .18, the build completes _without warnings or errors_ and I am missing a bunch of the pages at the root level that were previously generated in .17. The following html files aren't generated anymore and overview.html does not create links for these files either:

components.html
directives.html
injectables.html
pipes.html
classes.html

pages for individual components are still generated and overview.html is still generated

**Comment by vogloblinsky** [comment]
The new menu structure in 0.0.18 is lighter and cleaner.
The lists which were in those html files (components, directives, etc) are now in the menu, so for me these pages aren't required.

**Comment by trickpattyFH20** [comment]
gotcha. thanks for the clarification!

**Comment by vogloblinsky** [comment]
No problem.
