### ISSUE TITLE
[BUG] additional documentation destination file names are wrong

### ISSUE THREAD

**Issue by shlomiassaf** [compodoc/compodoc#282]
Given this sample:

![image](https://user-images.githubusercontent.com/5377501/29248884-eaaecd36-802b-11e7-8a56-db55a228efa8.png)

Left is file structure right is `summary.json` content

The output is 
![image](https://user-images.githubusercontent.com/5377501/29248886-03dee0c0-802c-11e7-8a73-9bcd3517a671.png)

So file names are an issue.

In a linux based system its a no go... 

In github pages I get 404.

PS: Sorry for the flood of issues :)

**Comment by vogloblinsky** [comment]
@shlomiassaf 
Didn't understand why it breaks, the demo works fine : 
https://compodoc.github.io/compodoc-demo-todomvc-angular/additional-documentation/actions/creation-of-a-todo.html

https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/master/additional-doc/summary.json#L12

I work on a Mac where the generation works fine.

![image](https://user-images.githubusercontent.com/2841805/29253000-1bc372fe-8073-11e7-8c8a-1dadd396f813.png)

**Comment by shlomiassaf** [comment]
I dont know, I have OSX as well.

The problem is with linux systems...

**Comment by vogloblinsky** [comment]
Cannot reproduce with a Linux system.
Which version are you using ?

**Comment by vogloblinsky** [comment]
@shlomiassaf Any news about your compodoc version ?

**Comment by vogloblinsky** [comment]
Closing it, if any problem re-open it @shlomiassaf
