### ISSUE TITLE
[BUG] Not able to generate graph on large projects

### ISSUE THREAD

**Issue by junedansari** [compodoc/compodoc#283]
Hi,
need your help/support as I am not able to generate graph getting below error on 1.0.0-beta.14 version
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime b
ut prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=
0
 
Kindly help here.

**Comment by junedansari** [comment]
There is around only 21 modules and 80-90 components.

OS: windows

**Comment by vogloblinsky** [comment]
Which version of Node.js and npm ?

**Comment by junedansari** [comment]
Thanks for reply.
node version : v6.9.5
npm version: 3.10.10
