### ISSUE TITLE
[BUG] Error with watch flag

### ISSUE THREAD

**Issue by samarthya** [compodoc/compodoc#284]
##### **Overview of the issue**
Error while using -w or --watch flag. It reports

TypeError: Cannot read property 'map' of undefined
Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

##### **Operating System, Node.js, npm, compodoc version(s)**
OS : MAC
NPM: 3.10.10
NODEJS: v6.10.2

##### **Compodoc installed globally or locally ?**
Locally as well as globally.
v 1.0.0-beta.13

##### **Reproduce the error**
Simple use compodoc -s tsconfig.json  -w and it gives the error.

**Comment by samarthya** [comment]
In case I use the command as under it works

compodoc -p tsconfig.json -s --watch

Is it that it is only meant to be used like this? If that is the case probably we need to update the documentation.

**Comment by vogloblinsky** [comment]
Can you please test last version 1.0.0-beta.14 ?

**Comment by samarthya** [comment]
I tried it doesn't works in beat-14.

**Comment by vogloblinsky** [comment]
@samarthya With which command ?

**Comment by samarthya** [comment]
Apologies for the delay. 
I used simple 

> compodoc -s tsconfig.json -w

**Comment by vogloblinsky** [comment]
@samarthya 
Your command cannot work or is not correctly handled. Last version (1.0.0-beta.15) should print that :

> No sources files available, please use -p flag

Use that : ```compodoc -p tsconfig.json -s --watch```

**Comment by samarthya** [comment]
Thank you.

**Comment by dominion-ubah** [comment]
hi im getting a parsing error on doc generation

**Comment by vogloblinsky** [comment]
@dominion-ubah can you describe a little your issue ?
