### ISSUE TITLE
[FEATURE] Indicating a optional parameter in comments

### ISSUE THREAD

**Issue by v1sionary** [compodoc/compodoc#288]
#### Q
Is there any way to indicate a optional parameter for a method in a component? 
I tried JSDoc syntax /  Google Closure Compiler syntax, but just could not found the optional field in generated documentation.

#### some info
compodoc version: 1.0.0-beta.14 (globally) 
nodejs version: 8.1.4
npm version: 5.0.3

#### code
```ts
@Component({
  selector: 'app-ze',
  templateUrl: './ze.component.html',
  styleUrls: ['./ze.component.css']
})
export class ZeComponent {

  constructor() { }

  /**
   * say sth
   *
   * @param {string} [words] some words
   * @return {string} sentence
   */
  say(words?: string) {
    return words ? `i would like to say: ${words }.`  : 'i have nothing to say.';
  }

}
```

thx!

**Comment by vogloblinsky** [comment]
Yes you are right, it should be mentionned. I will check what TypeScript provides in the AST.
