### ISSUE TITLE
[BUG] @internal tag does not work in watch mode

### ISSUE THREAD

**Issue by michaelkrone** [compodoc/compodoc#289]
##### **Overview of the issue**
When using `compodoc -p ./src/tsconfig.app.json -d ./build/documentation --disablePrivateOrInternalSupport --theme readthedocs -s -w -o` and adding an `@internal` tag to a property, the property is still listed in the generated documentation. However, if running a `compodoc -p ./src/tsconfig.app.json -d ./build/documentation --disablePrivateOrInternalSupport --theme readthedocs`, everythink looks fine and the property is not listed in the generated documentation

##### **Operating System, Node.js, npm, compodoc version(s)**
Ubuntu 16.04, Node.js v8.4.0, npm v5.4.0, compodoc ^1.0.0-beta.14

##### **Angular configuration, a `package.json` file in the root folder**
Project generated with @ angular/cli.

##### **Compodoc installed globally or locally ?**
locally, called by package.json scripts

##### **Motivation for or Use Case**
A watch should generate the same results as a single run.

##### **Reproduce the error**
Run a watch on your sources, add the `@internal` tag to a property -> In the generated documentation the internal property is still listed. Stop the watch and regenerate the documentation. The internal property is not listed anymore.

**Comment by vogloblinsky** [comment]
@michaelkrone In which kind of file are you ? Component ? Class ?

**Comment by vogloblinsky** [comment]
@michaelkrone any news ?

**Comment by michaelkrone** [comment]
@vogloblinsky Sorry, I will check this

**Comment by vogloblinsky** [comment]
Thanks

**Comment by michaelkrone** [comment]
@vogloblinsky I tried to reproduce this in Classes, Modules and function definitions, but it seems to work well. Closing this, sorry for the noise.

**Comment by vogloblinsky** [comment]
No problem @michaelkrone
