### ISSUE TITLE
Error: listen EACCES 0.0.0.0:8080

### ISSUE THREAD

**Issue by sebazburgos** [compodoc/compodoc#29]
I'm trying to see the documentation but when the "compodoc" it is serving the site it returns this message "Error: listen EACCES 0.0.0.0:8080".

**I'm using:**

angular-cli: 1.0.0-beta.17
NPM 3.10.7
Node 6.5.0

When I run: _**compodoc -p src/tsconfig.json -s**_ I receive this message
[16:58:01] Documentation generated in ./documentation/ in 64.032 seconds
[16:58:01] Serving documentation from ./documentation/ at http://127.0.0.1:8080
Error: listen EACCES 0.0.0.0:8080

When I run: _**compodoc -s**_ I receive this message
[07:10:36] Serving documentation from ./documentation/ at http://127.0.0.1:8080
Error: listen EACCES 0.0.0.0:8080

Thanks,

**Comment by vogloblinsky** [comment]
Seems the port 8080 is used by another process.
This lick can help : 
https://www.cyberciti.biz/faq/unix-linux-check-if-port-is-in-use-command/

**Comment by sebazburgos** [comment]
Hi @vogloblinsky, Can I change the port in a configuration file or using other command line parameter? 

By the way, I'm windows user and I need that port for IIS.

Thanks,

**Comment by vogloblinsky** [comment]
Yes i understand. i have planned to add an option/flag for this.
I will release a new version with that option tomorrow.

**Comment by vogloblinsky** [comment]
@sebazburgos 0.0.19 available

**Comment by sebazburgos** [comment]
Thanks man, I appreciate it very much.

**Comment by vogloblinsky** [comment]
You are welcome, feedbacks are always welcome for enchancing this tool.
