### ISSUE TITLE
Live Example feature request

### ISSUE THREAD

**Issue by glappatoni** [compodoc/compodoc#290]
Looking into the angular 2 material docs, i liked the feature of a live example for each component: https://material.angular.io/components/autocomplete/examples

Would it be possible to add it to compodocs?

I imagine an examples folder in each component with a example.js file which exports the example module plus a selector with whom the live example can be generated.

**Comment by vogloblinsky** [comment]
Available here : 
https://compodoc.github.io/website/guides/live-example-tab.html
I have updated the documentation site, this information was before in comments page.

**Comment by andrewantar** [comment]
Where is this tag supposed to be placed? Is there a code example of this example tab being implemented?

**Comment by rootical** [comment]
Agree, it's not clear at all what shall be put to `<example-url>` exactly.
