### ISSUE TITLE
[BUG] What is the purpose of the red "play" icon in front of private methods ?

### ISSUE THREAD

**Issue by msieurtoph** [compodoc/compodoc#291]
Hi,

First of all thank you for this really helpful module.

I noticed that in front of private method, I got a red "play" icon.
It makes reader think that something can be played or ran ... but there is no action binded to this icon. It just seems decorative. Or maybe I missed some annotations ...

Can you tell me what is the purpose  of this icon please ?

**Comment by vogloblinsky** [comment]
Can i have an example of code and a screenshot of the output html page ?

**Comment by msieurtoph** [comment]
Yeah, sure.

Here is the screenshot : 

![image](https://user-images.githubusercontent.com/7763445/29822232-09222ea6-8ccb-11e7-9ddd-02eee845c4e3.png)

And here is my code (from a component) : 
```
  /**
   * Méthode d'initialisation des flux observables (reactive programming) du composant.
   *
   * Lorsque que le couple de flux observables suivant émet une nouvelle combinaison,
   * procéde à une sélection automatique :
   * * liste des zones géographiques connues
   * * changement de zone sélectionnée en entrée du composant
   */
  private initUpdatesRx(): void {
    ....
  }
```

It appears on all private functions, whatever the class is (Component, Service, Guard, etc ...).

**Comment by vogloblinsky** [comment]
This icon is for function.
The lock icon is for private properties

**Comment by msieurtoph** [comment]
Ok, thank you for explanation.

I think there is an issue then because the icon appears only on private functions. The public ones do not have this little sign : 

![image](https://user-images.githubusercontent.com/7763445/29857531-6f0615b4-8d59-11e7-9ea6-8cad4c742dd2.png)

```javascript

  /**
   * Méthode d'ajout de la zone sélectionnée dans l'URL sous forme d'un queryParam : `zoneGeographique`.
   *
   * Utilisée pour permettre un accès direct à une zone par URL.
   *
   * @param {ZoneGeographique} [zone] zone géographique sélectionnée à ajouter dans l'URL
   */
  addZoneQueryParam(zone: ZoneGeographique): void {
    // ...
  }

  /**
   * Méthode d'initialisation des flux observables (reactive programming) du composant.
   *
   * Lorsque le couple de flux observable suivant emet une nouvelle combinaison, initialise la sélection de la zone issue du queryParam :
   * * liste des zones geographiques connues
   * * le queryParam `zoneGeographique`
   */
  private initUpdatesRx(): void {
    // ...
  }
```
