### ISSUE TITLE
[BUG] graph is hard to read

### ISSUE THREAD

**Issue by maxkorz** [compodoc/compodoc#295]
##### **Overview of the issue**

I'm developing a big project (10 modules and more coming) and the graph looks like this:

![](https://i.imgur.com/zCsRXuZ.png)

I'm following the "[SharedModule Good Practice](https://medium.com/@cyrilletuzi/understanding-angular-modules-ngmodule-and-their-scopes-81e4ed6f7407#2c25)" - I have declared a lot of components and directives in SharedModule and then I import it in other modules.

##### **Motivation for or Use Case**

It's hard to read the graph

##### **Reproduce the error**

1. Create 10 modules
2. Import 1 module in every other modules

##### **Suggest a Fix**

Detect a frequently imported module and display it next to the top (bootstrap) module

**Comment by vogloblinsky** [comment]
Last version 1.0.3 add a fullscreen button which helps reading the graph.
