### ISSUE TITLE
[BUG] Using the spread operator in module declaration is literally copied to documentation

### ISSUE THREAD

**Issue by lazarljubenovic** [compodoc/compodoc#298]
##### **Overview of the issue**

The following code...

```
const errors = [
  FooErrorComponent,
  BarErrorComponent,
  BazErrorComponent,
]

@NgModule({
  imports: [
    CommonModule,
  ],
  declarations: [
    CodeComponent,
    ...errors,
  ],
  exports: [
    CodeComponent,
  ],
  entryComponents: [
    ...errors,
  ],
})
```

will be rendered with `...errors` as the component's name in the docs.

Here's an example with the `...warnings` also being copy-pasted as a string.

![image](https://user-images.githubusercontent.com/7661457/30038862-aa9b389c-91c9-11e7-809d-bfa9914cdd5a.png)

There are no references to the actual content of those spread arrays.

##### **Suggest a Fix**

I haven't even peeked in the source code, but the bug tells me that this doesn't do any static analysis of the code, and it actually regexp-based. Just assuming. So not sure how easy it would be to fix at all, and would be out of scope for this project.

**Comment by vogloblinsky** [comment]
Related to https://github.com/compodoc/compodoc/issues/216

**Comment by msieurtoph** [comment]
+1 
... it would be cool.
