### ISSUE TITLE
A few feature requests

### ISSUE THREAD

**Issue by brian428** [compodoc/compodoc#30]
Just a few "nice to have" feature requests:

- Properties defined in constructor setters (e.g. `constructor(public someClass)`) are not currently included in the properties lists.
- An Interfaces section, similar to Classes section except listing any TS interfaces. Currently, interfaces don't seem to be included anywhere in the doc output.
- If the type for a property or parameter references a type that is available elsewhere in the docs, turn the type into a hyperlink to the documentation on that type. (Basically, types link to the docs on that type if they are available.)
  - Extra type linking bonus: if a type references an Angular type, link to the Angular API docs for that type?

As always, thanks for the very helpful tool!

**Comment by vogloblinsky** [comment]
@brian428 0.0.20 released with interfaces support and a new search bar.
Your others remarks are in the todo list 😉
