### ISSUE TITLE
[BUG] Array of custom interface not showing in documentation

### ISSUE THREAD

**Issue by spwoodall** [compodoc/compodoc#300]
##### **Overview of the issue**

Defining a custom interface and then using in param declaration not showing in documentation. 

Will not show `Subscription[]`, only `[]`.
```
import { Subscription } from 'rxjs/Subscription';

@Component()
export class Component {
    public subscriptions: Subscription[];
}
```
##### **Operating System, Node.js, npm, compodoc version(s)**

Using compodoc version 1.0.0-beta.15 
Additional info:
- macOS 10.12.6
- node v6.9.2
- npm 3.10.9
- Angular 4.1.2

##### **Related issues**

Thought it was similar/fixed with #287 

##### **Suggest a Fix**

It may have to do with the usage of the interface in an array. (Likely in the area with #287 was fixed, needing a check for use in array.)

**Comment by codemethis** [comment]
Using v1.0.1, this appears to be fixed for property types but not function return types
