### ISSUE TITLE
[QUESTION] How to ignore a Angular Module in while generating documentation? 

### ISSUE THREAD

**Issue by mukuljp** [compodoc/compodoc#301]
Overview of the issue

How to ignore a Angular Module while generating documentation? 
dont want to remove that module from dependencies just want to ignore /exclude while generating documentation.

Using compodoc version 1.0.0-beta.15
Additional info:

macOS 10.12.6
node v6.9.2
npm 3.10.9
Angular 4.1.2

**Comment by vogloblinsky** [comment]
Use exclude parameter inside your tsconfig.json, watch :

https://compodoc.github.io/website/guides/tips-and-tricks.html, last chapter

**Comment by MihaiComan87** [comment]
Hello @vogloblinsky , do you plan on implementing a more `compodoc`-specific way of configuring ignores/excludes?
The method you are recommending, of using the `tsconfig.json` `exclude` property, seems to be relying on the current way that the Typescript compiler is using the `file`, `include` and `exclude` properties when deciding what to compile (please correct me if I am wrong). If the Typescript team decides to change these rules, developers will have to change their includes and excludes and it might break the way documentation is being generated. 
I think decoupling documentation generation rules from compilation rules is better on the long term. But please let me know if I am missing something here. 

Just to give you a bit of context for my question, I am building a library and I want to generate documentation only for the API layer, not for the internal mechanics, as the documentation is aimed at developers using the library, not developers building the library. I still want to compile/bundle all of the modules, however.

**Comment by vogloblinsky** [comment]
@MihaiComan87 
Yes i understand this context. I plan to move to a specific config file for compodoc which could be stored inside an attribute of tsconfig.json, or a specific file compodoc.json.

**Comment by vogloblinsky** [comment]
@MihaiComan87 
1.0.9 add support fo @ignore JSDoc tag. Have a look and say to me if it fits well your need.

**Comment by MihaiComan87** [comment]
@vogloblinsky sounds great. When I have the time, I'll change our current Compodoc setup to use the JSDoc tag instead of the `tsconfig.json` entries.

**Comment by vogloblinsky** [comment]
ok i close the issue.
