### ISSUE TITLE
[FEATURE] Search includes folder or custom folder for xxx.component.md files

### ISSUE THREAD

**Issue by therealandeeee** [compodoc/compodoc#303]
##### **Overview of the issue**

We are about to start placing docs for components, etc, into xxx.component.md files to reduce the amount of text needed in the JSDoc comments. Currently, compodoc searches for these files in the folder where the component is declared. However, it would be very useful if we could place the .md files together in a single folder and instruct compodoc to find the files there. It might be easiest to just use the usual includes folder for this task but having a command line option to specify the folder would also work well.

##### **Motivation for or Use Case**

We have >200 components, directives, etc, and most of them will need their own .md file. Our production process uses tools like markdown-toc and also our own scripts to postprocess all our .md files. It would be much easier to apply the tools and scripts if the files were all together in a single folder (ie, we wouldn't need to specify all the paths to source folders individually).

Also, we are looking at other ways to manage all these .md files, either with the GitHub wiki (which has a separate repository) or with a completely separate GitHub project. It would be much easier to associate each xxx.component.md file with its correct component page if we could specify a folder path where compodoc could find them.

**Comment by vogloblinsky** [comment]
Could you provide an example of the structure you want to be supported ?

**Comment by therealandeeee** [comment]
Well, the folder for the .md files doesn't really need to have any subfolders or anything like that. We were thinking of something like a command line parameter called --mdFileBase where you supply any path you choose. The mdFileBase folder just contains all the .md files at the root level, so you would have

mdFileBase:
- apple.component.md
- banana.component.md
- cherry.service.md
   .
   .
...and then compodoc looks in *both* mdFileBase and the source folder of the xxx.component.ts file to find the corresponding .md file. I guess there would have to be a priority rule in cases where there is a .md file in both places (mdFileBase gets searched first?)

The other idea we thought of (possibly neater to implement) was just to use the path supplied with the --includes option. As far as I can see, files that are not in summary.json are just ignored currently, so extra xxx.component.md files in that folder don't seem to disrupt any existing functionality.
