### ISSUE TITLE
[BUG] @link for external url seems to be broken

### ISSUE THREAD

**Issue by Arikael** [compodoc/compodoc#305]
Hi there 

seems @link has issues with external urls

##### **Overview of the issue**

```
/**
 * see {@link http://www.google.ch|hello}
 * see {@link http://www.google.ch hello}
 * see [hello]{@link http://www.google.ch}
 */
export class ApplicationError extends Error {
```
renders like 
```
see {@link <a href="http://www.google.ch|hello}">http://www.google.ch|hello}</a>
see {@link <a href="http://www.google.ch">http://www.google.ch</a> hello}
see [hello]{@link <a href="http://www.google.ch}">http://www.google.ch}</a>
``` 
internal links like `{@link MyClass}` are rendered correct.

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10, 
node.js 8.4.0
npm 5.4.0
compodoc 1.0.1

##### **Angular configuration, a `package.json` file in the root folder**

not sure what to put in?
you want the whole package.json?

##### **Compodoc installed globally or locally ?**

both

##### **Motivation for or Use Case**

it should render a correct link with the correct description

##### **Reproduce the error**

see above

##### **Related issues**

maybe #237 is related?

**Comment by Arikael** [comment]
one other point I experienced after working with the tool (which is awesome by the way :) )

for example. if I use `{@link SomeExportedFunction}` all `@link` in the current comment section are not rendered.

```
// file 1
export function MyFunction() {

}

// file  2
/**
 * see {@link MyFunction}
 * see {@link SomeOtherClass}
 */
export class MyClass {

}
```

those links (both) won't be rendered at all.

if I replace `{@link MyFunction}` with something else like `{@link YetAnotherClass}`  both links will be rendered correctly. So I assume it has something to to with linking a function

I don't know if this and the intial bug are related. If you want I can open a new one.

**Comment by FabienDehopre** [comment]
any idea of when this bug will be fixed?
