### ISSUE TITLE
[FEATURE] per-file minimum coverage

### ISSUE THREAD

**Issue by stevengunneweg** [compodoc/compodoc#306]
##### **Overview of the issue**

I would like to have an option to set a per-file minimum coverage. Currently coverage only fails if the entire codebase falls below the threshold even though a single file could be completely undocumented.

##### **Operating System, Node.js, npm, compodoc version(s)**

OSX, NPM@5.4.0, Compodoc@1.0.1

##### **Compodoc installed globally or locally ?**

Installed v1.0.1 locally

##### **Motivation for or Use Case**

I'm using the coverageTest in CI but if someone doesn't document it does not necessarily fail the test.

##### **Reproduce the error**

Have a codebase of a certain coverage percentage (say 50%) and at least one file with a lower/no coverage. Run `compodoc --coverageTest 50` and see that the test succeeds.

##### **Suggest a Fix**

I would like to have an optional flag to set the per-file minimum coverage like `--coverageMinimum 30`.

**Comment by stevengunneweg** [comment]
@vogloblinsky I'm happy to see this has been worked on. Any idea when this feature will be released to NPM?

**Comment by vogloblinsky** [comment]
Right now, i had a little fix on README file to do.
https://www.npmjs.com/package/@compodoc/compodoc

**Comment by stevengunneweg** [comment]
Awesome! Many thanks
