### ISSUE TITLE
[BUG] @link inside add unnecessary 'interfaces' in URL.

### ISSUE THREAD

**Issue by kmathy** [compodoc/compodoc#311]
##### **Overview of the issue**

Inside one of my interface, I try to reference another interface. 

```
/** The new trainer to replace the precedent. See [Trainer]{@link Trainer} interface for more information*/
    trainer?: Trainer;
```
So, I'm in `interfaces/Change.html` and when I click on the link, I go to `interfaces/interfaces/Trainer.html`

##### **Operating System, Node.js, npm, compodoc version(s)**
`Windows 10`
`Node v8.1.2`
`npm 5.3.0`
`"@compodoc/compodoc": "^1.0.1"`

##### **Angular configuration, a `package.json` file in the root folder**

Angular 4.3.6, typescript 2.3.4

##### **Compodoc installed globally or locally**

Locally

##### **Motivation for or Use Case**

Maybe this can be good when we reference the interface outside the interface folder, but if we are inside
the interface folder, it needs to be relative. Correct me if I'm wrong :)

**Comment by vogloblinsky** [comment]
Can i have the folder structure where your interfaces are ?
