### ISSUE TITLE
Overview screen (layout)

### ISSUE THREAD

**Issue by Rafabin** [compodoc/compodoc#312]
#Seria possivel adicionar um recurso para esconder a parte inferior da tela? Melhoraria a visão da arvore para tela cheia...
(Would it be possible to add a feature to hide the bottom of the screen? Improve the view of the tree to full screen)
tnks =)
![print](https://user-images.githubusercontent.com/6231044/30675575-4cf818a8-9e4f-11e7-85a3-56a8f5333900.png)

**Comment by vogloblinsky** [comment]
Use a custom css :

https://compodoc.github.io/website/guides/tips-and-tricks.html

In your css :

```
.overview .container-fluid {
    display: none;
}
```

**Comment by Rafabin** [comment]
Ok. thank you!
