### ISSUE TITLE
[BUG] Compodoc -d not working as expected and warning issue

### ISSUE THREAD

**Issue by usmanajmal** [compodoc/compodoc#315]
##### **Overview of the issue**

Scripts from package.json:
 `"compodoc": "./node_modules/.bin/compodoc -p ./tsconfig.json -d ./docs"`

Command:
`$ npm run compodoc`

Running command above outputs following in the specified ./docs directory:

`$ ls docs`
`fonts	images	js	styles `

But files like `docscoverage.html, docsgraph, docsindex.html, docsmodules.html` and `docsoverview.html` are all dumped in main project directory. How come these files are not getting output in the ./docs directory?

Also, I have `"compodoc": "0.0.41"`  in my devDependencies and npm install complains about `deprecated compodoc@0.0.41: Compodoc has moved to @compodoc/compodoc`. The warning doesn't go away if I use `"@compodoc/compodoc": "0.0.41"`. Also tried `"@compodoc/compodoc": "0.0.1"` but same result. 

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: MAC OS Sierra (10.12.6)
Node: 7.3.0
NPM: 3.10.10

**Comment by usmanajmal** [comment]
Compodoc expect the docs folder to be named "documentation" always. When -d is not used and you have a directory named "documentation" in your project's root then all compdoc files are output in ./documentation. 

If you use -d option and specify a different name than "documentation" then the issue mentioned in ticket is hit. 

So, seem like this is a bug where we have to make sure any name given by user works. If it has to be "documentation", then we should clearly call it out and remove the -d option.

**Comment by vogloblinsky** [comment]
@usmanajmal Last version at this time is 1.0.1.

Could you try `npm i --save-dev @compodoc/compodoc` please, and restart your generation command ?
