### ISSUE TITLE
[BUG] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by ortonka** [compodoc/compodoc#316]
##### **Overview of the issue**

I have medium size project and I want to generate documentation.
![screenshot from 2017-09-29 12-51-40](https://user-images.githubusercontent.com/20769868/31013389-24aa50be-a516-11e7-9ecd-3c682a865b64.png)
After I run this command:
 <code>compodoc -p ./tsconfig.json</code>
this is the end of output:
![screenshot from 2017-09-29 12-51-11](https://user-images.githubusercontent.com/20769868/31013385-2004d85e-a516-11e7-912d-3eb1cae556df.png)
The documentation directory is generated but it does not contain fonts, js or style directory. 
##### **Operating System, Node.js, npm, compodoc version(s)**
Operating System: Ubuntu 16.04.
Node: v7.10.1
npm: 4.2.0
compodoc: 1.0.1

##### **Angular configuration, a `package.json` file in the root folder**
This is project for clients so I can not post any code.

{
  "name": "----------------------------------------------",
  "version": "----------------------------------------------",
  "description": "----------------------------------------------",
  "keywords": [],
  "author": "----------------------------------------------",
  "homepage": "----------------------------------------------",
  "license": "----------------------------------------------",
  "scripts": {
    "build:aot:prod": "npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail",
    "build:aot": "npm run build:aot:prod",
    "build:dev": "npm run clean:dist && npm run webpack -- --config config/webpack.dev.js --progress --profile",
    "build:docker": "npm run build:prod && docker build -t angular2-webpack-start:latest .",
    "build:prod": "npm run clean:dist && npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail",
    "build": "npm run build:dev",
    "ci:aot": "npm run lint && npm run test && npm run build:aot && npm run e2e",
    "ci:jit": "npm run lint && npm run test && npm run build:prod && npm run e2e",
    "ci:nobuild": "npm run lint && npm test && npm run e2e",
    "ci:testall": "npm run lint && npm run test && npm run build:prod && npm run e2e && npm run build:aot && npm run e2e",
    "ci:travis": "npm run lint && npm run test && npm run build:aot && npm run e2e:travis",
    "ci": "npm run ci:testall",
    "clean:dll": "npm run rimraf -- dll",
    "clean:aot": "npm run rimraf -- compiled",
    "clean:dist": "npm run rimraf -- dist",
    "clean:install": "npm set progress=false && npm install",
    "clean": "npm cache clean --force && npm run rimraf -- node_modules doc coverage dist compiled dll",
    "docker": "docker",
    "docs": "npm run typedoc -- --options typedoc.json --exclude '**/*.spec.ts' ./src/",
    "e2e:live": "npm-run-all -p -r server:prod:ci protractor:live",
    "e2e:travis": "npm-run-all -p -r server:prod:ci protractor:delay",
    "e2e": "npm-run-all -p -r server:prod:ci protractor",
    "github-deploy:dev": "npm run webpack -- --config config/webpack.github-deploy.js --progress --profile --env.githubDev",
    "github-deploy:prod": "npm run webpack -- --config config/webpack.github-deploy.js --progress --profile --env.githubProd",
    "github-deploy": "npm run github-deploy:dev",
    "lint": "npm run tslint \"src/**/*.ts\"",
    "node": "node",
    "postinstall": "npm run webdriver:update",
    "postversion": "git push && git push --tags",
    "preclean:install": "npm run clean",
    "preversion": "npm test",
    "protractor": "protractor",
    "protractor:delay": "sleep 3 && npm run protractor",
    "protractor:live": "protractor --elementExplorer",
    "rimraf": "rimraf",
    "server:dev:hmr": "npm run server:dev -- --inline --hot",
    "server:dev": "npm run webpack-dev-server -- --config config/webpack.dev.js --open --progress --profile --watch --content-base src/",
    "server:prod": "http-server dist -c-1 --cors",
    "server:prod:ci": "http-server dist -p 3210 -c-1 --cors",
    "server": "npm run server:dev",
    "start:hmr": "npm run server:dev:hmr",
    "start": "npm run server:dev",
    "test": "npm run lint && karma start",
    "tslint": "tslint",
    "typedoc": "rimraf docs && typedoc --options typedoc.json src/",
    "version": "npm run build",
    "watch:dev:hmr": "npm run watch:dev -- --hot",
    "watch:dev": "npm run build:dev -- --watch",
    "watch:prod": "npm run build:prod -- --watch",
    "watch:test": "npm run test -- --auto-watch --no-single-run",
    "watch": "npm run watch:dev",
    "webdriver-manager": "webdriver-manager",
    "webdriver:start": "npm run webdriver-manager start",
    "webdriver:update": "webdriver-manager update",
    "webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"
  },
  "dependencies": {
    "angular/animations": "~4.3.1",
    "angular/cdk": "2.0.0-beta.9",
    "angular/common": "~4.3.1",
    "angular/compiler": "~4.3.1",
    "angular/core": "~4.3.1",
    "angular/forms": "~4.3.1",
    "angular/http": "~4.3.1",
    "angular/material": "2.0.0-beta.9",
    "angular/platform-browser": "~4.3.2",
    "angular/platform-browser-dynamic": "~4.3.2",
    "angular/platform-server": "~4.3.2",
    "angular/router": "~4.3.2",
    "angularclass/hmr": "~2.1.3",
    "angularclass/hmr-loader": "^3.0.4",
    "angular-in-memory-web-api": "^0.3.2",
    "core-js": "^2.4.1",
    "dragula": "^3.7.2",
    "hammerjs": "^2.0.8",
    "has-flag": "^2.0.0",
    "http-server": "^0.10.0",
    "ie-shim": "^0.1.0",
    "ng2-ckeditor": "^1.1.9",
    "ng2-dragula": "^1.5.0",
    "npm": "^5.3.0",
    "querystringify": "^1.0.0",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.2",
    "ts-clipboard": "^1.0.15",
    "ts-loader": "^2.3.2",
    "tslint-language-service": "^0.9.6",
    "universalify": "^0.1.1",
    "y18n": "^3.2.1",
    "yn": "^2.0.0",
    "zone.js": "~0.8.16"
  },
  "devDependencies": {
    "angular/cli": "~1.2.6",
    "angular/compiler-cli": "~4.3.1",
    "types/hammerjs": "^2.0.34",
    "types/jasmine": "~2.5.53",
    "types/node": "8.0.26",
    "types/source-map": "^0.5.0",
    "types/uglify-js": "^2.6.28",
    "types/webpack": "~3.0.5",
    "add-asset-html-webpack-plugin": "^2.0.1",
    "angular2-template-loader": "^0.6.2",
    "assets-webpack-plugin": "^3.5.1",
    "awesome-typescript-loader": "~3.2.2",
    "codelyzer": "~3.1.2",
    "copy-webpack-plugin": "^4.0.1",
    "cross-env": "~5.0.2",
    "css-loader": "^0.28.0",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.3",
    "extract-text-webpack-plugin": "~3.0.0",
    "file-loader": "^0.11.1",
    "find-root": "^1.0.0",
    "gh-pages": "^1.0.0",
    "html-webpack-plugin": "^2.30.0",
    "imports-loader": "^0.7.1",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "istanbul-instrumenter-loader": "3.0.0",
    "jasmine-core": "^2.7.0",
    "json-loader": "^0.5.4",
    "karma": "^1.6.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-mocha-reporter": "^2.2.3",
    "karma-remap-coverage": "^0.1.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "~2.0.3",
    "ng-router-loader": "^2.1.0",
    "ngc-webpack": "~3.1.1",
    "node-sass": "^4.5.3",
    "npm-run-all": "^4.0.2",
    "optimize-js-plugin": "0.0.4",
    "parse5": "^3.0.2",
    "preload-webpack-plugin": "~1.2.3",
    "protractor": "^5.1.1",
    "raw-loader": "0.5.1",
    "rimraf": "~2.6.1",
    "sass-loader": "^6.0.3",
    "script-ext-html-webpack-plugin": "^1.8.5",
    "source-map-loader": "^0.2.1",
    "string-replace-loader": "~1.3.0",
    "style-loader": "^0.18.1",
    "to-string-loader": "^1.1.5",
    "ts-node": "^3.3.0",
    "tslib": "^1.6.1",
    "tslint": "^5.5.0",
    "tslint-loader": "^3.5.2",
    "typedoc": "~0.8.0",
    "typescript": "~2.4.2",
    "url-loader": "^0.5.8",
    "webpack": "~3.4.1",
    "webpack-dev-middleware": "~1.12.0",
    "webpack-dev-server": "~2.6.1",
    "webpack-dll-bundles-plugin": "^1.0.0-beta.5",
    "webpack-merge": "~4.1.0"
  },
  "repository": {
    "type": "git",
    "url": "----------------------------------------------"
  },
  "bugs": {
    "url": "----------------------------------------------"
  },
  "engines": {
    "node": ">= 4.2.1",
    "npm": ">= 3"
  }
}

##### **Compodoc installed globally or locally ?**

globally
##### **Motivation for or Use Case**

Documentation does not have any css, it doesn't look fine.
##### **Reproduce the error**

I can not post any code here. This project uses https://github.com/AngularClass/angular-starter as starting point.
##### **Related issues**

#217 
#269 
##### **Suggest a Fix**

Don't have any idea. :(

**Comment by vogloblinsky** [comment]
@ortonka Did you start your project recently with angular-starter ?
Compodoc was added recently in it. If i could have an approximate date, i will try to run 1.0.1 on it.
This could be a first track for solving this issue.

**Comment by fahmic** [comment]
@vogloblinsky  Project is started on July 12. Thank you for helping to solve this issue.

**Comment by ortonka** [comment]
@vogloblinsky Project is started on July 12. Thank you for helping to solve this issue.

**Comment by acoard** [comment]
Just wanted to confirm this is happening to my project as well, which did not use angular-starter.

Interestingly, I get the same error and importantly messages before the error.  The only difference is I'm missing a 'functions' that @ortonka's error shows.


```
[09:03:50] Process page   : document
[09:03:50] Process page   : variables
[09:03:50] Process page   : typealiases
[09:03:50] Process page   : enumerations
[09:03:50] Process page   : coverage
[09:03:51] RangeError: Maximum call stack size exceeded
```

One more thing.    I saw your comments [on issue 243](https://github.com/compodoc/compodoc/issues/243#issuecomment-318885755) and then upgraded compodoc to version `1.0.0-beta.14`.  Once I did this, I could see the "Process Page" logs would process additional files than before but the error still happened. I'd say that using the beta.14 version that it processed around 1/3rd more files, but there's still more yet.

Definitely keeping an eye on this issue it'd be great to use compodoc.  Thanks!

**Comment by acoard** [comment]
Perhaps this might help.  I tried experimenting with increasing the stack size.  Ultimately, this was the line I was using:

```
sudo /bin/bash -c "ulimit -s 65500; exec /usr/local/bin/node --stack-size=65500 /usr/local/bin/compodoc -p tsconfig.json --disableCoverage"
```

The behaviour is slightly different. Here's the output:

```
[09:56:25] Process page   : document
[09:56:25] Process page   : variables
[09:56:25] Process page   : typealiases
[09:56:25] Process page   : enumerations
Segmentation fault: 11
```

Because of `--disableCoverage`, the coverage option is gone and instead we just have enumerations.

The `ulimit -s 65500` and `node --stack_size=65500` were my attempt at increasing the stack size. I believe this works at least partially, and the result is that the more memory I allocate here the longer the app waits at the "enumerations" log.  More memory allocated, means more time it spends before it crashes.  However, with the memory over a certain threshold it leads to the segfault error above.  If you remove --stack-size, then you get the same behaviour I reported in my previous post.

**Comment by vogloblinsky** [comment]
@ortonka Just tried with Angular-starter repo, from july to now, no breaks.
It is related to your code i think.
Could you try if you have 5-10" to locate which file is breaking the stuff.
- commit all your current stuff
- delete folders or files until it works again
Thanks

**Comment by acoard** [comment]
Thanks so much for the prompt response. I can't believe I totally blanked on such an obvious debugging approach.  I found the file and resolved the issue.

I can't post the file due to NDA reasons, however I can describe it.

It was one file that looked something like:

```typescript
export class Example {
 static image= "/9j/........" //
}
```

The `image` property was base64 and wound up being 330kb.  I can see why this would throw the parser for a loop!

I've deleted the file and everything works fine.  Thanks again for the prompt response.  Let me know if you'd like any more information about the file if you want help reproducing the error.

Cheers.

**Comment by vogloblinsky** [comment]
Thanks for the information.
The base64 string is store inside Compodoc reference, and may be increase memory fingerprint.
Will try to reproduce it.

**Comment by sree526** [comment]
maximum call stack error issue is not fixed yet I guess I'm using compodoc version 1.0.1

**Comment by vogloblinsky** [comment]
Can i have your terminal logs ?
This issue is hard to fix because i cannot have the context of the error.

**Comment by sree526** [comment]
![callstackerror](https://user-images.githubusercontent.com/18196568/32157711-43ace838-bd6b-11e7-9017-43fc44dc823a.PNG)

**Comment by vogloblinsky** [comment]
Ok thanks
Same context than @ortonka 
It seems related to coverage page generation, or after main resources copy.
Did you have some times to find the source of the issue ?
Can we move to gitter https://gitter.im/compodoc/compodoc?

**Comment by sree526** [comment]
I tried to find solution but no luck I tried to exclude node-modules and tried to include only ts files in src folder still throwing same error. Here is my tsconfig.json {
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]   
  },
   "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

**Comment by sree526** [comment]
I dont have any image files in the component as well and not only images there are no other files in my any of the component.
