### ISSUE TITLE
angularjs(1) types generated in doc like 'undefined'

### ISSUE THREAD

**Issue by AntonMedviediev** [compodoc/compodoc#319]
##### **Overview of the issue**

I use your brilliant tool and in general all is good, but types like ng.* or angular.* is typed in generated docs like 'undefined'.  I tried to configure tsconfig file with zero performance.

Also I install your compodoc-ready-angularjs project, local install there compodoc and there also angular typings are undefined.
Maby I do something wrong?

Can you explaine how exactly compodoc use tsconfig.ts and where I make mistake?

 [Also i add link to stackoverflow](https://stackoverflow.com/questions/46589224/angularjs-1-types-ng-in-compodoc-are-undefined)

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10 x64
node v6.11.3
npm 3.10.10
angularjs 1.6.6
typescript 2.4.2
compodoc 1.0.1
angular-ts-decorators 0.0.23

##### **Angular configuration, a `package.json` file in the root folder**

in compodoc-ready-angularjs project I 

##### **Compodoc installed globally or locally ?**

local, but I also tried global installation

##### **Reproduce the error**
this code and screen from compodoc-demo-todomvc-angular1
`import {} from "angular";
export function AppRouting($stateProvider: ng.IAngularStatic, $urlRouterProvider: ng.IAngularStatic) {
`
and result on the image: 
[screen](http://prntscr.com/gtyn15)

**Comment by vogloblinsky** [comment]
This tool is for Angular 2+ projects, it doesn't support right now AngularJS projects writtent in TypeScript

**Comment by dwadezp** [comment]
Can i create pull request in order to fix this problem?

**Comment by vogloblinsky** [comment]
@dwadezp If you want.
