### ISSUE TITLE
feat(app): add Node.js / Gulp option

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#32]
Provide an access with Node.js

```
const compodoc = require('compodoc')
```

and with gulp ?

```
const compodoc = require('gulp-compodoc')
```

**Comment by vogloblinsky** [comment]
Gulp plugin repository instantiated here : https://github.com/compodoc/gulp-compodoc

**Comment by trickpattyFH20** [comment]
@vogloblinsky is there an example or recommended method for using compodoc in a node script?

**Comment by vogloblinsky** [comment]
The source code of https://github.com/compodoc/gulp-compodoc could help.
i will detail a bit more this in the README
