### ISSUE TITLE
Not all routes being scanned

### ISSUE THREAD

**Issue by kucharzyk** [compodoc/compodoc#33]
Hi,

I have angular-cli app with few lazy loaded modules.

After generating documentation there are only listed routes from first submodule.
But I have one main routing module and 3 submodules.

You can see my routing modules here: https://github.com/shardis/shardis/search?utf8=%E2%9C%93&q=RouterModule.for&type=Code

Only first AboutRoutingModule was scanned and listed in docs

**Comment by vogloblinsky** [comment]
There is an error on your [app-routing.module.ts](https://github.com/shardis/shardis/blob/c652aa2723937f112bf956ed817e376caba63da7/src/main/typescript/app/app-routing.module.ts#L52), there is a trailing comma in your array.
I release 0.0.22 version for supporting multiples components for same route

**Comment by kucharzyk** [comment]
Thanks for quick response
