### ISSUE TITLE
[BUG] Coverage does not ignore private members with TypeScript 2.5

### ISSUE THREAD

**Issue by stogle** [compodoc/compodoc#332]
##### **Overview of the issue**

Compodoc is not ignoring private members in document coverage.

##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc: 1.0.1
Node.js version : v6.11.3
Operating system : Windows 8.1

##### **Angular configuration, a `package.json` file in the root folder**

Occurs in the live demo as well

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

Incorrect coverage data.

##### **Reproduce the error**

In the live demo note the coverage for EmitterService is 33%, not 50%. The private _emitters properties is being included in the calculation.
https://compodoc.github.io/compodoc-demo-todomvc-angular/coverage.html

##### **Related issues**

I believe this is due to incorrect SyntaxKind IDs just like https://github.com/compodoc/compodoc/issues/197.

##### **Suggest a Fix**

I think 111 should be replaced with 112 in the following lines:

https://github.com/compodoc/compodoc/blob/master/src/app/application.ts#L989-L1187

**Comment by seekheart** [comment]
I don't think Angular supports TS > 2.4 as of yet?
