### ISSUE TITLE
[BUG] Poor source/template overview performance in safari browser

### ISSUE THREAD

**Issue by danielsogl** [compodoc/compodoc#333]
##### **Overview of the issue**
If I open the source tab/page or template in the safari browser, the render/scroll performance is really bad. I don't have this kind of problem in Chrome or IE.

##### **Operating System, Node.js, npm, compodoc version(s)**
macOS 10.13
NodeJs: 8.7.0
compodoc: 1.0.1
##### **Angular configuration, a `package.json` file in the root folder**
```
"@angular/animations": "4.4.4",
"@angular/cdk": "^2.0.0-beta.12",
"@angular/common": "4.4.3",
"@angular/compiler": "4.4.3",
"@angular/compiler-cli": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3"
```
##### **Compodoc installed globally or locally ?**
locally

##### **Reproduce the error**
Build the Documentation locally or deploy it and open any source or template tab in the Safari Browser

**Comment by vogloblinsky** [comment]
hi @danielsogl 
Did you have a live example online ?
Is there the same issue on the official demo ? https://compodoc.github.io/compodoc-demo-todomvc-angular/

**Comment by danielsogl** [comment]
Yes same problem with the compodoc docs. I tested different Documentations.

**Comment by vogloblinsky** [comment]
@danielsogl 
Can you explain a little more "the render/scroll performance is really bad" ?
I am on macOS 10.12.6 with Safari 11. Does seems ok for me.

**Comment by vogloblinsky** [comment]
@danielsogl any news ?

**Comment by vogloblinsky** [comment]
@danielsogl any news ?

**Comment by vogloblinsky** [comment]
I am closing it, no news since one month. Feel free to reopen it.
