### ISSUE TITLE
[FEATURE] Additional support for pipe doc

### ISSUE THREAD

**Issue by vleandersson** [compodoc/compodoc#336]
##### **Overview of the issue**
When documenting pipes, it would be preferable to be able to see JSDOC for the transform function (and maybe other functions as well in the pipe class). Currently you only see the meta-tag documentation, which is greatly including examples and additional notes.

##### **Operating System, Node.js, npm, compodoc version(s)**
Windows 10
@compodoc/compodoc: 1.0.1 with npm

##### **Compodoc installed globally or locally ?**
local install

##### **Motivation for or Use Case**
Adds posibility to see input parameters for the pipe, as well as what output it should give

**Comment by vogloblinsky** [comment]
Available In 1.0.4
