### ISSUE TITLE
[FEATURE] Fullscreen for modules overview

### ISSUE THREAD

**Issue by vleandersson** [compodoc/compodoc#337]
##### **Overview of the issue**

The modules overview (on the overview tab) gets unreadable on bigger project. It's a very nice freature, and I propose to make it fullscreen or at least take up the full screen space on the overview tab. This would make it possible to get a better view of your application, and work more smoothely with the overview graph.

##### **Motivation for or Use Case**

Used when working with architecutre of the app

##### **Suggest a Fix**
Fullscreen on click or:

CSS:
#module-graph-svg {
    width: 100%;
    height: 90vh;
}

And then re-center the graph in the svg

**Comment by vogloblinsky** [comment]
See https://github.com/compodoc/compodoc/issues/234#issuecomment-322024853
