### ISSUE TITLE
[BUG] Module overview visualisation: can not zoom in enought (PRIO HIGH)

### ISSUE THREAD

**Issue by vleandersson** [compodoc/compodoc#338]
##### **Overview of the issue**
On the overview tab, the modules visualisation can not be zoomed in enought for making the module texts visible. 

##### **Suggest a Fix**
This could be solved by #337 fullscreen mode, using the viable space better (squared tree layout) and loosing the zoom limit. The zoom limit could be made dynamic, depending on the tree size.

**Comment by vogloblinsky** [comment]
I am working on it here : https://github.com/compodoc/compodoc/issues/234#issuecomment-322024853

**Comment by vogloblinsky** [comment]
Fullscreen feature available in 1.0.2
