### ISSUE TITLE
[Question] complete documentation around a single function

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [compodoc/compodoc#342]
##### **Overview of the issue**

I am using compodoc for my project, I know basic detail of documentation but still, I am missing somehow details due to poor documentation on our site, can anyone help me to make perfect documentation for this example function (Is was taken from my component)

##### **detail for document function**

  ```
addContact(contact: Contact, createEditModal: any): void {
    this.contactService.createContact(contact).subscribe(() => {
      this.contactCreated = true;
      this.loaderService.toggleLoader(false);
      createEditModal.approve();
      this.ngOnInit();
    }, (error) => {
      this.unauthorizedError = error;
      this.loaderService.toggleLoader(false);
    });
  }
```

**Comment by vogloblinsky** [comment]
You can only document the primitive of your function like this :

```
/**
 * addContact description
 * @param  {Contact} contact         [description]
 * @param  {any}     createEditModal [description]
 */
addContact(contact: Contact, createEditModal: any): void {
...
```

If you have any remarks about the actual documentation, you are welcome.

**Comment by dev-fullstacktechnology** [comment]
I looked at the demo example available on our doc site. But they have most of the empty components.
https://compodoc.github.io/compodoc-demo-todomvc-angular/index.html

I suggest making at least minimal example of each type of angular elements with 100% documentation converge.
