### ISSUE TITLE
[FEATURE] add support for pug and other templating languages other than html

### ISSUE THREAD

**Issue by sinsunsan** [compodoc/compodoc#343]
##### **Overview of the issue**

I am working on a site that use [PUG](https://pugjs.org) Templates. When trying to generate doc for this site using compodoc the DOM and templates are empty as Compodoc do not understand other language than html.

But could be very useful for compodoc to be able to support those templating languages.

A time ago, I stumbled upon a library that make the abstraction on templating languages. That could be nice to have a wider support. 

Is it in your plan? 
Feasible? 
Any workaround you imagine to make it working anyway right now : 
    * precompiling the pug locally with other tool (Gulp...) ? 
    * Reading a webpack configuration and hooking in it (I am based on [Angular class starter](https://github.com/AngularClass/angular-starter)

**Comment by vogloblinsky** [comment]
Did you have an example of a component please ?

**Comment by sinsunsan** [comment]
For example this one but it is pretty standard in templateUrl you can add .pug template if you set it correctly in the webpack config. 


card-project.component.scss

````ts
import { Component, Input  } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

import { ProjectObject } from '../../../objects';

@Component({
  selector: 'card-project',
  templateUrl: 'card-project.template.pug',
  styleUrls: [ 'card-project.styles.scss' ],
})
export class CardProjectComponent {

  @Input()
  public project: ProjectObject;

  @Input()
  public showOrganization: false;

  constructor(
    private route: ActivatedRoute,
    private router: Router,
  ) {
  }

  public gotoProject() {
    this.router.navigate(['project', this.project.name]);
  }
}
````

'card-project.template.pug
````pug
  div(class="ui card")
    div(class="content")
      div(class="header project-name m-b-xs")
        a([routerLink]="['/project/', project.id]", *ngIf="project") {{ project.name }}

      div(class="meta")
        div(class="project-organization",
            *ngIf="project && project.organization && project.organization.name && showOrganization")
          a([routerLink]="['/organization', project.organization?.name]") {{ project.organization.name }}

        div(class="project-updated") {{ 'project.card.updated' | translate }} {{ project?.updated | amTimeAgo }}

        div(class="project-metrics float-right", *ngIf="project.topic_count > 0")

          div(class="project-topics-count inline m-l-xs",
            smDirTooltip="{{ project.topic_count }}  {{ 'project.card.topicsCount' | translate }}",
            smDirPosition="top right")
            a([routerLink]="['/project/', project.id]")
              i(class="list icon")
              span {{ project.topic_count }}

          div(class="project-members-count inline m-l-xs",
              smDirTooltip="{{ project.groups.length }}  {{ 'project.card.groupsCount' | translate }}",
              smDirPosition="top right")
              a([routerLink]="['/project/', project.id, 'settings', 'groups']")
                i(class="users icon")
                span {{ project.groups.length }}

          div(class="project-members-count inline m-l-xs",
              smDirTooltip="{{ project.users.length }}  {{ 'project.card.membersCount' | translate }}",
              smDirPosition="top right")
            a([routerLink]="['/project/', project.id, 'settings', 'members']")
              i(class="user icon")
              span {{ project.users.length }}
````

**Comment by vogloblinsky** [comment]
Did you know other templating libraries than pug ?
I could handle that by checking extension of file in templateUrl
I fnot html, just read the file, and disable the DOM tree tab

**Comment by sinsunsan** [comment]
Here is a recent comparison of js template language https://colorlib.com/wp/top-templating-engines-for-javascript/

I remember a sort of abstraction library on all language, but do not reach  to find it again. 

I think reading the extension is necessary, bu you also need a way to compile it to html. It is for that  reason that a meta compiler could may be useful if it exist.
