### ISSUE TITLE
[FEATURE] modify displaying detail of class variable declaration in table view

### ISSUE THREAD

**Issue by kunjan343** [compodoc/compodoc#344]
**Overview of the issue** 

I have compodoc integrated in my project which have very huge components. Some of them contain more then 50 variables.

So if I generate document with our library then it makes to much empty space and long documentation coverage.

**Snapshot of an issue**

![](https://i.imgur.com/kv3RHjZ.png)

**Suggestion workaround**

I am thinking about to display all class variable property in table view same as definition of a function.

**Comment by dev-fullstacktechnology** [comment]
I think that is actually happening due to library design as considering all first level declaration in one format.
Maybe this is actually beginning of the implementation of something good.

**Comment by kunjan343** [comment]
Yah, may be we should use type based classification to present different elements of the class.

**Comment by vogloblinsky** [comment]
Fixed for me with index table available in top of each page now.
