### ISSUE TITLE
[BUG] Generic types are missing

### ISSUE THREAD

**Issue by seokju-na** [compodoc/compodoc#345]
##### **Overview of the issue**

Return value of generics are not appeared on documentation.

This is my source code.

```typescript
login(data: AccountLoginRequestBody, saveToken?: boolean): Observable<AccountUserItem> {
        return this.http.post<AccountUserResponse>(ACCOUNT_MEMBER_AUTH_URL, data)
            .do((response) => {
                this.updateToken(response.token, saveToken);
                this._authorized = true;
            })
            .map((response) => {
                this.userInfo = apiAdapter.adapt<AccountUserResponse, AccountUserItem>(response);
                return this.userInfo;
            });
}
```

I want this function's return value to be displayed like `Observable<AccountUserItem>`, however the genercis were empty in document like `Returns : Observable<>`.

##### **Operating System, Node.js, npm, compodoc version(s)**

macOS 10.12.6
node.js 8.7.0
compodoc 1.0.1

##### **Angular configuration, a `package.json` file in the root folder**

```
"@angular/animations": "^4.2.4",
"@angular/common": "^4.2.4",
"@angular/compiler": "^4.2.4",
"@angular/core": "^4.2.4",
"@angular/forms": "^4.2.4",
"@angular/http": "^4.2.4",
"@angular/platform-browser": "^4.2.4",
"@angular/platform-browser-dynamic": "^4.2.4",
"@angular/router": "^4.2.4",
```

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

Parse generics correctly.

**Comment by vogloblinsky** [comment]
Fixed in 1.0.3
