### ISSUE TITLE
[BUG] Change markdown engine

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#349]
David DM now marks marked as unsecure : https://david-dm.org/compodoc/compodoc

Marked maintainer seems to not be active : https://github.com/chjj/marked/issues/938, https://github.com/chjj/marked/issues/937

Here is the list i found : 
- https://github.com/evilstreak/markdown-js - 6300 stars - last commit the Oct 18, 2017
- https://github.com/showdownjs/showdown - 5600 stars - last commit the Oct 26, 2017
- https://github.com/markdown-it/markdown-it - 4250 stars - last commit the Aug 24, 2017

Feedbacks are welcome for these libraries.

**Comment by realappie** [comment]
I personally recommend showdown, not only based on my own experience. But it seems to be the most active at the moment.

But on the other hand, markdown it has a plugins eco system which could be very valuable to utilize. Overall it seems to be the less active more mature alternative.

**Comment by vogloblinsky** [comment]
XSS issue on marked fixed : https://github.com/chjj/marked/releases/tag/v0.3.7

I roll back to marked, after a switch to the fork 8fold-marked.

As marked does the job for me, i close this issue.
