### ISSUE TITLE
[FEATURE] Expose the dependencies and HTML engines for extensibility

### ISSUE THREAD

**Issue by guilhermevrs** [compodoc/compodoc#357]
##### **Overview of the issue**

Expose the dependencies and HTML engines so I could generate custom documentation for a specific project

##### **Motivation for or Use Case**

The use case here is that I may have different angular projects that I would like to generate documentation using compodoc. The difference is that between each projects, I would like to include specific things in the template and/or handle an injectable or class as different definition.

For example:
Let' s say I have classes that will act like services for my whole application. I would like to display them not as classes, but in a section called Services.

Or let's say I have ngrx stores in another project. I would like to have a specific section for them.

Those examples (and many others) would not make sense in a general aspect, but only in the project itself.

**Comment by guilhermevrs** [comment]
If you agree with the idea, I would be glad to propose a PR for that

_Sent from my Samsung SM-A500FU using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by guilhermevrs** [comment]
If you agree with the idea, I would be glad to propose a PR for that

**Comment by vogloblinsky** [comment]
Can you explain a little here how we could achieve this ?
Schematics from angular-cli could be an option.
Plugins like esdoc could be another : https://github.com/esdoc/esdoc-plugins

**Comment by guilhermevrs** [comment]
Yes I was thinking something around the schematics from angular.

Basically I could indicate via cli option a custom engine for either the dependencies and/or render engine.
Once specified, we could init the app with them.
Those engines should implement each the correct interfaces, so that the application class can call the methods.

What do you think?

**Comment by guilhermevrs** [comment]
The default ones would be the same compodoc uses today. So no breaking change I'd say.

**Comment by dp-1a** [comment]
We looked at the options for building on top of the compodoc output and have seen that there is already an option to export the output of the crawling step as JSON with the `-e json` flag.

But ideally we want to avoid to read the JSON from the file system so we where wondering if it would be possible to expose the crawling and analysis part of compodoc so that it could be like a library. Ideally we want to do something like this:

```
// PSEUDO CODE
import {Application} from "compodoc";

const dependencies = new Application.generate();

renderMyWay(dependencies);
```
Do you think this would be feasible from your perspective What ?

**Comment by vogloblinsky** [comment]
yes watch the source code of this gulp plugin : https://github.com/compodoc/gulp-compodoc/blob/master/index.js

**Comment by theaccordance** [comment]
I evaluated this tool yesterday for my own TypeScript project (enterprise-grade B2B app), and the only thing holding me back from adopting it is my need for proper ngrx documentation alongside angular.  

I haven't explored the JSON output yet, that could address my needs, but at the same time, I want to put the effort into my project and not on the tools for the project.  If this was extensible, I would then have the option to add a plugin to support ngrx, or contribute a plugin to solve mine and others needs.  

As project leader, I want to provide my team with a singular source of documentation for the project, and I need to hold ngrx on equal footing to angular in terms of clear and concise documentation.  Clear and concise is where it fell short in my evaluation.

**Comment by ChristianUlbrich** [comment]
@theaccordance Okay, I've hacked something together. The compodoc codebase is _very unique_; but if you happen to have your ngRx actions to be Classes (as the ngRx example app recommends) and you divide them by purpose into Commands, Events, Documents (see [1]) you can have a look at https://github.com/zalari/compodoc/tree/document-ngrx. It adds _Events_ to compodoc and aggregates them by a `@Event` decorator. Of course naming conventions could also be used as a way to figure out, whether something is a simple class or an event.

[1] https://blog.nrwl.io/ngrx-patterns-and-techniques-f46126e2b1e5
