### ISSUE TITLE
[BUG]: Compodoc doesn't consider README.md of a component while creating a doc

### ISSUE THREAD

**Issue by sosharma1403** [compodoc/compodoc#358]
##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc version: 1.0.3

Node.js version : v6.11.1

Operating system : Windows 7

##### **Angular configuration, a `package.json` file in the root folder**

Refer: https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/master/package.json
Change ```scripts.doc = "compodoc -p src/tsconfig.json -d docs"```

##### **Compodoc installed globally or locally ?**

locally

##### **Reproduce the error**

Rename list.component.md to README.md

**Comment by vogloblinsky** [comment]
Sorry i prefer getting in the same "philosphy" as the official style guide, and force people to have the Readme file named like the original component.
