### ISSUE TITLE
[SUPPORT] : Compatibility with angular 5+

### ISSUE THREAD

**Issue by dev-fullstacktechnology** [compodoc/compodoc#359]
##### **Overview of the issue**
This is general support query with compatibility with angular 5 version since it was released recently. They made many changes so I am sure someone got an issue with the new update. If you have any then please comment here.

##### **Suggestion**
It is good to pass your debug snapshot with support so we can track common issues.

**Comment by vogloblinsky** [comment]
I will do a test tonight. I don't think it will break a lot.
I will also update to v5 the demo project.

**Comment by dev-fullstacktechnology** [comment]
Sounds great to me. Maybe the only couple of minor bugs. I will also check tonight and send you a message.

**Comment by kunjan343** [comment]
I checked in by generate a project from scratch by using angular-cli v1.5 and no errors are  been detected. Everything looks good.

**Comment by vogloblinsky** [comment]
Demo project updated to Angular 5, Compodoc works fine on it.

@dev-fullstacktechnology if you have any remarks, you are welcome.

**Comment by btgoodwin** [comment]
Any chance you all can relax the TypeScript version requirement?  The 5.0.0 release came out and \@angular/compiler-cli depends on tsickle 0.24.1 which is locked to TypeScript 2.4.2.  Since compodoc 1.0.4 is locked to 2.6.1, one ends up with NPM dependency errors when trying to use it with a Angular app.

I cloned compodoc 1.0.4, changed the TypeScript requirement to `^2.4.2` and ran `npm install && npm run build && run test`.  It seems to be okay with the slightly older version.

**Comment by ctaepper** [comment]
yes, angular 5 is locked to `typescript@2.4.2` maybe an older `ts-simple-ast` not depending on `typescript@2.6.1` will do the job, too?

**Comment by vogloblinsky** [comment]
I will contact ts-simple-ast maintainer for having a explantion about this high dependency of TypeScript 2.6.x

**Comment by vogloblinsky** [comment]
Things are moving.
I have submitted a PR to ts-simple-ast to relax TypeScript dependency.
When https://github.com/dsherret/ts-simple-ast/issues/144 is closed, i will close this one too.

**Comment by vogloblinsky** [comment]
https://github.com/dsherret/ts-simple-ast/issues/144 closed, version 4.2.0 of ts-simple-ast relax TypeScript version. I also downgrade the version required by Compodoc.
Coming in 1.0.6
