### ISSUE TITLE
Comment Format

### ISSUE THREAD

**Issue by jongunter** [compodoc/compodoc#36]
First off, excellent plugin! I've used plenty of javascript documentation generators and this has been the absolute easiest to get working out-of-the-box.

I think the docs could use some clarification about how to format code comments so compodoc can parse them. Or modifications should be made to the plugin to handle different comment formats. For example, in my angular cli project...

```
/**
 This comment seems to be parsed
*/
@Component(...
```

```
/*
 While this one (the WebStorm default block comment with only one *) does not.
*/
@Component(...
```

```
// Also, this one doesn't get parsed, either
@Component(...
```

**Comment by vogloblinsky** [comment]
Compodoc use typescript ast parser. Typescript use JSDoc comments.
I use an official API for getting comments, like in this page : https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker 

```
function serializeSymbol(symbol: ts.Symbol): DocEntry {
        return {
            name: symbol.getName(),
            documentation: ts.displayPartsToString(symbol.getDocumentationComment()),
            type: checker.typeToString(checker.getTypeOfSymbolAtLocation(symbol, symbol.valueDeclaration))
        };
}
```
I have added clarifications on the README for that.
