### ISSUE TITLE
[BUG] User defined type not accepting as a param in a method if there are string |user defined object is input for a method.

### ISSUE THREAD

**Issue by junedansari** [compodoc/compodoc#360]
Hi,
I am facing an issue for doc generation of a method as my method accepts either a user defined arguments(GrowlOptions) or string as given below, it is not giving me GrowlOptions as a  param once doc generated

```
  /**
   * Create Growl(toaster) for success messages.
   * @param options {string | GrowlOptions}options can have either message or title or object of growlOptions type.
   */
  public success(options: string | GrowlOptions): void {
}
```
Output: **success(options: string | )** doc showing only string as a param 
![image](https://user-images.githubusercontent.com/1515253/32438665-54d0bcd8-c311-11e7-8796-56548c029d9f.png)

Please let me know if i missed something.
Thanks

**Comment by junedansari** [comment]
![image](https://user-images.githubusercontent.com/1515253/32438599-17825166-c311-11e7-982b-be97898297e6.png)

**Comment by kunjan343** [comment]
I am writing as below and it is working perfect.
/**
   * Create Growl(toaster) for success messages.
   * @param {string | GrowlOptions} options can have either message or title or object of growlOptions type.
   */
  public success(options: string | GrowlOptions): void {
}
But I didn't tested with multiple options. So, check and let me know if it works.

**Comment by junedansari** [comment]
Hi @kunjan343 ,
@kunjan343 Thanks for your comment.

Which version of compodoc are you referring.in my case it is not working for mutiple optional arguments.

if it is predefined type like string | number | boolean , compodoc giving me all option as a param for that method but if i give growlOption | string, compodoc giving me  | string as param for that method.
please refer attached above screenshot

**Comment by vogloblinsky** [comment]
@junedansari Works fine for me with last version, 1.0.3

**Comment by junedansari** [comment]
Thank you so much itz working with  1.0.3.
