### ISSUE TITLE
Compodoc install Error in Angular 4

### ISSUE THREAD

**Issue by ahkeno** [compodoc/compodoc#362]
I try to install compodoc for my Angular 4 Application 
my node version is : v6.11.1 
npm version is v3.10.10 and 
Os is: Window 6.1.7601 and 
angular/cli verion is 1.2.6

I got this error while I install

```
Skipping optional dependency : fsevents@ 1.0.0
Skipping optional dependency : Unsupported platform 
```
after that warning , when I run "npm run compodoc" I got npm ERR! missing script : compodoc
--

**Comment by vogloblinsky** [comment]
Which npm command did you use to install it ?

**Comment by ahkeno** [comment]
npm install -g @compodoc/compodoc

**Comment by vogloblinsky** [comment]
oh yes, you have to put inside your package.json an npm script like this one : 
https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/master/package.json#L9
and after launch it with 
```
npm run doc
```

**Comment by ahkeno** [comment]
I did,
putting this " "@compodoc/compodoc": "^1.0.3", in  my package.json 
then when I run  `npm run doc`
It show 

npm ERR: missing script :doc

**Comment by vogloblinsky** [comment]
Add the line 9 of my example in your package.json

**Comment by ahkeno** [comment]
added and run 
then receive  ERROR:
` Provided source folder Angular was not found in the current directory`

**Comment by ahkeno** [comment]
I manage to run the documentation with this line
`"doc": "./node_modules/.bin/compodoc -p tsconfig.json"` 
can you tell me ,any risk I might face removing of the rest?

**Comment by kunjan343** [comment]
Try to install compodoc as dev dependency
```
npm install @compodoc/compodoc --save-dev
```
And then run `npm run doc`

**Comment by metaloha** [comment]
To address the `fsevents` warning above - that package is not needed on Windows platforms, and is not related to the problem you're describing :) It's completely safe to ignore that warning.

**Comment by vogloblinsky** [comment]
Clsoing this @ahkeno if you have any remarks, feel free to add it.
