### ISSUE TITLE
[BUG] : routing was not showing due to an exception error

### ISSUE THREAD

**Issue by kunjan343** [compodoc/compodoc#364]
##### **Overview of the issue**

I changed route module as per described in live example to expose my routes in compodoc, document was also generated successfully. All pages working fine. except for routes. When I open routes menu It is throwing me an error.

![image](https://user-images.githubusercontent.com/22045550/32598999-3255f8e2-c561-11e7-8011-0615dc1bff55.png)

-> Uncought TypeError: e.sort is not a function from d3.v3.min.js file

##### **Operating System, Node.js, npm, compodoc version(s)**
OS             : ubuntu 14.04
NodeJs      : v7.7.4
npm           : v4.1.2
compodoc : v1.0.4

##### **Compodoc installed globally or locally ?**

locally as dev dependency

**Comment by kunjan343** [comment]
![](https://i.imgur.com/oAcqjA5.png)
Here is my route file

**Comment by kunjan343** [comment]
Hey, I debug build code and found a bug, check the red box
![](https://i.imgur.com/AiA86ul.png)

**Comment by vogloblinsky** [comment]
Ok related to https://github.com/compodoc/compodoc/issues/216

**Comment by kunjan343** [comment]
And also the children is another route constant which is defined in separate file. So, we have to detect it to display on route.

**Comment by vogloblinsky** [comment]
Yes, we have to detect it is a dynamic variable, find it in imports or misc variables. I have done the same thing for component/directive metadatas https://github.com/compodoc/compodoc/commit/a5a3027ce278e5eac9e12494928a759cbb8b6c3e

**Comment by kunjan343** [comment]
I tested it by manually generating my tree data and now its working. The only thing we are missing is reading external routes from different file.

**Comment by vogloblinsky** [comment]
Yes, i have added in milestone 1.0.5. stay tuned
