### ISSUE TITLE
[FEATURE] add a modifier for `private static` in doc

### ISSUE THREAD

**Issue by rdkmaster** [compodoc/compodoc#367]
##### **Overview of the issue**

there is no way to distinguish a static method or variable of a class from a normal method or varable. for example, `toArray()` is a static method:

    public static toArray(rawData: any): any[] {
        return TableData.of(rawData).toArray();
    }

and in the export doc, it looks like this:

![image](https://user-images.githubusercontent.com/16191626/32685654-925a289c-c6d0-11e7-9ccc-abea2c3b7a0d.png)

in the summary section, all methods including the static or non-static ones are laying together:

![image](https://user-images.githubusercontent.com/16191626/32685696-517a4036-c6d1-11e7-955c-ad05568efe5d.png)

there is nothing to help the readers to learn that this is a **static method**

better to make some change in the exported doc, like:

![image](https://user-images.githubusercontent.com/16191626/32685643-672172f2-c6d0-11e7-8a34-0b006de9ae70.png)

1. use a `public static` modifier instead of `public` modifier;
2. use another style for the `public static` methods/variables;

**Comment by vogloblinsky** [comment]
Static are by default public, i will just fix the issue for private static.

**Comment by rdkmaster** [comment]
hi @vogloblinsky 

maybe you are misunderstanding me. I mean that compodoc should add `static` tag to the exported modifier of **static methods/variables**, by doing this, the doc readers can distinguish the static methods/variables with this `static` tag. 

as you can find in this picture:

![](https://user-images.githubusercontent.com/16191626/32685696-517a4036-c6d1-11e7-955c-ad05568efe5d.png)

there is no message in the exported doc to helper the readers to distinguish the static method/variables and the none-static ones.

I do not speek/write in English a lot, am i make myself clear?

**Comment by vogloblinsky** [comment]
Yes, i am working on it right now :smile:

**Comment by vogloblinsky** [comment]
![image](https://user-images.githubusercontent.com/2841805/32757422-aeb8caf0-c8df-11e7-9595-36b2ae29223f.png)

**Comment by rdkmaster** [comment]
thanks @vogloblinsky for the rapid replying, this is really what i want.

compodoc is great, thank again
