### ISSUE TITLE
Dom tree tab does not show graph for angular components with inline html templates 

### ISSUE THREAD

**Issue by r3vsan** [compodoc/compodoc#370]
##### **Overview of the issue**

I use compodoc to generate documentation of my angular 5 project which defines both components with separate HTML template file (for big templates) and components with inline template specified in the same .ts file (smaller templates). When i generate documentation, components with external html template file are correctly explained in DOM tree tab while components with inline template are not.

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10, node v8.9.1, compodoc 1.0.4

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "test-compodoc",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/router": "^5.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@compodoc/compodoc": "^1.0.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

##### **Compodoc installed globally or locally ?**

Compodoc is installed globally 

##### **Motivation for or Use Case**
I use compodoc to generate documentation of my angular 5 project which defines both components with separate HTML template file (for big templates) and components with inline template specified in the same .ts file (smaller templates). When i generate documentation, components with external html template file are correctly explained in DOM tree tab while components with inline template are not.

##### **Reproduce the error**

I generated a simple angular project with CLI and i generated two 2 test components. First component has separated html template file, second one has inline template.
Then i launch compodoc to generate documentation.
Generated documentation correctly show graph in dom tree tab for first component. Not the same for second component.

**Comment by vogloblinsky** [comment]
@r3vsan Do you have an example of the component with inline template.

**Comment by vogloblinsky** [comment]
Ok reproduced with the CLI
