### ISSUE TITLE
[BUG] Partial documentation is generated | Maximum call stack size exceeded

### ISSUE THREAD

**Issue by andrew19881123** [compodoc/compodoc#378]
##### **Overview of the issue**

When generating the documentation i get this error:
```javascript
RangeError: Maximum call stack size exceeded
```
The documentation is partial with missing components, directives and services.

I do have a couple of base64 images in the code, but there is a related issue stating this bug was fixed.

##### **Operating System, Node.js, npm, compodoc version(s)**

node: 8.5.0
npm: 5.3.0
os: win32 x64
compodoc: 1.0.3

##### **Angular configuration, a `package.json` file in the root folder**
```json
"devDependencies": {
    "angular/animations": "4.4.4",
    "angular/cli": "1.4.5",
    "angular/common": "4.4.4",
    "angular/compiler": "4.4.4",
    "angular/compiler-cli": "4.4.4",
    "angular/core": "4.4.4",
    "angular/forms": "4.4.4",
    "angular/http": "4.4.4",
    "angular/language-service": "4.4.4",
    "angular/platform-browser": "4.4.4",
    "angular/platform-browser-dynamic": "4.4.4",
    "angular/router": "4.4.4",
    "compodoc/compodoc": "1.0.3",
    "types/chai-as-promised": "^7.1.0",
    "types/jasmine": "~2.5.54",
    "types/jasminewd2": "2.0.3",
    "types/node": "6.0.89",
    "bootstrap": "4.0.0-beta",
    "chai": "4.1.2",
    "chai-as-promised": "7.1.1",
    "codelyzer": "~3.1.1",
    "core-js": "2.5.1",
    "cucumber": "2.2.0",
    "cucumber-tsflow": "2.2.0",
    "font-awesome": "4.7.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "jquery": "3.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "popper.js": "1.12.5",
    "primeng": "4.2.2",
    "protractor": "~4.0.0",
    "protractor-cucumber-framework": "4.0.8",
    "rxjs": "5.4.3",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "~2.3.4",
    "zone.js": "0.8.18"
  },
```

##### **Related issues**

An issues was closed but still the problem persist.
[#269](https://github.com/compodoc/compodoc/issues/269)

**Comment by vogloblinsky** [comment]
> I do have a couple of base64 images in the code, but there is a related issue stating this bug was fixed.

May be not...

How many image do you have ? average size in px ?

**Comment by andrew19881123** [comment]
2 images:

IMAGE 1

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAKO0lEQVR42u3dT4hdZxmA8Scyi1mMkEXEASOkECGFChEiRphCChUitGjpFBt0EReFFrqYgKUWa6WtUqSFVFwoVGiCAZUGqrTSLgINElCwYhYBs8hihCxGWmjAAbMYGBffXPKnM5M7N/d87/nO+/xgSDfe897Y+/Scc+99Z9f6+jqNOgQcBj4P7L3pZx7YHT1cEheAbwKr0YNoMrsaCsAssAA8CjxEebErnhFoWAsB2A08CzwNzEUPo02do0RgLXoQ7UyfAzALPAn8BE/pW3AWOIYRaMpM9ABbeBx4GdgfPYjGtrjxpxFoyGeiB7jNDPAq8Dt88bdokfL/nxrRpzOA3cBbwIPRg+iuLG38eSJ6EN1ZX84A7gP+ji/+oVgCno8eQnfWh5uAeykv/vnoQTR1J4DXo4fQ1qLPAOaAd/DFP1QnKW/fqqeiA/Bb4GD0X4I6dZIb7xCoZyID8DLw7ei/AHVuhvKujhHooah7AAeBf0Y/eVW1BjxA+eiweiLqDMD3ivOZAd6jfJ9DPRFxBnCU8i+CclqlnAl8GD2I6gdghvKWnzf+cluhROBy9CDZ1b4EWMQXv8rbvh8AB6IHya52AL4T/YTVG/P4GZBwNS8BZoGP8Dv9utVlyuXASvQgGdU8A3gQX/z6tAOUywH/3QhQMwDfin6y6q0DlHeGXPNWWc1LgI+APR0f49LGz/VaT2qgFojZx7AC3A9cif4LyKJWAGaB/3X4+GeBp4CPazyZBN4Ejgcd23sCFdW6BOjyTu9LwGP44h+K0T0B3x2ooFYA9nX0uBcpXyrSsBwA3sYbg52rFYCubu6cxgWUQ3WYcmPQCHSo9UsAP08+bAuUrxL3aXfloNQKwGc7etyrleZXnIcwAp2J3ggkjWMReCN6iCEyAGrFccp6MU2RAVBLloBXoocYEgOg1vyQG798RHfJAKhFrhufEgOgVrlufAoMgFrluvEpMABq2Qzll8u4aXhCBkCtm8V14xMzABqC0e+YdMnoDhkADcVu3DS8YwZAQzJaN+4ugTEZAA2NEdgBA6AhctPwmAyAhmq0adgIbMMAaMgWKBGYjR6krwyAhm6B8mEhF4pswgAog0XcKrQpA6AsFoFXo4foGwOgTJZwq9AtDICyWaIsFREGQDm9gluFAAOgvE4S9/sPe8MAKLM3SL5QxAAos9FWoaPRg0QxAMpuBniLpAtFDIBUvi/wHuUXkqZiAKRijvIryVMtFDEA0g2jXQJpImAApFvNU84EUiwUMQDSp40Wigw+AgZA2twByqbhQS8UMQDS1g4x8K1CBkDa3gLlcwKD3CVgAKQ7O8pAF4oYAGk8i8Cb0UNMmwGQxvc9BrZQxABIO7PEgFaLGQBp537AQBaKGABpMicZQAQMgDS5V2l8oYgB0GauRQ/QiNFCkWYjYAC0mX9HD9CQUQSaXChiALSZ5egBGjND+chwc18jNgDazJXoARo0R4O7BAyANnMJWI0eokGjhSL7ogcZlwHQVi5ED9CoecrlQBO7BAyAtvLn6AEa1sxCEQOgrbwbPUDjmlgoYgC0lWXgcvQQjev9QhEDoO14FnD3FihnAr3cJWAAtJ3T0QMMxBF6ulDEAGg7l/DdgGlZpIcRMAC6k19EDzAgi/RsoYgB0J2cBS5GDzEgT9OjCBgAjeO56AEGZgl4MXoIMAAaz/v4jsC0vUAPFooYAI3rKeDj6CEGJnyrkAHQuK4CT0QPMUChW4UMgHbij8Br0UMMTOhWIQOgnXoGOBM9xMCMInCk9oENgCbxfcrbg5qeGcpHhquuFjMAmsQacAz4TfQgAzNH+fLQ4VoHNACa1BrlpuAzG/+s6ZgD3qbSajEDoLv1GvAN/OrwNM0Dz9Y4kAHQNJwHvgL8GLgePYzGZwA0LdeBnwL3Aq/jLxdpggHQtC0DJ4AvUj49eCl6IG3NAKgrq8CvgS8D91DeOvw9sBI9mG7o1XICDdYycGrjB2AvsH/jz3ngC8Du6CEpd+D3TPC/OxI9+KQMgCJc3fgZivXoASblJYCUmAGQEjMAUmIGQErMAEiJGQApMQMgJWYApMQMgJSYAZASMwBSYgZASswASIkZACkxAyAlZgCkxAyAlJgBkBIzAFJiBkBKzABIiRkAKTEDICVmAKTEDICUmAGQEjMAUmIGQErMAEiJGQApMQMgJWYApMQMgJSYAZASMwBSYgZASswASIkZACkxAyAlZgCkxAyAlJgBkBIzAFJiBkBKzABIiRkAKTEDICVmAKTEDICUmAGQEjMAUmIGQErMAEiJzUQPoG2dBA5GD9GA08Cp6CFaZAD67SBwJHqIBvwleoBWeQkgJWYApMQMgJSYAZASMwBSYgZASswASIkZACkxAyAlZgCkxAyAlJgBkBIzAFJiBkBKzK8D99vPKd911/YuRg/QKgPQb+9HD6Bh8xJASswASIkZACkxAyAlZgCkxAyAlJgBkBIzAFJiBkBKzABIiRkAKTEDICVmAKTEDICUmAGQEjMAUmIGQErMAEiJGQApMQMgJWYApMQMgJSYa8GLgxs/atNF/N0AEzEAxSPAC9FDaGIvYQAm4iWAlJgBkBIzAFJiBkBKzABIiRkAKTEDICVmAKTEDICUmAGQEjMAUmIGQErMAEiJGQApMb8OXHwCLEcPoYl9Ej1AqwxA8frGj5SKlwBSYgZASswASIkZACkxAyAlZgCkxAyAlJgBkBIzAFJiBkBKzABIiRkAKTEDICVmAKTEDICUmAGQEjMAUmIGQErMAEiJ1QrAfzt63D2V5pe2MtfR467WGL5WAFY6etzDleaXtnKwo8f9T43hawXgakeP+2il+aWtfLejx+3qNXOL1gNwBHi60nOQbvcg8GRHj20AxvRL4FfA7krPRZoBngfe6fAYVQKwa319vcZxAD6i25t214GLwOVaT0gp7QUO0e1/cNaAzwHXun4yNQPwJnC81sGkhp0HHqhxoJqfA/hTxWNJLav2Wql5BjBHuQyYrXVAqVFfAq7UOFDNM4BV4FzF40ktukSlFz/U/yjwHyofT2pN1ddIzUsAKG+f/AvYX/OgUiOuAfdQ4e7/SO0zgDXgucrHlFrxMyq++KH+GcDIX/Fz/NLNloF7KZ9nqSbq68CeBUi3epHKL36IC8B54FTQsaW+OQeciThw1CUAlBuCHwALUQNIPXAF+CqVr/1HIgMAME+5H7AvcggpyCrwdcp7/yGiV4KtAA9TafuJ1DPHCHzxQ3wA2PgLeBj4OHoQqZI14Ang3ehBoi8BbraP8v3q+6IHkTq0AjwC/C16EOjHGcDIMuV66Gz0IFJHPqTc8OvFix/6FQAo9wIeo3xOIOSuqNSBNeA14H4qbfoZV58uAW63B/gRZeffTPQw0oTOUD7kU+0bfjvR5wCM7AdeBh6PHkTagfPACcqaut5qIQAje4GjlFXgR3CxiPplDbhA2ebzLj39L/7tWgrAzeYoMfga5cNEe2/6MQzq0hrlOn6Zckd/BfgH8D4NvpX9fxNyXo9uqE/nAAAAAElFTkSuQmCC',

---------------------------------------------------------------------------------------
IMAGE 2

data:image/gif;base64,R0lGODlhgACAAIAAAPz+/P7//yH5BAEAAAEALAAAAACAAIAAAAL+jI+py+0Po5y0KoCz3rz7D4bWSB7hiabqVrbRCsey5tbJjOepbev+3+G5gESikFRM/o4VpVPHnDynsujrY80aRFoGtqv9gm/BcVZsDqDTRw97634z4+y1vEZP2++tvHnPh1RW5xdYUggGaNg0qIe4yMghpwgp8Rh2WXkl+Uap+ZBp5fnZEBo1SrpgOreaStY4huqKIMtTO6vWaquLe4vHO+s7BOwq3EecanyITKosCIvr4DwyXVkdyRkNcU3BbehtyfwJvpmtLS1eTrVuNMz+PmUBP78eTn8fj46/71TK/69EFcCBRS4QPOjjFcKFM2gxJGhQhYmHAPWhgENx37b+Hbky3rPHxeNHkCAwinwn5WLHk+y6nTDJkorLkDFbpqRZUybJLznr7YzT0+fGlyuDBhxK1KhOfxyVLo3Y1KnQhkWlPoRplSHWrAi3coVY9StYsVfDkv3n9axGs1TPMQWStopbiwnZyp3rpV1BvHnh2o3Bt++SvzACC/S717BDxO0UT2Ts13FcwIRXSH48OLHkvZoPo6ULpbJE0PhA6W0smJ9pyIPfqiaNA3No12tpx5adY/Vn220nj+ZNT3duhcOBzxN+m3hvz6+N/4a6XHFd50Qvz4bN0Xpydc8dR7+ZfbNlUemslcfGAvt0d+Zihcr3C1oXT/DZp3ckf/HR+O10E71/skt+Z/zXTw/nzdSfcqgdIyB5DYp2l300EPJgfQzeh1+CgR2IIIbePXgKh4GI+BMGl3k1CYl3qIiUh9KByAqM2rDYYgYnmrUijX/oqN6HPKoHAF9c5KiWhjsWaeM3SCapJJKaODnOWcFwdY5UN15ZQQEAOw==',

**Comment by andrew19881123** [comment]
I don't think the partial documentation generated is due to the base64 images because i have two other projects where the docs is partial and i don't get any error in the generation. in particular the log doesn't shows the html files being created/processed. so i suppose the problem is the parser of the files of the project. another hint, the files being skipped are always the same.

**Comment by vogloblinsky** [comment]
Ok, can i have the terminal lines before the RangeError ?

**Comment by andrew19881123** [comment]
I cannot provide you with the logs nor the project because it's proprietary, not even an example because i don't know how to replicate it. sorry

**Comment by vogloblinsky** [comment]
Ok same bug reproduced with the file inside this issue : https://github.com/compodoc/compodoc/issues/410

**Comment by pain0486** [comment]
I'm having this same issue. I have excluded all test files all mock backend files, node modules and any base64 images. when I run the generator with the graph I get 2 errors
I get this one towards the beginning.
> [09:24:51] Process documentation coverage report
[09:24:51] Process main graph
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
[09:24:52] Ooops error during main graph generation, moving on next part with main graph disabled : : abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:27:15589)
    at stackTrace (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:27:15760)
    at abort (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:50:6350)
    at abortOnCannotGrowMemory (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:27:16630)
    at enlargeMemory (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:27:17075)
    at H6 (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:43:12336)
    at k6 (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:42:105869)
    at IK (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:35:82215)
    at HK (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:35:82147)
    at mV (D:\Users\Shane Montgomery\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\viz.js\viz.js:36:137849)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

and I get this one at the end

> [09:25:28] Process page   : functions
> [09:25:28] Process page   : variables
> Unhandled Rejection at: Promise {
>   <rejected> RangeError: Maximum call stack size exceeded
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1879:42)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17) } reason: RangeError: Maximum call stack size exceeded
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1879:42)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
>     at lunr.TokenStore.add (D:\Users\{{MyUserName}}\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\lunr\lunr.js:1891:17)
> [09:25:28] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)

However if I run with the switch --disableGraph I only get the 
`RangeError: Maximum call stack size exceeded`
Both will give me output in the docs director but the styles folder is never created.
