### ISSUE TITLE
[BUG] breaking update

### ISSUE THREAD

**Issue by beenotung** [compodoc/compodoc#380]
##### **Overview of the issue**

The release of 1.0.4 is a breaking update.

I was using `"@compodoc/compodoc": "^1.0.0-beta.9"`. It used to resolved to 1.0.1, now it resolve to 1.0.4, which is not backward compatible.

##### **Operating System, Node.js, npm, compodoc version(s)**

@compodoc/compodoc: 1.0.4

##### **Angular configuration, a `package.json` file in the root folder**

https://github.com/beenotung/ioniclib/blob/e5d7110c4472bde87987855e248d7ac89e57fb51/package.json

##### **Compodoc installed globally or locally ?**

compodoc installed locally

##### **Motivation for or Use Case**

This breaks the build flow.

##### **Reproduce the error**

run `compodoc -p tsconfig.json -d docs --disableCoverage --disablePrivateOrInternalSupport`

Error message of option '--disablePrivateOrInternalSupport' is not supported

##### **Related issues**

no so far.

##### **Suggest a Fix**

A. for compodoc: unpublish 1.0.4 and republish to 2.0.0
B. for client: explicitly point to 1.0.1 in the package.json
C. for client: change npm script to `compodoc -p tsconfig.json -d docs --disableCoverage --disablePrivateOrInternalSupport`

**Comment by vogloblinsky** [comment]
@beenotung 
Sorry for the problem it produce for you.
Just update to 1.0.4 and replace in your package.json --disablePrivateOrInternalSupport with --disablePrivate --disableInternal
add also --disableProtected and --disableLifeCycleHooks if you want
Regards

**Comment by beenotung** [comment]
I think this issue can be closed as the solution is clear.
