### ISSUE TITLE
[BUG] Error with node_modules

### ISSUE THREAD

**Issue by nickwinger** [compodoc/compodoc#382]
Trying to create a documentation, running compodoc i get the following error:
**Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github.

Unhandled Rejection at: Promise {
  <rejected> RangeError: Maximum call stack size exceeded
    at lunr.TokenStore.add (C:\Dev\KPD2.0\node_modules\lunr\lunr.js:1879:42)
    at lunr.TokenStore.add (C:\Dev\KPD2.0\node_modules\lunr\lunr.js:1891:17)
**

Somehow it has problems with lunr.js in node_modules.

Now my question is, why the heck is compodoc even parsing the node_modules ??????
I only want the documenation from my source code and NOT including any 3rd party node_modules stuff.
So why this error even happens ?
And how can i just tell compodoc to please ignore node_modules.

Thanks,
Nick

**Comment by vogloblinsky** [comment]
Can i have more information about how you run it ?

**Comment by nickwinger** [comment]
i installed it locally (--save-dev) and running it with npm script:
"compodoc": "compodoc src -p tsconfig.json",

command line:
npm run compodoc

**Comment by nickwinger** [comment]
i just installed it global and now it works.

But i need it locally, as the documentation should be generated on the build server

anyway it should work locally the same as installed global.

**Comment by nickwinger** [comment]
the last console ouput before the error (with the global installed compodoc) is:
Process page   : miscellaneous

I don't have a miscellaneous page in my project...
Maybe this is a hint ?

Still the question, why compodoc even looks outside of the "src" folder that i passed as an argument

**Comment by vogloblinsky** [comment]
Can i have the structure, jsut the structure of your project.
What i understand is :
YOUR_PROJECT_FOLDER
   node_modules
   src
   package.json
   tsconfig.json

**Comment by nickwinger** [comment]
22.11.2017  07:13    <DIR>          .
22.11.2017  07:13    <DIR>          ..
25.10.2017  08:49             1.324 .angular-cli.json
25.10.2017  08:49               245 .editorconfig
21.11.2017  18:06               583 .gitignore
21.11.2017  19:06    <DIR>          .idea
21.11.2017  18:06             1.379 .jazzignore
25.10.2017  08:49               740 .project
25.10.2017  08:49    <DIR>          .settings
25.10.2017  08:49             1.082 .travis-deploy.sh
25.10.2017  08:49               337 .travis.yml
07.11.2017  17:23    <DIR>          doc
09.11.2017  12:30    <DIR>          e2e
09.11.2017  10:03             1.558 karma.conf.js
21.11.2017  18:17    <DIR>          node_modules
21.11.2017  18:17           448.537 package-lock.json
21.11.2017  19:04             3.519 package.json
25.10.2017  08:49             2.327 pom.xml
25.10.2017  08:49               786 protractor.conf.js
30.10.2017  17:27               126 proxy.config.json
21.11.2017  09:24    <DIR>          src
21.11.2017  17:58               493 tsconfig.json
20.11.2017  15:26             2.807 tslint.json

**Comment by vogloblinsky** [comment]
May be related to this : https://github.com/compodoc/compodoc/issues/410
A file with base64 huge image

**Comment by nickwinger** [comment]
@vogloblinsky  
wow, you really nailed it. That was the problem.
I have a Typescript file with a  huge base64 string like so:
export const image = '<big base64>';

I removed it and now it works without problems !

thx

so, this can be closed as a duplicate to #410

**Comment by vogloblinsky** [comment]
Cool :+1:
