### ISSUE TITLE
[FEATURE] : Support routing module and lazy routes

### ISSUE THREAD

**Issue by thbt** [compodoc/compodoc#39]
Hey,
first of all, thanks for your amazing job !
Would it be possible to add support for routing modules and lazy loaded routes ? 
It seems that only inlined routes are supported for now

**Comment by vogloblinsky** [comment]
Hi,
Yep, i will update the ng2-demo for using lazy-loading module.
Compodoc seems supporting routing modules and lazy loaded routes with my current test.
The routes page need an update for better clarification between main route and child routes : https://github.com/compodoc/compodoc/issues/17
