### ISSUE TITLE
[BUG] Provide examples for [FEATURE] Add an interactive examples tab

### ISSUE THREAD

**Issue by AhnpGit** [compodoc/compodoc#390]
##### **Overview of the issue**

I'm looking on documentation of compodoc and try to create interactive examples of my Angular 2 components but I couldn't find an example of the file xx.component.example.html

##### **Operating System, Node.js, npm, compodoc version(s)**

angular/cli: "1.5.3",
compodoc/compodoc: "^1.0.4", (local)
typescript: "~2.4.2"
angular 5
node 8.9.1

##### **Motivation for or Use Case**

It would be nice if the documentation for compodoc has more details and how to implement each feature.

**Comment by vogloblinsky** [comment]
Did you read this page ?
The live demo has also an example : https://compodoc.github.io/compodoc-demo-todomvc-angular/components/TodoComponent.html#example

**Comment by AhnpGit** [comment]
I saw that example but it is not clickable.

**Comment by benjamincharity** [comment]
Clickable vs non-clickable is just a matter of what is in the demo.

It's up to the developer to create a working example somewhere like Plunker (or a local file that contains the full working component). Then you simply add the embed url to the docs:

```
/**
 * My component
 *
 * @example
 * <foo-bar
 *              theme="primary"
 *              (click)="myMethod($event)"
 * >Hi!</foo-bar>
 *
 * <example-url>https://embed.plnkr.co/plunk/W1t5Awrg7LLp4tyM?show=preview</example-url>
 */
```

Then that URL will be loaded when you click on the 'examples' tab:

![screen shot 2017-12-20 at 8 31 43 am](https://user-images.githubusercontent.com/270193/34209460-42c747a2-e560-11e7-8c50-ff597c404ede.png)

**Comment by vogloblinsky** [comment]
I will add tonight a complete tutorial explaining all the features of compodoc.

**Comment by jacobmmartin** [comment]
I have tried both this format and the format in the documents and my examples are not showing. 2 days ago I had them working. Any ideas?

**Comment by benjamincharity** [comment]
Can you share some code? Even better if we can pull the repo and try building the docs locally..

Only hiccup I ran into was when I was running the docs on `https` but my demo was a `http` (iframing `http` into an `https` page throws a security error)

**Comment by michael-letcher** [comment]
@vogloblinsky Can this be explained in the website? I'd love to add StackBlitz to the example pages

**Comment by hughanderson4** [comment]
Hi @vogloblinsky 
For a private library that can't host example code on Stackblitz:
How can I reference an example component that lives inside the same project?
Do I need to run 2 servers at the same time?  One for the documentation and a separate one for the Examples?  Or is there a way to make the Documentation site serve my example code?

**Comment by vogloblinsky** [comment]
You can host the documentation in a docs folder, and examples inside an example folder, and link them.

./docs
./examples
