### ISSUE TITLE
[BUG] generated codeblock in doc is not well formatted

### ISSUE THREAD

**Issue by rdkmaster** [compodoc/compodoc#392]
##### **Overview of the issue**

this bug looks like https://github.com/compodoc/compodoc/issues/253, but i think it is not exactly the same one.

the doc in the code is:

![image](https://user-images.githubusercontent.com/16191626/33353960-69c48b7e-d4eb-11e7-97a4-04112bd1880a.png)

but, the generated codeblock is not in a good format:

![image](https://user-images.githubusercontent.com/16191626/33354012-b2642ef2-d4eb-11e7-866e-073c0dd0711b.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

- node 6.10
- npm 3.10

##### **Angular configuration, a `package.json` file in the root folder**

yes

##### **Compodoc installed globally or locally ?**

globally 

##### **Reproduce the error**

try this commend:

```
    /**
     * xxxx yyyy zzzzz
     * ```
     * {
     *     data: [
     *         [11, 12, 13],
     *         [21, 22, 23],
     *         [31, 32, 33]
     *     ],
     *     field: ['field1', 'field2', 'field3'],
     *     header: ['header1', 'header2', 'header3']
     * }
     * ```
     */
```

##### **Related issues**

https://github.com/compodoc/compodoc/issues/253

**Comment by tanepiper** [comment]
Related to #391
