### ISSUE TITLE
[BUG] Error when installing: SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by nfdevil** [compodoc/compodoc#395]
##### **Overview of the issue**

When trying to do:
`npm install -g @compodoc/compodoc`
or on yarn
`yarn global add @compodoc/compodoc`
or a local install on an angular 5.0.1 application
(tried this in both git-bash and PowerShell)

I receive a coffee-script error:

NPM:
`... $ npm install -g @compodoc/compodoc
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
C:\Users\...\AppData\Roaming\npm\compodoc -> C:\Users\...\AppData\Roaming\npm\node_modules\@compodoc\compodoc\bin\index-cli.js

> coffee-script@1.12.8 postinstall C:\Users\...\AppData\Roaming\npm\node_modules\@compodoc\compodoc\node_modules\coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

[eval]:1
'if
^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)
    at evalScript (bootstrap_node.js:462:27)
    at startup (bootstrap_node.js:163:9)
    at bootstrap_node.js:608:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\@compodoc\compodoc\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! coffee-script@1.12.8 postinstall: `node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the coffee-script@1.12.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    ...\_logs\2017-11-30T11_15_39_557Z-debug.log`

Yarn:

`... $ yarn global add @compodoc/compodoc
yarn global v1.3.2
[1/4] Resolving packages...
warning @compodoc/compodoc > live-server > http-auth > node-uuid@1.4.8: Use uuid module instead
[2/4] Fetching packages...
warning Pattern ["colors@latest"] is trying to unpack in the same destination "C:\\users\\...\\AppData\\Local\\Yarn\\cache\\v1\\npm-colors-1.1.2-168a4701756b6a7f51a12ce0c97bfa28c084ed63" as pattern ["colors@~1.1.2","colors@^1.1.2"

]. This could result in a non deterministic behavior, skipping.
warning Pattern ["object-assign@latest"] is trying to unpack in the same destination "C:\\users\\...\\AppData\\Local\\Yarn\\cache\\v1\\npm-object-assign-4.1.1-2109adc7965887cfc05cbbd442cac8bfbb360863" as pattern ["object-assign@^4

.0.1","object-assign@^4.1.0","object-assign@^4.1.0","object-assign@^4.1.1","object-assign@^4"]. This could result in a non deterministic behavior, skipping.
warning Pattern ["send@latest"] is trying to unpack in the same destination "C:\\users\\...\\AppData\\Local\\Yarn\\cache\\v1\\npm-send-0.16.1-a70e1ca21d1382c11d0d9f6231deb281080d7ab3" as pattern ["send@0.16.1"]. This could result in a non deterministic behavior, skipping.
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠄ uglifyjs-webpack-plugin
[2/2] ⠄ coffee-script
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
error C:\users\...\AppData\Local\Yarn\config\global\node_modules\csextends\node_modules\coffee-script: Command failed.
Exit code: 1
Command: node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"

; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn

("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + res

et + "."); console.warn(""); }'
Arguments:
Directory: C:\users\...\AppData\Local\Yarn\config\global\node_modules\csextends\node_modules\coffee-script
Output:
[eval]:1
'if
^^^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:635:30)`

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Windows 10 Enterprise N 2016 LTSB
Node: 8.9.1
npm: 5.4.2
yarn: 1.3.2

##### **Compodoc installed globally or locally ?**

Trying both global and local installs, neither work

**Comment by karloscode** [comment]
Same issue here!!

**Comment by felipebri23** [comment]
I have the same issue

**Comment by vogloblinsky** [comment]
@karloscode @felipebri23 
Can i have ?
Node, npm, OS versions
Thanks

**Comment by karloscode** [comment]
We can use in local development changing the package.json but no work with CI

**Comment by vogloblinsky** [comment]
I don't use directly coffeescript inside compodoc.
Which dependency is related to that ? @KenVanGilbergen ?

**Comment by karloscode** [comment]
Yes , is in shelljs

https://github.com/shelljs/shelljs/blob/master/package.json

**Comment by vogloblinsky** [comment]
Yes it is a dev-dependency inside shelljs.

Here is the main issue inside coffeescript : https://github.com/jashkenas/coffeescript/issues/4805

No clear solution.

I will try to find a cleaner alternative.

**Comment by vogloblinsky** [comment]
After searching inside codebase, shelljs seems to not be used anymore. I remove the dependency.

Everyting will be fine with next release.
