### ISSUE TITLE
.documentation folder is not available error

### ISSUE THREAD

**Issue by yfain** [compodoc/compodoc#397]
I just installed compodoc and ran ```compodoc src -s``` from the root of my Angular 5 project (it's generated using Angular CLI). Got this error:

```
1.0.5

Node.js version : v8.1.3

Operating system : OS X El Capitan

[06:49:31] ./documentation/ folder doesn't exist
```

**Comment by vogloblinsky** [comment]
Did you generate the documentation before ?

```
compodoc -p src/tsconfig.json
```

**Comment by yfain** [comment]
No, this is the first time I generated the doc. I just followed the instructions in Getting Started:

```
# Install compodoc with npm
$ npm install -g @compodoc/compodoc
# Run compodoc in your project and serve it
$ compodoc src -s
```

**Comment by vogloblinsky** [comment]
Thanks, i have updated the page.

**Comment by yfain** [comment]
This is not correct: ```compodoc -p src/tsconfig.json```
This is correct: ```compodoc -p ./tsconfig.json```

**Comment by vogloblinsky** [comment]
Yes but the one inside src should work too : tsconfig.app.json

**Comment by RakeshGowdaM** [comment]
# Install compodoc with npm
$ npm install -g @compodoc/compodoc
# Run compodoc in your project and serve it
$ compodoc src -s

compodoc -p ./tsconfig.json

no one the documents are getting generated and document folder remain empty, and getting below message

Serving documentation from ./documentation/ at http://127.0.0.1:8080

**Comment by vogloblinsky** [comment]
Do you try ? 

```
compodoc -p ./tsconfig.json -s
```
