### ISSUE TITLE
[FEATURE] SCSS Language codeblock support

### ISSUE THREAD

**Issue by Epenance** [compodoc/compodoc#398]
##### **Overview of the issue**

It would be awesome if we could have SCSS support, as Compodoc uses Prism it shouldnt be hard to add.

##### **Motivation for or Use Case**

We use Compodoc to generate our documentation for all of our application, including our styleguide and having SCSS support would make it far easier to skim through and understand rather than just a "grey" code box.

**Comment by vogloblinsky** [comment]
Did you mean another "source" tab with css, or scss sourcecode ?

**Comment by Epenance** [comment]
Simply just and update to the prism include to include SCSS support.

Ill make a pull request shortly :-)
