### ISSUE TITLE
[FEATURE] : Version selector

### ISSUE THREAD

**Issue by frederikschubert** [compodoc/compodoc#40]
It would be great if there was an option to generate the documentation for a specific version of the project.
Then there could be a select box to switch between the different versions. See [here](http://ionicframework.com/docs/v2/api/) for an example.

**Comment by vogloblinsky** [comment]
@frederikschubert this can be implemented, but the responsability of linking each version to different folders will be on project developer.
compodoc doesn't handle history version.

**Comment by vogloblinsky** [comment]
No, but i think i could implement the same behavior like ionic very easily.

**Comment by softEngJason** [comment]
It would be super appreciated to add this @vogloblinsky !!
