### ISSUE TITLE
[BUG] Children support for routes definition (Route parsing error)

### ISSUE THREAD

**Issue by khoying** [compodoc/compodoc#400]
Release 1.0.5 appears to fix some parsing errors when using dynamic values for route attributes.  A fix for the bug: https://github.com/compodoc/compodoc/issues/216

As mentioned in the 216 bug, the fix at this time is only for "path" and "pathMatch" attributes with support for other attributes being added later.  Excellent!  I will be looking forward to that.

However in the meantime, wanted to let you know that the fix for 216 does not seem to be working for "path" and "pathMatch" attributes defined inside a "children" attribute of the route.

Thanks!

**Comment by vogloblinsky** [comment]
Hi,
No i need to add a recursive parsing loop for handling attributes like "data" or "children" to fix dynamic values inside them.
Keep in touch.

**Comment by attilacsanyi** [comment]
Any deadline on this @vogloblinsky? I using lots of routes from enums, and I have to disable doc generation due to this. Appreciate your help.

**Comment by vogloblinsky** [comment]
I have to figure out the recursive scanning of routes definitions and enums etc.
I am working on it these days.
