### ISSUE TITLE
[BUG] Output - type of $event partly incorrect

### ISSUE THREAD

**Issue by pfoedermayr** [compodoc/compodoc#401]
##### **Overview of the issue**

The type of the `$event` variable of an output property is `EventEmitter<type>` instead of `type`.

````ts
/**
 * Fires each time the active index changes.
 */
@Output() activeIndexChange: EventEmitter<number>;
````

![image](https://user-images.githubusercontent.com/17589486/33594090-d03d1b36-d992-11e7-945c-7cbd9d2ef4fe.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

**OS:** Win7 64bit
**Node:** 6.11.0
**npm:** 3.10.10
**compodoc:** 1.0.5

##### **Angular configuration, a `package.json` file in the root folder**

**Angular:** 5.0.5
**TypeScript:** 2.4.2

##### **Compodoc installed globally or locally ?**

globally

##### **Motivation for or Use Case**

The type of the outputs event variable should be shown correctly.

#### **Reproduce the error**

Add the code snipped provided above to a component.

##### **Related issues**

#60

**Comment by vogloblinsky** [comment]
@pfoedermayr can you explain what rendering do you expect ? i don't understand you issue.
This project use Compodoc and it seems ok for them : https://mattlewis92.github.io/angular-calendar/docs/components/CalendarDayViewComponent.html

**Comment by pfoedermayr** [comment]
@vogloblinsky IMHO this is (only) an issue if you are not too familiar with angular and how it works.
We faced this at work a few times, some new folks were typing the event type of an output as `EventEmitter<number>` instead of `number`.

#### Sample Component
````ts
@Component({ selector: 'my-component' })
export class MyComponent {
    @Output()
    activeIndexChange: EventEmitter<number>; // the type of activeIndexChange is EventEmitter<number>
}
````

#### Usage
````html
<my-component
    (activeIndexChange)="onActiveIndexChange($event)"> <!-- the type of $event is number -->
</my-component>
````

Right now compodoc renders the following inside the Output-section:
`$event type: EventEmitter<number>`
But if you look at it from the html-side (see the Usage example) I think
`$event type: number`
would be clearer / would make sense.

Thanks for your response, let me know if there are any open questions.
And by the way **this is an awesome project, keep up the good work**.

**Comment by vogloblinsky** [comment]
Sorry @pfoedermayr but i prefer having a generic way to handle typing with TypeScript and not adding specific switch for particular classes related to one framework.
