### ISSUE TITLE
[BUG] Unable to generate doc for routing based on environment variable 

### ISSUE THREAD

**Issue by priteshkapuriya** [compodoc/compodoc#402]
##### **Overview of the issue**

So I have implemented routes based on environment variable and compodoc fails to generate doc for the same,

I have environment.ts decides if its "webadmin" or "userportal" based on that it will load the routes for the webadmin or userportal

Unhandled Rejection at: Promise {
  <rejected> { SyntaxError: Syntax error at line 1 column 11 of the JSON5 data. Still to read: "[\"environment\".\"appl"
    at error (/home/cyberoam/pritesh/git/picasso-develop/ui/node_modules/json5/lib/json5.js:56:25)
    at Object.parse (/home/cyberoam/pritesh/git/picasso-develop/ui/node_modules/json5/lib/json5.js:511:13)
    at loopModulesParser (/home/cyberoam/pritesh/git/picasso-develop/ui/node_modules/@compodoc/compodoc/dist/index-cli.js:810:48)

##### **Operating System, Node.js, npm, compodoc version(s)**

Operating System : Ubuntu 14.04 LTS,
Node.js : v8.6.0
compodoc version : 1.0.5
 
##### **Angular configuration, a `package.json` file in the root folder**
attached
[package.json.zip](https://github.com/compodoc/compodoc/files/1538249/package.json.zip)

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

Unable to generate doc with current version

##### **Reproduce the error**

Install compodoc locally
run compodoc from ng cli using npm run compodoc

##### **Related issues**

No

**Comment by vogloblinsky** [comment]
Can i have an extract of the code for the routing file and the environment.ts for debugging ?

**Comment by priteshkapuriya** [comment]
sure attaching here.
[environments.zip](https://github.com/compodoc/compodoc/files/1538362/environments.zip)

**Comment by priteshkapuriya** [comment]
@vogloblinsky  
Did you got chance to look into this one, let me know in case you need any details from me.

**Comment by vogloblinsky** [comment]
Yes i will look that this week.
