### ISSUE TITLE
[BUG] baseUrl not taken in account ?

### ISSUE THREAD

**Issue by lpenet** [compodoc/compodoc#403]
##### **Overview of the issue**

It seems to me that the baseUrl property of the tsconfig.json file is not taken in account.

##### **Operating System, Node.js, npm, compodoc version(s)**

Debian GNU/Linux sid. Node v8.9.1. yarn 1.3.2. compodoc 1.0.5. typescript 2.4.2.

##### **Compodoc installed globally or locally ?**

Compodoc is installed globally.

##### **Motivation for or Use Case**

I have two source roots in my project :
* app
* common-package
So, I use "baseUrl": "." in tsconfig.json, so that I can do things like

    import {Symbol} from "package/subpackage";

compodoc analyses what is in app, but not what is in common-package.

I suppose it is not enforcing the "baseUrl" property.

**Comment by vogloblinsky** [comment]
Yes we don't use this property.
Did you a few minutes to setup just a little example with the CLI for reproducing this scenario and handle it ?
Thanks

**Comment by kpaxton** [comment]
Would love to use your product but I can't due to the same reason above. I use ```baseUrl``` as well but mine is set to ```src``` in our angular project. This allows me to use ```app\...``` in the import references instead of always using relative paths. 

Any idea on when you might put this in place?

**Comment by brian428** [comment]
Just a +1 on this. The relative imports always drove me crazy until I discovered the tsconifg path/baseUrl. Unfortunately, using it breaks compodoc.

**Comment by kpaxton** [comment]
@vogloblinsky I haven't tried this yet within an [NX Workspace](https://github.com/nrwl/nx) but they definitely use the idea of TSConfig Paths to use in import statements.  You might be able to an NX Workspace as an example of what we are talking about.

**Comment by vogloblinsky** [comment]
@kpaxton ok nice, i will look that asap

**Comment by brian428** [comment]
Sorry, if you just need an example of a tsconfig that uses this, I can append one here. I think you’ll get the jist immediately. It should be pretty straightforward path replacement to account for.

**Comment by vogloblinsky** [comment]
@brian428 A must-have is an Angular CLI fresh project with just 1-2 modules, 2-3 components, 1-2 services. Thanks by advance

**Comment by brian428** [comment]
Let me know if this helps. It's a fairly basic NX workspace that uses tsconfig paths to reference the libs/core module using `@nx-test/core`.
[nx-test.zip](https://github.com/compodoc/compodoc/files/1904000/nx-test.zip)

**Comment by davidmpaz** [comment]
I am also affected by this I think. In my case I have an ionic application with several `paths` defined inside a `yarn workspace`, the whole app is the workspace. So my config looks like:
```
....
        "baseUrl": ".",
        "paths": {
            "@namspace/module1": [
                "modules/module1/src/index"
            ],
            ....
            ....
            "@namspace/moduleN": [
                "modules/moduleN/src/index"
            ]
        }
....
```
looking forward to have this feature in main stream

Cheers

**Comment by brian428** [comment]
@vogloblinsky Just wondering if you've made any progress on this?

**Comment by vogloblinsky** [comment]
@brian428 no i didn't take the time. Your quick nx-test should help. I will look that asap.

**Comment by brian428** [comment]
@vogloblinsky I noticed that #596 was closed. Will that also take care of this issue?

**Comment by saeidzebardast** [comment]
@vogloblinsky Any progress or news?

**Comment by kpaxton** [comment]
I just updated my app to Angular6 with Nrwl/NX 6 and my config looks similar to what @davidmpaz stated above. Many different ```paths``` declared pointing to ```libs/lib/src/index.ts``` files. These are used in the components like: ```import { Class } from '@namespace/lib'. I end up getting an error trying to build all of them using the technique in the comment here: [275](https://github.com/nrwl/nx/issues/275#issuecomment-366720087).

I get:
```
Error: File not found: /{path}/libs/services/service/src/lib/@namespace/lib.ts
```
So it's not recognizing the ```paths``` option in the tsconfig still.

This is with compodoc v1.1.3.

I have not confirmed, but you should be able to reproduce with the [nx-examples](https://github.com/nrwl/nx-examples) repo and then creating a ```tsconfig.compodoc.json``` which ```includes: [apps/**/*.ts, libs/**/*.ts]```

mind you, this is about the ```paths```  issues, not ```baseUrl``` but I'm assuming they are the same issue.

**Comment by vogloblinsky** [comment]
@kpaxton Just restarted working on this issue. I started with nx-examples and added a tsconfig.compodoc.json file which includes "apps/**/*.ts" and "libs/**/*.ts".
No problem for me, compodoc didn't break.

@brian428 no errors for me with your nx-test sample.

**Comment by kpaxton** [comment]
@vogloblinsky I just tried again, seems to work now. You must have updated something in some later releases that fixed it. Thanks!

**Comment by brian428** [comment]
Hmm it's still not working for me with 1.1.5. Still getting an error like this (I have to sanitize the actual values here, but this should get the idea across):

```
Unhandled Rejection at: Promise {
  <rejected> { Error: File not found: C:/Developer/Projects/project1/src/app/@myclient/myapp/profile/profile.routes.ts
```

It's dying while parsing a very early file (app.routes.ts). The import within app.routes.ts looks like:
`import { ProfileRoutes } from "@myclient/myapp/profile/profile.routes";`

`ProfileRoutes` is just a `const` with an array of `Route` objects.

And within my tsconfig I have:
```
"compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "@myclient/myapp/*": [ "app/*" ]
    },
}
```

So as you can see, it's getting confused while trying to determine the path to the imported file. Looks like it's building the file path without taking into account/translating the `baseUrl` or `path` entry.

I'll see if I can create a better test app to reproduce this, because it looks like the simple nx-test example isn't cutting it.

**Comment by vogloblinsky** [comment]
@brian428 ok seems related to the codebase for dynamic variable inside routing.
The test project with baseurl configured works fine, but i miss to add this kind of scenario.
Keep in touch.

**Comment by brian428** [comment]
OK here's a basic app that demonstrates the problem. Just run `npm run compodoc` to see the file not found error. Let me know if this gets you on the right path to tracking down the problem. Thanks.
[paths_bug_app.zip](https://github.com/compodoc/compodoc/files/2377052/paths_bug_app.zip)

**Comment by brian428** [comment]
Just curious if this fix is still slated for the 1.1.7 release?

**Comment by brian428** [comment]
@vogloblinsky Did this fix make it into 1.1.7?

**Comment by brian428** [comment]
Just to add, in case it helps at all: one workaround for this is to use only relative imports for route constants. Once I switched these to relative imports (instead of using the path alias), Compodoc could find them.

In other words, this fails:
```
import { SomeRoutes } from "@company/project/user/user.routes";
```

But this works:
```
import { SomeRoutes } from "./user/user.routes";
```

So it's definitely an issue with path aliases being used to import an exported Routes const. Oddly, this **only** seems to affect Route imports. Everywhere else that I use the path alias in my imports, Compodoc seems to handle just fine. Hopefully that helps narrow down the problem a bit.

**Comment by westor21** [comment]
As I also reported already in #593 - this problem is still not solved for me.
No real fix available? Relative paths are not an option.

**Comment by Diegodlt** [comment]
Was this ever fixed?

**Comment by brian428** [comment]
As far as I know, it was never fixed, unfortunately.

**Comment by Veritread-Diego** [comment]
@brian428 Were you ever able to get around this issue?

**Comment by Diegodlt** [comment]
@brian428 Were you ever able to get around this issue?

**Comment by brian428** [comment]
Only by using the relative path imports for Route constants that I mentioned earlier in the thread.

**Comment by ReyOrtiz** [comment]
Is **compodoc** being actually maintained? This issue has been reported multiple times but I can't find any comment say that is going to be fixed.

**Comment by Diegodlt** [comment]
@ReyOrtiz I created a new bug, along with a sample project that replicates the bug, and it currently has an "accepted" status.

**Comment by ReyOrtiz** [comment]
@Diegodlt, oh, I see it. I will track it. Thanks!
