### ISSUE TITLE
documentation folder not generated

### ISSUE THREAD

**Issue by crh225** [compodoc/compodoc#41]
Hello, I have installed compodoc, and ran the command to generate the docs. it looks like it is working but no documentation folder is generated.

![image](https://cloud.githubusercontent.com/assets/19475195/21440053/b1b1f978-c856-11e6-984d-e3752b85c240.png)

**Comment by crh225** [comment]
here is my tsconfig
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "moduleResolution": "node",
    "skipDefaultLibCheck": true
  },
  "exclude": [
    "./node_modules",
    "./typings/main.d.ts",
    "./typings/main",
    "./typings/custom-signalr.d.ts"
  ],
  "filesGlob": [
    "./client/modules/**/*.ts",
    "./client/platform/**/*.ts",
    "!./node_modules/**",
    "./client/custom-typings.d.ts",
    "./typings/index.d.ts"
  ],
  "compileOnSave": false,
  "buildOnSave": false,
  "awesomeTypescriptLoaderOptions": {
    "useWebpackText": true
  }
}

**Comment by crh225** [comment]
here is my routes
```
import { RouterModule } from '@angular/router';
import { CoreRoutes } from './shared/models/core.models';
import { AuthService } from './shared/services/auth.service';
import { AuthGuardService } from './shared/services/auth-guard.service';
import { config } from './app.constants';



export const routes: CoreRoutes = [
    { path: '', redirectTo: 'home', pathMatch: 'full', appData: config.APPDATA_WEBAPI },

  // Lazy async modules
  {
      path: 'swagger',
      canActivate: [AuthGuardService],
      appData: config.APPDATA_WEBAPI,
      loadChildren: () => new Promise(resolve => {
          (require as any).ensure([], (require: any) => {
              resolve(require('./+swagger/swagger.module').SwaggerModule);
          });
      })
  },
  {
      path: 'testbed',
      canActivate: [AuthGuardService],
      appData: config.APPDATA_WEBAPI,
      loadChildren: () => new Promise(resolve => {
          (require as any).ensure([], (require: any) => {
              resolve(require('./+testbed/testbed.module').TestbedModule);
          });
      })
  },
  {
      path: 'profile',
      canActivate: [AuthGuardService],
      appData: config.APPDATA_WEBAPI,
      loadChildren: () => new Promise(resolve => {
        (require as any).ensure([], (require: any) => {
            resolve(require('./+profile/profile.module').ProfileModule);
        });
    })
  },
  {
      path: 'security',
      canActivate: [AuthGuardService],
      appData: config.APPDATA_WEBAPI,
      loadChildren: () => new Promise(resolve => {
          (require as any).ensure([], (require: any) => {
              resolve(require('./+security/security.module').SecurityModule);
          });
      })
  },
  {
      path: 'error',
      canActivate: [AuthGuardService],
      appData: config.APPDATA_WEBAPI,
      loadChildren: () => new Promise(resolve => {
          (require as any).ensure([], (require: any) => {
              resolve(require('./+error/error.module').ErrorModule);
          });
      })
  }
];
export const authProviders = [
    AuthGuardService,
    AuthService
];
export const routing = RouterModule.forRoot(routes);

```

**Comment by vogloblinsky** [comment]
Watching your console logs, the problem is in NavigatorComponent.
Can you paste the code if possible ?

**Comment by crh225** [comment]
I can next Tuesday. I'm out for the holidays and don't have access to the source code. Great work!

**Comment by crh225** [comment]
Is it odd that I am using @injectable componenets?

**Comment by manekinekko** [comment]
@crh225 Components can not be Injectable. Only services can. You can mix and match `@Component()` with `@Injectable()`.

**Comment by vogloblinsky** [comment]
Yes @crh225, @manekinekko is right, i will try to emit a warning for that case.

**Comment by crh225** [comment]
@vogloblinsky, @manekinekko, thanks for teaching me more about angular in the process!

**Comment by crh225** [comment]
To confirm, that was the issue. It did not like injectable in the component.

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/21526263/798b8f6e-cce8-11e6-92ad-7760d71f1ce6.png)
 one hour later....fyi Im using yarn and offline npm packages. Probably my fault still

**Comment by crh225** [comment]
going to add angular2-dependencies-graph globally in yarn and retry.

**Comment by crh225** [comment]
@vogloblinsky, The documentation folder did get generated. 

I have some feedback for enhancements. Is there way to make the menu navigation show/hide based on when you click the menu title? we use generated classes, one class for every db table and needless to say the list is very long. it would be helpful to be able to hide the list.
![image](https://cloud.githubusercontent.com/assets/19475195/21526599/f3d5861a-ccea-11e6-8f63-a9493315b4a9.png)

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/21526741/0f71c5d6-ccec-11e6-8041-d1cd8d6bc139.png)
It is still giving me this issue now. When I type in ngd -h in command window it just closes.

**Comment by crh225** [comment]
Im closing again. Sorry. I have to move on. I will pick this back up in the future when I get better at yarn. We just changed over to use npm offline packages and yarn. Im sure it is something I did.

**Comment by vogloblinsky** [comment]
@crh225, yep for the closing item in the menu, it is on my todo list

**Comment by vogloblinsky** [comment]
For yarn support, it is a known issue : https://github.com/compodoc/compodoc/issues/23
Watching and waiting from yarn side to fix it.

**Comment by vogloblinsky** [comment]
@crh225 toggle buttons int he menu added in last release ;)
