### ISSUE TITLE
[FEATURE]Improve stability by commiting package-lock.json

### ISSUE THREAD

**Issue by zamber** [compodoc/compodoc#413]
##### **Overview of the issue**

`package-lock.json` should be committed to ensure build stability. This is particularly bad for end users and probably is responsible for most of the issues reported.

##### **Operating System, Node.js, npm, compodoc version(s)**
any

##### **Angular configuration, a `package.json` file in the root folder**
There's no point in getting a users `package.json`, the compodoc version will be enough to get the same exact dependencies after commiting `package-lock.json`.

Also read https://stackoverflow.com/a/44210813/1225741

##### **Compodoc installed globally or locally ?**
Both.

##### **Motivation for or Use Case**
Compodoc broke for me and I started digging.

##### **Reproduce the error**

Not exactly a reproduction, more of a proof for cache collisions:

1. Remove all compodoc installations.
2. Clean the npm cache by hand (or do it in a throw-away VM)
3. `npm install compodoc -g`
4. Checkout repo and go to it.
5. `npm install`

You should get something like:

    ~/D/G/compodoc ❯ npm install                                                                                                                                               develop
    Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/zamber/.npm/_cacache/content-v2/sha512/40/a2'

    Unhandled rejection Error: EACCES: permission denied, open '/Users/zamber/.npm/_cacache/index-v5/3e/31/2197cee77b5d2211a8232dcec6293cd77f90f8b6b7672f245ae7fb40883a'

    Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/zamber/.npm/_cacache/content-v2/sha512/80/88'

    Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/zamber/.npm/_cacache/index-v5/10/3c'

    Unhandled rejection Error: EACCES: permission denied, mkdir '/Users/zamber/.npm/_cacache/content-v2/sha512/7b/59'ES: permission denied, mkdir '/Users/zamber/.npm/_cacache/index-v5/e3

##### **Related issues**

None that I could find. Probably noone noticed it before.

##### **Suggest a Fix**

Commit `package-lock.json` __every time it changes__. This will not impede your development speed in any way, nor contanimate seach results (at least not too much).

Make a point of it in the README too if need be.

I can do that but It's such a simple fix that anyone can do it.

Note that for releases it's possible to have the same benefits with shrinkwrap. More details are in the SO answer linked above.

**Comment by vogloblinsky** [comment]
For sure, it is done now :smile:

**Comment by zamber** [comment]
Nice time ;).
