### ISSUE TITLE
[BUG] Memory error during main graph generation

### ISSUE THREAD

**Issue by Karankang007** [compodoc/compodoc#414]
##### **Overview of the issue**

An error is thrown while generating the main graph:
```
[08:40:15] Process main graph
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
[08:40:16] Ooops error during main graph generation, moving on next part with main graph disabled : : abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than
the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:27:15589)
    at stackTrace (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:27:15760)
    at abort (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:50:6350)
    at abortOnCannotGrowMemory (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:27:16630)
    at enlargeMemory (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:27:17075)
    at H6 (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:43:12336)
    at k6 (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:42:105869)
    at IK (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:35:82215)
    at HK (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:35:82147)
    at mV (C:\Development\Web UI\Main\Test.App\node_modules\viz.js\viz.js:36:137849)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Windows 10x64
RAM: 16GB
Node: 6.11.3
NPM: 3.10.10

##### **Angular configuration, a `package.json` file in the root folder**
package.json:
```
...
"dependencies": {
    "@angular/animations": "~5.1.1",
    "@angular/cdk": "5.0.1",
    "@angular/common": "~5.1.1",
    "@angular/compiler": "~5.1.1",
    "@angular/core": "~5.1.1",
    "@angular/flex-layout": "~2.0.0-beta.12",
    "@angular/forms": "~5.1.1",
    "@angular/http": "~5.1.1",
    "@angular/material": "5.0.1",
    "@angular/platform-browser": "~5.1.1",
    "@angular/platform-browser-dynamic": "~5.1.1",
    "@angular/router": "~5.1.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "~2.5.3",
    "date-fns": "^1.29.0",
    "fuse.js": "^3.2.0",
    "hammerjs": "^2.0.8",
    "lodash": "~4.17.4",
    "object-hash": "~1.2.0",
    "quagga": "^0.12.1",
    "quirc-js": "^1.1.2",
    "rxjs": "~5.5.5",
    "web-animations-js": "^2.3.1",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "~1.6.1",
    "@angular/compiler-cli": "~5.1.1",
    "@angular/language-service": "~5.1.1",
    "@compodoc/compodoc": "~1.0.5",
    "@types/chance": "~0.7.35",
    "@types/fuse": "~2.5.2",
    "@types/jasmine": "~2.8.2",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "~4.14.91",
    "@types/node": "~8.5.1",
    "@types/object-hash": "~1.1.0",
    "@types/tinycolor2": "~1.4.0",
    "ajv": "^5.5.2",
    "chance": "~1.0.12",
    "codelyzer": "~4.0.2",
    "cpx": "~1.5.0",
    "cross-env": "~5.1.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "~1.3.0",
    "karma-html-reporter": "^0.2.7",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "~0.2.2",
    "karma-junit-reporter": "^2.0.0",
    "karma-spec-reporter": "~0.0.32",
    "karma-tfs-reporter": "^1.0.1",
    "ngx-i18nsupport": "~0.9.0",
    "npm-run-all": "~4.1.2",
    "protractor": "~5.2.2",
    "replace": "^0.3.0",
    "replace-in-file": "^3.0.0",
    "rimraf": "~2.6.2",
    "rxjs-tslint-rules": "^3.3.0",
    "tinycolor2": "~1.4.1",
    "ts-node": "~4.0.2",
    "tslint": "~5.8.0",
    "typescript": "2.4.2"
  }
```

##### **Compodoc installed globally or locally ?**
Locally

**Comment by vogloblinsky** [comment]
Compodoc breaks or continue to work ?

**Comment by Karankang007** [comment]
Compodoc continues to work.

**Comment by vogloblinsky** [comment]
Will be replaced in next versions by dynamic graph, see https://github.com/compodoc/compodoc/issues/234 for information.

**Comment by javafrog** [comment]
We are having the same problem, however, it breaks compodoc and we do not get any results. We can only get it to work by manually excluding some packages from the generation. Disabling graph generation via parameter does not seem to work, we run into the same error.

Can you provide a shorter term fix instead?

**Comment by vogloblinsky** [comment]
@javafrog Even if you disable graph generation, can i have more informations where it breaks ? Terminal logs ? (here or by email)

**Comment by javafrog** [comment]
Here's the log (somewhat cleaned up)

> <--- Last few GCs --->
[5676:0000020232EDB330]    35103 ms: Mark-sweep 1399.3 (1485.4) -> 1399.3 (1485.9) MB, 192.6 / 0.0 ms  allocation failure GC in old s
pace requested
[5676:0000020232EDB330]    35331 ms: Mark-sweep 1399.3 (1485.9) -> 1399.2 (1433.9) MB, 227.6 / 0.0 ms  last resort GC in old space re
quested
[5676:0000020232EDB330]    35559 ms: Mark-sweep 1399.2 (1433.9) -> 1399.2 (1430.9) MB, 227.6 / 0.0 ms  last resort GC in old space re
quested
<--- JS stacktrace --->
==== JS stack trace =========================================
Security context: 0000031C98E25EE1 <JSObject>
    2: replace(this=00000223421B6839 <Very long string[394964]>,000003EA7A275E69 <String[28]: >,000001609
C982201 <Very long string[377557]>)
    4: /* anonymous */ [C:\Users\...\AngularJS\nod
e_modules\@compodoc\compodoc\dist\index-cli.js:2856] [bytecode=000003EA7A275F81 offset=85](thi...
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewRawTwoByteString
 5: v8::internal::Smi::SmiPrint
 6: v8::internal::AllocationSpaceName
 7: v8::internal::SlicedString::SlicedStringGet
 8: v8::internal::compiler::Pipeline::AllocateRegistersForTesting
 9: 00000242377047A1
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! project@0.0.0 doc: `compodoc -p tsconfig.doc.json -s --hideGenerator --disableGraph`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the project@0.0.0 doc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Roaming\npm-cache\_logs\2018-04-24T08_03_14_256Z-debug.log

**Comment by vogloblinsky** [comment]
@javafrog Ok seems more related to the number of files parsed.
Can you supply the statistics table printed in your terminal ?

**Comment by vogloblinsky** [comment]
Yes thanks

**Comment by timwright35** [comment]
Any timeline on this, having same issue as @javafrog. It seems similar to building the app in AOT and having to use node --max_old_space, just no clue how to use that in this.

**Comment by vogloblinsky** [comment]
@timwright35 we have made improvements on the memory issue. The left menu is now a web-component injected at run time in the browser and not during documentation generation.
We will add a minimal mode in next version to give the ability for users to generate the lightest documentation UI. We hope it will help on this memory issue.
The other idea is to change the templating engine to one that's easily scale with very large codebase.

**Comment by timwright35** [comment]
@vogloblinsky Thanks for the information, I managed to get it to work, minus the main app graph generation, with node --max_old_space_size=8192 <path to node>/node_modules/@compodoc/compodoc/bin/index-cli.js

**Comment by javafrog** [comment]
Just wanting to let you know: Using @timwright35's workaround, we were able to get compodoc running for our complete project again.

**Comment by xmtigra** [comment]
the same problem;

 "@compodoc/compodoc": "1.1.5",

`Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
[16:27:44] Ooops error during main graph generation, moving on next part with main graph disabled : : abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.
`

**Comment by seshasui** [comment]
Same problem:

Error during graph generation: : abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

**Comment by queejie** [comment]
Same issue with 1.1.9.

**Comment by amcnulty** [comment]
> @vogloblinsky Thanks for the information, I managed to get it to work, minus the main app graph generation, with node --max_old_space_size=8192 (path to node)/node_modules/@compodoc/compodoc/bin/index-cli.js

This is similar to what worked for me. My version of compodoc is installed globally and not within the node_modules folder of my project so the path to my compodoc was a little different. The exact command that worked for me was as follows.

```bash
node --max-old-space-size=2048 /usr/local/bin/compodoc -p ./tsconfig.doc.json --config=compodoc.json
```
Ignore everything after the /usr/local/bin/compodoc as they are just configuration flags for compodoc. The real issue is getting enough memory allocation for running the documentation generation scripts (which for me 2048 MB was enough).

### System Information ###
* OS: OSX 10.14.6
* node v. 10.16.2
* compodoc v. 1.1.10

**Comment by herod2k** [comment]
> > @vogloblinsky Thanks for the information, I managed to get it to work, minus the main app graph generation, with node --max_old_space_size=8192 (path to node)/node_modules/@compodoc/compodoc/bin/index-cli.js
> 
> This is similar to what worked for me. My version of compodoc is installed globally and not within the node_modules folder of my project so the path to my compodoc was a little different. The exact command that worked for me was as follows.
> 
> ```shell
> node --max-old-space-size=2048 /usr/local/bin/compodoc -p ./tsconfig.doc.json --config=compodoc.json
> ```
> 
> Ignore everything after the /usr/local/bin/compodoc as they are just configuration flags for compodoc. The real issue is getting enough memory allocation for running the documentation generation scripts (which for me 2048 MB was enough).
> ### System Information
> 
>     * OS: OSX 10.14.6
> 
>     * node v. 10.16.2
> 
>     * compodoc v. 1.1.10
Tried both solutions but they don't work for me, I'm still getting the same error. Same node version and compodoc version, but on linux ubuntu 18.04

**Comment by javafrog** [comment]
This problem is still unsolved, there are only workarounds (i.e., disabling graph generation altogether).
Would be glad if there was a fix!

**Comment by dsanthosh411** [comment]
https://github.com/vogloblinsky https://github.com/amcnulty (path to node) means

**Comment by dsanthosh411** [comment]
{
  "name": "dart",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "sw_warroom": "sw-precache --root=dist/warroom --config=generateWorker.warroom.js",
    "sw_mobile": "sw-precache --root=dist/mobile --config=generateWorker.mobile.js",
    "webworker": "node_modules/babel-cli/bin/babel.js src/webworker/worker.js --out-file src/assets/worker.shim.js",
    "compodoc": "compodoc -p src/tsconfig.app.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.13",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "^8.2.13",
    "@angular/compiler": "^8.2.13",
    "@angular/core": "^8.2.13",
    "@angular/forms": "^8.2.13",
    "@angular/material": "^8.2.3",
    "@angular/material-moment-adapter": "^8.2.3",
    "@angular/platform-browser": "^8.2.13",
    "@angular/platform-browser-dynamic": "^8.2.13",
    "@angular/router": "^8.2.13",
    "@ng-bootstrap/ng-bootstrap": "^5.1.4",
    "@sentry/browser": "^5.8.0",
    "@types/bootstrap": "^4.2.2",
    "@types/pdfjs-dist": "^2.1.2",
    "ajv": "^6.9.1",
    "ajv-keywords": "^3.4.0",
    "angular-bootstrap-datetimepicker": "^2.2.1",
    "angular-plotly.js": "=1.3.2",
    "animate.css": "^3.7.0",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "core-js": "^3.4.1",
    "d3": "^5.9.2",
    "dayjs": "^1.8.16",
    "dexie": "^2.0.4",
    "express": "^4.16.4",
    "file-saver": "^2.0.0",
    "hammerjs": "^2.0.8",
    "handsontable": "6.2.2",
    "hashmap": "^2.3.0",
    "imagesloaded": "^4.1.4",
    "jodit": "3.2.27",
    "jodit-angular": "^1.0.81",
    "jquery": "^3.3.1",
    "lodash-es": "^4.17.11",
    "masonry-layout": "^4.2.2",
    "moment": "^2.24.0",
    "moment-es6": "^1.0.0",
    "ng-circle-progress": "^1.4.0",
    "ng-click-outside": "^5.1.1",
    "ng-masonry-grid": "^1.3.0",
    "ng-pick-datetime": "^7.0.0",
    "ng-pick-datetime-moment": "1.0.7",
    "ng2-charts": "2.3.0",
    "ng2-completer": "^3.0.0-beta.2",
    "ng2-nouislider": "^1.7.13",
    "ng2-panzoom": "^2.2.2",
    "ng2-password-strength-bar": "^1.2.3",
    "ng2-pdf-viewer": "^6.0.2",
    "ng2-select": "^2.0.0",
    "ng2-smart-table": "^1.3.5",
    "ngx-contextmenu": "^5.1.1",
    "ngx-infinite-scroll": "^8.0.1",
    "ngx-pinch-zoom": "^1.2.0",
    "ngx-print": "^1.2.0-beta.2",
    "ngx-quill": "^7.3.9",
    "nouislider": "^14.0.3",
    "numbro": "^2.1.1",
    "open-iconic": "^1.1.1",
    "papaparse": "^5.1.0",
    "plotly.js": "^1.47.4",
    "popper.js": "^1.14.7",
    "primeicons": "1.0.0",
    "primeng": "7.0.5",
    "qrcode": "^1.3.3",
    "quill": "^1.3.6",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.5.3",
    "ts-enum-util": "^4.0.0",
    "tslib": "^1.9.0",
    "url-parse": "^1.4.4",
    "workbox-sw": "^4.3.1",
    "worker-loader": "^2.0.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.18",
    "@angular/cli": "^8.3.18",
    "@angular/compiler-cli": "^8.2.13",
    "@angular/language-service": "^8.2.13",
    "@compodoc/compodoc": "^1.1.11",
    "@types/d3": "^5.7.1",
    "@types/jasmine": "^3.3.9",
    "@types/jquery": "^3.3.29",
    "@types/node": "^12.12.7",
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "codelyzer": "^5.0.1",
    "copyfiles": "^2.1.0",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.0.0",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "node-sass": "^4.13.0",
    "protractor": "^5.4.2",
    "puppeteer": "^2.0.0",
    "sw-precache": "^5.2.1",
    "ts-node": "^8.0.2",
    "tslint": "^5.12.1",
    "typescript": "3.4.5",
    "webpack": "^4.39.2",
    "workbox-build": "^4.3.1",
    "workbox-cli": "4.3.1"
  }
}

**Comment by KimBum** [comment]
After having these issues myself, I realized that it was because I had not actually installed compodoc globally or locally. Sadly there is still a tag in npm for just `compodoc` as a package, which points to version 0.0.41 for Angular 2.

Since the documentation advises you to have the following script in your package.json `"compodoc": "npx compodoc -p src/tsconfig.app.json"`, following it will automatically cause you to not actually install the current version, but hotloading that 0.0.41 package which obv. still contains the memory bug.

The official documentation still mentions the command `npx compodoc` fairly often, so maybe this "just" needs updating. And also maybe someone could get rid/deprecate that old npm package, which just causes confusion with the official @compodoc/compodoc repo.


Hopefully this was/is helpfull to someone~

**Comment by fassn** [comment]
>
> The official documentation still mentions the command `npx compodoc` fairly often, so maybe this "just" needs updating. And also maybe someone could get rid/deprecate that old npm package, which just causes confusion with the official @compodoc/compodoc repo.

No unfortunately, I am also facing the same issue and I do have the latest version installed.

**Comment by fassn** [comment]
I found a way to fix this error: You need to edit the viz.js file in your compodoc installation. ex: if installed globally, it can be located at _/usr/local/lib/node_modules/@compodoc/compodoc/node_modules/viz.js_
Get to the `Module["TOTAL_MEMORY"]||16777216` line and replace the value by the double for instance: `Module["TOTAL_MEMORY"]||33554432`.

In my case, it runs fine even though it gives me the following error instead:
`(node:24446) V8: /usr/local/lib/node_modules/@compodoc/compodoc/node_modules/viz.js/viz.js:33 Invalid asm.js: Function definition doesn't match use`

But in the end, it's pretty worthless, in my case the overview graph is very very small and you can't really zoom in that much.

Anyway, hope that can be useful to someone until a proper fix is released.
