### ISSUE TITLE
[FEATURE] Hide Accessor

### ISSUE THREAD

**Issue by tezine** [compodoc/compodoc#415]
##### **Overview of the issue**

It would be nice to have an option to ignore Accessors. 
Let's say I have the following Accessor:

```
@Input('font.family')
  protected set setFontFamily(family:string){
    this._fontFamily=family;
  }
```

Since I'd like to developers use only [font.family]='something', the Accessor shouldn't be documented. Only the Input should be documented. 

My suggestion is to implement one of the options below: 

1) Ignore Accessors marked as protected.
2) Add an option --disableAccessors 
3) Or maybe ignore the Accessor by using @ignore

**Comment by vogloblinsky** [comment]
```
/**
 * @ignore
 */
```
should do the job
