### ISSUE TITLE
[FEATURE] Try to detect type annotation based on default values

### ISSUE THREAD

**Issue by Sibiraj-S** [compodoc/compodoc#419]
Example
```
title = 'Hello World';
```
Here the type annotation is not provided as a string but mentioning that is trivial. Currently in docs. the type is mentioned only when type annotation is provided. this could be detected automatically based on default values.

**Comment by kingcody** [comment]
@vogloblinsky, @Sibiraj-S Is there currently any work being done on this or is it free to pick up?

**Comment by ukaaa** [comment]
Is this supposed to work for the type of Inputs? It fails for me for the boolean Input below:

```ts
@Input() removable = false;
```
results in:
```ts
{
    "name": "removable",
    "defaultValue": "false",
    "line": 13
    // <-- type is not present
}
```
