### ISSUE TITLE
Bug: double forward slash causes graph generation error

### ISSUE THREAD

**Issue by flashdave1973** [compodoc/compodoc#43]
![compodoc-16](https://cloud.githubusercontent.com/assets/7192793/21583886/931ec604-d061-11e6-9e9f-657285882006.jpg)

Should double forward slashes be treated as a single line comment?

I believe this causes a previously referenced [graph error](https://github.com/compodoc/compodoc/issues/23).
![compodoc-17](https://cloud.githubusercontent.com/assets/7192793/21583900/fcdaf612-d061-11e6-9d1e-c0a6bb48264a.jpg)

**Comment by flashdave1973** [comment]
in any event lines 18 & 20 - 26 should not be commented out

**Comment by vogloblinsky** [comment]
@flashdave1973 how did you install compodoc ? npm or yarn ?
what is your environment ?
i just added this code in the ng2 demo project, and generate the doc on mac without problem : 

```
import {
    Pipe,
    PipeTransform
} from '@angular/core';
import * as moment from 'moment';

@Pipe({
    name: 'dateDisplayFormat'
})

/**
 * implementation of DateDisplayFormatPipe : format birth date values for display in UI
 */

export class DateDisplayFormatPipe implements PipeTransform {
    transform(value: string) : string {
        // is defined ?
        if (value) {
            // TODO: replace with angular2localization implementation later
            return moment(value).locale('en-US').format('M/DD/YYYY');
        } else {
            return 'NA';
        }
    }
}
```

**Comment by flashdave1973** [comment]
I am on windows 7, Installed with `npm` v4.0.5 &  `node` v6.9.1. The only error I get is the graph error. However every component, service, module, pipe or any other file that contains a double quoted comment.... the docs comment out ever line there after.
![compodoc-18](https://cloud.githubusercontent.com/assets/7192793/21591835/e04e3210-d0d5-11e6-89ed-5d95604362e6.jpg)

**Comment by flashdave1973** [comment]
So it looks like I have 2 issues... I may have found the culprit behind one of them.....

the erros in the console screenshot points to an invalid path...
`C:\inetpub\NodeJsServer\LogistiCAD\LogistiCAD Web UI` is the actualy path to my project... however the error does not show the complete path.... seems it does not like the space in my folder name

**Comment by flashdave1973** [comment]
Update: removed the spaces in my project path folder and I am no longer getting an Error during graph generation. 

Having noticed  `// unsupported comment`, ill go ahead and close this ticket

**Comment by vogloblinsky** [comment]
@flashdave1973 bug reproduced with spaces in project path on windows, issue [here](https://github.com/compodoc/compodoc/issues/44)
