### ISSUE TITLE
[BUG] Dependency findit does not crawl all files

### ISSUE THREAD

**Issue by andrew19881123** [compodoc/compodoc#430]
##### **Overview of the issue**

when generating the documentation the library findit doesn't find all files in the project.
This problem is only present in the enviroment mentioned below.
Is it possible to switch to findit2?

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: windows 2008 r2
node: 8.9.4
npm: 5.6.0
compodoc 1.0.5

##### **Compodoc installed globally or locally ?**

locally

**Comment by fmasini** [comment]
+1 

I have had the same issue and we have fixed it installing **findit2**
Is it possible to switch to findit2?
