### ISSUE TITLE
[BUG] JsDoc @link not working for variables

### ISSUE THREAD

**Issue by totkeks** [compodoc/compodoc#433]
##### **Overview of the issue**

When trying to link to a variable (listed in compodoc under Miscellaneous / Variables) then the link is not resolved and instead {@link MY_VAR} is kept inside the comment.

Created a repo for this https://github.com/totkeks/compodoc-link-bug

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc 1.0.5

##### **Angular configuration, a `package.json` file in the root folder**

See repository.

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

I wanted to refer to the documentation for the variable. In this case it is used in conjuction with an @Inject annotation to inject a dependency via InjectionToken. Unfortunately that annotation is not visible anymore in the generated documentation, therefore I wanted to explicitly refer to it in the comment for the constructor.

##### **Reproduce the error**

Run `npm run docs` and check the generated documentation in the `docs` folder

##### **Related issues**

Have not seen any.

**Comment by vogloblinsky** [comment]
Fixed here : https://github.com/compodoc/compodoc/commit/0194c1b78cb64b6f6b705e3af4072698f21d8f34
Coming in 1.0.6
