### ISSUE TITLE
[BUG] watch files windows 10 version 1.0.5

### ISSUE THREAD

**Issue by Lexanius** [compodoc/compodoc#434]
Watch files on Version 1.0.5 not workung, on version 1.0.4 the watch working.

##### **Overview of the issue**

I run local ```.\node_modules\.bin\compodoc src/main/webapp/app -p tsconfig.compodoc.json -w -s -r 8090```
I get the result:

```
.\node_modules\.bin\compodoc src/main/webapp/app -p tsconfig.compodoc.json --coverageMinimumPerFile 70

1.0.5

Node.js version : v8.9.3

Operating system : Windows 10

[...]

[11:20:18] Documentation generated in ./documentation/ in 15.926 seconds using gitbook theme
[11:20:18] Serving documentation from ./documentation/ at http://127.0.0.1:8090
[11:20:18] Watching sources in main folder
```
But there is no update after file changes.

##### **Angular configuration, a `package.json` file in the root folder**

```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "removeComments": false,
        "strictNullChecks": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "alwaysStrict": true,
        "skipLibCheck": true,
        "noUnusedParameters": false,
        "noUnusedLocals": false,
        "suppressImplicitAnyIndexErrors": true,
        "downlevelIteration": true,
        "lib": [
            "es2017",
            "dom"
        ],
        "typeRoots": [
            "node_modules/@types"
        ]
    },
    "exclude": [
        "src/main/webapp/app/admin/admin.route.ts"
    ]
}
```

##### **Suggest a Fix**

PS: Thank You, for fixing the bugs so many times, Great job.

**Comment by vogloblinsky** [comment]
Hi
Watch files works fine for me with your configuration.
You put this command in your previous message : 
`.\node_modules\.bin\compodoc src/main/webapp/app -p tsconfig.compodoc.json --coverageMinimumPerFile 70`
Is this command which doesn't works as expected ?

**Comment by Lexanius** [comment]
No i mean the original command. 
But the error is gone now (seems to be a local error) in the first project.

In my second Project, a JHipster project, it not work. But i will do some research to this show it to you.
