### ISSUE TITLE
[FEATURE] Fix dependencies, Warning when installing Compodoc

### ISSUE THREAD

**Issue by Davilink** [compodoc/compodoc#438]
##### **Overview of the issue**

When i install compodoc@1.0.5 i get this warning : 
![image](https://user-images.githubusercontent.com/1498932/35118974-8e04e086-fc61-11e7-9db6-6a85e84a8f65.png)

When installing compodoc@1.0.5 with Typescript 2.6.2
![image](https://user-images.githubusercontent.com/1498932/35119485-154cb5e0-fc63-11e7-82ba-bfb6e45073ae.png)

![image](https://user-images.githubusercontent.com/1498932/35120226-68522368-fc65-11e7-96b4-5f36910dce51.png)
(After looking, this dependencies is use by watchr who is used be the live-server package, but the live-server has updated their dependency in the version 1.2.0, so it's will be a good idea to update your dependencies from liveserver@1.1.0 to liveserver@1.2.0)

##### **Operating System, Node.js, npm, compodoc version(s)**
OS: Window 10
Node: 8.1.2
Compodoc version: 1.0.5

##### **Angular configuration, a `package.json` file in the root folder**

Not sure what to put here

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

Get rid of the warning and stop using deprecated stuff.

For Typescript, maybe not fix the PeerDependies to fix version. Normally Typescript will change the majoer version in case of a breaking change, so using the tildes `~` like `"typescript: "~2.6.1"`

##### **Reproduce the error**

Install compodoc@1.0.5 Locally in a project

**Comment by vogloblinsky** [comment]
First issue with gulp-util fixed with this commit : https://github.com/compodoc/compodoc/commit/33b74e9a587895bc2f9279b426b87dac87154855
Second with this commit : https://github.com/compodoc/compodoc/commit/736b894f37df27b21ec17e934ff307e21ca10256
For the last here is an explanation why i didn't upgrade to 1.2.0 : https://github.com/compodoc/compodoc/issues/232
