### ISSUE TITLE
[FEATURE] Unit Test Coverage

### ISSUE THREAD

**Issue by michael-letcher** [compodoc/compodoc#440]
##### **Overview of the issue**
We love the documentation coverage, but would love another page that shows that coverage of unit tests, like what the Angular CLI provides

##### **Motivation for or Use Case**
Provide a clearer picture of what is covered and what is not.

Related to #112

**Comment by vogloblinsky** [comment]
Yes it could be a cool feature. I will check how works ESDoc.
Stay tuned.

**Comment by codeNoobie** [comment]
Hello @vogloblinsky 
We love your compodoc. Its a great tool. It would be really nice to show unit test coverage as well. Any update on this feature?

**Comment by vogloblinsky** [comment]
@codeNoobie 
No, i didn't take time to analyse how ESDoc handles this feature. I am focused during last weeks on new menu, and now on new graph engine without vis.js

**Comment by bhofmei** [comment]
This feature would be awesome! I think the easiest way to handle this would be to have a parameter for LCOV or JSON coverage that could be incorporated into the pages. istanbul's HTML output sorta follows a similar structure to compodoc

**Comment by bhofmei** [comment]
I was able to implement this pretty easily by passing the [istanbul json-summary](https://istanbul.js.org/docs/advanced/alternative-reporters/#json-summary) report to compodoc. Using istanbul output seems better than requiring coverage be part of the ESDoc. Implementing this required adding a parameter, updating the main data interface, adding a function to application.ts, updating menu.hbs, and creating a new hbs template for the unit tests. It took a few hours for me (and most of that time was spent orientating myself in the existing code).

![image](https://user-images.githubusercontent.com/16089658/41671650-c1a3449a-7485-11e8-9dc9-d3f152de0e79.png)

I can't figure out how to include the feature in unit tests to be able to contribute as a pull request.

**Comment by vogloblinsky** [comment]
Hi @bhofmei 
Very cool stuff. Just start a pull request, we will discuss in it the implementation you take.
Thanks by advance

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/pull/594
