### ISSUE TITLE
[FEATURE] Project information page

### ISSUE THREAD

**Issue by madoar** [compodoc/compodoc#441]
I'm currently want to generate an api documentation page for one of my projects. 
For this I want to use `compodoc`.
When creating the documentation page I discovered that I couldn't find any information about the package version and used dependencies.
It would be quite nice if such information would be contained in the created documentation.
This is especially important if the library has multiple versions, which are incompatible to each other.
In such cases it is important for the user to see for which library version the used documentation has been created for.

**Comment by vogloblinsky** [comment]
Yes, this can be added with a new entry in the "Getting started" menu.

**Comment by madoar** [comment]
@vogloblinsky is it also possible to add the version number of the library itself, i.e. if I would create a documentation of the current master branch of `compodoc`, the user can see somewhere in the documentation, that the documentation has been created for `compodoc` version `1.0.5`?
