### ISSUE TITLE
[FEATURE] Does not parse @todo

### ISSUE THREAD

**Issue by michael-letcher** [compodoc/compodoc#445]
##### **Overview of the issue**

```typescript
/** @todo this has something that needs doing */
const TYPE = 'test';
```

The above will not be parsed into the documentation.
It is good though that this type of comment does not get counted as documentation on the coverage though.

##### **Operating System, Node.js, npm, compodoc version(s)**
```
OSX 10.13.1
Node 6.11.2
Compo 1.0.5
```

##### **Compodoc installed globally or locally ?**
Local

##### **Motivation for or Use Case**
Should appear in the documentation

**Comment by vogloblinsky** [comment]
@michael-letcher 
If i understand well, you want @todo comments to appear in final documentation but not counted inside coverage ?

**Comment by michael-letcher** [comment]
Correct, or have a seperate list in the style of code coverage that lists out all the todos perhaps.

I think it would a be a good addition. This ticket probably shouldn't be a bug but rather a feature request.

Thank you,
Michael Letcher

Michaelletcher.com

________________________________
