### ISSUE TITLE
[FEATURE] Todo list

### ISSUE THREAD

**Issue by michael-letcher** [compodoc/compodoc#446]
##### **Motivation for or Use Case**
Would be nice to have a todo list created via the @todo (or any todo) in comment blocks.
This could give a nice overview of where attention is needed as there would (could) be more todos that needs to be fixed.

**Comment by vogloblinsky** [comment]
Duplicate of https://github.com/compodoc/compodoc/issues/383

**Comment by michael-letcher** [comment]
@vogloblinsky You can close this ticket due to duplicate
