### ISSUE TITLE
Compodoc suddenly not showing components / models

### ISSUE THREAD

**Issue by dealloc** [compodoc/compodoc#449]
##### **Overview of the issue**

I'm building a library in Angular 5 and am using Compodoc for generating the documentation.
This worked fine at first, however when I attempted to regenerate the documentation a while back I noticed that none of my components were being listed anymore, even though they first were.

My module is being documented (however none of the components are listed in it's documentation page either) and my services and interfaces seem to be generated as well.

Oddly enough, the interfaces are being included even though they are in a folder next to the models (which are classes) who are not being documented.

##### **Operating System, Node.js, npm, compodoc version(s)**

Operating system: Windows 10 x64
NodeJS: v8.7.0
NPM: 5.4.2
Yarn: 1.3.2
Compodoc: ^1 (1.0.5)

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

I want all my components to be documented.

##### **Reproduce the error**

I can't make the library itself open source but I'm willing to let a contributor take a look at a private repo with the source code.

Example of a class that's no longer being documented:
```typescript
import * as JwtDecoderProxy from 'jwt-decode';

/**
 * Represents an authenticated user.
 * This class is a convenience wrapper around the JWT token.
 */
export class User {
	/** The deserialized version of the JWT token. */
	private user: JwtUser;

	/** Get the unique identifier of this user. */
	public get Identifier(): string {
		return this.user.entityid.toString();
	}

	/** Get the audience this user's token was intended for. */
	public get Audience(): string {
		return this.user.aud;
	}

	/** Get the date this user's token expires. */
	public get Expiration(): Date {
		return new Date(this.user.exp * 1000);
	}

	/** Get the group this user belongs to. */
	public get Group(): string {
		return this.user.groupsid;
	}

	/** Get the date this user's token was issued. */
	public get IssuedAt(): Date {
		return new Date(this.user.iat * 1000);
	}

	/** Get the issuer of this user's token. */
	public get Issuer(): string {
		return this.user.iss;
	}

	/** Get the date this user's token becomes valid. */
	public get ValidSince(): Date {
		return new Date(this.user.nbf);
	}

	/** Get the roles associated with this user. */
	public get Roles(): string[] {
		if (this.user.role.constructor === Array) {
			return this.user.role as string[];
		}

		return [this.user.role as string];
	}

	/** Get the username of this user. */
	public get Username(): string {
		return this.user.unique_name;
	}

	/** Get the JWT token that represents this user. */
	public get Token(): string {
		return this.token;
	}

	/**
	 * Create a new user instance.
	 *
	 * @param token The JWT token that represents this user.
	 */
	public constructor(private readonly token: string) {
		// the reassignment is a (dirty) hack to make Rollup work (see https://github.com/rollup/rollup/issues/1420)
		const decoder = JwtDecoderProxy; // tslint:disable
		this.user = decoder(this.token) as JwtUser;
	}
}

```

Not sure if it's relevant, but here's the directory structure of the project:
![2018-01-25 15_21_17-user model ts - tokenauthenticationfrontend - visual studio code](https://user-images.githubusercontent.com/2164354/35392862-71b9e7f0-01e3-11e8-9ed8-c4aa0521e67a.png)

And here's the overview of the generated documentation:
![2018-01-25 15_22_19- camco_token documentation](https://user-images.githubusercontent.com/2164354/35392898-92d62dd6-01e3-11e8-9b3a-8a5244f2d4df.png)

**Comment by dealloc** [comment]
I just noticed that when I added a new model in the same directory as the other models (src/models/entities) it's being properly parsed.

Said entity:
```typescript
/**
 * Get the user as represented by the tokenauthentication API.
 *
 * Note that this entity is different from the AuthUser, which represents the authenticated user.
 */
export class User {
	// some comment.
}
```

**Comment by vogloblinsky** [comment]
@dealloc Can we discuss that by email ?, and if possible have access to the private repository for debugging ?

**Comment by dealloc** [comment]
I just did a reinstall on the project and ran compodoc again, it now seems to run without any problems.
That being said, the project has undergone quite some structural changes since I filed this issue and I cannot trivially revert it back to that state or give access to the repository.

I'm afraid I find myself unable to reproduce the reported error at this time

**Comment by vogloblinsky** [comment]
Ok i close it, if it comes back, reopen it ;)

**Comment by dealloc** [comment]
Will do!

**Comment by RakeshGowdaM** [comment]
CompDoc is not displaying the descriptions
Which are there in the template (.html) file only ts file comments are displaying.
