### ISSUE TITLE
[BUG] : wont serve or open generated documentation

### ISSUE THREAD

**Issue by flashdave1973** [compodoc/compodoc#45]
I have tested multiple configurations on multiple machines and I can not seem to get the project to serve the documentation. Either with the default settings or by specifying a port address. Also it does not seem to open generated documentation with `--open`

##### **Operating System, Node.js, npm Version(s)**

On windows 7 and mac, Installed with npm v4.0.5 & node v6.9.1

##### **Angular configuration, a `package.json` file in the root folder**

./node_modules/.bin/compodoc --theme stripe --name LogistiCAD-TNG-UI --tsconfig ./tsconfig.json --serve --port 2200 --open --hideGenerator

##### **Compodoc installed globally or locally ?**

both

![compodoc-19](https://cloud.githubusercontent.com/assets/7192793/21617446/2e0b8762-d1b4-11e6-8517-d524c6d3f3a5.jpg)

![compodoc-20](https://cloud.githubusercontent.com/assets/7192793/21617454/35716a76-d1b4-11e6-8be4-cfa07cbee121.jpg)

**Comment by vogloblinsky** [comment]
With a quickly test on my machine, seems to be a bug with port flag, it works fine when removing it.
I check that in detail asap.

**Comment by vogloblinsky** [comment]
Fixed in v0.0.28

**Comment by flashdave1973** [comment]
@vogloblinsky does `--open` work for you?

**Comment by flashdave1973** [comment]
@vogloblinsky FYI.... I love the project....

Would be willing to fork and do a `PR` if there is a section you would like for me to look at. Have you thought about adding component templates or styles?

**Comment by vogloblinsky** [comment]
@flashdave1973 works fine on my linux machine.

Just used https://github.com/compodoc/compodoc-demo-todomvc-angular2.

Clone the repo, npm i, and run

```./node_modules/.bin/compodoc -p src/tsconfig.json -s -o```

> Would be willing to fork and do a PR if there is a section you would like for me to look at. Have you thought about adding component templates or styles?

Cool ! I have started an issue with all the tasks needed for next minor release. https://github.com/compodoc/compodoc/issues/46

Leave a comment on the part you want to contribute.
