### ISSUE TITLE
[BUG] Cannot seem to display raw HTML.

### ISSUE THREAD

**Issue by sdwallace** [compodoc/compodoc#451]
##### **Overview of the issue**

I cannot seem to get HTML examples in my components documentation.  It attempts to render the working component  (because it is HTML) and what I really want is it to show the HTML, not the component.  Here is what I put in the top of a component.  I really want to show the HTML tags, etc. 

```
This component wraps all our input fields.  An example is:

<blockquote>
   <pre>
       <code>
            <our-control-group [control]="heroName" labelKey="heroName">
              <input #inputElement name="heroName" class="form-control"  [(ngModel)]="hero.name" required #heroName="ngModel" autocomplete="off">
            </our-control-group>
        </code>
    </pre>
</blockquote>
```

Can I do this without a working example on plunkr?

**Comment by sdwallace** [comment]
As a workaround the the above, this technique works to wrap the content in a disabled text field.
<textarea disabled="Disabled" rows="3" cols="140">
<our-control-group [control]="heroName" labelKey="heroName">
              <input #inputElement name="heroName" class="form-control"  [(ngModel)]="hero.name" required #heroName="ngModel" autocomplete="off">
</our-control-group>
</textarea>

**Comment by vogloblinsky** [comment]
Did you try to start with the three backtick ``` ?

**Comment by sdwallace** [comment]
No but it worked.  Thanks for the suggestion!

```
<our-control-group [control]="heroName" labelKey="heroName">
	<input #inputElement name="heroName" class="form-control"  [(ngModel)]="hero.name" required #heroName="ngModel" autocomplete="off">
</our-control-group>```
