### ISSUE TITLE
[BUG] Accessors not parsing all data correctly

### ISSUE THREAD

**Issue by Chowarmaan** [compodoc/compodoc#468]
##### **Overview of the issue**
I have created and commented some Accessors in my code and they are not being parsed into the documentation correctly.  This is also the reason for Documentation Code Coverage not being 100%

##### **Operating System, Node.js, npm, compodoc version(s)**
 Node : v9.4.0
    npm  : 5.6.0
    OS   : Windows 10

##### **Angular configuration, a `package.json` file in the root folder**
{
  "name": "A",
  "description": "A",
  "version": "0.0.1",
  "author": "Chowarmaan",
  "homepage": "",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "clean": "ionic-app-scripts clean",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "docs": "compodoc --tsconfig tsconfig.json --output docs/ --theme original --name \"App\" --customFavicon src/assets/icon/favicon.ico --serve --port 8800 --watch ",
    "test": "npm run jest --config jest.config.json --no-cache"
  },
  "dependencies": {
    "angular/common": "5.0.2",
    "angular/compiler": "5.0.2",
    "angular/compiler-cli": "5.0.2",
    "angular/core": "5.0.2",
    "angular/forms": "5.0.2",
    "angular/http": "5.0.2",
    "angular/platform-browser": "5.0.2",
    "angular/platform-browser-dynamic": "5.0.2",
    "ionic-native/core": "4.5.3",
    "ionic-native/network": "4.5.3",
    "ionic-native/splash-screen": "4.5.3",
    "ionic-native/status-bar": "4.5.3",
    "ionic/storage": "^2.1.3",
    "angularfire2": "^5.0.0-rc.6",
    "cordova-plugin-network-information": "1.3.4",
    "firebase": "^4.9.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "promise-polyfill": "^6.1.0",
    "rxjs": "^5.5.6",
    "sw-toolbox": "3.6.0",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "angular/cli": "^1.6.3",
    "compodoc/compodoc": "^1.0.6",
    "ionic/app-scripts": "3.1.8",
    "types/jest": "^22.1.2",
    "types/node": "^9.4.6",
    "jest": "^22.3.0",
    "jest-preset-angular": "^5.0.0",
    "reflect-metadata": "^0.1.12",
    "ts-jest": "^22.0.4",
    "typescript": "^2.7.1",
    "typescript-collections": "^1.3.2"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-network-information": {}
    }
  }
}

##### **Compodoc installed globally or locally ?**
Compodoc installed locally

##### **Motivation for or Use Case**
Missing documentation and documentation coverage is off then. See attached screen shot for the problem with the documentation in Compodoc-Accessors.png

##### **Reproduce the error**
Run the Compodoc across the Compodoc-Accessors.ts

Compodoc-Accessors.ts
```
/**
 * @class Class decorator for IntPair which is a custom data type that is an integer, comma, string
 */
export class A {
	/**
	 * Private Data number for testing
	 */

	private privatedata: number;
	/**
	 * Class constructor
	 */
	constructor() { }
	
	/**
	 * Simple get Accessor test
	 * @returns Internal number
	 */
	get Data():number {
		return this.privatedata;
	}

	/**
	 * Simple set Accessor test
	 * @param {number} Value Internal Number
	 */
	set Data(Value:number) {
		this.privatedata = Value;
	}
}
```

##### **Related issues**
385
[Compodoc-Accessors.ts.txt](https://github.com/compodoc/compodoc/files/1725668/Compodoc-Accessors.ts.txt)

**Comment by vogloblinsky** [comment]
Can i have an example of accessor documented ?

**Comment by vogloblinsky** [comment]
Ok seems there is an issue. here what i have :

![image](https://user-images.githubusercontent.com/2841805/36228978-0f691ece-11d6-11e8-91b4-bf8ed0399d4f.png)

**Comment by Chowarmaan** [comment]
Does not seem to get Parameters on the set

**Comment by vogloblinsky** [comment]
Ok fixed
