### ISSUE TITLE
Documentation Coverage does not update accurately

### ISSUE THREAD

**Issue by Chowarmaan** [compodoc/compodoc#469]
##### **Overview of the issue**
I had created an Angular pipe that extended the Date Pipe without any source comments.  The Documentation coverage correctly shows that coverage is at 0%.  However, I then add comments to the source file and save changes. Compodoc processes the file and shows it detects the changes. The actual documentation internal for the pipe is updated, but the overall coverage is not updated and remains at 0%

##### **Operating System, Node.js, npm, compodoc version(s)**
 Node : v9.4.0
    npm  : 5.6.0
    OS   : Windows 10

##### **Angular configuration, a `package.json` file in the root folder**
{
  "name": "A",
  "description": "A",
  "version": "0.0.1",
  "author": "Chowarmaan",
  "homepage": "",
  "private": true,
  "scripts": {
    "build": "ionic-app-scripts build",
    "clean": "ionic-app-scripts clean",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "docs": "compodoc --tsconfig tsconfig.json --output docs/ --theme original --name \"App\" --customFavicon src/assets/icon/favicon.ico --serve --port 8800 --watch ",
    "test": "npm run jest --config jest.config.json --no-cache"
  },
  "dependencies": {
    "angular/common": "5.0.2",
    "angular/compiler": "5.0.2",
    "angular/compiler-cli": "5.0.2",
    "angular/core": "5.0.2",
    "angular/forms": "5.0.2",
    "angular/http": "5.0.2",
    "angular/platform-browser": "5.0.2",
    "angular/platform-browser-dynamic": "5.0.2",
    "ionic-native/core": "4.5.3",
    "ionic-native/network": "4.5.3",
    "ionic-native/splash-screen": "4.5.3",
    "ionic-native/status-bar": "4.5.3",
    "ionic/storage": "^2.1.3",
    "angularfire2": "^5.0.0-rc.6",
    "cordova-plugin-network-information": "1.3.4",
    "firebase": "^4.9.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "promise-polyfill": "^6.1.0",
    "rxjs": "^5.5.6",
    "sw-toolbox": "3.6.0",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "angular/cli": "^1.6.3",
    "compodoc/compodoc": "^1.0.6",
    "ionic/app-scripts": "3.1.8",
    "types/jest": "^22.1.2",
    "types/node": "^9.4.6",
    "jest": "^22.3.0",
    "jest-preset-angular": "^5.0.0",
    "reflect-metadata": "^0.1.12",
    "ts-jest": "^22.0.4",
    "typescript": "^2.7.1",
    "typescript-collections": "^1.3.2"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-network-information": {}
    }
  }
}

##### **Compodoc installed globally or locally ?**
Compodoc installed locally

##### **Motivation for or Use Case**
Updating code coverage throughout the day is not reflected in the coverage report.

##### **Reproduce the error**
Take a file with no comments in the code as shown below:

    import { Pipe, PipeTransform } from '@angular/core';
    import { DatePipe } from '@angular/common';

    @Pipe({
        	name: 'sls_Date',
    })

    export class SlsDatePipe extends DatePipe implements PipeTransform {
	    transform(DateValue: number, args: string): string | null {
	    	    let DateObject: any;
		    if( DateValue < 20000101 || DateValue > 20991231) {
			    return DateValue.toString();
		    }

		    let DateString = DateValue.toString();
		    let Year:number = parseInt(DateString.substr(0,4));
	  	    let Month:number = parseInt(DateString.substr(4,2)) - 1;
		    let Day:number = parseInt(DateString.substr(6,2));
		    DateObject = new Date(Year, Month, Day);

		    let FormattedDate = super.transform(DateObject, args);
		    return FormattedDate;
	    }
    }

Add documentation for the class and the function and save the changes.  The documentation is updated with the parameters and the return, but not the code coverage (see attached image).

    import { Pipe, PipeTransform } from '@angular/core';
    import { DatePipe } from '@angular/common';

    @Pipe({
        	name: 'sls_Date',
    })

    /**
     * SLS Date Pipe to convert to and from the YYYYMMDD (number) to the Javascript Date object
     */
    export class SlsDatePipe extends DatePipe implements PipeTransform {
    	    /**
 	     * Convert the data from the numeric YYYYMMDD to the Javascript date format
	     * @param DateValue SLS Formatted number in the YYYYMMDD style
	     * @param args Angular Date Pipe args to control the output format
	     * @returns Text output following the Javascript date() formats
	     */
	    transform(DateValue: number, args: string): string | null {
	    	    let DateObject: any;
		    if( DateValue < 20000101 || DateValue > 20991231) {
			    return DateValue.toString();
		    }

		    let DateString = DateValue.toString();
		    let Year:number = parseInt(DateString.substr(0,4));
	  	    let Month:number = parseInt(DateString.substr(4,2)) - 1;
		    let Day:number = parseInt(DateString.substr(6,2));
		    DateObject = new Date(Year, Month, Day);

		    let FormattedDate = super.transform(DateObject, args);
		    return FormattedDate;
	    }
    }

![compodoc-coverage](https://user-images.githubusercontent.com/175738/36231580-91033cb4-11ac-11e8-8aa2-8216a93b13eb.PNG)

**Comment by vogloblinsky** [comment]
Put the comment of your pipe before the @Pipe.

```
/**
 * SLS Date Pipe to convert to and from the YYYYMMDD (number) to the Javascript Date object
 */
@Pipe({
    	name: 'sls_Date',
})
export class SlsDatePipe extends DatePipe implements PipeTransform {
```

**Comment by Chowarmaan** [comment]
Thanks. Moving the comment above the decorator solved the problem.
