### ISSUE TITLE
[FEATURE] : Is there any way to have documentation working without any server

### ISSUE THREAD

**Issue by dotnetjalps** [compodoc/compodoc#47]
##### **A way to work document without any server**

We have some use cases where we need to give documentation to our Vendor(Client) in some hard drive. I have tried this documentation its look super cool and I can see it can be generated locally in the folder. But this documentation needs a web server to display documentation. In our case, We need to have that works from anywhere in a physical folder. Double click via index.html from the physical folder. I was just wondering is there a way to generate that documentation that will work without the web server.

**Comment by vogloblinsky** [comment]
Hi,
Compodoc documentation is not planned for the moment to be used directly by opening index.html and having file:// urls in the browsers.
For example, Lunr.js index json file is loaded with ajax, and will failed in your context.

After 0.1.0 release, i will try to implement this option by removing the base html tag, handling links correctly, and store Lunr.js index json in a js file.
