### ISSUE TITLE
[BUG] external docs change sorting

### ISSUE THREAD

**Issue by vonsko** [compodoc/compodoc#471]
##### **Overview of the issue**

It looks like all the external docs change their sorting or positions just by themselves - I wasn't touching any of this docs, I was only working on docs of angular app (jsdocs) and that's all. I was showing yesterday some presentation for coworkers and someone asked why is everything messed up on production server - I've tested it and locally it looks the same (screen below)

![zrzut ekranu 2018-02-15 o 11 20 52](https://user-images.githubusercontent.com/1410880/36252039-aae64efe-1243-11e8-8acc-04f23cd646d5.png)

it worked before I'm 💯 sure :)

##### **Operating System, Node.js, npm, compodoc version(s)**

8.9.4 / 5.6.0 / 1.0.5 - 1.0.7

##### **Angular configuration, a `package.json` file in the root folder**

I recently updated angular-cli to 1.6.8, and tslint to 5.9.1 .
angular is 5.2.4 

##### **Compodoc installed globally or locally ?**

I think: locally

##### **Motivation for or Use Case**

look at the screen :)

##### **Reproduce the error**

no idea is this reproducable :/

##### **Related issues**

Couldn't find any

**Comment by vogloblinsky** [comment]
It it possible to just have your summary.json to reproduce the issue ?

**Comment by vogloblinsky** [comment]
Ok reproduced my others test files
