### ISSUE TITLE
document not generating

### ISSUE THREAD

**Issue by jothipandiyanjp** [compodoc/compodoc#475]
This is  tsconfig.json in my applicaion
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true
  },
  "exclude": [],
  "files": [ "AngularApp/main.ts" ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  }
}

With this tsconfig.json, the document is not generating

![image](https://user-images.githubusercontent.com/20284584/36353298-a27b33a2-14ea-11e8-97c1-bcf009b514cc.png)

**Comment by vogloblinsky** [comment]
Compodoc parse your tsconfig.json file and found the reference "files" with here only one file.
Create another file, `tsconfig.doc.json`, without `files` inside, and use this one for Compodoc.
