### ISSUE TITLE
[BUG] Unhandeled Rejection at Promise {

### ISSUE THREAD

**Issue by user472** [compodoc/compodoc#479]
##### ** When I try to use Compodoc i alwas get the same error message as seen below.**

![image](https://user-images.githubusercontent.com/36647069/36397610-c21bf2bc-15c3-11e8-912d-b766af4a136b.png)

##### **
Package.json

{
  "name": "",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json",
    "doc:build": "compodoc -p src/tsconfig.app.json",
    "doc:serve": "compodoc -s",
    "doc:buildandserve": "compodoc -p src/tsconfig.app.json -s",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "core-js": "2.5.3",
    "rxjs": "5.5.5",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/cli": "1.2.0",
    "@angular/compiler-cli": "4.4.6",
    "@angular/language-service": "4.4.6",
    "@compodoc/compodoc": "^1.0.7",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "6.0.95",
    "codelyzer": "3.0.1",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.1.1",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.3.1",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.2",
    "ts-node": "3.0.6",
    "tslint": "5.3.2",
    "typescript": "2.3.4"
  }
}
**

##### ** installed with the installation guide https://compodoc.github.io/website/guides/installation.html 
Last step does not work for me.**

**Comment by DHFW** [comment]
We have the same issue and error message. `Angular 5.1.2`. Running `"./node_modules/.bin/compodoc -p src/tsconfig.json"` results in the same error. `Compodoc 1.0.7`

**Comment by vogloblinsky** [comment]
1.0.8 has the option --disableRoutesGraph if you want to bypass this error

**Comment by user472** [comment]
Thanks for the tip. I "solved" the problem for me by switching to the node version 6.9.1.
