### ISSUE TITLE
[FEATURE] Source folder option

### ISSUE THREAD

**Issue by jiayihu** [compodoc/compodoc#48]
##### **Overview of the issue**

Seems strange to me that there is no option to specify where my source files are. Currently it scans all `.ts` file in my root folder, so with the following structure I get my `examples` folder scanned even if I don't wish it.

```
/
--examples
--src
```

##### **Suggest a Fix**

My current script is `compodoc ./src -p tsconfig.json -d doc -s` and I think it sounds reasonable to pass the source folder this way.

P.S. Great work anyway, very promising!

**Comment by vogloblinsky** [comment]
Added in v0.0.29, have fun !
