### ISSUE TITLE
[BUG] index html not generating

### ISSUE THREAD

**Issue by jothipandiyanjp** [compodoc/compodoc#480]
In package.json:
{
    "compodoc": "./node_modules/.bin/compodoc AngularApp/app -p tsconfig-doc.json -n \"App Documentation\" -d wwwroot/documentaion/docs --theme laravel"
}

After running this command,
      npm run compodoc

Console ouput: 
![image](https://user-images.githubusercontent.com/20284584/36414397-29bc208e-1648-11e8-956f-5f44aeeec059.png)

Index.html and other folders are not generating in docs folder, 
![image](https://user-images.githubusercontent.com/20284584/36414312-dbf4c676-1647-11e8-9779-883ced212cee.png)

**Comment by jothipandiyanjp** [comment]
The path which I gave is not taking correctly,
some of the folders like classes, directives, pipes are generated as docsclasses, docsdirectives.

![image](https://user-images.githubusercontent.com/20284584/36416164-42e71b9e-164e-11e8-91e7-37338a55b59d.png)

**Comment by vogloblinsky** [comment]
Can i have the structure of your directories ?
Node, OS, and compodoc versions please ?

**Comment by jothipandiyanjp** [comment]
node - v9.5.0
OS - Windows 10
compodoc - 1.0.7

**Comment by vogloblinsky** [comment]
@jothipandiyanjp 
Please can i have your directory structure starting from where you run compodoc ?
Difficult to me te reproduce without.

**Comment by jothipandiyanjp** [comment]
--app
    --package.json
    -- AngularApp
         --app
    --wwwroot
         --documentation
               --docs

I need to generate docs in the documentation folder

**Comment by vogloblinsky** [comment]
@jothipandiyanjp 
It could be very useful for debugging if you can send me a sample project with this structure with one module and one component.
Thanks

**Comment by vogloblinsky** [comment]
Fixed i think with last commits, check with release 1.1.3 coming today
