### ISSUE TITLE
[FEATURE] deprecated dependencies

### ISSUE THREAD

**Issue by LexNetAT** [compodoc/compodoc#481]
##### **Overview of the issue**

On NPM install or update are warnings about deprecated dependencies:
- gulp-util
- node-uuid
- coffee-script

##### **Operating System, Node.js, npm, compodoc version(s)**

- node v8.9.1
- npm v5.5.1
- compodoc v1.0.7

##### **Compodoc installed globally or locally ?**

locally

##### **Reproduce the error**

`npm install --no-optional --no-shrinkwrap --no-save`
> npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

`npm ls gulp-util`
> -- @compodoc/compodoc@1.0.7
> -- @compodoc/ngd-transformer@2.0.0-alpha.5
> -- @compodoc/ngd-core@2.0.0-alpha.3
> -- gulp-util@3.0.8

` npm ls node-uuid`
> -- @compodoc/compodoc@1.0.7
> -- live-server@1.1.0
> -- http-auth@2.4.11
> -- node-uuid@1.4.8

`npm ls  coffee-script`
> -- @compodoc/compodoc@1.0.7
> -- live-server@1.1.0
> -- watchr@2.6.0
> -- scandirectory@2.5.0
> -- taskgroup@4.3.1
> -- csextends@1.1.1
> -- coffee-script@1.12.7

##### **Suggest a Fix**

It would be nice to fix the warnings by using the suggested solutions or try a newer version if possible.

**Comment by vogloblinsky** [comment]
Yes the work of cleaning gulp-util for example has been done in compodoc himself, i had to do the same for @compodoc/ngd-core and @ngd-tranformer

**Comment by LexNetAT** [comment]
I'm looking forward for the new release - the current one is very useful. :+1:
