### ISSUE TITLE
[FEATURE]: How to ignore Angular Class properties from Angular component while generating documentation

### ISSUE THREAD

**Issue by CoolGuyInHotTown** [compodoc/compodoc#486]
How to ignore Angular Class properties from Angular component while generating documentaion?
I just want to ignore /exclude class properties from component files while generating documentation.
Because my overall code coverage is very low as i have lots of properties in the component files and I dont want to  write documnetion for the class properties.

Using compodoc version 1.0.0-beta.15

Additional info:

macOS 10.12.6
node v6.9.4
npm 3.10.9
Angular 2.2

**Comment by vogloblinsky** [comment]
What kind of properties ? Lifecycle hooks ? ngOnInit ?

**Comment by ukaaa** [comment]
I would also like to see a way to do this. I have a use case:
Some of our team's components have helper methods that cannot be made private because they are called directly from the template. Yet, I don't want these methods to show up in the documentation.

**Comment by vogloblinsky** [comment]
I think i will add support for @ignore, it is the most common way to ma,age this scenario.

**Comment by CoolGuyInHotTown** [comment]
I want to ignore below properties from Angular component.
For instance,
export class TestComponent {
 public test: number;
 public test1: string
}

Here I wish to ignore the proeprties test and test1 because in my code,I have around 10-15 class properties which decreases my code coverage percentage, So I just want to remove them.

Appriciate your help!!

**Comment by vogloblinsky** [comment]
As i said before, i will implement support of @ignore in JSDoc comment, and remove the statement from outputed documentation, and also affect doc coverage.
