### ISSUE TITLE
[BUG] parser freezes parsing method comments.

### ISSUE THREAD

**Issue by angularityio** [compodoc/compodoc#487]
##### **Overview of the issue**

When adding a specific method comment the parser gets stuck parsing a file and CPU goes wild. 

##### **Operating System, Node.js, npm, compodoc version(s)**

Mac OS Sierra 10.2.6
Compodoc 1.0.7
npm 5.5.1
angular/cli 1.6.8

##### **Angular configuration, a `package.json` file in the root folder**
[package.json and yarn.lock](https://gist.github.com/angularityio/41cd8c8f7a7f60b646af90ccf7bee323)

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

Doc generation hangs and never finishes...never, ever.

##### **Reproduce the error**

1) ng new myapp

2) Then add the following method with comments to app.component.ts

```

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  /**
   * Global dates validation method
   * valid if    1<2<=3<4<=5<6<=7    1<2<=3<4<=5<6<7b    1<2<=3<4<=5<6<7c
   *               scenario 1            scenario 2         scenario 3
   */
  aMethod() {
  }

}
```

3) compodoc -p tsconfig.json --name 'BugDemo' --theme readthedocs

The generation get's stuck on 

`[14:40:24] parsing        : /Users/wanjad/tmp/parsing/src/app/app.component.ts`

Note by removing the comment the issue disappears. 

##### **Related issues**

Don't know.

##### **Output**

![Image of bug](https://gist.githubusercontent.com/angularityio/41cd8c8f7a7f60b646af90ccf7bee323/raw/60a6e92fbe53da74409225b356d0efe639bd61ac/bug.gif)

**Comment by vogloblinsky** [comment]
Fixed with last version in the develop branch, i think due to an upgrade of marked library used for comment / markdown parsing.
