### ISSUE TITLE
[BUG] Syntax highlighting stops after unsupported comment (//)

### ISSUE THREAD

**Issue by chunghha** [compodoc/compodoc#49]
##### **Overview of the issue**

Syntax highlighting stops after unsupported comment by compodoc like this:
![image](https://cloud.githubusercontent.com/assets/24458075/21662310/a05a3134-d29e-11e6-97e8-96abdacb7ac4.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 7
node: 6.9.2
npm: 4.0.5
compodoc: 0.0.28

##### **Angular configuration, a `package.json` file in the root folder**
  "angular-cli": {},
  "scripts": {
    "start": "ng serve --proxy-config proxy.conf.json",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor",
    "compodoc": "./node_modules/.bin/compodoc -h stripe -p src/tsconfig.json"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~2.4.1",
    "@angular/compiler": "~2.4.1",
    "@angular/core": "~2.4.1",
    "@angular/forms": "~2.4.1",
    "@angular/http": "~2.4.1",
    "@angular/platform-browser": "~2.4.1",
    "@angular/platform-browser-dynamic": "~2.4.1",
    "@angular/router": "~3.4.1",
    "@webcomponents/custom-elements": "1.0.0-alpha.3",
    "clarity-angular": "^0.8.0",
    "clarity-icons": "^0.8.0",
    "clarity-ui": "^0.8.0",
    "core-js": "^2.4.1",
    "lodash": "^4.17.4",
    "mutationobserver-shim": "^0.3.2",
    "rxjs": "5.0.2",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.7.4"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.40",
    "@types/lodash": "^4.14.45",
    "@types/node": "^6.0.57",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "2.0.0-beta.4",
    "compodoc": "0.0.28",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "^3.0.0",
    "karma": "1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.1.0",
    "karma-remap-istanbul": "^0.4.0",
    "protractor": "~4.0.14",
    "ts-node": "~2.0.0",
    "tslint": "4.2.0",
    "typescript": "~2.0.10"
  }

##### **Compodoc installed globally or locally ?**
locally as seen in the package.json above.

##### **Reproduce the error**

I believe you can reproduce this issue by commenting with // on any line of your TS code.

**Comment by vogloblinsky** [comment]
Seems to be an highlight.js bug : https://github.com/isagalaev/highlight.js/issues/1390

**Comment by vogloblinsky** [comment]
After some debugging tests, it is the combination of handlebars + highlight.js who breaks the rendering.
