### ISSUE TITLE
[Feature]: Option to insert Custom Stylesheets

### ISSUE THREAD

**Issue by Sibiraj-S** [compodoc/compodoc#491]
##### **Overview of the issue**

Option to insert custom css/scss file.

Something like `compodoc --customStyle my-style.css`

##### **Motivation for or Use Case**

Even though there are 7 great themes available. It is a unique pleasure of having styles to our own taste.
i.e., editing the present theme to our choice.

**Comment by vogloblinsky** [comment]
did you try option --extTheme ?

**Comment by Sibiraj-S** [comment]
I guess i missed that. Will that replace the current theme.

I was talking about, having both `theme` and `externalTheme` at same time.

**Comment by vogloblinsky** [comment]
It will. You can override CSS rules in your file.
