### ISSUE TITLE
[FEATURE] tsconfig path mapping support 

### ISSUE THREAD

**Issue by thomassittig** [compodoc/compodoc#495]
##### **Overview of the issue**
This is only a question, because i didn't find any mention of it in the documentation:
does compodoc supports the path mapping options of [tsconfig](https://www.typescriptlang.org/docs/handbook/module-resolution.html).
I use it heavily in my current project and it seems it is ignored because compodoc tries to resolve the paths based purely on the import statements and ignores possible defined path mappings.

##### **Operating System, Node.js, npm, compodoc version(s)**

* Linux
* nodejs v6.11.5
* npm v3.10.10
* compodoc v1.0.7

##### **Compodoc installed globally or locally ?**
Locally

##### **Motivation for or Use Case**
See initial description

**Comment by thomassittig** [comment]
@vogloblinsky thank you for the fast response, even if it is a sad one :(

**Comment by vogloblinsky** [comment]
I will try to do my best.
If you know other tools around TypeScript that handle that, i am curious about their implementation.
One thing you could do if you have 15 minutes for helping me on this issue is :
- generate a blank project with the CLI
- add two or three custom path mapping
- use them inside the project, with for example 2-3 modules, and 4-5 components.
I could try after that adding this feature in Compodoc more easily.
Thanks

**Comment by thomassittig** [comment]
@vogloblinsky seems as it is supported anyways. a [fresh new project](https://github.com/thomassittig/compodoc-path-example) with a couple of modules and components  doesn't make any problems. so i hope it's "just" a path reference mambojambo in my project now.

**Comment by thomassittig** [comment]
@vogloblinsky i re-evaluating with a fresh new project, with the result that compodoc can already resolve path mappings. At least it seems so. Together with the research if this example project i think my problem is more orignated in how routes in my project are used.

**Comment by vogloblinsky** [comment]
> Using the spread-operator to concat my routes occured in not beeing able to create the documentation with an exception-stack that suggested that the path mappings could not be resolved.

I will release a new version with an option to disable routes graph generation.

**Comment by vogloblinsky** [comment]
1.0.8 released
