### ISSUE TITLE
[QUESTION] documentation folder not created with coverageTest flag

### ISSUE THREAD

**Issue by EugeneSnihovsky** [compodoc/compodoc#497]
##### **Overview of the issue**
For example I have two npm scripts
```
"doc1": "./node_modules/.bin/compodoc -p src/tsconfig.json --disablePrivate --coverageTest 100",
"doc2": "./node_modules/.bin/compodoc -p src/tsconfig.json --disablePrivate",
```

When I run `doc2` - all worked without errors and `documentation` folder created in root folder of my project.

When I run `doc1` - all worked without errors (I have 100% documentation coverage) but `documentation` folder not created at all and command runs much faster then `doc1`

Is this expected behavior? If this is a bug - I can provide more info, if needed. 
Thanks in advance.

**Comment by vogloblinsky** [comment]
Yes running coverageTest means you just want to test your documentation coverage with a single pass of Compodoc. The scan is done in memory.

**Comment by EugeneSnihovsky** [comment]
Now I understand. Maybe it make sense to add some description for `coverageTest` in [documentation](https://compodoc.github.io/website/guides/usage.html) to avoid this type of questions.
Thanks for help :)
