### ISSUE TITLE
[BUG] Graph Overview

### ISSUE THREAD

**Issue by tonogueira2** [compodoc/compodoc#503]
I recently followed other reports of the same error, so I updated my compodoc to the last version and continue the graph error on the overview screen. follow the error ->

Note: I use the latest version of Angular CLI and my project has 534 modules and 263 components and growing

Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
[21:51:53] Ooops error during main graph generation, moving on next part with main graph disabled : : abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

##### **Operating System, Node.js, npm, compodoc version(s)**
Win10
NodeJs v6.10.3
npm 5.7.1
Angular CLI 1.7.0

**Comment by vogloblinsky** [comment]
Last versions of Compodoc should detect this error in a try catch and disable graph rendring in the outputed documentation.
This static graph rendering process will be replaced in next release with a dynamic graph rendering in the browser.
See #234 for information.

**Comment by tonogueira2** [comment]
ok, thk...

**Comment by ssarkisy** [comment]
Is this possible now to generate big main overview graph?

**Comment by vogloblinsky** [comment]
Not for now. I have started the re-write of the graph engine. Work in progress, and sorry no estimate date.

**Comment by dbautistav** [comment]
@vogloblinsky, does an issue or project exist where we can follow (or help to) the development of the new graph engine? Thanks in advance!

**Comment by pborregg** [comment]
Yes, MY issue: https://github.com/compodoc/compodoc/issues/712

**Comment by pborregg** [comment]
Has this been finally resolved?

 

 

Peter Borreggine

Owner and Developer

Angular/Bootstrap/NodeJS/Databases/HTML5/CSS3/Responsive Web Design/SEO

WebParity.net <http://webparity.net/> 

A Service Connected Disabled Veteran Owned Business

WA State License: 603-501-609

360-830-8926 C

 

“Lead, Follow or Get Out of the Way…”

*	Lee Iacocca, former head of Chrysler and Ford

 

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. If you are not the intended recipient, please contact the sender and destroy all copies of the original message and its attachments. Any unauthorized review, use, disclosure, or distribution is prohibited.
