### ISSUE TITLE
[BUG] Extends Components inputs and disabledLifeCycleHooks 

### ISSUE THREAD

**Issue by Chazing** [compodoc/compodoc#505]
##### **Overview of the issue**

Hi
Thank you for adding a flat document option in the case of a component that inherits a base class.
We have some problems with this:

1. Inputs from base class are not documented in components nor in baseClass 

2. The disableLifeCycleHooks option does not work on base class. there are LifeCycleHooks functions in the base class, and even when i use disabledLifeCycleHooks option, the functions are still visible in the child component and base class.

3. Inheritance functions from external libraries such as Angular are also documented. For example, the base class extends Angular's ValueAccessorBase. in the documentations apear ValueAccessorBase functions.
 If the class is not in my code, I do not need to flat its functions

Many thanks for the amazing project!

##### **Operating System, Node.js, npm, compodoc version(s)**

"@compodoc/compodoc": "^1.0.9"
node v8.9.4

##### **Angular configuration, a `package.json` file in the root folder**

"doc:build": "compodoc -p src/tsconfig.app.json",
    "doc:serve": "compodoc -s",
   "doc:buildandserve": "compodoc -p tsconfig.documentation.json -a screenshots -y doc-styles/ -s  --includes markdown --hideGenerator --disableGraph --disableCoverage --disableSourceCode --disablePrivate --disableProtected --disableInternal --disableLifeCycleHooks"

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

I need a flat documentation of components for usage. which can see on one page everything that needs to be done to use the component. (selector, inputs, outputs) and I don't need to describe the code. Any additional things that is in the code for internal use and those who use Componente does not need is unnecessary for me.

##### **Reproduce the error**

- defined base class:

```
import { Observable } from 'rxjs/Observable';
import { ValueAccessorBase } from './value-accessor.base';

export abstract class ElementBase<T> extends ValueAccessorBase implements OnInit, OnDestroy {
    @Input() disabled: boolean;
    @Input() required: boolean;
    @Input() labelTextKey: string = "";

    @Output()
    focus = new EventEmitter();
    @Output()
    blur = new EventEmitter();

    private getGroupColWidth() {
        return this.isLabelAboveControl ? 'col-sm-' + this.controlWidthColumns : '';
    }

    constructor(protected el: ElementRef, protected _injector: Injector) {
        super();
    }

    ngOnInit() {
    }

    ngOnDestroy() {
    }

    protected onFocusIn($event?: any) {
        this.focus.emit(event);
    }

    protected onBlur($event?: any) {
        this.blur.emit(event);
    }
}
```

- Define chiled component:

```
import { Component, ElementRef, forwardRef, Injector, Input } from '@angular/core';
import { NG_VALUE_ACCESSOR } from '@angular/forms';
import { ElementBase } from "../base/element.base";

@Component({
    selector: 'my-textbox',
    templateUrl: 'my-textbox.component.html',
    providers: [{
        provide: NG_VALUE_ACCESSOR,
        useExisting: forwardRef(() => MyTextboxComponent),
        multi: true
    }]
})
export class MyTextboxComponent extends ElementBase<string> {
    @Input() placeholder: string = '';
    @Input() inputType: string = '';
    
    constructor(el: ElementRef, _injector: Injector) {
        super(el, _injector);
    }

    change(event) {
    }

    onFocusIn($event?: any) {
        $event.target.select();
        super.onFocusIn($event);
    }
}
```
then run: npm run doc:buildandserve

I would be grateful if you would treat.

**Comment by vogloblinsky** [comment]
Ok you issue is about the inheritance of a component with a class (without @component decorator). I will ad this scenario in the tool.
The other ones are managed : component <- component, class <- class

**Comment by vogloblinsky** [comment]
@Chazing can i have the code of `value-accessor.base.ts` file ?

**Comment by vogloblinsky** [comment]
Fixed for the first 2 points. Waiting informations for `inheritance functions from external libraries` issue.

**Comment by Chazing** [comment]
It works great! thanks
