### ISSUE TITLE
[FEATURE] typescript as a Peer Dependency

### ISSUE THREAD

**Issue by ITsvetkoFF** [compodoc/compodoc#507]
##### **Overview of the issue**

@vogloblinsky first of all, thanks for compodocs :)
And thanks for solving #359 (version 1.0.5  actually had 2 different typescripts inside node_modules)

This is neither BUG nor FEATURE, strictly saying. 
This is the issue to discuss the Typescript version that is used in compodocs and the possible way to add Typescript to a PeerDependency of Compodoc.
I guess some smart people may have some opinion on that...

##### **Motivation for or Use Case**
Solving this may result in:
- Consumers will not have 2 different typescripts in their node-modules -> saved space and install time
- This may help to avoid the situation when TS version of compodoc differs from TS version that is used by compodoc's consumer. For me it looks strange that *tool that is generating documentation is using another version of language than is actually used to compile the code*. So I'd expect that at least version of `ts-simple-ast` (that, I suppose, is doing analysis of my code) uses the same typescript as my code actually.

Example: in compodoc 1.0.9 typescript version is `^2.4` 
in angular 5.1 typescript version is `2.5.x`. 
in angular 5.2 typescript version is `2.6.x`. 
in angular master typescript version is `2.7.x`.
latest (1.7) angular cli has `~2.6.2`

Overall all that seems so fragile and I just want to define a way how to do that not so fragile at least in terms of a documentation :)

What if I upgrade to the newest angular that uses some of [these awesome features](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html)? will compodoc fail? 

Overall this ticket is to discuss the dependency matrix (compodoc and angular) and decide if it is possible to put typescript as a peer dependency.

**Comment by vogloblinsky** [comment]
Compodoc use internally `ts-simple-ast` for many AST nodes manipulation/traversing etc.

We have at the end inside a sample Angular CLI project :

- one version of TypeScript for `ts-simple-ast`
- one for Compodoc
- and one for the main project.

I have removed the dependency of typescript in compodoc, and relying on `ts-simple-ast` one. This will only remove one in the list.
`ts-simple-ast` use many internal APIs of TypeScript and had to control very carefully the version of TypeScript it uses.

I am feer that using peer depending will produce many errors at Compodoc runtime. For example, project with TS 2.4.2 and `ts-simple-ast` wants 2.7.1.

**Comment by ITsvetkoFF** [comment]
@vogloblinsky thanks for doing all that.
So I see... `ts-simple-ast` wants 2.7.1 and this is very strict. fair enough. Maybe we can do nothing here without magic.
is `ts-simple-ast` always following the latest typescript version?
(I just afraid of a situation when the language version that angular uses is higher than `ts-simple-ast` which is ridiculous)

**Comment by vogloblinsky** [comment]
> is ts-simple-ast always following the latest typescript version?

Yes @dsherret follow very quickly last versions of TypeScript. Angular takes more time to support last minor version of TypeScript.

**Comment by dsherret** [comment]
Yeah, I always upgrade to the latest version within at least a few days (if I'm aware of a release... if I'm slow and miss it then please open an issue :)).

The reason the dependency is strict is because there are occasionally breaking changes in the compiler API between minor versions or bugs in old versions of the compiler API. Additionally, I will sometimes add new features, which wouldn't work in an old version (ex. support for jsx fragments).

**Comment by vogloblinsky** [comment]
I am closing this, feel free to reopen if necessary.
