### ISSUE TITLE
[BUG]: Cannot read template for Component, whose template file is present at a different location 

### ISSUE THREAD

**Issue by adittripathi** [compodoc/compodoc#515]
##### **Overview of the issue**

Trying to generate docs for my project, where the template file of the component is not present in the same location as component.

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Windows 10
Nodejs: v6.9.2
npm:3.10.9
compodoc:^1.0.9

##### **Angular configuration, a `package.json` file in the root folder**
```
{
  "name": "digitaljuice-webapp",
  "version": "1.0.0",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/router": "3.4.8",
    "@angular/upgrade": "2.4.8",
    "@ngui/datetime-picker": "0.16.2",
    "angular-linky": "1.2.2",
    "angular2-color-picker": "1.3.1",
    "angular2-draggable": "1.0.4",
    "angular2-resizing-cropping-image": "1.0.0-final.4",
    "autolinker": "1.4.3",
    "bootstrap": "3.3.6",
    "core-js": "2.4.1",
    "ng2-file-upload": "1.2.0",
    "ng2-rating": "0.0.7",
    "ng2-scroll-to": "1.0.7",
    "ng2-toasty": "4.0.3",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.5.6",
    "systemjs": "0.20.9",
    "zone.js": "0.7.6"
  },
  "devDependencies": {
    "@compodoc/compodoc": "^1.0.9",
    "typescript": "2.0.2"
  },
  "scripts": {
    "compodoc": "./node_modules/.bin/compodoc -p ./tsconfig.json -d ./aditDocs"
  }
}

```

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

I think just when Angular 2 was released, there was no proper guideline that would tell where to keep the html files, and Angular 2 CLI was in pre-release stage, so I went ahead and set up the file system as recommended by tutorials available online. Now, when I want to generate the docs, looks like the HTML files need to be present in the same location as the component. Even if I try to do that, giving a URL relative to the component, gives error when running the code, browser says it can't find the template file.

**AddHeaderComponent.ts**
```
@Component({
    selector: 'Add-header',
    templateUrl: '/Content/Angular2/Development/partials/Community/AddHeader.html',
    styleUrls: ['Content/Angular2/Development/css/Community/PostInput.css', 
                     'Content/Angular2/Development/css/QnA/AskQuestionForm.css',
                     'Content/Angular2/Development/css/CommonStyle.css'],
})
```

**AddHeader.html**

```
<ul>
    <!--Feed Header *ngif="feedHeaderFlag"-->
    <li>
        <div id="FeedHeaderWrapper" *ngIf="communityProvider.headerColorFlag" [@shrinkOut]='state'>
            <input type="text" placeholder="Set the feed header text" id="FeedHeaderText" maxlength="50" class="AddLinkInputArea" [ngStyle]="{'color':communityProvider.textColor}"
                (keyup)="headarTextChange($event)" />
            <!--<input id="FeedHeaderColorPicker" type="button" name="favcolor" title="Pick color for Feed Header">-->
            <color-picker></color-picker>
        </div>
    </li>

</ul>
```

**File System:**
![image](https://user-images.githubusercontent.com/37613690/37701003-73d53ade-2d13-11e8-9a5e-b839b9640db1.png)

**Error that I get trying to generate docs**
![image](https://user-images.githubusercontent.com/37613690/37699636-7164da02-2d0e-11e8-9e18-65bda1bc7585.png)

**Comment by vogloblinsky** [comment]
Hi,
Regarding your file system architecture, where is located the root of your project ?
I see a `Content` folder at the beginning of the template path, which i didn't see in your screenshot.

**Comment by adittripathi** [comment]
Hi I have updated the screen shot of the folder structure in my original issue. Please check.

**Comment by adittripathi** [comment]
Hi are you acknowledging this as a bug? if so, can you tell me an estimated time that you will take to fix it?
Very kind of you to even acknowledge and reply. Thanks for all the effort.

**Comment by zaki-arain** [comment]
Hi, I have a similar issue. I am using 1.1.5. I run into the error after running `npm run compodoc`.

![screen shot 2018-10-17 at 11 41 30 am](https://user-images.githubusercontent.com/18267886/47102323-09bdc780-d202-11e8-8f55-57569c116726.png)

This is where I am using templateUrl.
![screen shot 2018-10-17 at 11 42 47 am](https://user-images.githubusercontent.com/18267886/47102333-117d6c00-d202-11e8-94cd-f03c07e86b95.png)

And this is the project structure.
![screen shot 2018-10-17 at 11 42 16 am](https://user-images.githubusercontent.com/18267886/47102329-0e827b80-d202-11e8-8890-3982a5a71266.png)

**Comment by vogloblinsky** [comment]
Why don't you do ./callDetail.component.html for templateUrl ?
Compodoc tries to find the path supplied related to the current path of the component.
I will try to reproduce

**Comment by zaki-arain** [comment]
I just gave that a shot, but I got this error: `Unhandled Promise rejection: Failed to load calldetail.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load calldetail.component.html`. It looks like it needs the path relative to the app folder.

**Comment by vogloblinsky** [comment]
Is this an Angular CLI project ?

**Comment by zaki-arain** [comment]
This is not an Angular CLI project. I've gone ahead and excluded the CallDetailComponent from my tsconfig, and I've been able to use Compodoc for the rest of my application successfully! Its really great. I'm not sure what it is about the CallDetailComponent's templateURL that is causing this error, but all the other components have played nicely with compodoc so far. Thanks again!

**Comment by vogloblinsky** [comment]
@adittripathi same question for you, is this an Angular CLI project ?
