### ISSUE TITLE
[FEATURE] Add ability to disable the DOM tree tab

### ISSUE THREAD

**Issue by Blakesalot** [compodoc/compodoc#517]
##### **Overview of the issue**

Similar to the disableSourceCode flag, it would be good to be able to disabled the DOM tree tab.

##### **Motivation for or Use Case**

My team would like to disable the DOM tree tab for our CompoDoc usage.

##### **Suggest a Fix**

I would like to contribute the implementation myself by adding a disableDomTree option and mimicking the implementation of the existing disableSourceCode feature.

**Comment by vogloblinsky** [comment]
@jensschneider Done
