### ISSUE TITLE
[BUG] Routes page will be available in documentation only if routing set up with additional module

### ISSUE THREAD

**Issue by vorotech** [compodoc/compodoc#518]
##### **Overview of the issue**

The routes registered in the separate module which is later imported in the main module are displayed correctly in the compodoc Routes page.
But the routes registered inside the module (as constants) and passed to `RouterModule.forRoot/forChild` are not visible in the compodoc Routes.
This applies for any module: AppModule, ExampleModule, etc

##### **Operating System, Node.js, npm, compodoc version(s)**

| OS     | Node.js | npm | compodoc  |
|:------:|:------:|:-----:|:-----:|
| Windows 10 | 8.10.0 | 5.7.1 | 1.0.9 |

##### **Angular configuration, a `package.json` file in the root folder**

<details><summary>package.json</summary><p>

```json
{
  "name": "compodoc-issues",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "doc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json -n \"Example documentation\" --includes doc --hideGenerator --theme material",
    "doc:serve": "npm run doc -- -s -w"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@compodoc/compodoc": "^1.0.9",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}
```
</p></details>

<details><summary>.angular-cli.json</summary><p>

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "compodoc-issues"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}
```
</p></details>

##### **Compodoc installed globally or locally ?**

Locally

##### **Reproduce the error**

The version of code with routes registered inside the modules. Doesn't generate the Routes page at all.
https://github.com/vorotech/compodoc-issues/tree/compodoc_no_routes

The version of code with routes moved to separate modules and imported to main modules.
https://github.com/vorotech/compodoc-issues/tree/compodoc_see_routes

<details> <summary>Routes screenshot</summary><p> 

![image](https://user-images.githubusercontent.com/2937451/37975459-11c8df1a-31e8-11e8-81d8-20022542f6c2.png)
</p></details>

<details> <summary>Overview screenshot</summary><p> 

![image](https://user-images.githubusercontent.com/2937451/37975481-1cfecc82-31e8-11e8-9045-daf44ae0d78a.png)
</p></details>  

<br/>
Git diff:  

https://github.com/vorotech/compodoc-issues/compare/compodoc_no_routes...compodoc_see_routes

##### **Related issues**

The https://github.com/compodoc/compodoc/issues/488 might be the same.

##### **Suggest a Fix**

No suggestions.

**Comment by vogloblinsky** [comment]
@Jonatthu the demo project contains routes defined in other module or in a constant inside another file.
https://github.com/compodoc/compodoc-demo-todomvc-angular/tree/master/src/app/about
Do you have an example please ?

**Comment by masteryada378** [comment]
This is still happening on version 1.1.9 @vogloblinsky

**Comment by alexagranov7** [comment]
This is still happening in version 1.1.10.
