### ISSUE TITLE
[QUESTION] How to hide internal components which shouldn't be documented.

### ISSUE THREAD

**Issue by galuwka** [compodoc/compodoc#519]
##### **Overview of the issue**
In our project we don't want to document inner component which are reused in our main components.
Is it possible to hide some components in compodoc, maybe using some hack?

##### **Operating System, Node.js, npm, compodoc version(s)**
node.js v6.10 npm v3.10

##### **Compodoc installed globally or locally ?**
globally 

##### **Motivation for or Use Case**
To hide components which shouldn't used by our customers.

Thank you in advance :)

**Comment by vogloblinsky** [comment]
```
/**
 * @ignore
 */
export class MyComponent {
...
}
```
