### ISSUE TITLE
[BUG] Incorrect Path to Files if no markdown in root folder

### ISSUE THREAD

**Issue by Chris3773** [compodoc/compodoc#524]
##### **Overview of the issue**

In the version 1.1.1 of compodoc the paths that are created are pointing to the wrong location.

`compodoc -p tsconfig-build.json -d ./docs --disablePrivate --disableInternal --theme material`

Version 1.0.9:
![image](https://user-images.githubusercontent.com/22506071/38143054-dd27b548-340c-11e8-92df-890ca8c51c87.png)

Version 1.1.1:
![image](https://user-images.githubusercontent.com/22506071/38143069-eb7726e2-340c-11e8-9468-1aecd223d0c8.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc: 1.1.1
Typescript version : 2.8.1
Node.js version : v8.9.4
Operating system : Windows 10

**Comment by vogloblinsky** [comment]
Hi

I cannot reproduce this issue with your environment.

In which page did you see `href=".../styles/material.css"` ?

Thanks

**Comment by Chris3773** [comment]
Looking more into the issue it's only a problem for the "index.html" file.

On a hunch I added a README.md file to my project and tried again and it worked just fine. So the issue only happens when the project is missing a README.md file.
