### ISSUE TITLE
[FEATURE] Asciidoc support

### ISSUE THREAD

**Issue by NicolasDeclercq** [compodoc/compodoc#530]
Could Asciidoc support for readme files and additional documentation be added to compodoc?

**Comment by vogloblinsky** [comment]
Compodoc use [Marked](https://github.com/markedjs/marked).
Maybe using the extension of the file we could switch to another parser uspporting Asciidoc

**Comment by IlCallo** [comment]
Since some time, a [JS AsciiDoc implementation](https://github.com/asciidoctor/asciidoctor.js/) is available and can probably be used to solve this issue.
