### ISSUE TITLE
[BUG] Can not show at sign started tag in example area.

### ISSUE THREAD

**Issue by tibszawo** [compodoc/compodoc#535]
##### **Overview of the issue**

Can not show at sign started tag in example area.

##### **Operating System, Node.js, npm, compodoc version(s)**

Operating System: Windows10, Node.js: v8.9.3, npm: 5.6.0, compodoc version: 1.0.9

##### **Compodoc installed globally or locally ?**

Compodoc installed locally

##### **Motivation for or Use Case**

Would like to show example usage for module.

##### **Reproduce the error**
```
/**
 * Example usage
 * 
 * ```
 * @NgModule({
 * declarations: [
 *   ....
 * ],
 * imports: [
 *   ...
 *   TestComp.forRoot({ modulName: 'test' } }),
 *   ...
 * ],
 * ...
 * })
 * ```
 */
@NgModule({
  imports: [
   ..
  ],
  declarations: [
  ...
  ],
  exports: [
    ...
  ],
  providers: [
   ...
  ]
})
```
##### **Suggest a Fix**

Double @ sign. Like: @@

**Comment by vogloblinsky** [comment]
Duplicate of https://github.com/compodoc/compodoc/issues/270
