### ISSUE TITLE
[FEATURE] Searching for keywords, components, interfaces, etc. returns nothing in the search.

### ISSUE THREAD

**Issue by bparkhurst** [compodoc/compodoc#537]
##### **Overview of the issue**

When we search for anything other than an exact component name, we don't get anything back in the results.  We can't really figure out how it is searching but it is pretty much useless.  This is a obviously a critical feature for a documentation tool and we are wondering if we can get someone to take a look at it.

##### **Operating System, Node.js, npm, compodoc version(s)**

Try searching on anything for components. keywords, component names, partial names, etc.  You will see it returns nothing unless you type the component name exactly.

##### **Angular configuration, a `package.json` file in the root folder**

This is our npm command:

        "doc": "compodoc -p src/tsconfig.app.json -a kinetic_logo.jpg --disableInternal --disableCoverage --disableSourceCode --disablePrivate --hideGenerator --disableGraph && open \"./documentation/index.html\"",

##### **Compodoc installed globally or locally ?**

locally

##### **Motivation for or Use Case**

You can't find anything using search in the documentation.

**Comment by vogloblinsky** [comment]
Yes i understand, Compodoc use lunr.js with a local index generated during documentation generation.

This could be an alternative : https://community.algolia.com/instantsearch.js

**Comment by bparkhurst** [comment]
So do you feel this could be fixed in the product?  This is a significant issue with the tool.  We love it, and would be willing to pay to help get this one fixed.

**Comment by vogloblinsky** [comment]
@bparkhurst thanks for your interest.
I will look at that asap with another way to present resuts easily
For the funding topic, there is an opencollective is you want to participate : https://opencollective.com/compodoc
Thanks by advance

**Comment by vogloblinsky** [comment]
First iteration on this issue : better results display, grouped by category

![localhost_8080__q todo](https://user-images.githubusercontent.com/2841805/39091091-6a0d3fea-45ed-11e8-8a9a-ed149f913f17.png)

**Comment by bparkhurst** [comment]
AWESOME!!!!

**Comment by vogloblinsky** [comment]
@bparkhurst I have added one-time donations in the collective, pick the one you want.
Thanks by advance
Regards

**Comment by bparkhurst** [comment]
What version do I need to update to in order to get this change?  We are on 1.1.2

**Comment by vogloblinsky** [comment]
In 1.1.3, will come very soon, this week or next one.

**Comment by bparkhurst** [comment]
Awesome!  We are releasing our software in 4 weeks so that is great timing.

**Comment by vogloblinsky** [comment]
I have updated 1.1.3 milestone : https://github.com/compodoc/compodoc/milestone/21
I just have some little bugs and features to include. Stay tuned.
