### ISSUE TITLE
[FEATURE] Use static data-target ids

### ISSUE THREAD

**Issue by manekinekko** [compodoc/compodoc#544]
## Curent behavior

Currently, we generate random target IDs (for menu items) `xs-injectables-links-module-AlgoliaModule-1a9144db-ebc8-4fb1-9fed-4eef05ea24d2`, eg:

```
<ul class="links collapse" id="xs-injectables-links-module-AlgoliaModule-1a9144db-ebc8-4fb1-9fed-4eef05ea24d2" >
```

When iterating on the documentation multiple times, even if the content of a file hasn't changed, we'll still have new generated target IDs which would force us to recommit those files.

We should compute those IDs based on some static yet unique value, eg. the page name (or path) being processed. 

## Expected behavior

Generate a new `target-id`value only if the file content has changed.

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/commit/1ce6543ada4884491314e66cb6e571e50ae6a739
