### ISSUE TITLE
[FEATURE] Git hook + documentation coverage 

### ISSUE THREAD

**Issue by manekinekko** [compodoc/compodoc#546]
Add the ability to run compodoc as a linting tool to report documentation coverage issues. This is similar to what the `lintstagged` tool does.

Having this feature would allow compodoc to run as a git hook, for instance.

**Comment by vogloblinsky** [comment]
@manekinekko 
From what i have read, a package like https://github.com/typicode/husky does the job ?
After installation, add the corresponding npm script :

```
...
	"precommit": "compodoc -p src/tsconfig.app.json --coverageTest 65"
...
