### ISSUE TITLE
[BUG] Using absolute path for -p/--tsconfig results in an error

### ISSUE THREAD

**Issue by IgorAufricht** [compodoc/compodoc#558]
##### **Overview of the issue**
When using an absolute path for the `-p`/`--tsconfig` parameter, a TS error like this is thrown:
```
error TS5058: The specified path does not exist: 'C:\dev\code\test\C:\dev\code\test\tsconfig.json'.
```

##### **Operating System, Node.js, npm, compodoc version(s)**
Win 10, npm 6, compodoc 1.1.2

##### **Angular configuration, a `package.json` file in the root folder**
Doesn't matter.

##### **Compodoc installed globally or locally ?**
Doesn't matter.

##### **Motivation for or Use Case**
I would expect I can pass either relative or absolute path.

##### **Reproduce the error**
1. Start with any working compodoc setup.
2. Run `npx compodoc -p $(pwd)/tsconfig.json` (or just `compodoc -p $(pwd)/tsconfig.json` if installed globally)

##### **Suggest a Fix**
A naive approach suggests using something like `path.resolve(tsConfigPath)` would fix the problem.

**Comment by demiro** [comment]
this issue is still around! if I define the -p path as absolute path, I get the same error

**Comment by vogloblinsky** [comment]
@demiro can you explain a little more your context ?
