### ISSUE TITLE
[BUG] "Unamed property" for Function Types interfaces

### ISSUE THREAD

**Issue by willgm** [compodoc/compodoc#565]
##### **Overview of the issue**

When documenting Function Types the "Documentation coverage" reports one missing item, which is a "Unamed property". Is it right? Is there any way to document this property?

##### **Operating System, Node.js, npm, compodoc version(s)**

Linux Fedora 27, Node v8.9.0, NPM v5.5.1, Compodoc v1.1.2

##### **Reproduce the error**

This piece of code:
```ts
/**
 * Builder function for the WebSocket object
 */
export interface IWebSocketBuilder {
  /**
   * @param appUrl Url of your project
   * @returns Minimal required WebSocket interface to use the real time module
   */
  (appUrl: string): IWebSocket;
}
```

Generates this Documentation coverage:
![captura de tela de 2018-05-14 17-31-00](https://user-images.githubusercontent.com/2189998/40021913-abe616a6-579c-11e8-96da-8ddc50386271.png)

With this description:
![captura de tela de 2018-05-14 17-31-24](https://user-images.githubusercontent.com/2189998/40021917-b5450b9e-579c-11e8-848e-00d53836429c.png)

**Comment by manekinekko** [comment]
Hi, can you try with this sample and let me know if you still have this issue:

```
/**
 * Builder function for the WebSocket object
 */
export interface IWebSocketBuilder {
  /**
   * @param appUrl Url of your project
   * @returns Minimal required WebSocket interface to use the real time module
   */
  appUrl: string: IWebSocket;
}
```

**Comment by manekinekko** [comment]
this seems to come from the fact that this property is an unnamed function: `(appUrl: string): IWebSocket;`.  Can you provide a sample code where you reference this function?
