### ISSUE TITLE
[BUG] Duplicate pages for injectables with custom decorators

### ISSUE THREAD

**Issue by CMoyle336** [compodoc/compodoc#581]
##### **Overview of the issue**

On injectables with multiple decorators or custom decorators, compodoc generates a duplicate page.

##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc: 1.1.3
OS: Windows 10
NPM: 5.6.0
Node.JS: 10.2.0
Angular/cli : 6.0.3
Angular: 6.0.4

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "ngs-workspace",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "deploy": "node node_modules/ng-salesforce/scripts/deploy-script.js",
    "setup": "node node_modules/ng-salesforce/scripts/setup-script.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.4",
    "@angular/common": "^6.0.4",
    "@angular/compiler": "^6.0.4",
    "@angular/core": "^6.0.4",
    "@angular/forms": "^6.0.4",
    "@angular/http": "^6.0.4",
    "@angular/platform-browser": "^6.0.4",
    "@angular/platform-browser-dynamic": "^6.0.4",
    "@angular/router": "^6.0.4",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "angular-star-rating": "^4.0.0-beta.3",
    "angular2-ladda": "^2.0.0",
    "animate.css": "^3.6.1",
    "archiver": "^2.1.1",
    "arrive": "^2.4.1",
    "bootstrap": "^4.1.1",
    "bootstrap-material-design": "^4.1.1",
    "chart.js": "^2.7.2",
    "core-js": "^2.5.4",
    "css-star-rating": "^1.2.4",
    "inquirer": "^5.2.0",
    "jquery": "^3.3.1",
    "ng-lazyload-image": "^4.0.0",
    "ng2-charts": "^1.6.0",
    "ng2-page-scroll": "^4.0.0-beta.12",
    "ngx-gallery": "^5.3.2",
    "ngx-slick": "^0.1.3",
    "node-sass": "^4.9.0",
    "open-iconic": "^1.1.1",
    "popper.js": "^1.14.3",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.1.0",
    "slick-carousel": "^1.8.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular-devkit/build-ng-packagr": "~0.6.0",
    "@angular/cli": "6.0.3",
    "@angular/compiler-cli": "^6.0.4",
    "@angular/language-service": "^6.0.4",
    "@apttus/ecommerce": "0.0.6",
    "@compodoc/compodoc": "^1.1.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "convert-units": "^2.3.4",
    "crypto-js": "^3.1.9-1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jsforce": "^1.8.4",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "locale-currency": "0.0.2",
    "lodash": "^4.17.10",
    "ng-packagr": "^3.0.0-rc.2",
    "ng-salesforce": "^0.1.89",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tsickle": ">=0.25.5",
    "tslib": "^1.7.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }
}

##### **Compodoc installed globally or locally ?**

Compodoc installed both globally and locally

##### **Motivation for or Use Case**

I have a custom decorator for my injectables in my library and, because of this, compodoc generators an extra page.

##### **Reproduce the error**

Create an injectable
Create a custom decorator
Use the custom decorator on the injectable
Run compodoc

**Comment by vogloblinsky** [comment]
@CMoyle336 could you provide a simple example for debugging purpose ? thanks

**Comment by CMoyle336** [comment]
@vogloblinsky My code looks something like this: https://plnkr.co/edit/WonRMjGxUUjlDUbE9wPf

**Comment by CMoyle336** [comment]
Thanks @vogloblinsky !
