### ISSUE TITLE
[BUG] @example + Angular decorator goes wrong

### ISSUE THREAD

**Issue by Chazing** [compodoc/compodoc#584]
##### **Overview of the issue**

When i wrote comment on  class, and in the code there is '@', the code black window not appear in the compodoc generated documentation, and the comment cut off/

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc version: 1.1.3

##### **Compodoc installed globally or locally ?**

locally

##### **Reproduce the error**

Write this code on class

\/**
  \* Usage example
  \* \```typescript
  \* export class FormExampleComponent {
 \* @ViewChild("pnl", { read: ViewContainerRef }) pnl: ViewContainerRef;
  \* constructor() { }
\*}
  \* \```
  \* \```html
  \* <div #pnl>
  \* </div>
  \* \```
 */
@Injectable()
export class SomeService {
...
  }
 run compodoc, and then you can see that the documentation not generated correctly.

Thanks

**Comment by vogloblinsky** [comment]
Duplicate of #203

**Comment by vogloblinsky** [comment]
Duplicate of #270
