### ISSUE TITLE
[Question] Is there an API documentation?

### ISSUE THREAD

**Issue by Itrulia** [compodoc/compodoc#587]
Hey :)

I am currently creating a custom angular/cli library builder and I want to embed compodoc in it. I don't want to use the CLI but the actual JavaScript.

Is there any documentation about that I can use? Unfortunately I wasn't able to find any.

**Comment by vogloblinsky** [comment]
Have a look at this : https://github.com/compodoc/gulp-compodoc/
It use the JS API and not the CLI

**Comment by Itrulia** [comment]
This is enough for me to work with it. Thanks!
