### ISSUE TITLE
[BUG] exclude files that aren't generated from being included in modules

### ISSUE THREAD

**Issue by mattlewis92** [compodoc/compodoc#59]
##### **Overview of the issue**
Currently if you exclude internal services / components etc for your lib, they still get referenced by the NgModule but no docs are generated for them.

##### **Suggest a Fix**
The list of files that will be generated is available from the beginning of the run, so the module generation code should just look up each dependency in this array first and exclude them if not included.

**Comment by vogloblinsky** [comment]
Did you have a use-case for clarification ?

**Comment by mattlewis92** [comment]
Sure thing, so on my calendar I have a load of internal components that the main externally usable ones are made up from: https://github.com/mattlewis92/angular-calendar

I exclude them via tsconfig so no docs get generated for them, but the parent `NgModule` still links to them.

Happy to work on a PR for this as well once I have some free time 😄
