### ISSUE TITLE
[FEATURE] Create .rst files to be able to use ReadTheDocs to export to any format

### ISSUE THREAD

**Issue by totkeks** [compodoc/compodoc#595]
##### **Overview of the issue**

I started wanted to start the discussion, whether it would make sense to have compodoc generate .rst files, which could be fed to sphinx/readthedocs in order to generate documentation in more formats than just HTML.

This issue came up, because we want to document things with readthedocs style documentation. I know there is a nice readthedocs theme for compodoc, but that is not the same.

What do you think about this?

**Comment by vogloblinsky** [comment]
Do you have an example of an open-source project with documentation using ReadTheDocs ?

**Comment by totkeks** [comment]
Sorry for the late reply.
It would look something like this http://mattermost-bot.readthedocs.io/ and the source files are here https://github.com/LPgenerator/mattermost_bot/blob/master/docs/index.rst

I was thinking that using the user written .md files (or maybe even .rst) in the angular project plus the files generated by your compodoc, would allow for a nice documentation. Basically the additional files would augment the compodoc documentation generated from classes and modules and so on.

**Comment by TheoLechemia** [comment]
+1 
It would be very usefull for a project who already has a readthedoc.

**Comment by vogloblinsky** [comment]
@TheoLechemia can you explain a little more the workflow you need ?

**Comment by TheoLechemia** [comment]
I already have a readthedoc site which read some .rst files from my github repo: https://geonature.readthedocs.io/fr/latest/
Compodoc is great, and I want to include it in my readthedoc to avoid have 2 differents sites for my doc.
