### ISSUE TITLE
[BUG] Child Class consider parent  method on the doc, but not JSDoc tags

### ISSUE THREAD

**Issue by rafapaulin** [compodoc/compodoc#599]
I have one parent class and one child class, both fully documented.

On the doc page of the child, all methods inherited from the parent are shown correctly, including the line reference where they are defined.

The issue is, on the code-coverage page, the child component computes all the methods of the parent, but not its documentation, leaving a flawed statistic.

**Comment by vogloblinsky** [comment]
Cannot reproduce.
Could you please share here a sample of two components to reproduce it. And a screenshot of the code coverage page you got.
Thanks
