### ISSUE TITLE
using todo mvc generating doc

### ISSUE THREAD

**Issue by daniele-zurico** [compodoc/compodoc#6]
Hi,
I checkout the project mvc and trying to run it on my side:
```
./node_modules/.bin/compodoc -f src/tsconfig.json -d doc
```

the generation process complete successfull running this command:
```
./node_modules/.bin/compodoc -f src/tsconfig.json -d doc
```
but when I try to run:

```
Danieles-MacBook-Pro-2:compodoc-demo-todomvc-angular2-master danielezurico$ compodoc -s
[11:22:49] Serving documentation at http://127.0.0.1:8080
[11:22:49] Entry file was not found
```

what I missed?

In the script n[m run doc there's that one:
-b https://compodoc.github.io/compodoc-demo-todomvc-angular2/
but no idea what it should be

**Comment by vogloblinsky** [comment]
I will fix that tonight and explain a bit more the serve flag with two scenarios : 
-  -f and -s (and -d)
-  -s and -d
I think you are in the second one, and compodoc doesn't correctly handle that.

**Comment by daniele-zurico** [comment]
```
Danieles-MacBook-Pro-2:~ danielezurico$ compodoc -d
[15:29:18] Entry file was not found
```
