### ISSUE TITLE
[FEATURE] Verbosity for coverage tests

### ISSUE THREAD

**Issue by leonboot** [compodoc/compodoc#606]
##### **Overview of the issue**

The compodoc CLI tool allows for running coverage tests. A full report with files that either meet or do not meet the minimum required percentage of coverage are either displayed in green or red lines. It would be nice to be able to show only the files that do not meet the requirements (maybe include the summary, too).

##### **Motivation for or Use Case**

We're using compodoc in our CI process. Running the coverage tests return too much information, the only relevant information for fixing a build that is broken due to a low coverage are the files that need additional docblocks. Providing the `--silent` option returns no output at all, so if our build fails due to compodoc exiting with a non-zero exit code, we have no clue as to what caused the build to fail.

##### **Suggest a Fix**

It would be handy if there was a `--show-only-failed` option.

**Comment by vogloblinsky** [comment]
Which flag do you use with the CLI ?

**Comment by leonboot** [comment]
The CI process runs compodoc with these parameters: `--silent --coverageTest=80 --coverageMinimumPerFile=80 --coverageTestThresholdFail`.

**Comment by vogloblinsky** [comment]
Ok, i think it will not change the default behavior and the exit status, so i can add the list of failing files easily.

**Comment by leonboot** [comment]
@vogloblinsky it indeed seems `--coverageTestThresholdFail` determines whether the exit code will be zero or non-zero. The non-zero code is good since it fails the build. All I'd need is a `--not-too-silent` and I'd be able to find the failure cause in the build log :)

**Comment by vogloblinsky** [comment]
Ok, --show-only-failed will do the trick. I keep that in mind

**Comment by vogloblinsky** [comment]
@leonboot i will implement the flag --coverageTestShowOnlyFailed but sorry the silent flag is too global and i cannot do an exception just for --coverageTestShowOnlyFailed flag.

**Comment by leonboot** [comment]
@vogloblinsky Sounds good to me! Looking forward to seeing this update in the next release 👍
