### ISSUE TITLE
[BUG] Route docs are not generated

### ISSUE THREAD

**Issue by x1unix** [compodoc/compodoc#607]
##### **Overview of the issue**

Routes information is not populated in generated docs.
Used [angular-started](https://github.com/gdi2290/angular-starter) as example for testing.

[Generated docs screenshot](http://prntscr.com/k64f0e)

##### **Operating System, Node.js, npm, compodoc version(s)**

* **Node**: `v9.11.1`
* **OS**: macOS 10.13, Windows 10
* **Compodoc**: `1.1.3`

##### **Angular configuration, a `package.json` file in the root folder**

Use [angular-starter](https://github.com/gdi2290/angular-starter) sources.

##### **Compodoc installed globally or locally ?**

Both

##### **If possible sourcecode of the file where it breaks**

Use [angular-starter](https://github.com/gdi2290/angular-starter) sources.

##### **Reproduce the error**

1. Clone [angular-starter](https://github.com/gdi2290/angular-starter).
2. Run `npm install` or `yarn install`
3. Generate docs using compodoc: `npm run docs:compodoc`
4. View docs: `npm run docs:compodoc:generate`

No route section generated

##### **Related issues**

https://github.com/compodoc/compodoc/issues/257

**Comment by vogloblinsky** [comment]
Ok i have found the main problem. It seems that in main.browser.ts, the `platformBrowserDynamic().bootstrapModule(AppModule)` is inside a function. Compodoc tries to find it directly at the root of the file.

**Comment by aziz-haddad** [comment]
same here, is this issue still there?

**Comment by x1unix** [comment]
@aziz-haddad got the issue resolved on the latest compodoc version.

**Comment by rever96** [comment]
I have the same problem.
package.json
```
[...]
  "engines": {
    "node": "8.10.0",
    "npm": "6.9.0"
  },
"scripts":{
[...]
    "compodoc": "npx compodoc -p src/tsconfig.app.json"
},
"devDependencies":{
[...]
"@compodoc/compodoc": "^1.1.9"
}
```
heres are my app.module.ts and app.routing.ts
[app..zip](https://github.com/compodoc/compodoc/files/3141885/app.zip)

I run "npm run compodoc" and get no errors, but the doc miss the routing page

**Comment by cybtroxy** [comment]
Yep, same problem here.

I though the const name should be "APP_ROUTES", but it doesn't matter, issue still there.
My app.module.ts has this in the imports:

`RouterModule.forRoot(
      appRoutes,
      {
        enableTracing: false, // <-- debugging purposes only
      }),`

For now we don't have routes in our docs. It's a "nice to have" hehe.

Great tool :D
