### ISSUE TITLE
[BUG] "Get dependencies data" stops without error

### ISSUE THREAD

**Issue by lexon0011** [compodoc/compodoc#61]
I try with the following command to generate a documenation of my angular 2 app:

`compodoc -p .\tsconfig.json -d doc`

The process exists without an error message, but nothing was generated. 

![image](https://cloud.githubusercontent.com/assets/16290662/21801761/57c851c4-d723-11e6-95da-208d06211296.png)

The app.component.ts file **doesn't work** with following content:

```
import { Component } from "@angular/core";
import { Router } from "@angular/router";
import { Location } from "@angular/common";

@Component({
    selector: "prm",
    template: `
        <div>
        <h1>test</h1>        
        </div>
    `
})
export class AppComponent {
    constructor(private router: Router, private location: Location) {
    }
}
```

I found out, that if I remove the constructor parameters, the file **works**:
```
import { Component } from "@angular/core";
import { Router } from "@angular/router";
import { Location } from "@angular/common";

@Component({
    selector: "prm",
    template: `
        <div>
        <h1>test</h1>        
        </div>
    `
})
export class AppComponent {
    constructor() {
    }
}

```

Thats my tsconfig.json
```
{
    "version": "2.1.4",
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "moduleResolution": "node",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "removeComments": true,
        "noImplicitAny": true,
        "declaration": false,
        "outDir": "dist/appbuild/app"
    },
    "exclude": [
        "node_modules",
        "typings/main",
        "typings/main.d.ts"
    ]
}
```

Does anyone knows what the problem might be?? Thanks for helping!

**Comment by vogloblinsky** [comment]
Hi,
I added yesterday the support of public properties in constructor for the documentation generation.
Your issue seems related to this feature. I miss to test private properties, i just tested public properties.
I watch that asap.

**Comment by nadhir-falta** [comment]
still getting the same thing, it stops the second it hits the first constructor in the app.
