### ISSUE TITLE
[QUESTION] Angular 6 Projects support

### ISSUE THREAD

**Issue by froodley** [compodoc/compodoc#610]
##### **Overview of the issue**

Seems like Angular 6 projects folder is ignored; need to include in the documentation

**Comment by vogloblinsky** [comment]
@froodley can you explain a little more ?

**Comment by arn-the-long-beard** [comment]
Hello.
I am using compodoc and it works perfectly  for normal Angular project.  ( I like it a lot 👍  )

We are talking for projects generated with the command :` ng generate library mylibrary`

Such library project are generated inside a " workspace " ( just a standard angular project ) in the folder ./projects, 

When I run compodoc in such "workSpace" , the ./projects/mylibrary folder is ignored and I cannot get documentation for the library.

Is there something to do to generate the documentation for a homemade angular library ( located in the ./projects/mylybrary ? :)
The way angular libraries are made is different in Angular 6. So maybe we are missing something somewhere :)

**Comment by froodley** [comment]
What he said :D

Sorry for not elaborating more in the original post, I only had a second at the time.

CompoDoc doesn't pick up on ./projects libraries, as stated.  Since this is the "new way" going forward with Angular to develop and deploy modules, it is essential that compodoc be able to parse these repos so we can share the docs for the libraries with our developers.

**Comment by arn-the-long-beard** [comment]
Hello,

I found out a way to do it.

In the package.json of the workspace ;

add this in the script file => compodoc -p  projects/mylibrary/tsconfig.lib.json -s -o -w

Then it works.

But I am not sure this is the proper solution.
It was simple ( I try it Saturday but I did not see that the name if tsconfig.lib.json instead of tsconfig.app.json

What do you think about it ?

**Comment by froodley** [comment]
Thanks!  That worked like a charm.  This needs to be added to the official documentation, although in retrospect it's a bit obvious :P

**Comment by santoshyadav198613** [comment]
I am going through same issue, when i add comments in my code ng build library-name gives lot of warning and error. Any fix for this issue.

**Comment by kunjan343** [comment]
Actually there is some confusion with the new structure especially when we deal with documentation.
In some apps, `./projects` contain user defined module packages which we need to include along with default project it self. But for the others, they can also develop multiple applications in one angular universal project.
Should we have to leave it same or need to define documentation based on list of projects?

**Comment by jvegaCUBA** [comment]
Hi there, you can generate documentation for your referenced project if you set your main tsconfig.json file like this script file =>"compodoc -p tsconfig.json -s -o -w" and the tool generate documentation for all items in both projects if it's are referenced in tsconfig.json file 

good luck ;)

**Comment by frontr-uk** [comment]
This is great and works, but it fails to create the doc for the app itself once you introduce ./projects

**Comment by vogloblinsky** [comment]
@frontr-uk Could you share your project folders structure ?

**Comment by abadakhshan** [comment]
@arn-the-long-beard

What should I do if I have multiple dependent libraries?

I don't want to create separate documentation for each of them. I want to have a unified documentation site, for all my libraries.

**Comment by abadakhshan** [comment]
I think my solution works.
But I'm not sure It's true or not.
Please check it.

https://github.com/compodoc/compodoc/issues/767#issuecomment-485065816

**Comment by maxandriani** [comment]
> I think my solution works.
> But I'm not sure It's true or not.
> Please check it.
> 
> [#767 (comment)](https://github.com/compodoc/compodoc/issues/767#issuecomment-485065816)

it does not when you have multiple library projects. The seconds lib overrides the first one.
