### ISSUE TITLE
[FEATURE] Do you have a plan for the internationalization ?

### ISSUE THREAD

**Issue by lichangfeng** [compodoc/compodoc#611]
I am from china,I want a doc use zh_cn. Do you have a plan for the internationalization ?

**Comment by vogloblinsky** [comment]
Hi, i can implement the codebase for that, and you can do a PR for the translations ?

**Comment by lichangfeng** [comment]
Ok，thank you，I'll do that.

**Comment by vogloblinsky** [comment]
@lichangfeng Codebase is eady for i18n
You can do a PR by adding your locale in `./src/locales` folder

**Comment by lichangfeng** [comment]
@vogloblinsky Hi~
How can I use it when I add a locale file as zh_CN? Is it a command param of compodoc?

**Comment by lichangfeng** [comment]
@vogloblinsky I did it, but when I run: 
compodoc ./src -d ./compodoc -p tsconfig.json --theme stripe --hideGenerator --disableSourceCode --disableTemplateTab --disableDomTree --language=zh_CN
it not works.

**Comment by vogloblinsky** [comment]
Oh sorry, i miss a step :
- run npm start after the npm install, it will compile the CLI localy

**Comment by lichangfeng** [comment]
@vogloblinsky ,it still not work, I try npm start and npm build.

**Comment by lichangfeng** [comment]
@vogloblinsky , I run the cmd in another project:
compodoc ./src -d ./compodoc -p tsconfig.json --theme stripe --hideGenerator --disableSourceCode --disableTemplateTab --disableDomTree --language=zh_CN

**Comment by vogloblinsky** [comment]
After your npm start you should have this :

```
> @compodoc/compodoc@1.1.3 start /home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc
> npm run test:watch


> @compodoc/compodoc@1.1.3 test:watch /home/vogloblinsky-local/Documents/www/TMP/compodoc/compodoc
> npm-watch

No task specified. Will go through all possible tasks
[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: src/**/*.ts
[nodemon] starting `npm run -s build`

./src/index-cli.ts → dist/index-cli.js...
created dist/index-cli.js in 3.3s

./src/index.ts → dist/index.js...
created dist/index.js in 3.2s
[nodemon] clean exit - waiting for changes before restart
```

**Comment by lichangfeng** [comment]
@vogloblinsky Yes, I have done a PR with the locale.

**Comment by vogloblinsky** [comment]
Cool i have cleaning and adding a control on the requested language with the flag.
Release tonight 1.1.4 if all is fine.

**Comment by lichangfeng** [comment]
@vogloblinsky , I will create another PR to complete zh_CN.ts.
