### ISSUE TITLE
[BUG] Interface will not show as documented

### ISSUE THREAD

**Issue by tcoz** [compodoc/compodoc#612]
##### **Overview of the issue**

Coverage report does not show documented interface. 

##### **Operating System, Node.js, npm, compodoc version(s)**

Mac OS 10.12.5, Node v8.11.1, npm 6.2.0, Angular CLI 6.0.8, compodoc 1.1.3

##### **Angular configuration, a `package.json` file in the root folder**

I can not reveal the package.json (work related etc). I am using a CLI-generated workspace, modified with the nx workspace schematics. 

##### **Compodoc installed globally or locally ?**

Locally

##### **If possible sourcecode of the file where it breaks**

No break in particular. The interface just shows up in red in the coverage report. No amount of fiddling with the JSDoc alters this. 

##### **If possible your terminal logs before the error**

Again, not really an "error" in this manner. The interface just will not show as documented in the coverage report. 

##### **Motivation for or Use Case**

Can't achieve 100% coverage. (It's not just this interface, but this one interface is a shining example; it is fully documented, exactly as other interfaces elsewhere in the project, but this one won't show as doc'd). 

##### **Reproduce the error**

In file auth-feature.reducers.ts, I have an interface, doc'd this way:

/**
 * Interface for [etc...]
 * @interface AuthFeatureData
 * @export AuthFeatureData
 */
export interface AuthFeatureData { ... }

##### **Related issues**

All in all, it looks like all my ngrx files will not doc. I have classes (e.g. Actions) that will not show as doc'd no matter what I try. There's a couple of other items that have the same problem, but I suspect if I can focus on this one (since it is overt), I can probably see what I'm doing wrong (or what is going wrong) elsewhere. 

##### **Suggest a Fix**

How do I get these showing as doc'd?

**Comment by vogloblinsky** [comment]
Could you restart without any jsdoc comment before AuthFeatureData and see if it appears in the doc ?

**Comment by tcoz** [comment]
Tried it, it made a difference, but unfortunately not the desired one. Possibly a hint...

When I remove any kind of comment at all (so nothing there), and regen the docs, the file in question drops to the top of the list, red. 0% doc'd. 

When I put the comment back, (with or without attributes, they do not appear to make any diff, per your docs that seems to check out), the file is still red, but doc'd at 4%. 

There are no other interfaces in the docs, and the file itself is very small (a very simple ngrx reducer). 

I can't post that file, but, here's the structural description...

There is an interface, constant, and function. All of them are exported. There's nothing else in the file (except the JSdoc comments on the constant and function). They are contained in a folder named "+state" (this appears to be an evolving convention for naming ngrx-specific folders). 

Interestingly, the constant and function do not show up on the coverage list at all.

**Comment by tcoz** [comment]
Here's an example, maybe you can tell me what I'm doing wrong. 

/**
 * When the user "selects all", this gets broadcast out for all other rows to hear.
 */
export interface SelectAllEvent {
  selectall: boolean;
}

This interface won't show up as doc'd no matter what I do. It continues to appear as a red line item in the document coverage list.

**Comment by paulstelzer** [comment]
Keep in mind to add comments to each parameter too

/**
 * When the user "selects all", this gets broadcast out for all other rows to hear.
 */
export interface SelectAllEvent {
/**
* Select all
*/
  selectall: boolean;
}

**Comment by tcoz** [comment]
That doesn't appear to be a requirement for getting an interface to appear as documented. I mentioned that the problem appears isolated to the interfaces in the ngrx files. Otherwise my interfaces in other files (where I do not doc the internals) appear covered.

**Comment by vogloblinsky** [comment]
Cannot easily reproduce the bug.
Do you have 5' of time to create a simple repo reproducing the issue ?
Thanks

**Comment by codephobia** [comment]
I was having the same issue, but looks like it was a problem with the watcher. Upon closer inspection I was seeing two entries for the interface, one with 100% coverage and one with 0%. Rebuilding the docs from scratch resolved the duplication.

**Comment by tcoz** [comment]
I'll see if I can gen something today.

**Comment by tcoz** [comment]
FYI I'll be picking this back up in earnest. I'm using compodoc on a pretty weighty project.
