### ISSUE TITLE
[BUG] Trailing comma in routing definitions

### ISSUE THREAD

**Issue by PhilippSoehnlein** [compodoc/compodoc#62]
##### **Overview of the issue**

compdoc can't parse route definitions that have trailing commas in it, because compodoc uses a JSON parser for that.
It would be nice if compodoc could actually could handle routes defined with trailing commas. 

##### **Motivation for or Use Case**
We have a strict trailing comma policy (enforced via tslint) and therefore compodoc fails to generate routing documentation for us.

##### **Reproduce the error**

Define a route definition that has trailing commas.

##### **Related issues**

This is a follow-up to #26.
Oh, and #51 is basically the same problem.

##### **Suggest a Fix**

I currently do a temporary search and replace to get rid of the trailing commas in the routing definition with the following regex: `myCode.replace(/,(\s*[}\];])/gm, '$1');`
I understand that this is not a real fix, because as always with regex parsing it leaves to many loopholes (comments for example). Retrieving the routes with a real syntax parser is better.
The code line in question is this one: https://github.com/compodoc/compodoc/blob/7c48c3a51d990b0531b1e5a5fdd51521a8ff0db2/src/app/compiler/dependencies.ts#L317

**Comment by vogloblinsky** [comment]
I am working on a refactoring of routes support, with lazy loading, childs etc, and a better routes page with a cool D3.js graph.
The JSON.parse will be deleted, and a routes handling used with AST to code generation.
Keep in touch in the next days.
