### ISSUE TITLE
[BUG]: Function return value is formatted wrongly in the docs

### ISSUE THREAD

**Issue by skasgarv** [compodoc/compodoc#622]
##### **Overview of the issue**
Assume I have a Angular 5+ service and a function inside the service as follows
`
@Injectable()
export class ABC {

	/**
	* Gets some data
	* @returns Map<string, number>
	*/

	get someData(): Map<string, number> {

		// do something here

	}
}
`

When I run compodocs and generate the docs, Returns section is wrongly formatted to `Map<stringnumber>` instead of **Map<string, number>**
The comma in the return type is ignored.

##### **Operating System, Node.js, npm, compodoc version(s)**
Windows 10 64 bit OS
node v6.12.0
npm 3.10.10
@compodoc/compodoc": "~1.1.2"

##### **Angular configuration, a `package.json` file in the root folder**
Not needed. You can replicate the issue using the example provided above.

##### **Compodoc installed globally or locally ?** Locally

Any  help regarding this issue is greatly appreciated. Thank you.

**Comment by skasgarv** [comment]
![capture](https://user-images.githubusercontent.com/18016940/44362145-1c2fb500-a48e-11e8-84c2-8c56b681662e.PNG)

**Comment by vogloblinsky** [comment]
@skasgarv could you do a test with last version, 1.1.3 ?

**Comment by skasgarv** [comment]
@vogloblinsky 
I tested with version 1.1.3 and the problem still exists. 
Also I can see the commit has been pushed to "develop" branch and not to version 1.1.3.

Can we reopen this Issue  please.
Thank you so much.
