### ISSUE TITLE
[QUESTION] Is there a way to hide the Overview link?

### ISSUE THREAD

**Issue by YoussefTaghlabi** [compodoc/compodoc#627]
##### **Overview of the issue**
Is there a way to hide the Overview link? 

![image](https://user-images.githubusercontent.com/1639024/44631131-19bdd700-a936-11e8-94ab-62c01cf0f02c.png)

**Comment by YoussefTaghlabi** [comment]
I can do it via css but it will be nice to have a CLI flag

**Comment by vogloblinsky** [comment]
Yes, but for now use a custom css and hide the section with it.
Regards
