### ISSUE TITLE
[BUG] Route data using enum causes parse error

### ISSUE THREAD

**Issue by slubowsky** [compodoc/compodoc#632]
##### **Overview of the issue**

Using an enum in route definition (specifically in data) crashes compodoc. Using a number instead if the enum allows it to complete.
Build fails with:
```
Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Expected to find an initializer.
  ....
```

##### **Operating System, Node.js, npm, compodoc version(s)**

Angular CLI: 6.1.5
Node: 10.9.0
Npm: 6.2.0
OS: win32 x64
Angular: 6.1.6
Compodoc: 1.1.5

##### **Compodoc installed globally or locally ?**

local

##### **If possible sourcecode of the file where it breaks**

```
const routes: Routes = [{
  path: '',
  component: MyComponent,
  // Enum breaks compodoc
  // data: { dataType: SomeEnum.entry },
  // number works...
  data: { dataType: 2 },
  resolve: {
    myValue: MyValueResolve
  }
}];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  ...
```

**Comment by bartios** [comment]
Looks like #525 to me, I'm having the exact same issue.

**Comment by jizza** [comment]
Same issue:
```
const routes: Routes = [
  { path: 'path/:id', component: DetailsComponent, data: { tab: Tabs.all } },
];
```
