### ISSUE TITLE
[QUESTION] NPM INSTALL FAILURE:  extract:ts-simple-ast: verb gentlyRm don't care about contents; nuking

### ISSUE THREAD

**Issue by DamengRandom** [compodoc/compodoc#633]
I am a Windows user, and my current facing issue is I cannot install Compodoc package into my local codebase. 

When I run this command: 'npm install --save-dev @compodoc/compodoc', the installation is like never finish until I click Ctrl + C. 

Any hands for help?

**Comment by vogloblinsky** [comment]
What is your version of Node.js, npm ? OS ?

**Comment by DamengRandom** [comment]
Hi there, my node version is 8.11.3, and my npm version is 4.0.5, and my OS is Windows 10.

Any specific version required in order to install this compodoc plugin?

**Comment by DamengRandom** [comment]
I have updated my npm version to 6.4.1 and also updated/installed newer vscode version, and then I have successfully installed compodoc package. I guess it might be caused by the npm and vscode version issues. Anyway, it works now.
