### ISSUE TITLE
[DISCUSSION] Projects using Compodoc

### ISSUE THREAD

**Issue by maurei** [compodoc/compodoc#635]
I really enjoyed generating the documentation for [my project ](https://maurei.github.io/ngx-table-editor/) using compodoc. I noticed you have a [list of projects](https://compodoc.app/guides/miscellaneous.html) using compodoc. If you want to list mine to, would be nice, feel free :)

**Comment by vogloblinsky** [comment]
Thanks i will add it.

**Comment by vogloblinsky** [comment]
From those coming here, feel free to list your project here.

**Comment by Airblader** [comment]
@vogloblinsky I'm still in the process of getting to shipping 1.0, but I am using compodoc for the API docs for https://ngqp.io. The documentation is still in the works, though. :-)

**Comment by vogloblinsky** [comment]
@Airblader Project added, thanks for using it.

**Comment by rmasonh18** [comment]
I note that documentation coverage can be quite extensive (50 ..for example) which I would like to keep but not enforce. In other words, I like how the tool renders the documentation even if developer does not document the code per required specs. But I would like to only enforce a required header file with copyright notice meanwhile keep the other documentation produced by the tool and change the coverage to green when header file is in place. Any suggestions as to how to enable such feature within compodoc?

**Comment by vogloblinsky** [comment]
@rmasonh18 i don't think it is the role of compodoc to handle that. Linting tools are here for that, have a look at that : https://github.com/Stuk/eslint-plugin-header
