### ISSUE TITLE
[REQUEST] i18n locales

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#636]
Since 1.1.4 i18n is added inside Compodoc for generated documentation.

If anyone is interested for enhancing the tool or requesting a particular language, post a message here.

**Comment by predorock** [comment]
I can provide translation for italian language

**Comment by vogloblinsky** [comment]
@predorock Cool, i have added a doc for that : https://github.com/compodoc/compodoc/blob/develop/docs/i18n.md
Thanks by advance

**Comment by predorock** [comment]
I have translate all the keywords in Italian, but i cannot figure out how to translate the menu item "additional documentation". I have also translate it in french but seems to not be traslatable, is possible to traslate the menu item? or seem to be a bug?

**Comment by predorock** [comment]
Yes the translation is correct. I have added the pr on compodoc repo.
Thanks @vogloblinsky

**Comment by mercury83** [comment]
Hey @vogloblinsky! I've just opened a PR to provide hungarian language translations.
