### ISSUE TITLE
[BUG] Issue while running installation command on Windows 10

### ISSUE THREAD

**Issue by mghildiy** [compodoc/compodoc#641]
I am facing an issue running following command on Windows 10.

npm i -g @compodoc/compodoc
This command never completes. Stuck at message:

verb gentlyRm don’t care about contents; nuking C:\Users….

**Comment by vogloblinsky** [comment]
what are your versions of Node.js and npm ?
Can i ave the full logs of your terminal ?
Thanks

**Comment by mghildiy** [comment]
npm version:
4.6.1

node version:
v8.10.0

Logs contain company specific data. So I  would need to talk to people in my org.

**Comment by vogloblinsky** [comment]
Ok, did it works in your project ?

```
npm i -D @compoddoc/compodoc
```

**Comment by mghildiy** [comment]
No.
Command failed, saying
'artifactory' is not in npm registry.

**Comment by vogloblinsky** [comment]
@mghildiy watch this thread : https://github.com/npm/npm/issues/11834

**Comment by mghildiy** [comment]
@vogloblinsky thanks for the link.

**Comment by kunjan343** [comment]
Mine installed successfully with node package version 8.9.1. Try to use this version, it is more likely to be compatible with other packages.
![screenshot 3](https://user-images.githubusercontent.com/8202667/45685751-0d5d2080-bb68-11e8-9dbd-fb2b6c293219.png)
