### ISSUE TITLE
Frantic sidebar refresh

### ISSUE THREAD

**Issue by peterennis** [compodoc/compodoc#645]
##### **Overview of the issue**

Demo.
Click on sidebar links.
https://compodoc.github.io/compodoc-demo-todomvc-angular/miscellaneous/typealiases.html
![compo](https://user-images.githubusercontent.com/140737/45187429-772f0f00-b1e5-11e8-97c7-b8083ce53fad.gif)

**Comment by vogloblinsky** [comment]
Hi @peterennis it is a normal behavior. There is a little JavaScript file that detect the activated link in the menu, and scroll to it after a little delay when the page opens.
