### ISSUE TITLE
[FEATURE] Initial sorting of documentation coverage table

### ISSUE THREAD

**Issue by Spielboerg** [compodoc/compodoc#646]
##### **Overview of the issue**

Since I updated to 1.1.5, the documentation coverage table is no longer sorted ascending by the statements column but descending. Thus perfectly documented files are at the top, while the "problem files" are not visible at first.

##### **Motivation**

My workflow:
1. Generate documentation
2. Check which files are not 100% or highly covered.
3. Add documentation in these files
4. After changing one or more files, I regenerate the documentation to check again if I missed any missing documentation

To find files with lower coverage, I now have to manually sort the table by "statements". I know it's not a big issue but it's a little bit annoying (especially if you know that it has worked before).

##### **Preferred Fix**

Change the sorting settings to the previous version or add an option flag like `--coverageSorting` with possible parameters:
file-asc, file-desc,
type-asc, type-desc,
identifier-asc, identifier-desc,
statements-asc, statements-desc

**Comment by vogloblinsky** [comment]
In the last version and in the demo project, sorting is done by default now with statements-desc : https://compodoc.github.io/compodoc-demo-todomvc-angular/coverage.html
