### ISSUE TITLE
[FEATURE] styleUrls tab in component detail view

### ISSUE THREAD

**Issue by daniel-leroux** [compodoc/compodoc#648]
##### **Overview of the issue**
I dont see any SCSS tab in component detail view.

Example:
```typescript
@Component({
  selector: 'example-test',
  template: `<div class="test">Hello World!</div>`,
  styleUrls: ['./test.component.scss']
})
export class Forms {
}
```

```scss
:host {
 .test {
    background-color: red;
 }
}
```

After 'compodoc -s' i see only Info, Source and Template but no Style(scss) tab.

##### **Angular configuration, a `package.json` file in the root folder**

Angular 6 with CLI and sub projects

##### **Compodoc installed globally or locally ?**

Locally

##### **Related issues**

#399

**Comment by vogloblinsky** [comment]
This could be a feature. It is not a bug. Right now, compodoc doesn't handle the file referenced inside __styleUrls__

**Comment by ehnruiz** [comment]
@vogloblinsky What would be involved in order to complete this feature.  I would like to contribute if possible but I am not familiar with the compodox codebase.  Thank you

**Comment by danielleroux** [comment]
@vogloblinsky @ehnruiz I have just implemented the feature, but im not able to create a Pull Request.

**Comment by vogloblinsky** [comment]
@daniel-leroux we cross developed i think the feature. You should be able to push a PR on the develop branch. You have to fork the repo first. I will wait your implementation to compare them.
Thanks
