### ISSUE TITLE
[BUG] Compodoc not generating but including

### ISSUE THREAD

**Issue by FeezyHendrix** [compodoc/compodoc#650]
Windows 10, node 8 angular 6

![image](https://user-images.githubusercontent.com/27918971/45369179-35370c00-b5dd-11e8-8db4-e5cf1776165c.png)

It appears to see the files but it's not generating

**Comment by MarkoCen** [comment]
Same here, 
Windows 10,
node 10.3,
angular 7.0-beta

**Comment by vogloblinsky** [comment]
@FeezyHendrix 
Can i have the full logs ?

**Comment by settergren** [comment]
I had the same issue and I solved it by removing an angular 1.75 dependency in my package.json. I'm not sure how it got in there since I'm using @angular 6+.

I noticed that the compdoc logs said something about detecting AngularJS.

After removing the dependency everything is working great!

**Comment by matcho** [comment]
Same issue here. Below are the dependencies (from `package.json`). Can't figure out which one makes Compodoc believe it's an AngularJS project…

```
"dependencies": {
    "@angular/animations": "^7.1.4",
    "@angular/common": "^7.1.4",
    "@angular/compiler": "^7.1.4",
    "@angular/core": "^7.1.4",
    "@angular/forms": "^7.1.4",
    "@angular/http": "^7.1.4",
    "@angular/platform-browser": "^7.1.4",
    "@angular/platform-browser-dynamic": "^7.1.4",
    "@angular/router": "^7.1.4",
    "angular-bootstrap-md": "^7.1.1",
    "angular2-chartjs": "^0.5.1",
    "core-js": "^2.6.1",
    "file-saver": "^2.0.0",
    "font-awesome": "^4.7.0",
    "he": "^1.2.0",
    "mathjax": "^2.7.5",
    "ngx-md": "^7.0.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "tslib": "^1.9.0",
    "webpack-dev-server": "^3.1.14",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.11.4",
    "@angular/cli": "^7.1.4",
    "@angular/compiler-cli": "^7.1.4",
    "@angular/language-service": "^7.1.4",
    "@types/file-saver": "^2.0.0",
    "@types/jasmine": "~3.3.5",
    "@types/jasminewd2": "^2.0.6",
    "@types/node": "^8.0.0",
    "codelyzer": "^4.5.0",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "^5.4.2",
    "ts-node": "~7.0.1",
    "tslint": "~5.12.0",
    "typescript": "~3.1.1"
  }
```

**Comment by jmlopez-rod** [comment]
In my case I have found that when using the flag `--coverageTest 70` (the help menu says that it defaults to 70) then no documentation is generated. If I remove it then it just generates but there is no way of stopping it.

Are we supposed to do 2 calls? One with the coverage test to fail in case we go below a certain percentage and the next one to generate the docs?

```
compodoc: 1.1.9

TypeScript version used by Compodoc : 2.9.1

TypeScript version of current project : 3.3.3333

Node.js version : v8.14.0

Operating system : macOS Mojave
```
