### ISSUE TITLE
[Feature] Allow ability to password protect passed parameter to Live-server module for serve.

### ISSUE THREAD

**Issue by crtjer** [compodoc/compodoc#651]
##### **Overview of the issue**

As a developer, I would like the ability to password protect the documentation. Given Compodoc uses live-server, which accepts a parameter for a password file path, we could allow the ability to pass a password path over to them.

##### **Motivation for or Use Case**
You may have a public facing url for hosting but want a simple auth shared with a development group so they can access the documentation.

##### **Suggest a Fix**

A simple new parameter option to pass to the live-server declaration.

**Comment by vogloblinsky** [comment]
__live-server__ is used for me just during development phase, in watch mode for example or when you are writing your documentation.
For me after that, you have to host somewhere your generated documentation with an usual server like Apache or nginx. With them you could easily add a .htpasswd file and protect your documentation.
It is not for me the responsability of compodoc to manage that.
