### ISSUE TITLE
how to use i18n is ZH-CN?(如果把文档生成中文版的？)

### ISSUE THREAD

**Issue by luohong123** [compodoc/compodoc#652]
##### **Overview of the issue**
I input commands on the GIT tool is`compodoc -p src/tsconfig.app.json --theme postmark --disableSourceCode --disableGraph --disableTemplateTab --disableDomTree --disableCoverage --disablePrivate --disableProtected --disableInternal --disableLifeCycleHooks --hideGenerator`  ,how to use i18n is ZH-CN commands ?（我在git工具上输入自动生成文档的命令，让文档中文化命令是如何使用的？）

**Comment by vogloblinsky** [comment]
Sorry i miss to add the flag in the documentation website, fixed now : https://compodoc.app/guides/usage.html
