### ISSUE TITLE
[BUG] relative links for search results break when you are in a subfolder

### ISSUE THREAD

**Issue by Waldbillig-Thomas** [compodoc/compodoc#653]
##### **Overview of the issue**

when doing a search, the links of the search results are relative
this works correctly when you are on the root page but if you are on the following page:
```http://localhost:8080/modules/AppModule.html```
and search for the appmodule for example the resulting link will be as follows:
```<a href="modules/AppModule.html">module - AppModule</a>```
which will redirect you to:
```http://localhost:8080/modules/modules/AppModule.html```
instead of 
```http://localhost:8080/modules/AppModule.html```

##### **Operating System, Node.js, npm, compodoc version(s)**

ubuntu@18.04
npm@6.4.1
compodoc@0.0.41
##### **Compodoc installed globally or locally ?**

locally

##### **If possible sourcecode of the file where it breaks**

could not find it

##### **If possible your terminal logs before the error**

no errors in terminal

##### **Motivation for or Use Case**

redirecting to a nonexisting page

##### **Reproduce the error**

see above

##### **Related issues**

/

##### **Suggest a Fix**

change search-result-item link have a static href link

**Comment by vogloblinsky** [comment]
Please could you update to last version, 1.1.5, cannot reproduce your bug, and you are on a previous version of compodoc.
thanks

```
npm i -D @compodoc/compodoc
```
