### ISSUE TITLE
[QUESTION]: Is there a way to hide certain sections in Compodocs

### ISSUE THREAD

**Issue by skasgarv** [compodoc/compodoc#655]
First of all, thank you for an amazing project :)

I have been using Compodocs to generate documentation for my Angular project and I have a question.

On the left side of Compodocs, we see various sections such as Getting Started, Modules, Classes and so on.

Suppose I want to hide a section. For example Miscellaneous section should be not been seen in compodocs.  Is that possible?

Use case: The documentation generated by the project will be consumed by external users.  I have used @internal tags to hide items that the end user should not be concerned with.
Now I want to hide Miscellaneous section as well since the end users will not be concerned about the internal enums, type aliases and functions.

If hiding the entire Miscellaneous section is not possible, is there a way to hide subsections?

Any help regarding the issue is deeply appreciated.

Thank you.

**Comment by vogloblinsky** [comment]
Hi, there is no way to do that right now insted using a custom css file and hiding sections in the menu.
