### ISSUE TITLE
[QUESTION/FEATURE] Ability to group classes and functions separately

### ISSUE THREAD

**Issue by chrillewoodz** [compodoc/compodoc#656]
##### **Overview of the issue**
I'm using Angular and I have two or more folders which I'd like to group by type, not class/function.

For instance I have a folder called `decorators` and another one called `validators`, however in the docs they show up under `miscellanous/functions` and `classes` instead of `decorators` and `validators`. Is there any way to control how they are grouped? The folder structure in your project should be persisted in the docs in my opinion. Or if it could somehow be configurable using either tsconfig's `paths` or the compodoc config file.

##### **Motivation for or Use Case**
This would make it more clear what the classes/functions actually are to the reader rather than having to find it out from digging in the src code.

**Comment by vogloblinsky** [comment]
Compodoc tries to stay closed to first nature of the code inside your file. It is for that they end up inside misc/functions.
May be with a custom JSDoc tags we could add this feature.

**Comment by chrillewoodz** [comment]
That does sound like a good solution, any idea when this could be implemented?

**Comment by jefersonduwe** [comment]
I would like this feature too.

**Comment by jefersonduwe** [comment]
Could this issue be reopened?
I would really like this feature.
