### ISSUE TITLE
[BUG] compodoc --port 8090 => Entry file was not found

### ISSUE THREAD

**Issue by jeka5555** [compodoc/compodoc#66]
When you try to change the port, an error occurs: "Entry file was not found". 

![image](https://cloud.githubusercontent.com/assets/1672108/21933332/e230f2e6-d99c-11e6-9ac6-43e225b75c33.png)

**Comment by vogloblinsky** [comment]
You miss to specify the tsconfig file

**Comment by jeka5555** [comment]
I set the path to the file in package.json : **"compodoc": "./node_modules/.bin/compodoc -p ./tsconfig.json"**

**Comment by jeka5555** [comment]
my tsconfig.json file:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es2015", "dom" ],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  }
}

```

**Comment by vogloblinsky** [comment]
Can i have a screenshot of your directory structure ? the first screenshot display node_modules only.

**Comment by jeka5555** [comment]
Attached, what you asked:

![image](https://cloud.githubusercontent.com/assets/1672108/21972317/a5439bb6-dbb0-11e6-902b-14cf2d772557.png)

**Comment by jeka5555** [comment]
The project is deployed in a directory **\web\new-customer-portal\src\main\webapp**

![image](https://cloud.githubusercontent.com/assets/1672108/21972526/203a00fc-dbb2-11e6-9672-d3f4ef0a00b4.png)

**Comment by jeka5555** [comment]
I can give more some information to help you solve the problem?

**Comment by vogloblinsky** [comment]
Ok, if i understand well, you want to serve the generated documentation after the generation or not ?
Your npm scripts task does just generation right now, add the ```-s``` flag to serve directly.

**Comment by jeka5555** [comment]
Thank you! Indeed, I executed the commands in sequence, and it was necessary to immediately:

`compodoc -r -s 8090`
