### ISSUE TITLE
[FEATURE] generate docs for nested modules

### ISSUE THREAD

**Issue by joeattardi** [compodoc/compodoc#660]
##### **Overview of the issue**

In our application, we have a `shared` module directory which, in turn, contains several nested modules. Running compodoc against this project does not generate documentation for these nested modules or components. 

##### **Motivation for or Use Case**

It would be nice to have documentation for our nested modules as well so that our project is completely documented.

**Comment by TimArsen** [comment]
This would be great! If they generated docs for all modules imported by modules in your /src folder, this would fix the issue.
