### ISSUE TITLE
[FEATURE] Compodoc to measure documentation coverage

### ISSUE THREAD

**Issue by RomanKisilenko** [compodoc/compodoc#67]
##### **Motivation for or Use Case**
It is very useful to know if the team documents the code as it is specified in project standards. For this, measuring the documentation coverage (i.e. number of items documented versus total number of items which can be reasonably documented) is a valuable tool. 

For instance, esdoc generates the coverage report for ES6 code and we find it very useful to process results automatically in a CI.

**Comment by vogloblinsky** [comment]
Hi,
Yes, it could be a nice feature. I keep this idea for next major release.
R.
