### ISSUE TITLE
[BUG] private tags and unexported functions

### ISSUE THREAD

**Issue by jmlopez-rod** [compodoc/compodoc#671]
There are some function which we may define in files which are more like utility functions so they do not get exported. Since they are not methods there is no way to attach the `private` modifier to it.

As a result compodoc generates documentation for it. I have seen that if I add the tag `@private` then the documentation does not get generated. See these screenshots:

```ts
/**
 * @private Utility function to control the animation.
 */
function sinInOut(t: number): number {
  return (1 - Math.cos(Math.PI * t)) / 2;
}
```

![screen shot 2018-10-05 at 5 39 43 pm](https://user-images.githubusercontent.com/1810397/46563178-ab215100-c8c5-11e8-96cc-b639b92f0b08.png)

If I remove the `@private` then the documentation gets attached.

```ts
/**
 * Utility function to control the animation.
 */
function sinInOut(t: number): number {
  return (1 - Math.cos(Math.PI * t)) / 2;
}
```

![screen shot 2018-10-05 at 5 40 43 pm](https://user-images.githubusercontent.com/1810397/46563210-d015c400-c8c5-11e8-87da-4c6c05c77f22.png)

## Bug?

If we add the `@private` tag then there shouldn't be anything generated for it and thus it should not count in the documentation coverage as it currently does.

Even though I added comments because it has the `@private` tag I get this:

![screen shot 2018-10-05 at 5 42 58 pm](https://user-images.githubusercontent.com/1810397/46563282-25ea6c00-c8c6-11e8-8570-dade3aea05be.png)

## Versions:
```
$ tsc --version
Version 3.0.1
$ compodoc --version
1.1.5
```

**Comment by jmlopez-rod** [comment]
You can also see in these screnshots that compodoc was not able to figure out the type of the parameter because they are in a function as already reported in https://github.com/compodoc/compodoc/issues/647.

**Comment by vogloblinsky** [comment]
Use @ignore to simple ignore this function

**Comment by JustinBeckwith** [comment]
👋 Greetings!  I'm interested in submitting a fix for this, if it would be considered.  Would it be cool if I opened a PR?
