### ISSUE TITLE
[BUG] Left navigation is missing in Internet Explorer 11

### ISSUE THREAD

**Issue by child-of-god** [compodoc/compodoc#673]
When I am trying to view the documentation generated in Internet explorer, the left navigation menu is missing. But its visible when run in Chrome browser. Please find the below script errors captured from Internet Explorer's console.

 SCRIPT1002: Syntax error
File: menu-wc.js, Line: 3, Column: 40

SCRIPT1002: Syntax error
File: lazy-load-graphs.js, Line: 1, Column: 50

The issue is replicable if you run the demo app https://compodoc.github.io/compodoc-demo-todomvc-angular/ in IE browser.

**Comment by vogloblinsky** [comment]
which version of IE ?
I think a polyfill for menu web component is missing.

**Comment by child-of-god** [comment]
Hi @vogloblinsky ,
Thanks for the quick response. I am  using IE 11 for testing. Please do let me know if you need any more details.

Regards,
Vishnu

**Comment by vogloblinsky** [comment]
Ok related to IE11 custom elements support + ES6 class.
Need to had a polyfill + transpile correctly menu-wc.js file to ES5.

**Comment by child-of-god** [comment]
Sure, will wait for the 1.1.6 milestone. Thanks .
