### ISSUE TITLE
[FEATURE] Multi ignore properties in classes

### ISSUE THREAD

**Issue by clm2609** [compodoc/compodoc#674]
##### **Overview of the issue**

I'm documenting some components with their expected inputs, use examples and descriptions, but i don't want some of the properties or methods to appear in my documentation, as this documentation is for someone to use the component.  Using @ignore on every one of them is tedious and will bloat my code. I cannot set them up as private as I use them in my template or they are implementations of interfaces. 

##### **Suggest a Fix**

Something like @multiignore-start and @multiignore-end would be nice and anything between this tags would then be ignored by the doc generator
```ts
/**
* @multiignore-start
*/
properties and methods here are ignored
/**
* @multiignore-end
*/
```

**Comment by nejsimon** [comment]
This would be awesome!

Right now I have something like:
```ts
  /**
   * @internal
   */
  foo = 1;

  /**
   * @internal
   */
  bar = "";

  /**
   * @internal
   */
  baz = false;
```

Lots of comment lines for just three lines of properties.
