### ISSUE TITLE
[BUG] "tsconfig.json" file was not found in the current directory

### ISSUE THREAD

**Issue by Limpuls** [compodoc/compodoc#679]
Running command  compodoc -p src/tsconfig.json does not produce any documentation but instead gives back an error saying:

> "tsconfig.json" file was not found in the current directory

tsconfig.json is included inside project folder and I run the command from project folder.

**Comment by vogloblinsky** [comment]
Can i have more information about your project structure ? The command you use ? thanks

**Comment by awacode21** [comment]
I don't know something about @Limpuls project structure. But i created an own bug ticket here: https://github.com/compodoc/compodoc/issues/687
Is that enough information or do you need any further information?

**Comment by margaritluch** [comment]
I experience the same problem now, so i guess the isssue hasnt been solved yet :/

**Comment by margaritluch** [comment]
Just found the [answer](https://stackoverflow.com/questions/50869875/documentation-of-angular-project-using-compodoc) to all my worries. Sharing it here, so everyone can use :)

**Comment by vogloblinsky** [comment]
@Limpuls issue still relevant ?
