### ISSUE TITLE
[BUG] Documentation of parameters

### ISSUE THREAD

**Issue by lexon0011** [compodoc/compodoc#68]
I tried to document the parameters of a method wih the following code:

```
/**
 * @param {string} somebody Somebody's name.
 */
public sayHello(somebody) {
    alert('Hello ' + somebody);
}
```

Unfortunately, the description of the parameter is not included in the generated documentation. Is there a way to do it?

**Comment by vogloblinsky** [comment]
Typescript AST API provide simple comment extraction without support of JSDoc tags.
https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript
I will add a complete support like Typedoc soon.

**Comment by lexon0011** [comment]
Thank you very much! Is approximately estimated until the feature is available?

**Comment by vogloblinsky** [comment]
Already done yesterday night after found the TypeScript internal API for it.
I am just finishing another great feature "Documentation coverage" and release soon a new version, maybe this afternoon. :smile:

**Comment by lexon0011** [comment]
Incredible! Thanks for doing it so fast!

**Comment by vogloblinsky** [comment]
Feedbacks are motivating a lot :smile:

**Comment by lexon0011** [comment]
Thanks, the feature works great!
