### ISSUE TITLE
[BUG] @example Code examples do not work with code blocks

### ISSUE THREAD

**Issue by BrunnerLivio** [compodoc/compodoc#684]
##### **Overview of the issue**

When trying to run the following JSDoc:

```JavaScript
/**
   * Checks if the database responds in (default) 1000ms and
   * returns a result object corresponding to the result
   * @param key The key which will be used for the result object
   * @param options The optional options for the database ping check
   * 
   * @example
   * ```TypeScript
   * databaseHealthIndicator.pingDb('db', { timeout: 800 });
   * ```
   */
```

I get the following result

![compodoc_bug](https://user-images.githubusercontent.com/9899423/47958762-6c6cdc80-dfd2-11e8-843e-80cc559fa513.png)

This occured with my **NestJS** project

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc: 1.1.6
node: 9.11.2
os: ubuntu 17.10

##### **Compodoc installed globally or locally ?**

Locally

**Comment by kinwa91** [comment]
+1. Also seeing this issue.
