### ISSUE TITLE
[BUG] Not able to run compodoc on windows machine

### ISSUE THREAD

**Issue by awacode21** [compodoc/compodoc#687]
##### **Overview of the issue**

When trying to run compodoc on a windows machine it is throwing an error that says "Provided source folder Frontend was not found in the current directory". Apart from the fact that we do not use any folder called "Frontend" we also never configured something like that.
We simply installed compodoc and run it with the standard config file.
The problem is only existing on windows. On my mac there is no problem at all. So what is wrong with configuration?

##### **Operating System, Node.js, npm, compodoc version(s)**

Operating System: Windows 10
Compodoc version: 1.1.6
Typescript version: 3.1.3
npm version 6.4.1
node version 10.10

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "my-frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "prod": "ng build --base-href=/upload/",
    "test": "ng test",
    "lint": "ng lint",
    "stylelint": "stylelint '**/*.scss'",
    "e2e": "ng e2e",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json -w -s -o --hideGenerator --includes src/docs -d ./docs -n 'Frontend - Documentation' --theme 'material'"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.0.2",
    "@angular/cdk": "^7.0.2",
    "@angular/common": "^7.0.2",
    "@angular/compiler": "^7.0.2",
    "@angular/core": "^7.0.2",
    "@angular/forms": "^7.0.2",
    "@angular/http": "^7.0.2",
    "@angular/material": "^7.0.2",
    "@angular/platform-browser": "^7.0.2",
    "@angular/platform-browser-dynamic": "^7.0.2",
    "@angular/router": "^7.0.2",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.8",
    "@fortawesome/free-solid-svg-icons": "^5.5.0",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "normalize.css": "^8.0.0",
    "rxjs": "^6.0.0",
    "stylelint-scss": "^3.3.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.4",
    "@angular/compiler-cli": "^7.0.2",
    "@angular/language-service": "^7.0.2",
    "@compodoc/compodoc": "^1.1.6",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "stylelint": "^9.6.0",
    "stylelint-config-standard": "^18.2.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~3.1.6"
  }
}

##### **Compodoc installed globally or locally ?**

locally

##### **If possible sourcecode of the file where it breaks**

not known

##### **If possible your terminal logs before the error**

> compodoc -p src/tsconfig.app.json -w -s -o --hideGenerator --includes src/docs -d ./docs -n 'Frontend - Documentation' --theme 'material'

1.1.6
 
Typescript version : 2.9.1
 
Node.js version : v10.10.0
 
Operating system : Windows 10
 
[14:08:10] No configuration file found, switching to CLI flags.
[14:08:10] Provided source folder Frontend was not found in the current directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-frontend@0.0.0 compodoc: `compodoc -p src/tsconfig.app.json -w -s -o --hideGenerator --includes src/docs -d ./docs -n 'Frontend - Documentation' --theme 'material'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-frontend@0.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

##### **Motivation for or Use Case**

On my project team, we want to use compodoc as documentation tool for our Angular project. But apart from me, the whole team is using windows machines and not able to run compodoc. My Mac is the only machine where it is running. So if we do not find a fix, we need to reject compodoc.

##### **Reproduce the error**

npm run compodoc in project root folder using a windows machine

##### **Related issues**

--

##### **Suggest a Fix**

--

**Comment by Skrutten** [comment]
Have the same problem:

[10:49:45] Process page   : routes
Unhandled Rejection at: Promise {
  <rejected> TypeError: Cannot read property 'depth' of undefined
    at Object.eval [as main] (eval at createFunctionContext (XXXXXXXXXXXXXXXXXXXX\node_modules\@compodoc\compodoc\node_modules\handlebars\dist\cjs\handlebars\compiler\javascript-compiler.js:254:23), <anonymous>:8:93)
    at main (XXXXXXXXXXXXXXXXXXXX\node_modules\@compodoc\compodoc\node_modules\handlebars\dist\cjs\handlebars\runtime.js:175:32)

**Comment by awacode21** [comment]
I am not sure if it is the same problem when you have a complete different error message?

**Comment by Skrutten** [comment]
@awacode21 sorry. I read your case like a drunk donkey

**Comment by vogloblinsky** [comment]
@awacode21 seems related to quotes with Windows in command line. 
Watch the section " https://compodoc.app/guides/usage.html " in this link : https://compodoc.app/guides/usage.html

**Comment by awacode21** [comment]
Makes sense! Thank you for your help!
