### ISSUE TITLE
[BUG] TypeError: Cannot read property 'configuration' of undefined

### ISSUE THREAD

**Issue by MarkTiedemann** [compodoc/compodoc#69]
Running `compodoc -p src/tsconfig.json -y src/my-theme/ -s`, I get a `TypeError`:

```
C:\...\node_modules\compodoc\dist\index-cli.js:2620

fs.copy(... + path.sep + this.configuration.mainData.output + '/styles/'), function (err) {

TypeError: Cannot read property 'configuration' of undefined
```

If I go to[ `dist/index-cli.js:2620`](https://github.com/compodoc/compodoc/blob/master/dist/index-cli.js#L2620) and change `this.configuration.mainData.output` to `that.configuration.mainData.output`, it works (since in line `2614`, `var that` is assigned ` = this;`).

Edit: Found the bug in [`src/app/application.ts:355`](https://github.com/compodoc/compodoc/blob/b9af14b26ec476cbac6918e80f54d4b676fb189f/src/app/application.ts#L355).

Hope this helps. :)

**Comment by vogloblinsky** [comment]
Thanks reproduced and fixed, fix coming with next release.

**Comment by MarkTiedemann** [comment]
Thanks, @vogloblinsky! That was a quick fix. :)
