### ISSUE TITLE
[FEATURE] Lazy Loaded Routes

### ISSUE THREAD

**Issue by timwright35** [compodoc/compodoc#690]
##### **Overview of the issue**

Currently it does not seem that the routes that are lazy loaded in the system are found and used in the routers section of the generated documentation.

##### **Operating System, Node.js, npm, compodoc version(s)**

Node v8.12.0
npm 6.4.1
compodoc 1.1.5

##### **Angular configuration, a `package.json` file in the root folder**

package.json in root folder, no clue what else is needed here, no config for compodoc in here.

##### **Compodoc installed globally or locally ?**

Globally and locally

##### **If possible sourcecode of the file where it breaks**

N/A

##### **If possible your terminal logs before the error**

N/A

##### **Motivation for or Use Case**

A better visual of the routing system in the documentation

##### **Reproduce the error**

N/A

##### **Related issues**

Possibly #39 or #609

**Comment by PierreLucB** [comment]
The issue is still there with the last version of compodoc.
