### ISSUE TITLE
[FEATURE] NGRX sections

### ISSUE THREAD

**Issue by timwright35** [compodoc/compodoc#693]
##### **Overview of the issue**

Compodoc has the ability to figure out if something is a pipe etc and add it to the right section in the menu. It does not understand reducers/stores/etc. It would be nice to have sections that were for NGRX.

##### **Operating System, Node.js, npm, compodoc version(s)**

Linux, Node v10.13.0, npm v 6.4.1, compdoc 1.1.

##### **Compodoc installed globally or locally ?**

Both

##### **Motivation for or Use Case**

We use NGRX throughout our app and at the moment all the NGRX code is put into classes and miscellaneous. Not organized in a way that would make it easy to look up each store etc.

**Comment by mPrest-FE** [comment]
any news on this feature?

**Comment by Superd22** [comment]
+1 Is this something you'd consider ? Are PRs welcome ?

**Comment by jamesona** [comment]
I was excited to stumble across compodoc, but I'd have to consider it unusable without ngrx support. Having it report every action class as the same type of first order class as a data model is impossible to navigate.

**Comment by zd333** [comment]
+1

**Comment by NothingNatarajan** [comment]
Yes It would be nice to have NgRX pattern in the documentation with action flow and store diagram.

**Comment by 13ademeister** [comment]
+1

**Comment by sebastiandg7** [comment]
+1

**Comment by DUBANGARCIA** [comment]
+1

**Comment by cruncher19** [comment]
+1

**Comment by jamesona** [comment]
bump for relevance: actions are solved by newer ngrx patterns, but it would still be very nice to have first class recognition of effects and reducers
