### ISSUE TITLE
[BUG] - Vulnerability Identified in Event-stream, used by live-server@1.2.0

### ISSUE THREAD

**Issue by markwpearce** [compodoc/compodoc#696]
##### **Overview of the issue**

Current Compodoc version (in master) depends on live-stream@1.2.0, which contains the vulnerability identified here:

https://github.com/dominictarr/event-stream/issues/116

In Develop branch, the dependency to live-server has been updated to 1.2.1, which fixes the issue
(https://github.com/tapio/live-server/issues/285)

##### **Operating System, Node.js, npm, compodoc version(s)**

This impacts latest available Compodoc version (v1.1.6), although on the develop branch, v1.1.6 has been updated

##### **Suggest a Fix**

Suggestion: release new version (1.1.7) which fixes the vulnerability

**Comment by vogloblinsky** [comment]
I will release a new version tonight.

**Comment by markwpearce** [comment]
Wow. That was a fast response!

**Comment by YoussefTaghlabi** [comment]
A medium article that describes the attack in details: https://medium.com/intrinsic/compromised-npm-package-event-stream-d47d08605502

**Comment by FarajiA** [comment]
I've also opened an issue with Live Server so that they can use the most up to date version of  `event-stream`.
https://github.com/tapio/live-server/issues/286

**Comment by vogloblinsky** [comment]
Fixed by live-server 1.2.1 and last version of Compodoc 1.1.7
