### ISSUE TITLE
[FEATURE] : generate json only

### ISSUE THREAD

**Issue by valorkin** [compodoc/compodoc#7]
Please add an option to create only json with documentaion

**Comment by vogloblinsky** [comment]
Can you explain a bit more the feature ?
Do you just want something like that in ./documentation ?

```
{
    "modules": [{
        "name": "AppComponent",
        ...
    }],
    "components": [...]
    ...
}
```

**Comment by valorkin** [comment]
yep, it will be more than enough

**Comment by valorkin** [comment]
like coverage reports: json or|and html

**Comment by vogloblinsky** [comment]
What is the goal on having just an json file ?

**Comment by valorkin** [comment]
Than I can import this json and render api docs in ng2-bootstrap and other in a way I need

**Comment by vogloblinsky** [comment]
After some researches for compodoc enhancements, this example can be a good starting point : http://documentation.js.org/html-example/index.json
