### ISSUE TITLE
[BUG]: Route parsing

### ISSUE THREAD

**Issue by hajonsoft** [compodoc/compodoc#701]
![image](https://user-images.githubusercontent.com/9623964/49837523-7f09cc80-fd5b-11e8-88a3-dff408b34100.png)

**Comment by vogloblinsky** [comment]
Is it possible to have the sourcecode of prospects.common.ts ?

**Comment by Jonatthu** [comment]
@vogloblinsky This issue can be closed, but now we are having problems with generating the routes when we have the routes being loaded from a normal const

```
@NgModule({
	declarations: [
	],
	imports: [
		BrowserModule,
		BrowserAnimationsModule,
		RouterModule.forRoot(ROOT_ROUTES),
		...ROOT_IMPORT_MODULES
	],
	providers: [],
	bootstrap: [RootComponent],
})
export class AppModule { }

```
