### ISSUE TITLE
[BUG] JSDoc parser unable to parse "@"

### ISSUE THREAD

**Issue by jkwlui** [compodoc/compodoc#703]
##### **Overview of the issue**

Anytime there's a "@" character within a JSDoc tag (@param, @example), it is cut off from the documentation output:

<img width="819" alt="screen shot 2018-12-13 at 12 25 59 pm" src="https://user-images.githubusercontent.com/4001432/49965542-51935f00-fed2-11e8-9785-7ac61d561ec4.png">

Source:

```typescript
  /**
   * Simple method
   *
   * @example
   * Parses JSDoc correctly before the "@" and this doesn't show up
   */
  simpleMethod() {
  }
```

##### **Operating System, Node.js, npm, compodoc version(s)**

Node.js v10.12.0
npm v6.4.1
compodoc v1.1.7

##### **Angular configuration, a `package.json` file in the root folder**

```json
{
  "name": "compodoc-test-project",
  "version": "1.0.0",
  "scripts": {
    "docs": "compodoc -p tsconfig.json --output docs"
  },
  "devDependencies": {
    "@compodoc/compodoc": "^1.1.7"
  }
}
```

##### **Compodoc installed globally or locally ?**

locally

##### **If possible sourcecode of the file where it breaks**

`src/index.ts`
```typescript
class HelloWorld {
  /**
   * Simple method
   *
   * @example Parses JSDoc correctly before the "@" and this doesn't show up
   */
  simpleMethod() {
  }
}
```

##### **If possible your terminal logs before the error**

Normal

##### **Motivation for or Use Case**

We're trying to include examples for using our library, and it's npm package is published under a scope - `@organization/package-name` that's how we uncovered this issue.

##### **Reproduce the error**

1. Generate docs using compodoc and output html
2. Check the output

##### **Related issues**

There are similar issues with trying to include code using `@example` tag:
https://github.com/compodoc/compodoc/issues/684

##### **Suggest a Fix**

I'm suspecting it's because of the way JSDoc is parsed, so it's entirely likely that the issue lies in the the parser dependency of `compodoc`, however I don't have enough knowledge of the way the parser works so I'm hoping for some help here :)

**Comment by kinwa91** [comment]
I'm happy to submit a PR if you could point me to where the issue is!

**Comment by vogloblinsky** [comment]
@kinwa91 Thanks for the proposal. The issue is located inside TypeScript JSDoc tags parser...

I am investing time for evaluating TSDoc project which could help soon.

**Comment by kinwa91** [comment]
Thanks! [referencing](https://github.com/compodoc/compodoc/issues/634) `tsdoc` migration issue to track :)
