### ISSUE TITLE
[BUG] Missing components top level navigation item

### ISSUE THREAD

**Issue by Lightw3ight** [compodoc/compodoc#704]
##### **Overview of the issue**

No _Components_ node is visible as a top level navigation item
There is a _Modules_ that contains all my modules and their associated components but in a lot of cases we have a 1:1 relationship of modules to components so this node is un usable due to its size

##### **Operating System, Node.js, npm, compodoc version(s)**
Windows 10
Node:  10.11.0
Npm: 6.4.1
Compodoc ^1.0.9

##### **Angular configuration, a `package.json` file in the root folder**

```
scripts: {
    "docs:serve": "compodoc -p src/tsconfig.docs.json --extTheme helpers/docs/theme/ -a helpers/docs/assets --includes helpers/docs --disablePrivate --disableInternal --hideGenerator -s -r 8888",
}
```

Angular config
```
        "ng-ui": {
            "root": "projects/ng-ui",
            "sourceRoot": "projects/ng-ui/src",
            "projectType": "library",
            "prefix": "lib",
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-ng-packagr:build",
                    "options": {
                        "tsConfig": "projects/ng-ui/tsconfig.lib.json",
                        "project": "projects/ng-ui/ng-package.json"
                    }
                },
                "test": {
                    "builder": "@angular-devkit/build-angular:karma",
                    "options": {
                        "main": "projects/ng-ui/src/test.ts",
                        "tsConfig": "projects/ng-ui/tsconfig.spec.json",
                        "karmaConfig": "projects/ng-ui/karma.conf.js",
                        "scripts": [
                            "node_modules/jquery/dist/jquery.min.js",
                            "node_modules/select2/dist/js/select2.min.js"
                        ]
                    }
                },
                "lint": {
                    "builder": "@angular-devkit/build-angular:tslint",
                    "options": {
                        "tsConfig": ["projects/ng-ui/tsconfig.lib.json", "projects/ng-ui/tsconfig.spec.json"],
                        "exclude": ["**/node_modules/**"]
                    }
                }
            }
        },
```

tsconfig
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": ".",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "noImplicitAny": true,
        "target": "es5",
        "typeRoots": ["node_modules/@types", "projects/ng-ui/src/typings"],
        "lib": ["es2018", "dom"],
        "paths": {
            "@company/ng-ui": ["projects/ng-ui/src/public_api"],
            "@company/ng-ui/*": ["projects/ng-ui/src/lib/*"],
            "@company/ng-doc-tools": ["projects/ng-doc-tools/src/public_api"],
            "@company/ng-doc-tools/*": ["projects/ng-doc-tools/src/lib/*"]
        },
        "module": "es2015"
    }
}
```

library ts config
```{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "outDir": "../../out-tsc/lib",
        "baseUrl": ".",
        "target": "es2015",
        "module": "es2015",
        "moduleResolution": "node",
        "declaration": true,
        "sourceMap": true,
        "inlineSources": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "suppressImplicitAnyIndexErrors": true,
        "importHelpers": true,
        "types": ["jquery", "lodash", "node", "quill", "quill-delta"],
        "lib": ["dom", "es2018"]
    },
    "angularCompilerOptions": {
        "annotateForClosureCompiler": true,
        "skipTemplateCodegen": true,
        "strictMetadataEmit": true,
        "fullTemplateTypeCheck": true,
        "strictInjectionParameters": true,
        "enableResourceInlining": true
    },
    "exclude": ["src/test.ts", "**/*.spec.ts"]
}
```
##### **Compodoc installed globally or locally ?**

tried both

##### **If possible sourcecode of the file where it breaks**

I dont know where is breaks

##### **If possible your terminal logs before the error**

[11:25:11] Prepare modules
[11:25:11] Prepare directives
[11:25:11] Prepare injectables
[11:25:11] Prepare pipes
[11:25:11] Prepare classes
[11:25:11] Prepare interfaces
[11:25:11] Prepare miscellaneous
[11:25:11] Process documentation coverage report
[11:25:11] Adding external markdown files
[11:25:11] Additional documentation: summary.json file found
[11:25:11] Process main graph
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
[11:25:12] Ooops error during main graph generation, moving on next part with main graph disabled : : abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

##### **Motivation for or Use Case**

We would prefer to use the components node as the modules node is too big

##### **Reproduce the error**

I dont know if the above error is related to my issue or not, other than that error, it keeps building and appears to work fine

**Comment by vogloblinsky** [comment]
I am sorry, but you are facing an external effect of the main process of Compodoc for dealing modules elements.
Compodoc handles modules as a first source of reference, and if a component is declared inside, it will be references inside the module menu.
