### ISSUE TITLE
[QUESTION] Is there a way to skip the generation of Style sheet option alongside Source code and Template tab 

### ISSUE THREAD

**Issue by siddartha999** [compodoc/compodoc#705]
##### **Overview of the issue**
Is there a way to skip the generation of Style sheet tab, which is present beside the Info option for 
Components and Modules?

##### **Compodoc installed globally or locally ?**

Ideally we don't want to display the style sheet code in the documentation part. Is there away to skip that during the generation of the documentation folder, just like skipping the Source code and template tab.

**Comment by vogloblinsky** [comment]
--disableStyleTab should do the work

**Comment by siddartha999** [comment]
It works! Thanks!!
