### ISSUE TITLE
[FEATURE] : Embed images in markdown

### ISSUE THREAD

**Issue by zpydee** [compodoc/compodoc#71]
I'm trying unsuccessfully to embed images into the various README.md files in my documentation. Is this possible?

**Comment by vogloblinsky** [comment]
Not supported right now, but can add quickly an option for that.
What is the folders architecture of your project ?
The images will be stored on a specific folder ?

**Comment by zpydee** [comment]
actually, figured this out.

created `docs` and `docs/images` folder in advance and place my image there. compodoc kept the image file intact when it generated.

i think this is a good generic solution, so perhaps just add to documentation...

**Comment by zpydee** [comment]
alternatively, add support for a folder in `root` called (imho) `docs-images`

**Comment by zpydee** [comment]
actually, the latter may be better for users that add `/docs` to `.gitignore`.

perhaps add a flag `--images name-of-images-folder`?

**Comment by vogloblinsky** [comment]
Yep, i had that style of option in mind.

**Comment by zpydee** [comment]
i'll leave it for you to close the issue when you're ready :-)

**Comment by vogloblinsky** [comment]
Added in v0.0.34, have fun 👍

**Comment by zpydee** [comment]
Amazing, well done and thanks! If I have ideas for other features, I'll be sure to suggest.
Great tool by the way :-)

**Comment by vogloblinsky** [comment]
You are welcome.

**Comment by zpydee** [comment]
I assume assets folders should sit in root of project?

**Comment by vogloblinsky** [comment]
yes for now, what's the problem ?

**Comment by zpydee** [comment]
just a quick comment. i notice that your implementation keeps the same name I specify. will this cause problems if a user uses `images`, `fonts` or another common asset folder name as one you already use (overwrite, etc?).

**Comment by bevrard** [comment]
I would like to use an image asset in the component info (or maybe in a new tab illustration).  
Is it possible?

**Comment by vogloblinsky** [comment]
Embed an assets folder with -a flag : -a screenshots

and link it in your markdown file : 

![Screenshot-1](screenshots/home.png)

**Comment by bevrard** [comment]
Ok it will work for the Readme.md, but i would like to add a screenshot on this page for example:
https://compodoc.github.io/compodoc-demo-todomvc-angular/components/AboutComponent.html

**Comment by bevrard** [comment]
It's working :+1:  Thanks!

**Comment by vogloblinsky** [comment]
Cool, happy documentation 😄  !

**Comment by gigi199596** [comment]
Hello,

Sorry to re-open an old topic but I tried to do as you said @vogloblindsky and I can't get the picture to load inside a comment section /** */. Is it even possible to do it? Or it is just for .md files?

for your information, all the files are effectively copied inside `documentation/screenshots` but when I use:
`![Screenshot-1](screenshots/agreementscore.png)`

I get a broken image logo on my doc page.

Thanks for your help

Gilles

**Comment by imike57** [comment]
> Hello,
> 
> Sorry to re-open an old topic but I tried to do as you said @vogloblindsky and I can't get the picture to load inside a comment section /** */. Is it even possible to do it? Or it is just for .md files?
> 
> for your information, all the files are effectively copied inside `documentation/screenshots` but when I use:
> `![Screenshot-1](screenshots/agreementscore.png)`
> 
> I get a broken image logo on my doc page.
> 
> Thanks for your help
> 
> Gilles

It's related to the path. it seem if the folder is without simple quote it look for relative path, and with for absolute

try to use -a 'screenshots' instead -a screenshots

I guess a better way would be that the path is automatically corrected in the md copied file to the assets folder... So we can kept the images in the same folder than the component instead an unique folder..
