### ISSUE TITLE
[BUG] Continue to have issues with Cannot Enlarge Memory Arrays

### ISSUE THREAD

**Issue by pborregg** [compodoc/compodoc#712]
##### **Overview of the issue**

Hello,

So I've been all over the web, here in gitlab and still no solution. I'm a 58 year old programmer with over 35 years experience.  Here's my issue(s);

...
[14:59:05] Process module graph: ScreeningModule
[14:59:05] Process module graph: ScreeningRoutingModule
[14:59:05] Process module graph: ScreenshotModule
[14:59:06] Process module graph: SearchModule
[14:59:06] Process module graph: SearchRoutingModule
[14:59:06] Process module graph: SharedModule

Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0

Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0

[14:59:06] abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10 pro
npm info using npm@6.4.1
npm info using node@v8.11.1

##### **Angular configuration, a `package.json` file in the root folder**

{
	"name": "new-enrollment",
	"version": "0.0.0",
	"license": "MIT",
	"scripts": {
		"ng": "ng",
		"doc:build": "compodoc -p tsconfig.json",
		"doc:serve": "compodoc -s",
		"doc:buildandserve": "compodoc -p tsconfig.json -s",
		"reports:doc": "node ./tools/scripts/compodoc.js",
		"start": "ng serve",
		"build": "ng build",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e",
		"gulp": "gulp"
	},
	"private": true,
	"dependencies": {
		"@agm/core": "^1.0.0-beta.3",
		"@angular/animations": "^5.2.7",
		"@angular/cdk": "5.2.4",
		"@angular/common": "^5.2.7",
		"@angular/compiler": "^5.2.7",
		"@angular/core": "^5.2.7",
		"@angular/forms": "^5.2.7",
		"@angular/http": "^5.2.7",
		"@angular/material": "^5.2.5",
		"@angular/platform-browser": "^5.2.7",
		"@angular/platform-browser-dynamic": "^5.2.7",
		"@angular/platform-server": "^5.2.7",
		"@angular/router": "^5.2.7",
		"@ng-bootstrap/ng-bootstrap": "2.0.0",
		"@ng-select/ng-select": "2.4.2",
		"@ngrx/effects": "5.2.0",
		"@ngrx/entity": "^5.2.0",
		"@ngrx/store": "5.2.0",
		"@ngrx/store-devtools": "5.2.0",
		"@ngui/datetime-picker": "^0.16.2",
		"@tensorflow/tfjs": "^0.13.0",
		"@types/animejs": "^2.0.0",
		"@types/cropperjs": "^1.1.3",
		"@types/fabric": "^1.5.43",
		"@types/html2canvas": "0.5.32",
		"@types/jspdf": "1.1.31",
		"addstyles": "^1.0.5",
		"angular-bootstrap-affix": "^0.2.4",
		"angular-froala-wysiwyg": "^2.8.1",
		"angular-mentions": "^0.8.0",
		"angular-split": "^1.0.4",
		"angular-svg-round-progressbar": "^1.2.1",
		"angular-tag-cloud-module": "^2.4.0",
		"angular2-busy": "https://github.com/Sky4CE/angular2-busy/tarball/static-template",
		"angular2-draggable": "^1.4.2",
		"angular2-google-maps": "0.17.0",
		"angular2-highcharts": "^0.5.5",
		"angular2-hotkeys": "^2.0.4",
		"angular2-mentions": "^0.7.3",
		"angular2-moment": "^1.9.0",
		"animejs": "^2.2.0",
		"aos": "^3.0.0-beta.6",
		"base64-img": "^1.0.4",
		"bodybuilder": "2.2.15",
		"bootstrap": "^3.3.7",
		"cache-loader": "1.2.2",
		"child_process": "^1.0.2",
		"classlist.js": "^1.1.20150312",
		"core-js": "^2.4.1",
		"cors-anywhere": "^0.4.1",
		"cropperjs": "^1.4.1",
		"curl": "^0.1.4",
		"dom-to-image": "^2.6.0",
		"elasticsearch": "15.1.1",
		"fabric": "^2.3.6",
		"ffmpeg": "0.0.4",
		"font-awesome": "^4.7.0",
		"gulp-version-append": "0.2.0",
		"hammerjs": "^2.0.8",
		"highcharts": "6.0.7",
		"html2canvas": "1.0.0-alpha.12",
		"imagemagick": "^0.1.3",
		"jquery": "^3.2.1",
		"jspdf": "1.3.5 ",
		"lemmatizer": "^ 0.0.1",
		"lodash": "^4.17.10",
		"ng-multiselect-dropdown": "^0.1.9",
		"ng2-archwizard": "^2.1.0",
		"ng2-bootstrap-modal": "https://github.com/Sky4CE/ng2-bootstrap-modal/tarball/v.1.0.2",
		"ng2-bs3-modal": "^0.10.4",
		"ng2-ckeditor": "1.1.9",
		"ng2-completer": "^1.5.2",
		"ng2-file-upload": "^1.2.1",
		"ng2-inputmask": "^0.2.5",
		"ng2-ion-range-slider": "2.0.0",
		"ng2-select": "^1.2.0",
		"ng2-split-pane": "^1.4.0",
		"ng2-stomp-service": "^1.2.2",
		"ng2-ui": "^0.14.1",
		"ng2-validation": "^4.2.0",
		"ng4-popover": "^1.0.23",
		"ng5-slider": "^1.1.3",
		"ngx-bootstrap": "^2.0.5",
		"ngx-cookie": "^2.0.1",
		"ngx-editor": "^3.3.0",
		"ngx-highlight": "0.0.3",
		"ngx-logger": "^3.1.0",
		"ngx-masonry": "^1.1.2",
		"ngx-perfect-scrollbar": "^5.3.3",
		"ngx-toastr": "^6.3.0",
		"ngx-virtual-scroller": "1.0.4",
		"ngx-webcam": "0.2.0",
		"ngx-wow": "^1.0.2",
		"nlcst-parse-english": "^1.1.2",
		"nlcst-pattern-match": "^1.3.4",
		"npm": "^5.6.0",
		"path": "0.12.7",
		"pluralize": "^7.0.0",
		"popover": "^2.4.1",
		"pos": "^0.4.2",
		"primeng": "6.1.7",
		"rxjs": "^5.5.6",
		"simplengrams": "^0.1.2",
		"slick-carousel": "^1.6.0",
		"sockjs-client": "^1.1.4",
		"stompjs": "^2.3.3",
		"stopword": "^0.1.9",
		"style-loader": "^0.23.1",
		"underscore": "^1.8.3",
		"unoconv": "^0.1.2",
		"web-animations-js": "^2.3.1",
		"webui-popover": "^1.2.18",
		"zone.js": "^0.8.4"
	},
	"devDependencies": {
		"@angular/cli": "^1.7.4",
		"@angular/compiler-cli": "^5.2.7",
		"@angular/language-service": "^4.0.0",
		"@compodoc/compodoc": "^1.1.2",
		"@types/googlemaps": "3.29.0",
		"@types/jasmine": "2.5.45",
		"@types/node": "^6.0.108",
		"angular-ide": "^0.9.44",
		"codelyzer": "^3.0.1",
		"gulp": "4.0.0",
		"jasmine-core": "^2.6.2",
		"jasmine-spec-reporter": "^4.1.0",
		"karma": "^1.7.0",
		"karma-chrome-launcher": "^2.1.1",
		"karma-cli": "^1.0.1",
		"karma-coverage-istanbul-reporter": "^1.4.2",
		"karma-jasmine": "^1.1.2",
		"karma-jasmine-html-reporter": "^0.2.2",
		"protractor": "^5.1.2",
		"ts-node": "^3.0.4",
		"tslint": "^5.3.2",
		"typescript": "2.4.2"
	},
	"description": "This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 1.1.3.",
	"main": "gulpfile.js",
	"repository": {
		"type": "git",
		"url": "https://git.acompany/somecode.git"
	},
	"keywords": [],
	"author": ""
}

##### **Compodoc installed globally or locally ?**

BOTH!

I'm running the following in git bash window:

$ compodoc -s ALLOW_MEMORY_GROWTH=1 -p tsconfig.json -d documentation

This yields the following error:

1.1.7

Typescript version : 2.9.1

Node.js version : v8.11.1

Operating system : Windows 10

[14:59:51] No configuration file found, switching to CLI flags.
[14:59:51] Provided source folder ALLOW_MEMORY_GROWTH=1 was not found in the current directory

##### **If possible your terminal logs before the error**

NA

##### **Motivation for or Use Case**

I cannot continue with COMPDOC and I desperately need to finish the documentation.  This is a HUGE app

I have a large app and it fails

I've tried this... from this example:  https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js - Scroll to the accepted solution....

const {spawn} = require('child_process');
console.log("spawn defined: before spawn");

//spawn(/^win/.test(process.platform) ? 'npm.cmd' : 'npm run compdoc',
//        ['-p', 'tsconfig.json', '-d', 'documentation/'], {
//  stdio: 'inherit',
//  shell: true
//});

spawn('npm run compdoc', ['-p', 'tsconfig.json', '-d', 'documentation/'], {
  stdio: 'inherit',
  shell: true
});

//const cmd = spawn('compdoc', ['-p', 'tsconfig.json', '-d', 'documentation/']);

//console.log(process.cmd);
//spawn('Spawn Help: ', ['--help']);
//console.log("spawn CONSTANT: ", cmd);

//cmd.stdout.pipe(process.stdout);
//cmd.stderr.pipe(process.stdout);

//(function () {
//  console.log("inside function");
//  //var childProcess = require("child_process");
//  var oldSpawn = cmd.spawn;
//
//  function mySpawn() {
//    console.log('spawn called');
//    console.log(arguments);
//
//    var result = oldSpawn.apply(this, arguments);
//    return result;
//  }
//
//  console.log("before spawn");
//  cmd.spawn = mySpawn;
//})();

##### **Related issues**

Several times but not in the exact context I have...

##### **Suggest a Fix**

DAMN RIGHT, this is a "GEM" and I'll help you contribute but you need to show where and how, STEP-BY-STEP how to increase the memory and either call COMPDOC via command line script that I wrote.

I placed it in the ROOT directory in ./tools/scripts/compdoc.js

I call it via:

node tools/scripts/compdoc.js

and get an error below...

spawn defined: before spawn
npm info it worked if it ends with ok
npm info using npm@6.4.1
npm info using node@v8.11.1
npm ERR! missing script: compdoc
npm timing npm Completed in 185ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-01-03T23_05_48_923Z-debug.l
og

and here's that LOG:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compdoc',
1 verbose cli   '-p',
1 verbose cli   'tsconfig.json',
1 verbose cli   '-d',
1 verbose cli   'documentation/' ]
2 info using npm@6.4.1
3 info using node@v8.11.1
4 verbose stack Error: missing script: compdoc
4 verbose stack     at run (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
5 verbose cwd C:\petersprojects\wwwroot\repos\kyp-frontend
6 verbose Windows_NT 10.0.16299
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "compdoc" "-p" "tsconfig.json" "-d" "documentation/"
8 verbose node v8.11.1
9 verbose npm  v6.4.1
10 error missing script: compdoc
11 verbose exit [ 1, true ]

**Comment by vogloblinsky** [comment]
Try to render the doc without the graph with the flag --disableGraph

**Comment by pborregg** [comment]
But I need the graphs...that's the whole point.

I will try it...

**Comment by pborregg** [comment]
So far so good... hanging after last process page... 3 min, just hanging... no errors...so far.

**Comment by pborregg** [comment]
[15:21:08] Copy main resources
[15:21:09] Documentation generated in ./documentation/ in 93.794 seconds using gitbook theme
[15:21:09] Serving documentation from ./documentation/ at http://127.0.0.1:8080

Not done yet but still no errors

Looking good! But I need the graphs!!!

**Comment by vogloblinsky** [comment]
Try something like that, it will increase the memory allocated to Node.js.

```
node --max-old-space-size=8192 ./node_modules/@compodoc/compodoc/bin/index-cli.js -p tsconfig.json -d documentation
```

The problem is located to an external library we are using for static graph rendering which has issues with big graph. We are working on another implementation.

**Comment by pborregg** [comment]
OK, so I ran Vogloblinksy's solution 

node --max-old-space-size=8192 ./node_modules/@compodoc/compodoc/bin/index-cli.js -p tsconfig.json -d documentation

get this halfway through, but it continues

[15:27:12] Process documentation coverage report
[15:27:12] Process main graph
[15:27:13] Ooops error during main graph generation, moving on next part with main graph disabled
: : RangeError: Maximum call stack size exceeded

Then it fails at the bottom before the final graphs... as always

[15:27:28] Process module graph: SharedModule
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the c
urrent value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the siz
e at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before
 the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile wit
h  -s ABORTING_MALLOC=0
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the c
urrent value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the siz
e at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before
 the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile wit
h  -s ABORTING_MALLOC=0
[15:27:29] abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X
 higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows
increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a h
igher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this
abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

**Comment by pborregg** [comment]
When it hits SHARED-MODULE, that folder has 16 folders and the shared.module.ts

If that helps...

**Comment by pborregg** [comment]
Also, when I click on modules, I get 404 error NOT FOUND...thoughts on why this happens throughout?

But I digress, I need to focus on the matter at hand, why I cannot get all the graphs to render and compdoc hangs at this larger module.

Can't I not render graphs for shared.module.ts and allow all others?

**Comment by pborregg** [comment]
Does anyone have a solution here?

**Comment by vogloblinsky** [comment]
Hi, sorry, not right now. The work on changing the graph engine is at around 75%. We will except a release this month.

**Comment by pborregg** [comment]
Awesome!

 

 

Peter Borreggine

Owner and Developer

Angular/Bootstrap/NodeJS/Databases/HTML5/CSS3/Responsive Web Design/SEO

WebParity.net <http://webparity.net/> 

A Service Connected Disabled Veteran Owned Business

WA State License: 603-501-609

360-830-8926 C

 

“Lead, Follow or Get Out of the Way…”

*	Lee Iacocca, former head of Chrysler and Ford

 

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. If you are not the intended recipient, please contact the sender and destroy all copies of the original message and its attachments. Any unauthorized review, use, disclosure, or distribution is prohibited.

**Comment by pborregg** [comment]
Vincent, any luck with fixing this bug?

Thanks,

Peter

**Comment by pborregg** [comment]
Vincent,

28 days ago you stated this:

Hi, sorry, not right now. The work on changing the graph engine is at around 75%. We will except a release this month.

We're at 4 FEB 19... I need, respectfully, this to work with larger apps... You program ROCKS, man... I need a workaround for now or a date when you'll have the fix to this larger problem.

Thanks Vincent

Peter

**Comment by pborregg** [comment]
Vincent,

You're not responding. This is not a great way for effective communications with the people that LOVE what you've created.

C'mon man, let us know what's happening.  We need you and we need your software to work or suggest a workaround. You're holding up progress... just communicate with us... please.

Thank you for all your hard work. Do you need help?

Let us ALL KNOW!!! We are here and will support you. That's what fellow devs do, man.

Cheers,

Peter

**Comment by vogloblinsky** [comment]
Hi @pborregg 

I have re-started the work on graph engine. T have to test it on existing projects, and compare both versions.

I will post updates soon. I cannot give a day or week, but that's now my next big bug fixes.

**Comment by pborregg** [comment]
Thank you sir!

 

 

Peter Borreggine

Owner and Developer

Angular/Bootstrap/NodeJS/Databases/HTML5/CSS3/Responsive Web Design/SEO

WebParity.net <http://webparity.net/> 

A Service Connected Disabled Veteran Owned Business

WA State License: 603-501-609

360-830-8926 C

 

“Lead, Follow or Get Out of the Way…”

*	Lee Iacocca, former head of Chrysler and Ford

 

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. If you are not the intended recipient, please contact the sender and destroy all copies of the original message and its attachments. Any unauthorized review, use, disclosure, or distribution is prohibited.

**Comment by pborregg** [comment]
Vincent,

Thank you. Of Note: The documentation fails only when it gets to SharedModule (Folder) which has only to components in that.  Could there be something there that may be preventing it from continuing?

Also, here are some warnings that may be of assistance:

    provide: NG_SELECT_DEFAULT_CONFIG, useValue: {
        notFoundText:
    }

    provide: HighchartsStatic, useFactory: highchartsFactory
}
[09:37:21]                :     - {
    provide: PERFECT_SCROLLBAR_CONFIG, useValue: DEFAULT_PERFECT_SCROLLBAR_CONFIG
}

    provide: , useValue: environment.timeoutConfig
}
[09:37:21]                :     - ErrorsHandlerService
[09:37:21]                :     - {
    provide: ErrorHandler, useClass: ErrorsHandlerService
}

[09:37:24]                :     - {
    provide: NG_VALUE_ACCESSOR, useExisting: forwardRef(() => MaskedInputComponent), multi: true
}
[09:37:32] -------------------
[09:37:32] Project statistics
[09:37:32] - files      : 4494
[09:37:32] - module     : 76
[09:37:32] - component  : 453
[09:37:32] - directive  : 21
[09:37:32] - injectable : 226
[09:37:32] - injector   : 1
[09:37:32] - guard      : 1
[09:37:32] - pipe       : 49
[09:37:32] - class      : 419
[09:37:32] - interface  : 159
[09:37:32] - route      : 302
[09:37:32] -------------------

It starts this part....

[09:37:32] Prepare components

And notice a problem here...

[09:37:34] Process main graph
[09:37:39] Ooops error during main graph generation, moving on next part with main graph disabled : : RangeError: Maximum call stack size exceeded

it continues.... and dies here...

[09:38:09] Process module graph: SharedModule
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0
[09:38:09] abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

HTH

Peter

**Comment by pborregg** [comment]
Vincent.... still no update?

I really need this to be fixed. I'm using visJS for something else in my app...it's freaking cool... would that be helpful or does that not address the type of graphs you're building with Compodoc?

BTW, my company loves what your code does... It rocks... just need to get over this hurdle.

Cheers,

Peter

**Comment by pborregg** [comment]
Hello Vincent. It's now APR 10th and we haven't heard back from you as to status of this bug. We all know you're very busy and respect and can appreciate that. Please just let everyone know whether you're making progress, blocked, need our help, etc... Share the branch and I can make a feature branch or something. It only breaks for me at a certain point otherwise, there's no other issues.  It's the same place that it breaks. This tells me it's something in my code that's breaking your software.

If we can identify what causes that, it may go a long way to helping you fix the bug.

Let us/me know what we can do to be of assistance, sir.

Peter

**Comment by pborregg** [comment]
Vincent, 

Why are you not responding. You promised to have something 3 mos ago... Please. Let us know what's going on and if there's a workaround. 

I love your compodoc software but it's got to work... my company loves it, but it's got to work!

Please update everyone. You're responding to others are recently as 14 hours ago... but this request and subsequent request for updates was started by in January.... with not a word.

Please give us breadcrumbs...ok?

Thanks,

Peter

**Comment by SDohle** [comment]
Any news on this?

**Comment by pborregg** [comment]
I haven’t heard JACK!

 

I think he’s out of business.

 

Very disappointing

**Comment by Gruwa** [comment]
Same error for 1.1.9

**Comment by pborregg** [comment]
Gruwa and Steffen. I agree, he's out of business or simply doesn't care. So we three need to pull this into our own repo and continue the work. If you agree, then set up a repo for us three and let's make it even better. We've give the owner of this PLENTY of time to rectify this issue and he's NOT responded.

If you agree, I'll make the repo or you guys can and let's remake this so it WORKS! PERIOD!

We'll give credit where credit is due but this is a MAJOR BLOCKER...

**Comment by vogloblinsky** [comment]
@pborregg
I am not out of business. I am just the only maintainer of this tool.
I know this issue is very confusing for users. 
I have a solution ready to add. 
I can add you inside early testers if you want.
Give me some good vibes and i will try to fix this asap.

**Comment by pborregg** [comment]
You’re ALIVE!

 

Vincent… you rock man add all of us concerned. 

 

Thank you and yes, please.

 

V/r

 

 

Peter Borreggine

Owner and Developer

Angular/Bootstrap/NodeJS/Databases/HTML5/CSS3/Responsive Web Design/SEO

WebParity.net <http://webparity.net/> 

A Service Connected Disabled Veteran Owned Business

WA State License: 603-501-609

360-830-8926 C

 

“Lead, Follow or Get Out of the Way…”

*	Lee Iacocca, former head of Chrysler and Ford

 

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. If you are not the intended recipient, please contact the sender and destroy all copies of the original message and its attachments. Any unauthorized review, use, disclosure, or distribution is prohibited.

**Comment by pborregg** [comment]
We will ALL give you good vibes sir.

 

Let’s just do this as a team ok? My company is using it and I will make sure my boss knows you fixed this. This is an invaluable tool for us.

 

Cheers,

 

 

Peter Borreggine

Owner and Developer

Angular/Bootstrap/NodeJS/Databases/HTML5/CSS3/Responsive Web Design/SEO

WebParity.net <http://webparity.net/> 

A Service Connected Disabled Veteran Owned Business

WA State License: 603-501-609

360-830-8926 C

 

“Lead, Follow or Get Out of the Way…”

*	Lee Iacocca, former head of Chrysler and Ford

 

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. If you are not the intended recipient, please contact the sender and destroy all copies of the original message and its attachments. Any unauthorized review, use, disclosure, or distribution is prohibited.

**Comment by Gruwa** [comment]
Yes, let's do this!

> @pborregg
> I am not out of business. I am just the only maintainer of this tool, with a daily job, a family...
> I know this issue is very confusing for users.
> I have a solution ready to add.
> I can add you inside early testers if you want.
> Give me some good vibes and i will try to fix this asap.

**Comment by pborregg** [comment]
I’m on vacation from now until the 6th of August.

 

Let’s circle back then.

 

 

Peter Borreggine

Owner and Developer

Angular/Bootstrap/NodeJS/Databases/HTML5/CSS3/Responsive Web Design/SEO

WebParity.net <http://webparity.net/> 

A Service Connected Disabled Veteran Owned Business

WA State License: 603-501-609

360-830-8926 C

 

“Lead, Follow or Get Out of the Way…”

*	Lee Iacocca, former head of Chrysler and Ford

 

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. If you are not the intended recipient, please contact the sender and destroy all copies of the original message and its attachments. Any unauthorized review, use, disclosure, or distribution is prohibited.

**Comment by SDohle** [comment]
> I have a solution ready to add.
> I can add you inside early testers if you want.

:+1:

**Comment by pborregg** [comment]
Please Sent via the Samsung Galaxy S8, an AT&T 5G Evolution capable smartphone
-------- Original message --------From: Steffen <notifications@github.com> Date: 8/4/19  23:58  (GMT-08:00) To: compodoc/compodoc <compodoc@noreply.github.com> Cc: Pete Borreggine <peter@webparity.net>, Mention <mention@noreply.github.com> Subject: Re: [compodoc/compodoc] [BUG] Continue to have issues with Cannot
  Enlarge Memory Arrays (#712) 

I have a solution ready to add.

I can add you inside early testers if you want.



👍



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/compodoc/compodoc/issues/712?email_source=notifications\u0026email_token=ABL5IFYYUAEILOTZ43GS6X3QC7FTFA5CNFSM4GNDV2BKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3Q36WA#issuecomment-518111064",

"url": "https://github.com/compodoc/compodoc/issues/712?email_source=notifications\u0026email_token=ABL5IFYYUAEILOTZ43GS6X3QC7FTFA5CNFSM4GNDV2BKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3Q36WA#issuecomment-518111064",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by AdamStanley** [comment]
@vogloblinsky 
I have a large project experiencing this error as well. I'd be happy to assist with testing/integration of the new graphing engine. Let me know if there's anything I can do that would be helpful.

**Comment by pborregg** [comment]
Please… we all have this problem and Vincent really needs our help.

 

 

Peter Borreggine

Owner and Developer

Angular/Bootstrap/NodeJS/Databases/HTML5/CSS3/Responsive Web Design/SEO

WebParity.net <http://webparity.net/> 

A Service Connected Disabled Veteran Owned Business

WA State License: 603-501-609

360-830-8926 C

 

“Lead, Follow or Get Out of the Way…”

*	Lee Iacocca, former head of Chrysler and Ford

 

This email message is for the sole use of the intended recipient(s) and may contain confidential and privileged information. If you are not the intended recipient, please contact the sender and destroy all copies of the original message and its attachments. Any unauthorized review, use, disclosure, or distribution is prohibited.
