### ISSUE TITLE
[FEATURE] Collapse extra documentation children nodes by default

### ISSUE THREAD

**Issue by bparkhurst** [compodoc/compodoc#714]
##### **Overview of the issue**

It would be REALLY REALLY nice to have the additional documentation treeview nodes display collapsed by default if they have children in the summary.json file.

They currently all show expanded, so if the list is long, the core SDK documentation is pushed off the bottom of the left panel.  

Collapse them by default.

##### **Operating System, Node.js, npm, compodoc version(s)**

All

##### **Angular configuration, a `package.json` file in the root folder**

Feature

##### **Compodoc installed globally or locally ?**

globally

**Comment by vogloblinsky** [comment]
Fixed @bparkhurst 
Just collapsed first entries of additional menu which have children. If children have also children, don't collapse them.

![image](https://user-images.githubusercontent.com/2841805/51262011-b8b0a180-19b1-11e9-8c2a-e9f7eb4a3168.png)

**Comment by bparkhurst** [comment]
This is awesome!  When do you think it will be available?

**Comment by vogloblinsky** [comment]
Yes it will be very soon. I hope next week.
