### ISSUE TITLE
[ENHANCEMENT] Compodoc installation takes 140MB of size

### ISSUE THREAD

**Issue by abhijeetkpawar** [compodoc/compodoc#716]
##### **Overview of the issue**
The @compodoc/compodoc installation takes up **~109MB** of size. This is huge size and something looks incorrect with dependencies.

[![install size](https://packagephobia.now.sh/badge?p=@compodoc/compodoc@1.1.7)](https://packagephobia.now.sh/result?p=@compodoc/compodoc@1.1.7)

##### **Operating System, Node.js, npm, compodoc version(s)**

Compodoc version: **1.1.7**

##### **Angular configuration, a `package.json` file in the root folder**

NA

##### **Compodoc installed globally or locally ?**

Locally

**Comment by abhijeetkpawar** [comment]
> 
> 
> Please use the correct scope on npm : @compodoc/compodoc
> 
> Just done a test with a fresh install : the 2 huge folders are ts-simple-ast and typescript. I have to update ts-simple-ast and remove the dependency of typscript because ts-simple-ast import another version too.

Thanks. Updated the package. Its actually 109 MB

**Comment by vogloblinsky** [comment]
Update :
It is not directly Compodoc which pull TypeScript dependency, it is @compodoc/ngd-core

```
npm ls typescript

├─┬ @compodoc/ngd-transformer@2.0.0
│ └─┬ @compodoc/ngd-core@2.0.0
│   └── typescript@2.9.2 
└─┬ ts-simple-ast@12.4.0
  └── typescript@2.9.1 
```

**Comment by abhijeetkpawar** [comment]
@vogloblinsky 
The package size is now bumped to ~140MB
[![install size](https://packagephobia.now.sh/badge?p=@compodoc/compodoc)](https://packagephobia.now.sh/result?p=@compodoc/compodoc)

**Comment by abhijeetkpawar** [comment]
Seems like there is no active development on this project? @vogloblinsky
