### ISSUE TITLE
[FEATURE] Documentation of multiple apps on one website

### ISSUE THREAD

**Issue by jizza** [compodoc/compodoc#719]
Our team has multiple Angular apps and libraries spread over multiple repositories. We want to have everything documented on one website.

One option we're looking at is to create a script that iterates over all repos, run compodoc, and then generate our own menu, with each menu-item linking to the docs of the repo concerned.

Am I correct that this is not currently supported and do you think this is the best way to go for now?

**Comment by jizza** [comment]
Thanks kum-deepak, interesting idea!
How did you setup the tsconfig to only include the folders you need?

**Comment by kum-deepak** [comment]
See https://www.typescriptlang.org/docs/handbook/tsconfig-json.html, I used "include" and "exclude" - both of which take multiple entries.

**Comment by vogloblinsky** [comment]
Hi,
I need to think about a way to handle that with Compodoc, monorepo with CLI, monorepo with Nx, simple app and libraries.

**Comment by drakenfly** [comment]
I'm also using a NX workspace with multiple apps and libraries. I think it would be a great idea to provide the option for a "menu to tsconfig" mapping.

So, afterwards the menu entries are grouped by the name and only contain the sources from the linked tsconfig file.

Example:
`mappings.json
{
  "App 1": "apps/app1/tsconfig.app.json",
  "Lib 1": "libs/lib1/tsconfig.lib.json"
}
`

Now, all menu entries are split:

- Modules
  - App1
      - Modules of App 1
 - Lib 1
    - Modules ao Lib 1
- Components
  - App 1
  - Lib 1
...

**Comment by allout58** [comment]
Ideally, you would just parse the `angular.json` file and use it to find the appropriate `tsconfig.json` files and combine them. This should cover at least the broad case of both Angular workspaces and Nx workspaces.

**Comment by vogloblinsky** [comment]
Yes @allout58 i think that's how i will support this use-case.
My nest question is "how to display them?" i don't want to extend the current menu with that.
My current vision :
- find `angular.json` file
- parse it and detects apps and libs
- generates compodoc for each 
- namespace the output in folders, one for each
- generate a index page listing all the documentations available
