### ISSUE TITLE
[FEATURE] : class dependencies tree/list

### ISSUE THREAD

**Issue by brian428** [compodoc/compodoc#72]
##### **Overview of the issue**

Populating testing module dependencies can be a challenge for classes with a large dependency tree. While mocking dependencies is an option, it would be quite helpful to be able to see the full dependency tree for a given class. This would include injected dependencies and child components. A tree like this (either graphical or a text-based list) would make populating testing module dependencies a lot easier.

The dependencies for the class could be a full listing of the entire tree (all the way down), or just the direct dependencies. In the latter case, if these were clickable links to those classes, it would still be fairly easy to navigate down through the tree to trace through the dependency tree. Either one of these would still be a big help.

**Comment by vogloblinsky** [comment]
By talking about classes, you mean classes of components ?
Did you have an exemple ?

**Comment by brian428** [comment]
I guess I mean anything "Angular" that's testable. So `@Component()`, `@Directive()`, `@Injectable()`, etc. 

So:
- If `ServiceA` has `ServiceB` injected, dependencies would be: `ServiceB` 
- If `ComponentA` has `ServiceA` injected, and its template uses `ComponentB`, `ComponentC`, and `DirectiveD`, dependencies would be: `ServiceA`, `ComponentB`, `ComponentC`, `DirectiveD`

So again, the idea is that if I create a test for `ComponentA`, I know what dependencies I need to define in the testing module. 

I was just writing tests today and thinking "man, I wish there was something to make it easier to trace all these dependencies". Particularly component dependencies, since there's no easy way to look at a component class and see what its view dependencies are (other than manually looking through the template for selectors). 

I'm not even sure this is possible, since it probably depends on what class information Compodoc has access to internally. And I can imagine dependent directives being harder to determine than components, since I would think selectors are easier to identify, while directives could be harder to differentiate from any other attribute binding in a template.

Let me know if what I'm trying to say makes sense. Thanks!

**Comment by zpydee** [comment]
@brian428 you should also look at using the `NO_ERRORS_SCHEMA_` in your tests. that way you don't need to declare any of the components in your template, making test setup much easier.
