### ISSUE TITLE
Enhancement - Don't "repaint" the menu in the left sidebar on every  page selection

### ISSUE THREAD

**Issue by bparkhurst** [compodoc/compodoc#721]
##### **Overview of the issue**

This is a feature request and probably lower priority...but.

When selecting pages in the left sidebar menu, it repaints the menu each time.  While it keeps your selection on the menu, it is pretty hard on the eyes to watch it repaint each time.

Can you load it without rendering it and make it feel more snappy?
##### **Operating System, Node.js, npm, compodoc version(s)**

normal, standard package.json

##### **Compodoc installed globally or locally ?**

globally and locally both.

##### **If possible sourcecode of the file where it breaks**

standard, generated documentation has this symptom.

##### **Motivation for or Use Case**

To make the UX better with the framework!

##### **Reproduce the error**
Generate docu and start selecting different pages in the documentation. Also, have children for the hierarchy.

##### **Related issues**

None

##### **Suggest a Fix**

Use a "state management" solution to save the menu and restore it without repainting the menu.

<!-- Love compodoc? Please consider supporting our collective:
LOVE IT...DONATED 👍

**Comment by vogloblinsky** [comment]
Hi
Compodoc generates HTML pages, so each time you click on a link it opens a new page.
I don’t want to change this behavior, and starting generate another Web application for documenting an application ;)
