### ISSUE TITLE
[FEATURE] Search customization.

### ISSUE THREAD

**Issue by hrocha16** [compodoc/compodoc#726]
##### **Overview of the issue**

Ability to change MAX_SIZE_FILE_SEARCH_INDEX via CLI.
Ability to omit 'body' field and only use 'title' via CLI.

If this is approved I will submit a PR with the feature.

##### **Motivation for or Use Case**

This gives developers more customization in the search, instead of modifying the index-cli file before building.

**Comment by janhelbich** [comment]
Ability to change MAX_SIZE_FILE_SEARCH_INDEX via CLI would be most appreciated.

**Comment by vogloblinsky** [comment]
@hrocha16 go for PR ;)
Thanks by advance
