### ISSUE TITLE
[DISCUSSION] Angular Compiler Abstraction 

### ISSUE THREAD

**Issue by adover** [compodoc/compodoc#729]
Hi there,
I'm wondering if there's been a consideration or an attempt to abstract the compiler and have it run as a standalone? I've got a set of documentation which is already built and I want to inject the documentation in as an Angular module without a theme. I'd be looking to do this work but it would involve lifting a chunk of the codebase out and turn it into a dependency.

As I'm using Nrwl there could be scope for this being built as an extension for NX where you can compile a set of documentation into a project.

**Comment by vogloblinsky** [comment]
> I've got a set of documentation which is already built and I want to inject the documentation in as an Angular module without a theme.

What do you mean ?
