### ISSUE TITLE
[BUG] npm audit failure

### ISSUE THREAD

**Issue by Adam-Kernig** [compodoc/compodoc#731]
NPM Audit has caught another issue out

│ High          │ Prototype Pollusion                                          
│ Package       │ handlebars                                                   
│ Patched in    │ >=4.0.13                                                     
│ Dependency of │ @compodoc/compodoc [dev]                                    
│ Path          │ @compodoc/compodoc > handlebars                              
│ More info     │ https://npmjs.com/advisories/755                             

This is using v.1.1.8

**Comment by jtneal** [comment]
Fixed in #733 - Still needs to be released.
