### ISSUE TITLE
Automate dependency updates

### ISSUE THREAD

**Issue by JustinBeckwith** [compodoc/compodoc#734]
There are a few dependencies in `package.json` that are super out of date.  Now that `npm audit` is starting to flag these more often, it would be great to automate the process of submitting PRs to update out of date deps.

I've used both of these, and have been super happy:
- https://greenkeeper.io/
- https://renovatebot.com

They're pretty easy to set up, but require an admin on the repo to do it :)

**Comment by vogloblinsky** [comment]
Hi, thanks for referencing these tools.
Some dependencies are not updated because i need to rewrite some parts of the codebase.
I prefer checking each week manually if i can update them.

**Comment by JustinBeckwith** [comment]
Makes sense :) The benefit of using something like greenkeeper is that it doesn't just make the change on master.  It submits a PR, runs CI, and then you choose if it gets merged or not.  That having been said - I totally get it if you're happy with where you are :)
