### ISSUE TITLE
[BUG]: Fails before generating documentation, error

### ISSUE THREAD

**Issue by nikhilknoldus** [compodoc/compodoc#735]
[BUG]: A picture speaks more, so when the doc generation process is about to complete it ends in an error which I can't understand because it isn't pointing to any file. Please help out.

![image](https://user-images.githubusercontent.com/10805658/52903951-28cd7400-324b-11e9-9348-c9606988de12.png)

**Comment by vogloblinsky** [comment]
Hi, can you follow the issue template and provide informations like compodoc version, etc
and a more detail log screenshot please ?

**Comment by nikhilknoldus** [comment]
@vogloblinsky Sure, here is another snapshot,

##### **perating System, Node.js, npm, compodoc version(s)**: 
Windows 10, 64Bit, NodeJS: 9.10, npm:  5.6.0, Compodoc Version: 1.1.8.
##### **Angular configuration, a `package.json` file in the root folder**
Yes, simply installed compodoc and added it's script tag that's it.
##### **Compodoc installed globally or locally ?** 
Locally
##### **If possible sourcecode of the file where it breaks** 
From errors it's not possible to see which file causing the error so not Possible
##### **If possible your terminal logs before the error** 
Done
##### **Motivation for or Use Case**
##### **Reproduce the error**
Yes, after installing and adding script, running, npm run compodoc
##### **Related issues**
##### **Suggest a Fix**1.1.8


![image](https://user-images.githubusercontent.com/10805658/52908263-03b32280-3298-11e9-8861-7788798dcd55.png)

**Comment by vogloblinsky** [comment]
What is `Task-1` in your codebase ?

**Comment by nikhilknoldus** [comment]
@vogloblinsky `Task-1` is nothing in my codebase, it seems like just compodoc convention.
![image](https://user-images.githubusercontent.com/10805658/52967982-e2eee800-33d1-11e9-8a06-6ec8649c464d.png)


Please help man.

**Comment by vogloblinsky** [comment]
ok it seems Task is a class or something else, that seems to appears twice in your codebase, and compodoc detect it, Task-1 is an increment of Task
what is Task in your codebase ?

**Comment by nikhilknoldus** [comment]
Cool, task is a model in this codebase, which is getting used in multiple places, application nowhere breaks because of task but I am unable to understand what is the cause compodoc is breaking here. What I should do, I tried `typedoc` and `AngularDoc` but they aren't competing `compodoc` I need `compodoc` to work.

**Comment by mark922** [comment]
I am also having the same problem. I don't have any duplicate classes either. Here is the error that I am getting: 

<img width="1280" alt="screen shot 2019-02-21 at 1 03 19 pm" src="https://user-images.githubusercontent.com/6478433/53151402-26677300-35d9-11e9-85b5-54eea5da0e2e.png">

Using Compodoc Version: 1.1.8

**Comment by vogloblinsky** [comment]
@nikhilknoldus Could you share the code of this model here ?
If not, send me by email.
I cannot debug without reproducing it.
Thanks

**Comment by vogloblinsky** [comment]
@nikhilknoldus any news ?

**Comment by mark922** [comment]
@vogloblinsky If it helps then I can share my model with you

**Comment by vogloblinsky** [comment]
@mark922 Yes by email : vincent [.] ogloblinsky [@] gmail [.] com

**Comment by mark922** [comment]
I have sent you the class file for which it is producing this error. Let me know if you find anything or need any help from my side.

**Comment by mark922** [comment]
@nikhilknoldus Did you find any older version of compodoc which is not producing this error ?

**Comment by nikhilknoldus** [comment]
> @nikhilknoldus Did you find any older version of compodoc which is not producing this error ?

No @mark922 I tried the older version but still the error is same.
Sorry @vogloblinsky I wasn't getting notifications and I was out, but I notice the issue is closed without any solution, is there any solution yet?

**Comment by mark922** [comment]
@nikhilknoldus I guess it has been released in [v1.1.9](https://github.com/compodoc/compodoc/releases/tag/1.1.9)

**Comment by vogloblinsky** [comment]
@nikhilknoldus yes fixed in 1.1.9

**Comment by nikhilknoldus** [comment]
Thanks, @vogloblinsky 🌮 🕺 🎉 😃  you made my Friday man, Happiness all over!
