### ISSUE TITLE
Security issue with handlebar package

### ISSUE THREAD

**Issue by Dunos** [compodoc/compodoc#736]
Installing the latest version of Compodoc (1.1.8) returns NPM AUDIT errors with the handlebar package:

| High                   │ Prototype Pollution      
│ Package             │ handlebars                             
│ Patched in         │ >=4.0.13                                   
│ Dependency of │ @compodoc/compodoc [dev]              
│ Path                    │ @compodoc/compodoc > handlebars            
│ More info            │ https://npmjs.com/advisories/755       

Should update the dependencies to fix the problem.

You can replicate installing version 1.1.8 and doing "npm audit"

**Comment by vogloblinsky** [comment]
Fixed, coming soon in 1.1.9

**Comment by rkara** [comment]
Do you have an estimate on when 1.1.9 will be released?  Our CI process gates builds based on the high audit level vulnerabilities.

**Comment by rkara** [comment]
[1.1.9](https://www.npmjs.com/package/@compodoc/compodoc) was released today for anyone watching this

**Comment by xmlking** [comment]
now we have  `static-eval`  as Moderate Vulnerability
`@compodoc/compodoc > pdfmake > pdfkit > fontkit >      unicode-properties > brfs > static-module > static-eval`

**Comment by shanedg** [comment]
Yeah `npm audit` tells me I traded 1 High Vulnerability for 4 Moderate?
