### ISSUE TITLE
[BUG] Does not generate full documentation but no error

### ISSUE THREAD

**Issue by JanMalch** [compodoc/compodoc#740]
##### **Overview of the issue**

Running the compodoc command does run without error, finds all components that it should but does not generate all documentation. Only a `documentation/js/routes/routes_index.js` folder is created. Also there is no console output `Documentation generated ...`.
When using the `--minimal` flag it does create the complete documentation succesfully.

It worked earlier and now it doesn't work without changing the compodoc config. So this might be due to a code change inside the project, which compodoc cannot process. Unfortunately I cannot provide the code, but I think there should atleast be some error output?

The last console output is that the documentation coverage is above the threshold

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 7
Node v10.9.0
compodoc ^1.1.8

`compodoc -p src/tsconfig.app.json`

##### **Compodoc installed globally or locally ?**

locally

**Comment by vogloblinsky** [comment]
Can you test again with last version ?

**Comment by JanMalch** [comment]
Updating to `1.1.10` resolved this issue, thanks!
