### ISSUE TITLE
[FEATURE] documentation for configuration file and schema setup

### ISSUE THREAD

**Issue by IlCallo** [compodoc/compodoc#741]
##### **Overview of the issue**
I checked multiple times the documentation but could not find a guide explaining config file setup and usage.
I ended up on https://github.com/compodoc/compodoc/issues/379 and had to check into the code to understand which name the file should/could have (I later found it into [Usage page](https://compodoc.app/guides/usage.html) at `--config` option).

Same thing on how to set the JSON schema, which I found thanks to https://github.com/compodoc/compodoc/issues/577.

In VSCode, I had to add

```json
"files.associations": {
  ".compodocrc": "json"
 },
"json.schemas": [
  {
    "fileMatch": ["/.compodocrc"],
    "url": "https://raw.githubusercontent.com/compodoc/compodoc/master/src/config/schema.json"
  }
]
```

to setting to make it work ([reference](https://code.visualstudio.com/docs/languages/json#_json-schemas-settings)) and I'm not even sure I actually have to rely on the one on github or if there is one hosted somewhere else.

_Edit: I found out some projects use the schema located at `./node_modules/@compodoc/compodoc/src/config/schema.json`, which seems a better practice than referencing it at GitHub master branch_

It would be useful to better document how to use config file and, if there's a way, to make VSCode and other IDE to automatically recognize `.compodocrc` and other accepted file names as JSON files and apply automatically the right schema (it happens with `.babelrc`, I guess there's a way to do it).

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10
Node 10.x
yarn 1.13
compodoc 1.1.8

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

It took me nearly half an hour to search documentation and info around, it will be nice to take only 2 min with a short explanation page.

##### **Related issues**

https://github.com/compodoc/compodoc/issues/379
https://github.com/compodoc/compodoc/issues/577

**Comment by vogloblinsky** [comment]
Sorry for that.

I have updated the website : https://compodoc.app/guides/usage.html

**Comment by IlCallo** [comment]
Thank you!
