### ISSUE TITLE
[BUG] Exclude files listed in tsconfig.app.json

### ISSUE THREAD

**Issue by mayureshs** [compodoc/compodoc#743]
##### **Overview of the issue**
Unable to exclude files listed in tsconfig.app.json within Angular 7 project.

##### **Operating System, Node.js, npm, compodoc version(s)**
Node 10.15.1
npm 6.7.0
compodoc: "1.0.5"

##### **Angular configuration, a `package.json` file in the root folder**
{
  "name": "source3",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "npx compodoc -p src/tsconfig.app.json --theme readthedocs -d documentation",
    "clean": "rm -rf node_modules",
    "reinstall": "npm run clean && npm install",
    "rebuild": "npm run clean && npm install && npm run build",
    "analyze": "ng build -prod --stats-json && webpack-bundle-analyzer dist/stats.json",
    "build-prod": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --aot --base-href /ESWeb/dist/"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "7.2.3",
    "@angular/common": "7.2.3",
    "@angular/compiler": "7.2.3",
    "@angular/core": "7.2.3",
    "@angular/flex-layout": "7.0.0-beta.23",
    "@angular/forms": "7.2.3",
    "@angular/http": "7.2.3",
    "@angular/platform-browser": "7.2.3",
    "@angular/platform-browser-dynamic": "7.2.3",
    "@angular/router": "7.2.3",
    "@ng-idle/core": "6.0.0-beta.3",
    "@ng-select/ng-select": "2.15.3",
    "@ngrx/store": "^7.2.0",
    "@ngrx/store-devtools": "^7.2.0",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "@types/underscore": "1.8.9",
    "ajv": "6.8.1",
    "ajv-keywords": "3.3.0",
    "anchorify": "1.0.2",
    "angulartics2": "7.4.1",
    "bootstrap": "^3.3.7",
    "bootstrap-toggle": "2.2.2",
    "clean-css": "4.2.1",
    "core-js": "2.6.3",
    "datatables": "1.10.18",
    "jquery": "3.3.1",
    "karma-teamcity-reporter": "1.1.0",
    "masonry-layout": "^4.2.1",
    "ng-fullcalendar": "1.7.1",
    "ng-multiselect-dropdown": "0.2.3",
    "ng2-charts": "1.6.0",
    "ng2-translate": "5.0.0",
    "ngx-popover": "0.0.16",
    "popper.js": "1.14.7",
    "rxjs": "6.4.0",
    "rxjs-compat": "^6.4.0",
    "summernote": "0.8.11",
    "toastr": "2.1.4",
    "tslib": "^1.9.0",
    "underscore": "1.9.1",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "^7.3.0",
    "@angular/compiler-cli": "7.2.3",
    "@angular/language-service": "^7.2.3",
     "@compodoc/compodoc": "1.1.8",
    "@types/jasmine": "3.3.8",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.3.29",
    "@types/node": "^10.12.21",
    "codelyzer": "^4.0.1",
    "istanbul-instrumenter-loader": "^3.0.1",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~2.0.0",
    "karma-coverage": "^1.1.2",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^3.0.0",
    "protractor": "~5.4.2",
    "protractor-jasmine2-html-reporter": "0.0.7",
    "source-map-explorer": "^1.5.0",
    "ts-node": "~8.0.2",
    "tslint": "~5.12.1",
    "typescript": "^3.2.4",
    "webpack-bundle-analyzer": "^3.0.3"
  }
}

##### **Compodoc installed globally or locally ?**

Compodoc installed locally and globally

##### **If possible sourcecode of the file where it breaks**

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": ["node"]
  },
  "exclude": ["test.ts", "**/*.spec.ts", "**/*.jpg"]
}

##### **If possible your terminal logs before the error**
Including      : C:\Code\Development\SP\source\src\assets\trubo150.jpg

##### **Motivation for or Use Case**

Would like to exclude files listed in tsconfig.app.json

**Comment by alphagold89** [comment]
same problem using  tscconfig.json, (your own tsconfig) ignores include and exclude

**Comment by bvermolen** [comment]
We have the same problem with an Angular 8 project with a library. When running "npx compodoc -s -p projects/library-name/tsconfig.lib.json" from the project root. All files are included (/src/*, /dist/*, /project/*), but it is excluding the *.spec.ts files.

The tsconfig.lib.json does contain the exclusions:
`  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "../../dist/"
  ]`

**Comment by vogloblinsky** [comment]
@mayureshs the syntax "/*.jpg" breaks compodoc for me here. Is it possible to have a repro in a sample repository ?
