### ISSUE TITLE
[BUG] Angular Route Guards not Checked Correctly

### ISSUE THREAD

**Issue by stevengunneweg** [compodoc/compodoc#745]
##### **Overview of the issue**

When running `compodoc -p src/tsconfig.app.json --coverageTest 100 --coverageMinimumPerFile 100` the coverage for my Angular route guards is not calculated correctly.

The issue seems to be with the class constructor. When adding `@ignore` to its documentation the coverage is 100%.

##### **Operating System, Node.js, npm, compodoc version(s)**

NPM: 6.4.1
node: 10.12.0
@compodoc/compodoc: 1.1.8

##### **Angular configuration, a `package.json` file in the root folder**

I'm using the default `angular.json` and `src/tsconfig.app.json` that come with Angular 7.

##### **Compodoc installed globally or locally ?**

Locally

##### **If possible sourcecode of the file where it breaks**

auth.guard.ts
```typescript
import {
	Injectable,
} from '@angular/core';

import {
	Router,
	CanActivate,
} from '@angular/router';

/**
 * Guard to prevent page access without authentication
 * @implements {CanActivate}
 */
@Injectable()
export class AuthGuard implements CanActivate {

	/**
	 * Class constructor
	 * @param {Router} router
	 */
	constructor(
		public router: Router,
	) {
	}

	/**
	 * Method to evaluate whether page access is allowed
	 * @return {boolean}
	 */
	canActivate(): boolean {
		this.router.navigate(['login']);
		return false;
	}
}
```

##### **If possible your terminal logs before the error**

```
...
75 % for file src/app/routes/route-guards/auth.guard.ts - under minimum per file
-------------------
Documentation coverage (99%) is not over threshold (100%)
Documentation coverage per file is not over threshold (100%)
```

##### **Motivation for or Use Case**

I'm trying to reach 100% code coverage but this bug prevents me from achieving this. My current workaround is to add `@ignore` to the constructor documentation.

##### **Reproduce the error**

Add the route guard shown above to an Angular 7 project and run the command in the description above.

##### **Related issues**

None that I have found.

**Comment by vogloblinsky** [comment]
The router variable for Router instance miss a comment, here is the correct syntax to have 100% for your file

```
/**
 * Class constructor
 * @param {Router} router MISSINGDOC
 */
```

**Comment by stevengunneweg** [comment]
@vogloblinsky thanks for your response. Your solution fixes the issue.

Why is it that that is required in my route guard but not in other files?
I use the same documentation in my page components (see example below). The coverage of these files is 100%.

```
/**
 * Header component
 * @implements {OnInit}
 */
@Component({
	selector: 'app-header',
	templateUrl: './header.component.html',
})
export class HeaderComponent implements OnInit {

	/**
	 * Class constructor
	 * @param {Router} router
	 * @param {Store<RootStoreInterface>} store
	 */
	constructor(
		private router: Router,
		private store: Store<RootStoreInterface>,
	) {
}
```

**Comment by cappster** [comment]
+1
