### ISSUE TITLE
[BUG] Does not work with NRWL integrated Angular Project

### ISSUE THREAD

**Issue by codestitch** [compodoc/compodoc#746]
##### **Does not generate documentation for NRWL integrated angular project**

I'm using NX to structure my project and accommodate multiple apps and reuse components via libraries. Upon following instructions in compodoc guide I didn't encounter any error, only couple of warnings and was able to serve the documentation. However, it wasn't able to document the components.

##### **Operating System, Node.js, npm, compodoc version(s)**

**Angular CLI: 7.0.1
Node: 8.12.0
OS: win10 x64
Angular: 7**

##### **Angular configuration, a `package.json` file in the root folder**

```
 "dependencies": {
    "@angular/animations": "^7.1.3",
    "@angular/cdk": "^7.1.1",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/material": "^7.1.1",
    "@angular/material-moment-adapter": "^7.1.1",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "@nrwl/nx": "7.1.1",
    "@ngrx/effects": "6.1.0",
    "@ngrx/entity": "6.1.0",
    "@ngrx/router-store": "6.1.0",
    "@ngrx/store": "6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "zone.js": "^0.8.26"
     ....
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.4",
    "@angular/cli": "7.0.1",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/language-service": "^7.0.0",
    "@ngrx/store-devtools": "6.1.0",
    "@nrwl/schematics": "7.1.1",
    "@types/node": "^8.9.5",
     ....
}
```

##### **Compodoc installed globally or locally ?**

installed globally

##### **If possible sourcecode of the file where it breaks**

It runs fine w/ some warnings.

##### **If possible your terminal logs before the error**

Warning when running `npm run compodoc` i got these warnings.

![capture](https://user-images.githubusercontent.com/5573444/53490813-90c25c80-3a8c-11e9-8ac6-4b4fc36cacda.PNG)

##### **Motivation for or Use Case**

I'm using NX to structure multiple applications and reuse libraries. And looking forward for compodoc to document it.

##### **Reproduce the error**

Create new angular project via nrwl@7.1.1 and add compodoc. Serve it.

**Comment by barryajones** [comment]
Have you looked at this?

https://github.com/nrwl/nx/issues/275#issuecomment-366720087

or 

https://compodoc.app/guides/tips-and-tricks.html#documentation-of-several-apps-in-a-monorepository

**Comment by MarkPieszak** [comment]
So adding a (root-level) tsconfig.compodoc.json file

```
{
  "extends": "./tsconfig.json",
  "include": [
    "apps/**/*.ts",
    "libs/**/*.ts"
  ]
}
```

And firing compodoc up via a package.json script:

```
"compodoc": "npx compodoc -p ./tsconfig.compodoc.json -s",
```

Seems to work, but for some reason - one of my libraries (no matter what is done with tsconfig paths/etc) doesn't work, it tries to get it from the current location `xyz/xyz/app/@namespace-whatever/auth`, although every other one works.

By doing relative paths `../../../../libs/@namespace-whatever/auth` it all works, but very strange that this one specific library (no different than others) doesn't work.

Even more bizarre, removing all the tsconfig paths etc - it all still works regardless. I'm stumped :D

**Comment by tashoecraft** [comment]
I have the exact same issue as @MarkPieszak. One project randomly doesn't use the aliases. Using the setup specific by the docs results in having each app have it's own doc site that doesn't include the libraries, which isn't exactly what I'd want. This may be more user specific, but I'd rather have the docs all in one place, but a way to segment out each app and see it's tree.
