### ISSUE TITLE
[QUESTION/FEATURE] How to document "slots" (ng-content)

### ISSUE THREAD

**Issue by mistic100** [compodoc/compodoc#749]
I am creating a library which uses a lot of transclusion slots. These are obviously absent from the documentation because they only exist in the template and are not tied to a property of the class.

Is there a prefered way to document these ? Ideally I would like a seperated "Slots" section in the generated documentation, to make it clear they are not input/outputs.

Compodoc 1.1.9

**Comment by vogloblinsky** [comment]
Hi, we could add a Slot tab in the component page, and parse the template and try to find `<slot>` tags and display them with their name, but that's all for the detection part.

**Comment by mistic100** [comment]
It wouldn't add any value I think, without description it is not better than looking at the template tab.

Perhaps it can be combined with a custom code block annotation ?

```
/**
 * Description of the component
 *
 * @slot Main slot
 * @slot selector - other slot
 */
```
