### ISSUE TITLE
[BUG] Code blocks in README.md not work as expected

### ISSUE THREAD

**Issue by belizar** [compodoc/compodoc#750]
##### **Overview of the issue**

I edit readme.md file and add code block

![image](https://user-images.githubusercontent.com/37871475/54204798-c7986980-44b3-11e9-8496-6bbab5b821de.png)

The result is 

![image](https://user-images.githubusercontent.com/37871475/54204841-dd0d9380-44b3-11e9-9cbf-a3c16043259d.png)

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10
Node v8.9.1
compodoc v1.1.9

##### **Compodoc installed globally or locally ?**

locally

**Comment by christophercr** [comment]
Same problem here. Downgrading to version 1.1.8 for the moment where it works as expected...

**Comment by berikin** [comment]
I add that it does not only affect 'README.md', it affects all markdown files, including those added through additional documentation. Also, Downgrading to version 1.1.8 works fine.
