### ISSUE TITLE
[BUG] watch don't work for angular library

### ISSUE THREAD

**Issue by avihai-radwin** [compodoc/compodoc#756]
##### **Overview of the issue**

After i run:
`compodoc -w -r 38084 -p ./projects/rws-lib/tsconfig.lib.json -s -o`
And edit code or docs it don't detect changes

##### **Operating System, Node.js, npm, compodoc version(s)**

OS: Windows 10
Node: v10.15.3
npm: 6.9.0
compodoc: ^1.1.9

**Comment by imike57** [comment]
On my side, for an Angular Library it work.. but not perfectly... 
In fact, it refresh for jsdoc change in ts files... But for *.md files, changes are detected, yet nothing is updated. So each time I have to stop the watching et build again... Any idea why ? 

"@compodoc/compodoc": "^1.1.9",

**Comment by imike57** [comment]
> ##### **Overview of the issue**
> After i run:
> `compodoc -w -r 38084 -p ./projects/rws-lib/tsconfig.lib.json -s -o`
> And edit code or docs it don't detect changes
> 
> ##### **Operating System, Node.js, npm, compodoc version(s)**
> OS: Windows 10
> Node: v10.15.3
> npm: 6.9.0
> compodoc: ^1.1.9

You should add the -w flag at the end maybe...

here mine 

"compodocLib": "npx compodoc -p projects/ng-evostrap/tsconfig.lib.json -s -w"

**Comment by avihai-radwin** [comment]
> > ##### **Overview of the issue**
> > After i run:
> > `compodoc -w -r 38084 -p ./projects/rws-lib/tsconfig.lib.json -s -o`
> > And edit code or docs it don't detect changes
> > ##### **Operating System, Node.js, npm, compodoc version(s)**
> > OS: Windows 10
> > Node: v10.15.3
> > npm: 6.9.0
> > compodoc: ^1.1.9
> 
> You should add the -w flag at the end maybe...
> 
> here mine
> 
> "compodocLib": "npx compodoc -p projects/ng-evostrap/tsconfig.lib.json -s -w"

I tried got the same result
the flag work because i can see in the console:
`Watching sources in rws-lib folder`
but still no change after i edit the files
