### ISSUE TITLE
[FEATURE] less verbose cli output

### ISSUE THREAD

**Issue by simbo** [compodoc/compodoc#759]
(Version 1.1.9)

### Problem

compodoc's cli output is quite verbose. There is the `--silent` option, but this way also error messages and build success messages are hidden.
There should be a way to not spam your screen or CI logs and although see error and success messages.

### Suggestions

Make cli output less verbose by default. Only display warnings, errors and final success or fail messages. Nobody needs to be informed about hundreds of successful operations.

Offer options to show more output for debugging (e.g. `--verbose`, `--debug` or `--loglevel=info`).

Offer CI friendly output (e.g. `--ci` = no big splash screen logo or unnecessary whitespace with loglevel error).

**Comment by bamazap** [comment]
`--silent` doesn't even get rid of all of the command line output

**Comment by jepstein-eagle** [comment]
@bamazap Are you asking about the banner in silent mode? If so, #747 addresses that functionality (to be released as part of 1.2.0 😄).

Following on @simbo, The ability to control log output levels more than an on / off option would be beneficial for our use case as well on a build server. We like compodoc a lot, but we want to bring out exceptions and warnings in our logs by having less information about normal operations.

**Comment by vogloblinsky** [comment]
@jepstein-eagle @simbo Well receive, will add output levels in version 1.1.10

**Comment by vogloblinsky** [comment]
@jepstein-eagle @simbo 
I am planning to add this in next release. I will use this lib : https://github.com/pimterry/loglevel
The levels ordered are : trace, debug, info, warn, error
- default level for Compodoc : info
I will add a flag for selecting level --loglevel=XXX
I will add short flags : 
--verbose for trace level
--debug for debug level
--ci for warn
Ok for you ?

**Comment by jepstein-eagle** [comment]
@vogloblinsky Thank you for following up and completing this work!

These will work well for our use case on the build server! In terms of the short flags, I have several suggestions for maximum customization:
1. `--trace ` for trace (Is this needed?)
1. `--warn` or `--ci` for warn (Not everyone might use this for continuous integration so it covers more cases?)
1. `--error` for error (Is this needed?)

Keep up the great work! 🎸

**Comment by jepstein-eagle** [comment]
Can this stay open stale bot? It will be released as part of 1.1.11, which has not been released.

Ohh how I enjoy conversing with machines...

**Comment by jepstein-eagle** [comment]
Can this stay open stale bot? It will be released as part of 1.1.12, which has not been released.

**Comment by jepstein-eagle** [comment]
Can this stay open stale bot? It will be released as part of 1.1.12, which has not been released.

**Comment by jepstein-eagle** [comment]
Can this stay open stale bot? It will be released as part of 1.1.12, which has not been released.

**Comment by simbo** [comment]
@jepstein-eagle I am on `"@compodoc/compodoc": "1.1.19"` and none of these cli options are working.
has this ever been merged?

**Comment by jepstein-eagle** [comment]
Hey, thanks for checking into this @simbo after a few days, haha! I also tried, and I do not think this functionality has been merged yet...

**Comment by jtama** [comment]
Hi this is still not available and generating tons and tons of logs in ci. Please add this `--ci option` !

**Comment by vogloblinsky** [comment]
—silent doesn’t do the trick ?

**Comment by jtama** [comment]
Sorry I haven't even tried, so the issue marke as closed by stalebot and saw the "won't fix" label. Stoped there.

It does work with the `--silent` option though. Thanks.
