### ISSUE TITLE
[BUG] Issue rendering Markdown tables, list, and indented list

### ISSUE THREAD

**Issue by vogloblinsky** [compodoc/compodoc#76]
Markdown tables, list, and indented list are not styled.

**Comment by zpydee** [comment]
@vogloblinsky including tables also results in white space (multiple `<br>` tags) above the table.

<img width="717" alt="screen shot 2017-01-20 at 8 34 18 am" src="https://cloud.githubusercontent.com/assets/6129162/22138853/633eab28-deeb-11e6-8876-7ff900c7db6c.png">

<img width="721" alt="screen shot 2017-01-20 at 8 36 06 am" src="https://cloud.githubusercontent.com/assets/6129162/22138884/98abe5fa-deeb-11e6-8c1e-b19a56b17a26.png">

**Comment by vogloblinsky** [comment]
@dave can you provide an example markdown

**Comment by zpydee** [comment]
As soon as i'm back at my desk :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by zpydee** [comment]
```
/**
 * Like any Angular application, the purpose of this module is simply to orchestrate the remainder of the  
 * modules. In our specific case, this involves importing the `CoreModule`, `ShellModule`,  `FeaturesModule` 
 * and `AppRoutingModule`, and declaring the main `AppComponent`.
 * 
 * In addition, the  module also allows developers to manage some application variables through the 
 * introduction of an `app.config.ts` file, which allows customisation of the following services:
 * 
 *  ##### CoreModule Configurability
 * 
 * CoreModule Service | Configuration variables
 * --- | ---
 * http | __baseUrl__: The base url of the api end-point. As can be seen, this is set as an environment variable
 * auth | __requireLogin__: switches off sign-in requirement for apps which offer public features only and thus don't require authentication
 * 
 */
```

**Comment by vogloblinsky** [comment]
Ok fixed, coming in next release today

**Comment by icemanven** [comment]
hi , i still have the same issue, the table is not styled, i just get de pipes
