### ISSUE TITLE
[FEATURE] Custom Script Resources

### ISSUE THREAD

**Issue by simbo** [compodoc/compodoc#760]
Is there a way to add custom javascript resources to the template like you can add custom css files via `extTheme`?

I would like to add more languages to prism... and I can think of more usecases (e.g. custom tracking scripts for piwik/matomo).

If this feature is not supported yet, I think it's worth implementing. :)
Maybe I could create a PR...

**Comment by vogloblinsky** [comment]
Yes go for it, PR is welcome ;)
