### ISSUE TITLE
[BUG] Watch mode watching generated documentation, not source code

### ISSUE THREAD

**Issue by Chowarmaan** [compodoc/compodoc#763]
##### **Overview of the issue**
Running the compodoc using a .compodocrc does not work correctly with the open, serve and watch options.  Using the configuration file, the output indicates that the watch is watching for changes in the docs folder, not the source folder.  Changing source code does not cause a rebuild of the documentation.  Modify the generated files in the docs output does cause a rebuild of the documentation.

```
.compodocrc
{
    "open": true,
    "output": "docs/DevAPI",
    "serve": true,
    "theme": "original",
    "tsconfig": "tsconfig.json",
    "watch": true
}
```

package.json script

		"compodoc": "compodoc --config .compodocrc",

Run on the command line with `npm run compodoc`

Sample of the output:

[14:24:48] External custom favicon copy succeeded
[14:24:48] Documentation generated in docs/DevAPI/ in 20.166 seconds using original theme
[14:24:48] Serving documentation from docs/DevAPI/ at http://127.0.0.1:8080
[14:24:48] Watching sources in docs folder

Change the index.html file that was generated will get additional output:

[14:28:01] File docs\DevAPI\index.html has been changed
[14:28:01] File docs\DevAPI\index.html.bak has been added

The command line `$ compodoc --serve --open --tsconfig tsconfig.json --watch --theme original --name "Peel Dart League"` does not work properly either.

##### **Operating System, Node.js, npm, compodoc version(s)**
Windows 10
Node V11.6.0
npm 6.9.0
Compodoc 1.1.9

##### **Angular configuration, a `package.json` file in the root folder**
package.json

{
	"name": "sample",
	"description": "sample",
	"version": "2.0.0",
	"private": true,
	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"build": "ng build",
		"test": "ng test --code-coverage",
		"lint": "ng lint",
		"e2e": "ng e2e",
		"compodoc": "compodoc --config .compodocrc",
		"stryker": "stryker run stryker.conf.js"
	},
	"dependencies": {
		"@angular/animations": "~7.2.0",
		"@angular/cdk": "^7.3.5",
		"@angular/common": "~7.2.0",
		"@angular/compiler": "~7.2.0",
		"@angular/core": "~7.2.0",
		"@angular/fire": "^5.1.2",
		"@angular/flex-layout": "^7.0.0-beta.24",
		"@angular/forms": "~7.2.0",
		"@angular/material": "^7.3.5",
		"@angular/platform-browser": "~7.2.0",
		"@angular/platform-browser-dynamic": "~7.2.0",
		"@angular/router": "~7.2.0",
		"core-js": "^2.5.4",
		"firebase": "^5.9.1",
		"hammerjs": "^2.0.8",
		"rxjs": "~6.3.3",
		"rxjs-compat": "^6.4.0",
		"tslib": "^1.9.0",
		"typescript-collections": "^1.3.2",
		"zone.js": "~0.8.26"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "~0.13.0",
		"@angular/cli": "~7.3.4",
		"@angular/compiler-cli": "~7.2.0",
		"@angular/language-service": "~7.2.0",
		"@compodoc/compodoc": "^1.1.9",
		"@stryker-mutator/core": "^1.1.0",
		"@stryker-mutator/html-reporter": "^1.1.0",
		"@stryker-mutator/karma-runner": "^1.1.0",
		"@stryker-mutator/typescript": "^1.1.0",
		"@types/jasmine": "~2.8.8",
		"@types/jasminewd2": "~2.0.3",
		"@types/node": "~8.9.4",
		"codelyzer": "~4.5.0",
		"jasmine-core": "~2.99.1",
		"jasmine-spec-reporter": "~4.2.1",
		"karma": "~4.0.0",
		"karma-chrome-launcher": "~2.2.0",
		"karma-coverage-istanbul-reporter": "~2.0.1",
		"karma-jasmine": "~1.1.2",
		"karma-jasmine-html-reporter": "^0.2.2",
		"protractor": "~5.4.0",
		"ts-node": "~7.0.0",
		"tslint": "~5.11.0",
		"typescript": "~3.2.2"
	}
}

##### **Compodoc installed globally or locally ?**
Compodoc installed locally

##### **Motivation for or Use Case**
The tool is monitoring the directory for the code it generated, not the source code being changed.

##### **Reproduce the error**
Run the compodoc with the .compodocrc file in the root directory of the project.

**Comment by waji-io** [comment]
Have the same problem

**Comment by vogloblinsky** [comment]
@Chowarmaan cannot reproduce. Could you try on your side using this repo https://github.com/compodoc/compodoc-demo-todomvc-angular ?
Thanks

**Comment by Chowarmaan** [comment]
I tried it with the latest version, and I cannot duplicate the issue anymore.  The last line of the watch `[09:25:02] Already watching sources in docs folder` seems to indicate that this might be the wrong folder, but in checking and testing with sources in both folders, I cannot duplicate the issue.
