### ISSUE TITLE
[QUESTION] Solely document inputs/outputs

### ISSUE THREAD

**Issue by LukasMachetanz** [compodoc/compodoc#764]
Hey,

I just would like to know if it is possible to just document the inputs `@Input()` and outputs `@Output()` in components. In other words to just document the interface of the component.

Thanks. :)

**Comment by vogloblinsky** [comment]
Yes, add a jsdoc tag on it, watch the example project : https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/master/src/app/list/todo/todo.component.ts
