### ISSUE TITLE
[BUG] Code blocks are not properly rendered in the README.md file

### ISSUE THREAD

**Issue by zolakt** [compodoc/compodoc#765]
I'm not sure if I'm doing it right, but I just can't get it to work. I'm using the same example as you have on your demo app README.md.

This is the code I add to the readme file:
```javascript
function hello() {
    console.log('hello world !');
}
```
And this is the output I get:
![image](https://user-images.githubusercontent.com/1048531/55611736-af4ffd80-5786-11e9-9f7a-2f28c2270a83.png)

As you can see it's not transformed to html correctly. There is no pre block. There is no "language" attribute on the code block... so prism.js doesn't pick it up.

I'm using the the 1.1.9 version. Tried also with 1.1.8 and 1.1.7... same result.
Am I doing something wrong or is it a bug?

Unrelated, but table syntax also doesn't work in README.md

**Comment by berikin** [comment]
Hi, you have to use the [GitHub Flavored Markdown ](https://help.github.com/en/articles/creating-and-highlighting-code-blocks). There is a problem in version 1.1.9, but if you use the development branch it will work correctly.

**Comment by zolakt** [comment]
Ok thanks. Although, I tried with 1.1.8 and 1.1.7... got the same error.
I'll have to wait for a release, can't use the development branch, since it could break the CD at some point.

**Comment by berikin** [comment]
> 
> 
> Ok thanks. Although, I tried with 1.1.8 and 1.1.7... got the same error.
> I'll have to wait for a release, can't use the development branch, since it could break the CD at some point.
> For now I resorted to writing html tags.

If you are concerned about version stability then switch to version 1.1.8 and write the code block as follows in the README.md (removing spaces in `` ` ` ` `` :

` ` `javascript
function hello() { 
    console.log('hello world !'); 
} 
` ` `

```javascript
function hello() { 
    console.log('hello world !'); 
} 
```

**Comment by zolakt** [comment]
Thanks. I'll give it a try again, although I did get the same problem with 1.1.8.
Also I don't think 1.1.8 annotates static members, and that is a much bigger showstopper than formatting code blocks.

**Comment by admosity** [comment]
This is how https://github.com/compodoc/compodoc-demo-todomvc-angular looks like with version 1.1.9.

![image](https://user-images.githubusercontent.com/4655972/58658808-61232a80-82ef-11e9-8c33-f69ac4b56114.png)

This also looks to be the same issue: #776
