### ISSUE TITLE
[FEATURE] Support @publicApi (or custom) tag

### ISSUE THREAD

**Issue by Airblader** [compodoc/compodoc#766]
##### **Overview of the issue**

We can currently control whether documentation is emitted for some entity (be it a class, function, …) by using `@internal` or `@private` in combination with `disableInternal` and `disablePrivate`, respectively.

In my (probably not uncommon) usecase I only want to document what I consider public API. With the current solution I need to remember to mark everything I don't consider public as mentioned, which can quite easily be forgotten.

I would much rather do what, e.g., Angular is doing itself as well: use an explicit tag such as `@publicApi` to document *only* what I want to be emitted in the documentation. Thus my feature request is either to support this along with some `onlyPublicApi` flag, or alternatively allow passing a single or a list of tags via some `onlyAnnotatedWith` setting.

##### **Related issues**

Somewhat related: https://github.com/compodoc/compodoc/issues/128

**Comment by pburgmer** [comment]
Would be great to have a explicit marker for public API. For library projects it would be cool to just include exports of public_api.ts (or the entry point file) automatically.
