### ISSUE TITLE
[FEATURE] Generate unified documentation for angular-cli library

### ISSUE THREAD

**Issue by abadakhshan** [compodoc/compodoc#767]
I create a project with angular-cli with multiple libraries.
These libraries are dependent on each other and I want to create unified documentation for these libraries.
I found this 
https://github.com/compodoc/compodoc/issues/610#issuecomment-406983160
that helps me to create separate documentation for each library.
But I want unified documentation .
How can I do that?

**Comment by micoll12268** [comment]
You can create a tsconfig.compodoc.json file with the includes you need for your libraries and run compodoc based on that. 

compodoc -p tsconfig.compodoc.json

**Comment by abadakhshan** [comment]
@micoll12268

Thank you 

I created a tsconfig.compodoc.json in "Projects" folder 

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "include": [
      "**/*.ts"
    ]
  }
}
```

and then  

`compodoc -p projects/tsconfig.compodoc.json -s -o -w`

It worked correctly.
