### ISSUE TITLE
[BUG] The dot npm package has a vulnerability

### ISSUE THREAD

**Issue by dennisporterjr** [compodoc/compodoc#769]
##### **Overview of the issue**

Current Compodoc/ngd version (in master) depends on dot@1.1.1, which contains the vulnerability identified here:

https://www.npmjs.com/advisories/798

This is causing npm audit checks to break.

##### **Operating System, Node.js, npm, compodoc version(s)**

Looks like this dependency was added 2 years ago. And all versions of dot are affected.

https://github.com/compodoc/ngd/commit/bb3c75cc3de493f5339320e3250389805b4d6b6b

##### **Suggest a Fix**

Doesn't look like dot is actively developed any more because the last release was [2 years ago](https://github.com/olado/doT/releases). So I think you'd need to replace it with a different npm package.

**Comment by x2pdenjo** [comment]
Is there planned to replace this package? They won't fix it.

**Comment by vogloblinsky** [comment]
Sorry but dot Advisory page said : "No fix is currently available".
We are re-writing graph engine to a client-side solution. This re-write will fix this issue when available.
