### ISSUE TITLE
[BUG] npm audit returns - command injection

### ISSUE THREAD

**Issue by kthomas182** [compodoc/compodoc#774]
##### **Overview of the issue**

running npm audit returns: 

│ Moderate      │ Command Injection                                            │
│ Package       │ dot                                                          │
│ Patched in    │ No patch available                                           │
│ Dependency of │ @compodoc/compodoc [dev]                                     │
│ Path          │ @compodoc/compodoc > @compodoc/ngd-transformer > dot         │
│ More info     │ https://nodesecurity.io/advisories/798                       │

##### **Operating System, Node.js, npm, compodoc version(s)**

Angular CLI: 7.3.6
Node: 10.4.1
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         7.3.6
@angular/cdk                       6.4.7
@angular/cli                       7.3.6
@angular/compiler-cli              7.2.13
@angular/flex-layout               6.0.0-beta.15
@angular/material                  6.4.7
@angular/material-moment-adapter   6.4.7
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.6
@schematics/update                 0.13.6
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.29.0

**Comment by nrbabcock** [comment]
Are there any plans to fix this? Is this project even maintained any more?

**Comment by vogloblinsky** [comment]
Yes i have this issue on the radar, but the dot package seems to no have activity on that since the nodesecurity report : https://github.com/olado/doT/issues/281
