### ISSUE TITLE
[BUG] README.md is broken in compodoc but correct on GitHub

### ISSUE THREAD

**Issue by klemenoslaj** [compodoc/compodoc#776]
##### **Overview of the issue**

When generating the documentation with compodoc, markdown in general is completely broken.  
The perfect example is README.md, which looks fine directly on GitHub, but it's broken in compodoc generated page.  

I even tried to change my README.md completely to the same as on the following repo: https://github.com/compodoc/compodoc-demo-todomvc-angular

##### **Operating System, Node.js, npm, compodoc version(s)**

- OSX
- node v10.15.1
- npm 6.9.0
- yarn 1.15.2
- compodoc 1.1.9

##### **Angular configuration, a `package.json` file in the root folder**

https://raw.githubusercontent.com/klemenoslaj/ng-action-outlet/compodoc-broken-markdown/package.json

##### **Compodoc installed globally or locally ?**

Locally.

##### **If possible sourcecode of the file where it breaks**

Full sourcecode available in the repo mentioned in the next section "Reproduce the error".

##### **Reproduce the error**

To reproduce the problem:
- clone the following repository: https://github.com/klemenoslaj/ng-action-outlet
- checkout branch: compodoc-broken-markdown
- install dependencies with `yarn`
- execute `yarn docs:build.serve`
- open http://127.0.0.1:8080 with browser of choice

**Comment by tanepiper** [comment]
Can confirm the same issue on https://tanepiper.github.io/ngx-tinynodes/additional-documentation/tinynodes-library-docs/ngx-editorjs-readme.html

**Comment by anodynos** [comment]
I have the same issue. 

The [syntax highlighting](https://help.github.com/en/articles/creating-and-highlighting-code-blocks#syntax-highlighting) of including files .md files that appear in "additional documentation" is broken when you use code fences i.e "```....```".  

When you ident the code, it works, but without any language parsing/style (just a black box with white text)

**Comment by anodynos** [comment]
Any updates on this  @manekinekko? 
I read in some comments that the development branch fixes this, maybe we could have a new release?
Regards

**Comment by vogloblinsky** [comment]
I will release a new version next week

**Comment by ITsvetkoFF** [comment]
@vogloblinsky do you need some help with this fix? :)

**Comment by ruslanguns** [comment]
How you rendering the markdown gets fixed soon... Thanks in advance!

**Comment by vogloblinsky** [comment]
Yep i will release a new version tonight
