### ISSUE TITLE
[QUESTION] cannot generate Docs

### ISSUE THREAD

**Issue by xxyyzz2050** [compodoc/compodoc#780]
I cannot generate docs for this [project](https://github.com/xxyyzz2050/eldeebCMS), even though it works well without Angular or typescript errors, and I can serve it in the browser.

also, I need to exclude some dirs from the docs. for example I want to generate separate docs for each library in my project,
or to not include 'test' folders in my docs, because they just created for testing purposes.

I use angular universal,
and I made compodoc options as a property in my package.json

another note:
when I remove "-p package.json" from the cmd, it gives an error: tsconfig.json not found

**Comment by Trewaters** [comment]
I just discovered compodoc a couple days ago but I was able to build documentation using this in my package json scripts...

`"compodoc":"npx compodoc -p src/tsconfig.app.json"`

When I run this `npm run compodoc` it builds for me. Hope that helps.

**Comment by vogloblinsky** [comment]
@xxyyzz2050 just works for me with this :

```
compodoc -p src/tsconfig.app.json
```

**Comment by xxyyzz2050** [comment]
I don't have a problem with the command itself, it makes compoDoc run (regardless of the issue that it dosen't discover package.json itself unless I pass -p package.json),

but running compodoc causes an error in some files. please clone the repo and try to run compodoc to see the error
