### ISSUE TITLE
[FEATURE] Support for deployurl or basehref

### ISSUE THREAD

**Issue by slimm609** [compodoc/compodoc#782]
##### **Overview of the issue**

Support for a basehref or deployurl.     We are trying to serve compiled compodoc files in a subfolder structure instead of at the root.    so our Document root would be /$service/documentation.    Currently all branding and links fail because they are trying to reference the base url with / and its not finding it at that location. 

##### **Operating System, Node.js, npm, compodoc version(s)**

node 10.15
compodoc - latest

**Comment by slimm609** [comment]
or rather, it looks like its using the deployurl or basehref from the project.    Ideally, overriding that to be a subfolder of that would be ideal

**Comment by bhofmei** [comment]
I second this. Similarly, I'd love to be able to set the url of the link in the top of the menu and/or be able to add an additional link above that. Namely, I want to embed compdoc into a website and want that menu link to go to the website's home page not the compodoc portion home page

**Comment by slimm609** [comment]
an accepted and known issue but being closed as won't fix?
