### ISSUE TITLE
[FEATURE] disableSourceCode flag for json format

### ISSUE THREAD

**Issue by snovos** [compodoc/compodoc#785]
It works with **html** format, but in **json** `sourceCode` is still there and makes file size really huge. Would be great if by setting that flag to true, it would omit `sourceCode` property from json

**Comment by snovos** [comment]
Any updates on this?

**Comment by demiro** [comment]
I need this as well, how come it shows?
looks like it shows on normal (html) format as well, regardless of the flag :/

**Comment by vogloblinsky** [comment]
@demiro works fine for JSON right now ;)

**Comment by demiro** [comment]
> @demiro works fine for JSON right now ;)

yeah, it does, for the TS code... but HTML or CSS is still there... even if I use `--disableTemplateTab --disableStyleTab`
