### ISSUE TITLE
[FEATURE] Documentation for monorepository

### ISSUE THREAD

**Issue by sergeik** [compodoc/compodoc#793]
Hello everyone,
I work on the library project that uses monorepository architecture. 

- @company/core
    - @company/core/auth
    - @company/core/i18n
- @company/module
    - @company/module/reports
    - @company/module/admin
- @company/ui
    - @company/ui/datepicker
    - @company/ui/datatable

Compodoc  generates awesome documentation, but there are few missed parts:
1. I don't see any ways how I can create documentation groupped by packages.
2. Modules/components etc. don't contain information about package they belong

These packages are not separate projects but parts of one library, that's why I need only one documentation  instance.

Any advice would be appreciated.

**Comment by vogloblinsky** [comment]
Compodoc doesn't support out of the box right now monorepository. I have to work on that soon.
