### ISSUE TITLE
[BUG] missing generate page

### ISSUE THREAD

**Issue by Tuqzar** [compodoc/compodoc#799]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'compodoc' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
5 info lifecycle client-app@0.0.0~precompodoc: client-app@0.0.0
6 info lifecycle client-app@0.0.0~compodoc: client-app@0.0.0
7 verbose lifecycle client-app@0.0.0~compodoc: unsafe-perm in lifecycle true
8 verbose lifecycle client-app@0.0.0~compodoc: PATH: *************( my secret :( )
9 verbose lifecycle client-app@0.0.0~compodoc: CWD: C:\WORK\backend\Books.WebNew\ClientApp
10 silly lifecycle client-app@0.0.0~compodoc: Args: [ '/d /s /c', 'npx compodoc -p src/tsconfig.app.json -s' ]
11 silly lifecycle client-app@0.0.0~compodoc: Returned: code: 1  signal: null
12 info lifecycle client-app@0.0.0~compodoc: Failed to exec compodoc script
13 verbose stack Error: client-app@0.0.0 compodoc: `npx compodoc -p src/tsconfig.app.json -s`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid client-app@0.0.0
15 verbose cwd C:\WORK\backend\Books.WebNew\ClientApp
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "compodoc"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error client-app@0.0.0 compodoc: `npx compodoc -p src/tsconfig.app.json -s`
22 error Exit status 1
23 error Failed at the client-app@0.0.0 compodoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

_____________________________________ in console
[10:03:02] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client-app@0.0.0 compodoc: `npx compodoc -p src/tsconfig.app.json -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client-app@0.0.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\taliev\AppData\Roaming\npm-cache\_logs\2019-06-27T07_03_02_904Z-debug.log

**Comment by vogloblinsky** [comment]
Could you explain a little more your problem please ?
