### ISSUE TITLE
[BUG] Documentation not generated due to interfaces bug

### ISSUE THREAD

**Issue by siegerx3** [compodoc/compodoc#80]
##### **Overview of the issue**

Documentation generation fails during coverage report but not showing any error.

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10,
Node 6.2.0
compodoc 0.0.34 local&global

Error happens in line 436 of src/app/application.ts [Link](https://github.com/compodoc/compodoc/blob/master/src/app/application.ts#L436) when the `properties` property of an interface is not found and it's `length` is accessed.

As far as i know, interfaces don't have properties.

I would make a PR but i don't know what's your desired solution to this problem.

**Comment by vogloblinsky** [comment]
Hi,
Fine, same reports here : https://github.com/compodoc/compodoc/issues/65 but without indication for debugging.
I have fixed that this morning, did you have an interface example for testing ?

**Comment by siegerx3** [comment]
`export interface DialogButton {
  text: string;
  action?: () => void;
}`

I guess any will do but that's the one i tried it with.

**Comment by vogloblinsky** [comment]
Did'nt break on my side before my fix from this morning...

**Comment by siegerx3** [comment]
What do you mean? It didn't break until you fixed what supposedly caused the break?

But your fix will definitely solve this problem.

**Comment by vogloblinsky** [comment]
Using your interface, i cannot reproduce the error like this one : 

![image](https://cloud.githubusercontent.com/assets/3470892/22031097/92a82f62-dcd7-11e6-85f4-d8620b405e71.png)

**Comment by siegerx3** [comment]
Are you testing this with your fix included?
Because the version i'm getting from npm doesn't have the check for `properties` and `length`.

If i remove the interfaces part from the coverage check, everything works fine on that part.

**Comment by siegerx3** [comment]
Actually i'm unable to reproduce the error now aswell.

Earlier i also had an emtpy folder except the above interface, i ran compodoc and it just stopped after the coverage report without any error message.
So i added logs in the index-cli.js to find out what line is causing the error until i ended up at where i said.

I also outputted the `.inter` object to check if properties is in fact missing, and it was...

**Comment by vogloblinsky** [comment]
0.0.35 online, made a test with it

**Comment by siegerx3** [comment]
So, it is definitely working now with 0.0.35...
Guess you can label it as "unreproducable error but it doesn't matter because it's fixed now" ^^

Thanks tho! Very glad i found this library. Just needed this.

**Comment by vogloblinsky** [comment]
Thanks, how did you find it ?

**Comment by siegerx3** [comment]
The error or this library?

**Comment by siegerx3** [comment]
I think it was this question [http://stackoverflow.com/questions/37950403/angular2-documentation-generator](http://stackoverflow.com/questions/37950403/angular2-documentation-generator)

**Comment by vogloblinsky** [comment]
Thanks ;)
I may be need to marketing on stackoverflow.

**Comment by siegerx3** [comment]
[http://stackoverflow.com/search?q=angular2+documentation](http://stackoverflow.com/search?q=angular2+documentation)

First five questions might be useful to write an answer.

I'm sure i'll be contributing a bit in the future. I'll be using it now and i might have some features or bugs to fix ;)

**Comment by vogloblinsky** [comment]
You are welcome for features more than bugs :smile:

**Comment by siegerx3** [comment]
Bugs are easier to find tho :/ For features i will have to take a deeper look at the code first to understand what's happening^^ For now i'm satisfied anyway :)
