### ISSUE TITLE
[ENHANCEMENT] Code becomes clutter due to too much comments

### ISSUE THREAD

**Issue by basheerOct** [compodoc/compodoc#800]
Why need for comment on every property or above on every `interface, component or enum` as it clutters the code but rather tidy? e.g

```
interface User {
 username: string;
 password: string;
}
```
Is there any need for the comments for the above `interface` at all?

**Comment by vogloblinsky** [comment]
Can you explain a little more your issue ? thanks

**Comment by Dk-Raziel** [comment]
Just to add on this enhancement, this is the stack-overflow question that bringed me here. (Easier than copy pasting)

https://stackoverflow.com/questions/57207368/how-to-properly-document-interface-properties-in-compodoc-angular2

But basically the clutter happens with this

```
/**
 * Weather information
 */
interface CityWeather {
  /**
   * Weather condition id
   */
  id: number;

  /**
   * Group of weather parameters (Rain, Snow, Extreme etc.)
   */
  main: string;

  /**
   * Weather condition within the group
   */
  description: string;

  /**
   * Weather icon id
   */
  icon: string;
}
```

And he's asking for something like this

```
/**
 * Weather information
 *
 * @property id Weather condition id
 * @property main Group of weather parameters (Rain, Snow, Extreme etc.)
 * @property description Weather condition within the group
 * @property icon Weather icon id
 */
interface CityWeather {
  id: number;
  main: string;
  description: string;
  icon: string;
}
```
