### ISSUE TITLE
[BUILD]: Update Open Collective

### ISSUE THREAD

**Issue by emanuelbuholzer** [compodoc/compodoc#803]
### Overview
The package `opencollective` is [officially deprecated](https://github.com/opencollective/opencollective-postinstall/issues/15#issuecomment-459245103) leads to issues like https://github.com/opencollective/opencollective-postinstall/issues/15. 

### Suggested Fix
Upgrade to the replacement `opencollective-postinstall` which contains functionality to disable the Open Collective message (e.g. CI) and is more leightweight.

**Comment by vogloblinsky** [comment]
Fixed by https://github.com/compodoc/compodoc/pull/804
