### ISSUE TITLE
[BUG] Unable to generate compodoc of mutiple project

### ISSUE THREAD

**Issue by prashantkoshta** [compodoc/compodoc#806]
Compodoc is not generating for sub projects. In my case i have main application within we have multiple angular project (sub application example ng application subapp1) so in this case only main application generated. if sub application compodoc need then i have to point subapp config. but both together in one compodoc not getting generated.

**Comment by pstephenwille** [comment]
Have you seen this issue, it might help.
https://github.com/compodoc/compodoc/issues/767
