### ISSUE TITLE
[FEATURE] Search results configurable MAX_RESULTS and pagination

### ISSUE THREAD

**Issue by tzinckgraf** [compodoc/compodoc#811]
We are hitting an issue with the MAX_RESULTS being hard-coded. We want to show all the results, as opposed to just the first 15. Ideally, this would have pagination as well.

If this is reasonable, I can put the code together and submit a PR.

I found two issues similar, but not quite the same
https://github.com/compodoc/compodoc/issues/619
https://github.com/compodoc/compodoc/issues/726

**Comment by vogloblinsky** [comment]
@tzinckgraf no problem for a PR.

**Comment by tzinckgraf** [comment]
I submitted a PR for this issue.

I made it a command line option for now. I started to look at pagination, but that would be a much bigger change. Happy to create another FEATURE request for that.
