### ISSUE TITLE
[FEATURE] Overview graph hard to read on large projects

### ISSUE THREAD

**Issue by some1awesome** [compodoc/compodoc#814]
##### **Overview of the feature**
We love compodoc, but we can't really use the graph on the overview page because our app is so large that the graph is pretty hard to read. Is there a way that the nodes of the graph can be laid out farther separated in larger projects?

##### **Motivation for or Use Case**
We can't really read the graph, but feel that if we could it would be extremely useful.

This is a picture of what it looks like in our project when it is completely zoomed in.

![image](https://user-images.githubusercontent.com/14840143/61329165-eac48400-a7d9-11e9-8f12-bad2064b89f8.png)

**Comment by sonofflynn89** [comment]
Please! This would make all the difference for a project I'm working on.

**Comment by Rob1kelly15** [comment]
I agree.  This is a tool we love using, but becomes really hard to manage and see as our application grows.  If we could have more control over the spacing and layout of the graph this would be much more useful for large projects such as ours.

**Comment by vogloblinsky** [comment]
I understand. I have started working on a new engine which will draw the graph client-side, but i am not satisfied about the rendering. Need to find a way to draw it cleaner for very large graph.
I have in parallel started refactoring the codebase to fix many regular issues.

**Comment by jparry67** [comment]
Agreed! My friend agrees too!
