### ISSUE TITLE
[FEATURE] Usage Tab

### ISSUE THREAD

**Issue by some1awesome** [compodoc/compodoc#815]
##### **Overview of the feature**
It would be incredibly helpful if there was a new tab type that listed where the item is being used.  For example todo.component.ts uses todo.service.ts, therefore todo.component.ts would be listed on the "usage" tab on the todo.service.ts page. 

##### **Motivation for or Use Case**

We are so often making changes to shared components or services that are used throughout our app.  We would love to be able to easily see what impact a change to one of those would cause throughout the app.  It would be incredibly valuable to us to be able to see exactly what other components or services use a given item.

**Comment by jparry67** [comment]
Yes this would be very helpful! Especially on really big apps.

**Comment by sonofflynn89** [comment]
Thumbs up for this one! Please Implement!
