### ISSUE TITLE
[BUG] Compodoc , There was a problem during parsing or generation of the documentation

### ISSUE THREAD

**Issue by MelGharbi** [compodoc/compodoc#824]
Hi, I cannot run compodoc. I tried a local and a global install, but i have the same error message. 

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/Cellar/node/12.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compodoc'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.6.0
4 verbose run-script [ 'precompodoc', 'compodoc', 'postcompodoc' ]
5 info lifecycle octeria.barometre@2.1.0~precompodoc: octeria.barometre@2.1.0
6 info lifecycle octeria.barometre@2.1.0~compodoc: octeria.barometre@2.1.0
7 verbose lifecycle octeria.barometre@2.1.0~compodoc: unsafe-perm in lifecycle true
8 verbose lifecycle octeria.barometre@2.1.0~compodoc: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle octeria.barometre@2.1.0~compodoc: CWD: /Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin
10 silly lifecycle octeria.barometre@2.1.0~compodoc: Args: [ '-c', 'npx compodoc -p src/tsconfig.app.json' ]
11 silly lifecycle octeria.barometre@2.1.0~compodoc: Returned: code: 1  signal: null
12 info lifecycle octeria.barometre@2.1.0~compodoc: Failed to exec compodoc script
13 verbose stack Error: octeria.barometre@2.1.0 compodoc: `npx compodoc -p src/tsconfig.app.json`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:203:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:203:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid octeria.barometre@2.1.0
15 verbose cwd /Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/Cellar/node/12.6.0/bin/node" "/usr/local/bin/npm" "run" "compodoc"
18 verbose node v12.6.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error octeria.barometre@2.1.0 compodoc: `npx compodoc -p src/tsconfig.app.json`
22 error Exit status 1
23 error Failed at the octeria.barometre@2.1.0 compodoc script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by vogloblinsky** [comment]
Try using it without npx

**Comment by vogloblinsky** [comment]
Ok just tried on my side.

use the syntax : `npx @compodoc/compodoc ...`

I have updated the documentation.

**Comment by MelGharbi** [comment]
Hi @vogloblinsky, thank you for your quick answer, but i'm still facing the same bug. Even if i updated the script command to :     "compodoc": "npx compodoc -p src/tsconfig.app.json -w -s"
and tried also with     "compodoc": "compodoc -p src/tsconfig.app.json -w -s" and     "compodoc": "npx @compodoc/compodoc -p src/tsconfig.app.json -w -s"

the trace of the execution is : 
`Unhandled Rejection at: Promise {
  <rejected> SyntaxError: JSON5: invalid character '(' at 1:143
      at syntaxError (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1083:17)
      at invalidChar (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1028:12)
      at Object.value (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:287:15)
      at lex (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:78:42)
      at Object.parse (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:25:17)
      at loopModulesParser (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:5102:40)
      at RouterParserUtil.constructRoutesTree (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:5127:13)
      at AngularDependencies.getDependencies (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:7814:50)
      at CliApplication.Application.getDependenciesData (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:9277:40)
      at /Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:9087:23 {
    lineNumber: 1,
    columnNumber: 143
  }
} reason: SyntaxError: JSON5: invalid character '(' at 1:143
    at syntaxError (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1083:17)
    at invalidChar (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:1028:12)
    at Object.value (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:287:15)
    at lex (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:78:42)
    at Object.parse (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/node_modules/json5/lib/parse.js:25:17)
    at loopModulesParser (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:5102:40)
    at RouterParserUtil.constructRoutesTree (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:5127:13)
    at AngularDependencies.getDependencies (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:7814:50)
    at CliApplication.Application.getDependenciesData (/Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:9277:40)
    at /Volumes/DaStuff/MobileDevs/Le_Barometre/barometre_admin/node_modules/@compodoc/compodoc/dist/index-cli.js:9087:23 {
  lineNumber: 1,
  columnNumber: 143
}
[12:03:59] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! octeria.barometre@2.1.0 compodoc: `npx compodoc -p src/tsconfig.app.json -w -s`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the octeria.barometre@2.1.0 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/melgharbi/.npm/_logs/2019-08-02T11_03_59_162Z-debug.log
`

**Comment by vogloblinsky** [comment]
Ok now seems

**Comment by MelGharbi** [comment]
My routing file don't seam to have any error in it, i just double check everything. While starting the code generation, all the routes are shown ! 

Here my app routing file :

> import { Routes } from '@angular/router';
import { AdminLayoutComponent } from './shared/components/layouts/admin-layout/admin-layout.component';
import { AuthLayoutComponent } from './shared/components/layouts/auth-layout/auth-layout.component';
import { AuthGuard } from './shared/services/auth/auth.guard';
import { WebLayoutComponent } from './shared/components/layouts/web-layout/web-layout.component';

export const rootRouterConfig: Routes = [
  {
    path: '',
    redirectTo: 'home/two',
    pathMatch: 'full'
  },
  {
    path: '',
    component: WebLayoutComponent,
    children: [
      {
        path: 'home',
        loadChildren: () =>
          import('app/web/home/home.module').then(m => m.HomeModule),
        data: { title: 'Accueil' }
      }
    ]
  },
  {
    path: 'signin',
    redirectTo: 'sessions/signin',
    pathMatch: 'full'
  },
  {
    path: '',
    component: AuthLayoutComponent,
    children: [
      {
        path: 'sessions',
        loadChildren: () =>
          import('app/modules/sessions/sessions.module').then(
            m => m.SessionsModule
          ),
        data: { title: 'Session' }
      }
    ]
  },
  {
    path: '',
    component: AdminLayoutComponent,
    canActivate: [AuthGuard],
    children: [
      {
        path: 'profile',
        loadChildren: () =>
          import('app/modules/profile/profile.module').then(m => m.ProfileModule),
        data: { title: 'Profile', breadcrumb: 'PROFILE' }
      },
      {
        path: 'dashboard',
        loadChildren: () =>
          import('app/modules/dashboard/dashboard.module').then(
            m => m.DashboardModule
          ),
        data: {
          title: 'ADMIN.LAYOUT.DASHBOARD.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.DASHBOARD.0.BREADCRUMB'
        }
      },
      {
        path: 'users',
        loadChildren: () =>
          import('app/modules/users/users.module').then(m => m.UsersModule),
        data: {
          title: 'ADMIN.LAYOUT.USERS.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.USERS.0.BREADCRUMB'
        }
      },
      {
        path: 'entities',
        loadChildren: () =>
          import('app/modules/entities/entities.module').then(
            m => m.EntitiesModule
          ),
        data: {
          title: 'ADMIN.LAYOUT.ENTITIES.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.ENTITIES.0.BREADCRUMB'
        }
      },
      {
        path: 'commitments',
        loadChildren: () =>
          import('app/modules/commitments/commitments.module').then(
            m => m.CommitmentsModule
          ),
        data: {
          title: 'ADMIN.LAYOUT.COMMITMENTS.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.COMMITMENTS.0.BREADCRUMB'
        }
      },
      {
        path: 'indicators',
        loadChildren: () =>
          import('app/modules/indicators/indicators.module').then(
            m => m.IndicatorsModule
          ),
        data: {
          title: 'ADMIN.LAYOUT.ASSIGNED_INDICATORS.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.ASSIGNED_INDICATORS.0.BREADCRUMB'
        }
      },
      {
        path: 'results',
        loadChildren: () =>
          import('app/modules/results/results.module').then(m => m.ResultsModule),
        data: {
          title: 'ADMIN.LAYOUT.RESULTS.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.RESULTS.0.BREADCRUMB'
        }
      },
      {
        path: 'articles',
        loadChildren: () =>
          import('app/modules/articles/articles.module').then(
            m => m.ArticlesModule
          ),
        data: {
          title: 'ADMIN.LAYOUT.ARTICLES.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.ARTICLES.0.BREADCRUMB'
        }
      },
      {
        path: 'log',
        loadChildren: () =>
          import('app/modules/log/log.module').then(m => m.LogModule),
        data: {
          title: 'ADMIN.LAYOUT.LOG.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.LOG.0.BREADCRUMB'
        }
      },
      {
        path: 'help',
        loadChildren: () =>
          import('app/modules/help/help.module').then(m => m.HelpModule),
        data: {
          title: 'ADMIN.LAYOUT.HELP.0.TITLE',
          breadcrumb: 'ADMIN.LAYOUT.HELP.0.BREADCRUMB'
        }
      }
    ]
  },
  {
    path: '**',
    redirectTo: 'sessions/404'
  }
];

**Comment by vogloblinsky** [comment]
I think it is the new syntax `import('app/modules/help/help.module').then(m => m.HelpModule),`. A PR was been submitted for that but not currently released.
I hope i could release something next week.

**Comment by MelGharbi** [comment]
Oh okkey !! no worries, that'll give me enough time to finish all the comments on my app ;) 
Looking forward to use that amazing generator ;) 
Thank you so much

**Comment by MelGharbi** [comment]
Hi @vogloblinsky, how are you doing ? is there any update on this bug please ?

**Comment by sebastiandg7** [comment]
@vogloblinsky, any news about this?

**Comment by MelGharbi** [comment]
> @vogloblinsky, any news about this?

Update please !?

**Comment by JiaHongL** [comment]
@vogloblinsky
Update please ! ~~~~~

**Comment by vogloblinsky** [comment]
New routing syntax is available in 1.1.11. Is it better with this version ?

**Comment by MelGharbi** [comment]
Perfect ! It works like a charm. Thank you @vogloblinsky
