### ISSUE TITLE
[BUG] Unable to generate document with Angular 8

### ISSUE THREAD

**Issue by developerad2017** [compodoc/compodoc#832]
##### **Overview of the issue**

The present angular 8 structure has been do not have the tsconfig.app.json file in src foler. Now this file is at root level and Compodoc fail to generate report as it still searches for tsconfig.app.json file unde src folder.

**Comment by jelgersma** [comment]
Could just parse the -p arg.
`npx compodoc -p tsconfig.app.json`

P.s: Note that youll probably stumble onto [this](https://github.com/compodoc/compodoc/issues/831#issuecomment-521999407) problem after doing so

**Comment by developerad2017** [comment]
The above command helps to resolve the problem and it does generate the doc now. Thanks.
