### ISSUE TITLE
[BUG] Left-hand navigation is missing in Internet Explorer 11

### ISSUE THREAD

**Issue by sullyTheDev** [compodoc/compodoc#835]
##### **Overview of the issue**

When I am trying to view the documentation generated in IE 11, the left navigation menu is missing. But it's visible when run in a Chrome browser window. Please find the below script errors and screenshot captured from Internet Explorer's console.

![Capture](https://user-images.githubusercontent.com/31122729/63354050-bc364d80-c331-11e9-963a-0091fa36f6a7.PNG)

SCRIPT1002: Syntax error
File: menu-wc.js, Line: 4, Column: 40

The issue is replicable if you run the demo app https://compodoc.github.io/compodoc-demo-todomvc-angular/ in IE browser.

There did seem to be a similar issue that was marked CLOSED in Oct, 2018
Link here:    #673

**Comment by vogloblinsky** [comment]
Sorry, the source code of the Web component of the menu is in ES6 and is not right now transpiled to ES5 for supporting IE11 again. Will fix that soon.
