### ISSUE TITLE
[FEATURE/QUESTION] compdoc published on gitlab/github pages

### ISSUE THREAD

**Issue by djleonskennedy** [compodoc/compodoc#839]
##### **Overview of the feature**

Hello, is there any information how to use `compdoc` with `gitlab/github` pages ?

There is no documentation how to automatically build and deploy generated docs to pages, i think i'd be very halpfull

Than you

**Comment by vogloblinsky** [comment]
Yep, just added a page in the doc. Thanks for mentionning it.

https://compodoc.app/guides/hosting.html

**Comment by djleonskennedy** [comment]
@vogloblinsky thank you!
