### ISSUE TITLE
To include the index.html and other bootstraping and configuration files into the compodoc

### ISSUE THREAD

**Issue by eduardoalvarezguerra** [compodoc/compodoc#845]
Hi.
Into the compodoc generated report by compodoc there is not included the bootstrapping files, e.g. index.html or main.ts or the configuration files, e.g. the .json files.
In my view, this information is very important, regarding to understand better any Angular application.
Is there any way to include those files into the documentation?
Many thanks in advance. 
Regards.

**Comment by vogloblinsky** [comment]
These files would be included if they contains specific code handled by compodoc : class, function, variable, etc.
main.ts file most of the time doesn't contain these kind of informations
