### ISSUE TITLE
.tsx support for ts-node [BUG]

### ISSUE THREAD

**Issue by Freit02** [compodoc/compodoc#846]
##### **Overview of the issue**
Hello, 
Not really sure if this is an issue or a potential feature request as I am new to the Angular/Typescript world. I've been searching for a documentation tool for my Typescript projects and found Compodoc and am really excited about what it does and how nice it looks. I noticed when running the tool that it documented just my .ts files. I was searching some open issues and it seems this had potentially been fixed to also document .tsx files but it doesn't seem to be happening for me. It may be a configuration issue on my end but not sure. 
Any help is greatly appreciated!

##### **Operating System, Node.js, npm, compodoc version(s)**
Node.js: v10.16.1
Compodoc: v6.9.0
Compiler: Ts-node 

##### **Angular configuration, a `package.json` file in the root folder**
Package JSON: 

> {
>   "name": "item_master",
>   "homepage": "http://localhost:3000/Documentation",
>   "version": "1.2.0",
>   "private": true,
>   "proxy": "http://localhost:5000",
>   "dependencies": {
>     "@material-ui/core": "^4.4.1",
>     "@material-ui/icons": "^4.4.1",
>     "@trendmicro/react-sidenav": "^0.4.5",
>     "@types/jest": "^24.0.15",
>     "@types/ramda": "^0.26.21",
>     "@types/react-burger-menu": "^2.2.5",
>     "@types/react-dom": "^16.8.4",
>     "@types/react-select": "^3.0.4",
>     "@types/yup": "^0.26.20",
>     "axios": "^0.19.0",
>     "jsdoc": "^3.6.3",
>     "material-ui": "^0.20.2",
>     "moment": "^2.24.0",
>     "ramda": "^0.26.1",
>     "react": "^16.8.6",
>     "react-bootstrap": "^1.0.0-beta.9",
>     "react-burger-menu": "^2.6.10",
>     "react-dom": "^16.8.6",
>     "react-router-dom": "^5.0.1",
>     "react-scripts": "3.0.1",
>     "react-select": "^3.0.4",
>     "react-sidenav": "^4.0.3",
>     "typescript": "^3.2.1",
>     "yup": "^0.27.0"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test",
>     "eject": "react-scripts eject",
>     "doc": "typedoc --options ./typedoc.json"
>   },
>   "eslintConfig": {
>     "extends": "react-app"
>   },
>   "browserslist": {
>     "production": [
>       ">0.2%",
>       "not dead",
>       "not op_mini all"
>     ],
>     "development": [
>       "last 1 chrome version",
>       "last 1 firefox version",
>       "last 1 safari version"
>     ]
>   },
>   "devDependencies": {
>     "@types/jest": "^24.0.15",
>     "@types/material-ui": "^0.21.7",
>     "@types/node": "^12.7.5",
>     "@types/react": "^16.8.23",
>     "@types/react-burger-menu": "^2.2.5",
>     "@types/react-dom": "^16.8.4",
>     "@types/react-router-dom": "^4.3.4",
>     "docs-ts": "^0.2.1"
>   },
>   "description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
>   "main": "index.js",
>   "author": "",
>   "license": "ISC"
> }

TSConfig: 

> {
>   "compilerOptions": {
>     "target": "es6",
>     "lib": ["dom", "dom.iterable", "esnext", "es6"],
>     "moduleResolution": "node",
>     "allowJs": true,
>     "noImplicitAny": true,
>     "noImplicitThis": true,
>     "strictNullChecks": true,
>     "skipLibCheck": true,
>     "esModuleInterop": true,
>     "allowSyntheticDefaultImports": true,
>     "strict": true,
>     "forceConsistentCasingInFileNames": true,
>     "module": "esnext",
>     "resolveJsonModule": true,
>     "isolatedModules": true,
>     "noEmit": true,
>     "jsx": "preserve"
>   },
>   "include": ["src"],
>   "exclude": ["**node_modules/**"]
> }

##### **Compodoc installed globally or locally ?**
Compodoc installed locally

##### **Motivation for or Use Case**
Most of my files are a tsx rather than ts, so the documentation currently is about 20% of my project

##### **Related issues**
[FEATURE] - StencilJS projects support #640 dealt with a Stencil compiler but roughly the same issue

##### **Suggest a Fix**
Apologies if this is not fixable or a bad question - I'm a fairly inexperienced Dev and don't totally grasp all the concepts this interacts with
Thanks again for any help you provide!

**Comment by vogloblinsky** [comment]
can you reproduce the bug with this sample ? https://github.com/compodoc/compodoc-demo-stencil
