### ISSUE TITLE
[FEATURE] additional tab per folder / module / component

### ISSUE THREAD

**Issue by rickvandermey** [compodoc/compodoc#849]
We would love to have a feature like additional-doc, but for each file, and that it would add a tab for each additional doc created. is this even possible?

for example: https://rickvandermey.github.io/angular-starterkit/documentation/components/ErrorPageComponent.html create additional doc at this point with extra tabs

**Comment by JanMalch** [comment]
I think you are looking for this: https://compodoc.app/guides/tips-and-tricks.html#documentation-of-each-components

**Comment by rickvandermey** [comment]
this would be perfect for MD files indeed. but with the additional-doc feature, we could possibly extend each component with a HTML file, which renders an iframe (blegh, i know) of storybook for example, or stackblitz

**Comment by JanMalch** [comment]
I see what you mean. For the storybook use case there is https://compodoc.app/guides/live-example-tab.html
