### ISSUE TITLE
[BUG] Generated documentation is wrong when different Angular modules have same variable name for component list.

### ISSUE THREAD

**Issue by aravindh-nagarajan** [compodoc/compodoc#850]
_Overview of the issue_
Generated documentation is wrong when different modules have same variable name for component list.

Compodoc version: 1.1.11
NPM version: 6.4.1
Angular version: 8.2.0

Issue description
        We have two differnt modules (Say Kit and KitSecondary), these two are imported in app.module.ts.

```
 import { AppComponent } from './app.component';
 import { KitModule } from './modules/kit/index';
 import { KitSecondaryModule } from './modules/kit-secondary/index';

 @NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    KitModule,
    KitSecondaryModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

Each Module(Kit and KitSecondary) has one component. 
KitModule.ts - has `successAlertComponent`. This is in an Array called `components`

```
const components = [
  SuccessAlertComponent,
];

@NgModule({
    declarations: [
      ...components,
    ],
    entryComponents: [
      ...components,
    ],
    exports: [
      ...components,
    ],
    imports: [
        CommonModule,
    ],
})
export class KitModule { }
```

now, The second module - KitSecondary - has another component, which also is in an array with the same variable name

```
const components = [
  WarningAlertComponent,
];

@NgModule({
    declarations: [
      ...components,
    ],
    entryComponents: [
      ...components,
    ],
    exports: [
      ...components,
    ],
    imports: [
        CommonModule,
    ],
})
export class KitSecondaryModule { }
```

Now the expected document should have - 

- Two modules (Kit and KitSecondary).
- Kit should have successAlertComponent
- KitSecondary should have warningAlertComponent

Instead the generated component looks like this:
![two-modules](https://user-images.githubusercontent.com/49676938/66996733-dd77a800-f0ee-11e9-8c9f-16b44629759a.png)
![kit-1](https://user-images.githubusercontent.com/49676938/66996738-e0729880-f0ee-11e9-868a-6a06333b0208.png)
![kit-2](https://user-images.githubusercontent.com/49676938/66996747-e4061f80-f0ee-11e9-8f22-e9d992756158.png)

You can see that, In generated document, both modules has the same component information. and notice the, `entryComponents` section in the module screenshot, that also wrong.

**Comment by vogloblinsky** [comment]
Can you take some time to make a repro repository, easiest for me to debug and fix it.
Thanks

**Comment by aravindh-nagarajan** [comment]
Repro repo: https://github.com/aravindh-nagarajan/compodoc-issue-repo

Please let me know if you need any additional information.

Thank you.
