### ISSUE TITLE
[FEATURE] disable styles tab

### ISSUE THREAD

**Issue by pburgmer** [compodoc/compodoc#855]
##### **Overview of the feature**

Template, DomTree and SourceCode tabs can already be disabled via an option. Styles tab can't, there is no option. Could you please add an option to disable styles tab as well.

##### **Motivation for or Use Case**

I want to keep the documentation as lean as possible. Therefore I want to disable a lot of compdoc's features. Mainly the already mentioned tabs.

**Comment by RobinNL** [comment]
The style tab goes away when you configure a "navTabConfig" array inside the compodocrc or as a CLI option. This seems to be a bug though because it's only because style is not available as an ID inside this config.

Example:
` "navTabConfig": [
    {
      "id": "example",
      "label": "Overview"
    },
    {
      "id": "info",
      "label": "Code"
    },
    {
      "id": "readme",
      "label": "Design and usage"
    },
    {
      "id": "templateData",
      "label": "HTML"
    },
    {
      "id": "source",
      "label": "Typescript"
    },
    {
      "id": "tree",
      "label": "DOM Tree"
    }
  ],`

**Comment by pburgmer** [comment]
@RobinNL Thanks. Works for me.
