### ISSUE TITLE
[FEATURE] - add override flag for default location of  README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.md files

### ISSUE THREAD

**Issue by greenstevester** [compodoc/compodoc#857]
##### **Overview of the feature**

add a flag to specify/override the default location of README.md, CHANGELOG.md, CONTRIBUTING.md, LICENSE.md, TODO.md files?

##### **Motivation for or Use Case**

I would like to override the default location and have them reside in a ./docs/folder instead of the project root

##### **Related issues**

None - it's a new feature

**Comment by dopry** [comment]
I'd like to add a second use case. We're developing an angular component library.  We have structure as follows /projects/lib, projects/docs, /projects/showcase.  The /README.md is written for the developers of the component library so we can easily onboard developers to working on the component library and it is the first documentation they see when visiting the repo. /projects/lib/README.md is written for the consumers of our component library and has quick starts instructions and links to references. It is published with our packages.  Compodoc also targets our component library consumers. We would like it to include the /projects/lib/README.md. It is currently pulling in the README.md written for our component library developers. Changing the way the repo is organized would create and awkward developer experience for our internal developers, and as it stands it creates and awkward developer experience for our consumers. Being able to specify an Alternate README.md would allow us to deliver a better DX to both of our developer audiences.

**Comment by greenstevester** [comment]
Verbatim to @dopry 's usage of compodoc, we **also** are developing an angular component library which has two audiences, 1) internal component library developers and 2) consumers of the library. 
If compodoc was extended to cover this use-case, I am sure it would gain a substantial user-base as I already investigated using dgeni, storybook, gitbook, angulardoc.io,readTheDocs and all of them fell short of what we needed.

**Comment by dopry** [comment]
@vogloblinsky hey what's will stalebot shooting down feature requests?
