### ISSUE TITLE
[FEATURE] : support exported type

### ISSUE THREAD

**Issue by shlomiassaf** [compodoc/compodoc#86]
Great work!!!

I did not see typescript `type` keyword reflected in the output.

```ts
export interface SomeOne {
  age: number;
}
export type Something = SomeOne | string
```

`SomeOne` appears of the docs, `Something` does not.

**Comment by shlomiassaf** [comment]
export const xyz = 15;
export class Something {
}
```

only the class exported.

**Comment by vogloblinsky** [comment]
Related : https://github.com/compodoc/compodoc/issues/55
@shlomiassaf It is not supported right now. I will start a new category "Miscellaneous" where this little exports of const, let, type etc could be referenced.

**Comment by dharsanav** [comment]
It would be better to provide support for files that contain only functions(without any class) like 
```javascript
export function testA(){
}
export function testB(){
}
```

**Comment by shlomiassaf** [comment]
@vogloblinsky Thanks!

Since you track it there I will close this I guess :)
