### ISSUE TITLE
[FEATURE] Support --watch with --exportFormat json

### ISSUE THREAD

**Issue by kroeder** [compodoc/compodoc#862]
##### **Overview of the feature**

I figured out that `-w` only works with `-s` but not with `-e json`.
The goal of this feature request is that `compodoc -w -e json` is working and re-generates the `documentation.json` after a file has changed.

##### **Motivation for or Use Case**

It allows third party tools to use the generated `documentation.json` during dev time.
I'd be happy to contribute if that helps to add this feature! 🙂

**Comment by kroeder** [comment]
Is this still in progress? 🙂

**Comment by chin2km** [comment]
Any update here?

**Comment by JBusch** [comment]
Would be really nice if this would be fixed. It would be needed for proper storybook integration see:
https://github.com/storybookjs/storybook/issues/8672
