### ISSUE TITLE
[BUG] Files are not captured when baseUrl = "src" in tsconfig.json

### ISSUE THREAD

**Issue by Diegodlt** [compodoc/compodoc#864]
##### **Overview of the issue**

Compodoc does not generate documentation for any files located in the src folder when the baseUrl = "src" in tsconfig.json. The baseUrl was changed to this so the app can use absolute paths, such as "@app/core/*."

##### **Operating System, Node.js, npm, compodoc version(s)**

Angular version: 8.2
Node version: 10.3.1

##### **Angular configuration, a `package.json` file in the root folder**

{
  "name": "admin-dashboard",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compodoc": "npx compodoc -p tsconfig.app.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.3",
    "@angular/common": "~8.2.3",
    "@angular/compiler": "~8.2.3",
    "@angular/core": "~8.2.3",
    "@angular/forms": "~8.2.3",
    "@angular/platform-browser": "~8.2.3",
    "@angular/platform-browser-dynamic": "~8.2.3",
    "@angular/router": "~8.2.3",
    "bootstrap": "4.1.1",
    "ngx-bootstrap": "^5.1.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.0",
    "@angular/cli": "~8.3.0",
    "@angular/compiler-cli": "~8.2.3",
    "@angular/language-service": "~8.2.3",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

##### **Compodoc installed globally or locally ?**

It is installed globally.

**Comment by vogloblinsky** [comment]
Hi @Diegodlt 
I have some difficulties to reproduce it. Can you supply a sample project generated with Angular CLI ?
Thanks

**Comment by Diegodlt** [comment]
Hello @vogloblinsky,

I made a sample project that is producing the same results. Here's the link, https://github.com/Diegodlt/compodoc-test. Thank you.

**Comment by bdphil86** [comment]
This issue still exists.
