### ISSUE TITLE
[BUG] Extended interfaces not showing properties of parent

### ISSUE THREAD

**Issue by romaric-juniet** [compodoc/compodoc#865]
##### **Overview of the issue**

When an interface A inherits from an interface B, only the properties of A are shown. There isn't a sign that there is an inheritance

![image](https://user-images.githubusercontent.com/11988817/68182759-4dce6680-ffd5-11e9-8b59-0fb823eca53b.png)
![image](https://user-images.githubusercontent.com/11988817/68182767-5757ce80-ffd5-11e9-8841-1f72c3b31671.png)
https://v2-docs-js-lib.request.network/interfaces/IRequestData.html#info

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10, node v10.15.3, npm 6.4.1, compodoc 1.1.10

##### **Angular configuration, a `package.json` file in the root folder**

No angular, just a regular typescript package.
Repro [here](https://v2-docs-js-lib.request.network/interfaces/IRequestData.html#info)
package.json [here](https://github.com/RequestNetwork/requestNetwork/blob/development/packages/request-client.js/package.json)

##### **Compodoc installed globally or locally ?**

Locally

##### **Motivation for or Use Case**

Because of this bug, the property list of an interface is incorrect. It's missing inherited properties

##### **Related issues**

https://github.com/compodoc/compodoc/issues/281

##### **Suggest a Fix**

Thanks!

**Comment by vogloblinsky** [comment]
Ok it is a little bit tricky for your context. The IRequest is inside another package. Need a way to handle that...

**Comment by romaric-juniet** [comment]
I see, it is complex indeed. Thanks for the quick answer
