### ISSUE TITLE
[FEATURE] Link to file in project's repository

### ISSUE THREAD

**Issue by JanMalch** [compodoc/compodoc#873]
##### **Overview of the feature**

It would be nice to directly link to the file in a repository. Currently the component template only prints the file path. With a new field in the compodoc config (or reading it from the `package.json`) you could define a base path to a repository (e.g. `https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/master/`).

So in the end instead of
```html
<h3>File</h3>
<p class="comment">
    <code>src/app/shared/components/empty-component.ts</code>
</p>
```

you have

```html
<h3>File</h3>
<p class="comment">
  <a href="https://github.com/compodoc/compodoc-demo-todomvc-angular/blob/master/src/app/shared/components/empty-component.ts">
    <code>src/app/shared/components/empty-component.ts</code>
  </a>
</p>
```

##### **Motivation for or Use Case**

It's quite useful to be able to go directly to the source file, to quickly review code.
Also you don't copy the whole code for the documentation, which might bloat the documentation for large projects.

---

The biggest challenge is the base path. The ideal way would be to refer to the exact commit hash in the URL. But I think a link to the master would already be quite useful.

If you like the idea I'm willing to work on it and submit a PR.

**Comment by vogloblinsky** [comment]
yes it could be very cool !
we can discuss that later

**Comment by JanMalch** [comment]
Unfortunately I can't confirm that this is working, but I gave it a shot here: https://github.com/JanMalch/compodoc/commit/9b809994b6a0a4583e1cd9ff2967f2571d5bdd8a
You can use a `{{commit}}` placeholder in the `repoSrcUrl` to insert the current git HEAD.

I would like to try it but when following the "Development process" steps in `CONTRIBUTING` I only get a simple server with some markdown files but no documentation is generated?
