### ISSUE TITLE
[BUG] Spread operator is not supported in routes definition

### ISSUE THREAD

**Issue by sfratini** [compodoc/compodoc#883]
##### **Overview of the issue**

When parsing the project, if the route module file has any spread operator the parsing fails with the exception. 

Same issue as this, but I confirmed that refactoring my code works so the issue is just the spread operator: https://github.com/compodoc/compodoc/issues/608 

`[10:00:55] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Expected to find an initiailizer of kind 'ArrayLiteralExpression'.`

##### **Operating System, Node.js, npm, compodoc version(s)**

Node v8.13.0
NPM 6.4.1
Compodoc 1.1.11

##### **Compodoc installed globally or locally ?**

Locally

Code that breaks:
```
const adapted = OldRoutes.map(path => ({
  path: path.substr(1),
  component: OldRoutesComponent
}))

const routes: Routes = [
{
  path: 'test',
  component: GreetingComponent
},
...adapted
];

```
Code That works:
```
const adapted = OldRoutes.map(path => ({
  path: path.substr(1),
  component: OldRoutesComponent
}))

adapted.push({
  path: 'test',
  component: GreetingComponent
})

const routes: Routes = adapted;
```

##### **Motivation for or Use Case**

I feel spread operators are a very often used shortcut and would be great to support them. 

##### **Reproduce the error**

Just use the spread operator in the routes array. 

##### **Related issues**

https://github.com/compodoc/compodoc/issues/608

**Comment by DaSchTour** [comment]
🤨
