### ISSUE TITLE
Hi, Can we use this with Angular Js projects? If yes please share the steps to do. 

### ISSUE THREAD

**Issue by arunreghu** [compodoc/compodoc#888]
Hi,
Can we use this with Angular Js projects? If yes please share the steps to do.

**Comment by vogloblinsky** [comment]
Sorry but this tool is not compatible with AngularJS projects.

**Comment by arunreghu** [comment]
@vogloblinsky Do you know any similar app for doing the same in angular Js. I have an angularJs project and its going to finish soon so I have to give a detailed documentation for my client. Can you help me to find a solution?
