### ISSUE TITLE
not working under angular 8

### ISSUE THREAD

**Issue by ihrwebentwickler** [compodoc/compodoc#891]
no documentation coverage and other missing sites under angular 8:

node version v10.16.2

console.log says:
Version mismatch when loading serialised index. Current version of lunr '2.3.6' does not match serialized index '2.3.8'

@angular/animations : ^8.2.5
@angular/cdk : ^8.1.4
@angular/common : ^8.2.5
@angular/compiler : ^8.2.5
@angular/core : ^8.2.5
@angular/forms : ^8.2.5
@angular/platform-browser : ^8.2.5
@angular/platform-browser-dynamic : ^8.2.5
@angular/router : ^8.2.5
@asymmetrik/ngx-leaflet : ^6.0.1
@ngx-translate/core : ^11.0.1
@ngx-translate/http-loader : ^4.0.0
@types/leaflet : ^1.5.4
angular-font-awesome : ^3.1.2
classlist.js : ^1.1.20150312
font-awesome : ^4.7.0
highcharts : ^7.2.0
highcharts-angular : ^2.4.0
leaflet : ^1.5.1
moment : ^2.24.0
ng-click-outside : ^5.1.1
ng-inline-svg : ^9.0.1
npn-slider : ^1.3.2
primeicons : ^2.0.0
primeng : ^8.0.3
rxjs : ^6.5.3
tslib : ^1.10.0
zone.js : ~0.9.1

**Comment by amirzenoozi** [comment]
I have same issue but it works on angular 7, what should we do ?

**Comment by davide1995** [comment]
Same issue here

**Comment by amirzenoozi** [comment]
I Found a Solution For This Bug
If we use this below script it will work (for me 😁):

```json
"scripts": {
  "compodoc": "compodoc --tsconfig tsconfig.json"
}
```

I hope it helps you

**Comment by ZTKlein** [comment]
@amirzenoozi is right. I haven't used compodoc on older projects, so I don't know if this is a bug or not, but compodoc's usage page tells you to use -p (or --tsconfig) flags to specify the tsconfig file.

**Comment by ihrwebentwickler** [comment]
thanks @amirzenoozi and @ZTKlein, it works with:
"compodoc --tsconfig tsconfig.json -s"

then this is no bug, i close the issue. ##npx compodoc -p tsconfig.app.json -s## is not working, but this is not the compodoc's usage-documentation.
