### ISSUE TITLE
Unhandled Rejection at Promise

### ISSUE THREAD

**Issue by clone47** [compodoc/compodoc#897]
Hi. While generating a doc, i got an error. On that time, the script is accessing app-routing.module.ts file.

`[18:06:24] parsing        : ../src/app/app-routing.module.ts
[18:06:24] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
  <rejected> Error: Could not find the node's symbol.`

Any luck?

**Comment by nnit-TroelsJensen** [comment]
Is it related to this bug - https://github.com/compodoc/compodoc/issues/784
