### ISSUE TITLE
[BUG] JSDoc-style default value not showing for properties

### ISSUE THREAD

**Issue by jlutz777** [compodoc/compodoc#908]
##### The default value in JSDoc-style comments isn't showing in the docs.

We use the @default jsDoc comment in our code, and they don't show up in the documentation generated from CompoDoc.

##### **Operating System, Node.js, npm, compodoc version(s)**

compodoc 1.1.9

##### **Compodoc installed globally or locally ?**

Locally

##### **If possible sourcecode of the file where it breaks**

/**
   * Whether or not the component is loading
   *
   * @default false
   */
  @Input()
  get loading() {
    return this._loading;
  }
  set loading(value) {
    this._loading = coerceBooleanProperty(value);
  }
  private _loading = false;

##### **If possible your terminal logs before the error**

N/A

##### **Motivation for or Use Case**

Our docs don't show the default value for properties.

##### **Reproduce the error**

I don't think it has anything to do with the problem, but we are generating json from compodoc. It results in:
{
                    "name": "loading",
                    "description": "\<p\>Whether or not the component is loading\</p\>\n",
                    "line": 88
                },

For what it's worth, I tried for non-properties and saw the same result.

##### **Related issues**

Appears to be a feature in this issue:
https://github.com/compodoc/compodoc/issues/453

**Comment by Spielboerg** [comment]
I have the same problem and noticed that in addition to that the types in the setter are not recognized. If I take the example from above and add types for the setter:
```ts
/**
 * Whether or not the component is loading
 * @default false
 */
@Input()
set loading(isLoading: boolean) {
  ...
}
...
```

The generated json looks like this:
```json
...
{
  "name": "loading",
  "description": "<p>Whether or not the component is loading</p>\n",
  "line": 88,
  "type": ""
},
...
```

I have also tried the following tags, unfortunately without success:
```ts
@type boolean

@param {boolean} loading
```

@vogloblinsky If you think that this is off-topic, I can create a new issue.

**Comment by jlutz777** [comment]
Please don't close this if you think it is possible.
