### ISSUE TITLE
[BUG] JSON output missing "rawdescription" on several types

### ISSUE THREAD

**Issue by zbream** [compodoc/compodoc#909]
##### **Overview of the issue**

When outputting to JSON, I noticed that the following types are missing a `rawdescription` field:

* pipes
* interfaces
* injectables
* directives
* modules (not important for my usecase)
* miscellaneous (not important for my usecase)

##### **Motivation for or Use Case**

I'm working on a custom integration with [StorybookJS](https://github.com/storybookjs/storybook). For displaying documentation, the library will parse raw markdown from the JSDoc. I need access to the raw markdown for the types listed above, _not_ the HTML-safe description field, to avoid encoding issues.

##### **Reproduce the error**

Create Compodoc JSON output for the types listed above.

##### **Related issues**

#875 

##### **Suggest a Fix**

Add the properties to the necessary fields in `angular-dependencies.ts`.

**Comment by willemsendennis** [comment]
With the same (storybook) motivation I'd love to see this fixed. What is the plan with this? Are you open to other contributors?

**Comment by jlutz777** [comment]
Could we get this reopened? I think my PR would fix it.
