### ISSUE TITLE
[FEATURE] - Documentation of Directives

### ISSUE THREAD

**Issue by lexon0011** [compodoc/compodoc#91]
We use Directives in our Angular 2 application, but in the documentation is only the Filename and the full source code - but no documentation of Methods, Metadata, ...

![image](https://cloud.githubusercontent.com/assets/16290662/22243088/2070bc12-e226-11e6-9b8c-42b7429c9b23.png)

**Comment by vogloblinsky** [comment]
Did you have a example of code ?

**Comment by lexon0011** [comment]
Here is one sample file:

[popoverValidation.directive.zip](https://github.com/compodoc/compodoc/files/727425/popoverValidation.directive.zip)
