### ISSUE TITLE
[DISCUSSION] Can compodoc be used for backend typescript?

### ISSUE THREAD

**Issue by egdelgadillo** [compodoc/compodoc#913]
##### Can compodoc be used for backend typescript?

I'm about to start a new backend project, and at the same time I saw the frontend, using Angular, is going to use compodoc for it's documentation generation. I didn't know it, but I fell in love instantly.

What about using compodoc for backend projects? All information I've found is related to Angular, and even it's name suggests that. I did not find any issue related to this either. I haven't tried it myself for backend document generation, but I wanted to ask you guys first if it's a viable solution, instead of using the already known typedoc and tsdoc

What do you think? Have you used it before? Is there any special steps I need to follow to achieve this?

Thanks!

**Comment by josecolella** [comment]
@egdelgadillo Compodoc is used for projects like NestJS which is a backend typecript based web framework
