### ISSUE TITLE
[BUG] Code snippets are not rendered properly

### ISSUE THREAD

**Issue by ShadowManu** [compodoc/compodoc#915]
##### Using code snippets in TSDoc tags does not render properly

The error is visible, for example, in Compodocs' demo site: https://compodoc.github.io/compodoc-demo-todomvc-angular/interfaces/ClockInterface.html

The `ClockInterface` description uses a code snippet and the error is visible.

**Comment by dhruvaldarji** [comment]
This issue also occurs for code snippets provided under the `@example` tag. 

![compodoc-jsdoc-examples](https://user-images.githubusercontent.com/3433281/77481867-f6515b80-6dfa-11ea-8166-174d09ae07ac.png)
<img width="726" alt="compodoc-output" src="https://user-images.githubusercontent.com/3433281/77481868-f6515b80-6dfa-11ea-9ba1-d438244c76ce.png">

Would very much appreciate a resolution for this issue.

**Comment by dhruvaldarji** [comment]
@ShadowManu , I've gotten around this issue based on a suggestion from #922 
https://github.com/compodoc/compodoc/issues/922#issuecomment-600906601

----- 
![compodoc-jsdoc-get_user_by_id](https://user-images.githubusercontent.com/3433281/77778553-8e338d00-7027-11ea-8c03-824bde756f4c.png)
<img width="1439" alt="compodoc-snippet-get_user_by_id" src="https://user-images.githubusercontent.com/3433281/77778555-8e338d00-7027-11ea-8cd5-a7d9f053d085.png">
