### ISSUE TITLE
[FEATURE] - Support for {@link} from JSDoc

### ISSUE THREAD

**Issue by lexon0011** [compodoc/compodoc#92]
We use the `{@link} `tag in our comments, like

```
/**
 * See {@link MyClass} and [MyClass's foo property]{@link MyClass#foo}.
 * Also, check out {@link http://www.google.com|Google} and
 * {@link https://github.com GitHub}.
 */
```

see [JSDoc](http://usejsdoc.org/tags-inline-link.html)

Is it possible to include this link-tags to the generated documentation?

Thanks!

**Comment by pburrows** [comment]
@link does not seem to be getting parsed for properties. For the following comments:


```
/**
 * Event object emitted by {@link AutoFormMasterComponent}
 */
export interface IAutoFormEvent {

	/**
	 * The original {@link FieldDefinition} object that participated in this event. Can be used
	 * to determine which field was modified
	 */
	fieldDefinition: FieldDefinition;

	/**
	 * The original {@link Event}
	 */
	event: Event;
}
```

The {@link AutoFormMasterComponent} is getting parsed correctly, but the two @link tags in the property descriptions are not.

**Comment by tommueller** [comment]
This is in the docs now, but it does not work for me. It breaks the parsing of the comment. If I paste the exact example from the docs (both for internal and external links): 
```
    /**
     * @param {string} target  The target to process see {@link Todo}
     *
     * @example
     * This is a good example
     * processTarget('yo')
     *
     * @returns      The processed target number
     */
```
it generates this output:

>  Parameters :
> 
>  target
> 
>   The target to process see {
> 
>  Example :
> 
> This is a good example processTarget('yo')
> Returns : Observable<>
> 
> The processed target number

**Comment by vogloblinsky** [comment]
@tommueller Related to https://github.com/compodoc/compodoc/issues/237
Completed, released soon in 1.0.0-beta.14

**Comment by tommueller** [comment]
Great, thanks!

**Comment by 007300** [comment]
in 1.0.0-beta.14:
{@link xxx} is getting parsed for properties still not correctly:
only "{" will be represented

**Comment by vogloblinsky** [comment]
@007300 
Any example ?

**Comment by 007300** [comment]
/**
	 * Creates a typed instance of the ApiService with the endpoint selected from the {@link ApiMap} with the endpointKey
	 * @param {string} endpointKey The key to pick the enpoint from the {@link ApiMap}
	 */

then it generates:


Name | Type | Description
-- | -- | --
endpointKey | string | The key to pick the enpoint from the {

The second {@link} is broken

**Comment by vogloblinsky** [comment]
@007300 
Seems related to https://github.com/Microsoft/TypeScript/issues/16498
I open another specific issue for that : https://github.com/compodoc/compodoc/issues/294
