### ISSUE TITLE
[QUESTION] When will a new release be made --> 1.1.12

### ISSUE THREAD

**Issue by loxy** [compodoc/compodoc#920]
It would be nice if there is a new release, especially with: https://github.com/compodoc/compodoc/commit/baf122cd9b046fc3ee45919131661bda3204f40e included and regarding: https://github.com/compodoc/compodoc/issues/860
Or is this project dead?

**Comment by vogloblinsky** [comment]
Hi @loxy 
this project is not dead, i just try to find some time for restarting a clean codebase while fixing bugs and adding new features...

**Comment by loxy** [comment]
Sounds great! But can you somehow prepare a release of the current code base?

**Comment by jlessard93** [comment]
will 1.1.12 hopefully support Angular 9? I am currently working on an Angular 9 project and tried implementing Compodoc with varying degrees of success. I decided after some tinkering around to wait until the next release.

**Comment by loxy** [comment]
?

**Comment by napstr** [comment]
It seems that there are a lot of improvements and features targetted and completed at the 1.1.12, 1.2, 1.3, 1.4 milestones. Are they in a state to be released? Or is that just an illusion, due to the mass closings of the stale bot? What can the community to do support these releases going out?

**Comment by loxy** [comment]
Ping

**Comment by loxy** [comment]
Pong

**Comment by klemenoslaj** [comment]
As it appears like this project is being unmaintained right now? 🤔 
 @vogloblinsky can the community help out in some way?

**Comment by vogloblinsky** [comment]
> As it appears like the project really is being unmaintained right now? 
> @vogloblinsky can the community help out in some way?

@klemenoslaj 
I will have some time this weekend to restart this project : codebase rewrite, Angular 10 support etc

**Comment by klemenoslaj** [comment]
@vogloblinsky that sounds great. Let me know if I can help in any way.

**Comment by ReyOrtiz** [comment]
> > As it appears like the project really is being unmaintained right now?
> > @vogloblinsky can the community help out in some way?
> 
> @klemenoslaj
> I will have some time this weekend to restart this project : codebase rewrite, Angular 10 support etc

Hello @vogloblinsky , don't mean to rush or anything. Have you had chance to work on next release? Thanks

**Comment by literalpie** [comment]
We are also hoping for a release. It's a shame that improvements have been merged, but no one can benefit from them because there hasn't been a release.
