### ISSUE TITLE
[BUG] compodoc doesn't generate example section

### ISSUE THREAD

**Issue by SanaeHanaoui** [compodoc/compodoc#922]
##### **Overview of the issue**
I have followed the instructions in the documentation and tried as it was described yet it doesn't generate the example section. I tried everything everyone mentioned yet nothing is working for me 

##### **Operating System, Node.js, npm, compodoc version(s)**
windows 10
node v12.14.1
npm 6.13.4
compodoc 1.1.11

##### **Compodoc installed globally or locally ?**

it is installed golbally

**Comment by ozee** [comment]
@SanaeHanaoui I'm not sure if this helps or not, but when documenting typescript, I had to do the following (I had to add spaces between the tick marks for the example):
```
/**
 *
`` `ts
// some code here
`` `
 */
```

**Comment by dhruvaldarji** [comment]
Examples sections are generated when the `@example` decorator is applied in the jsdoc.
