### ISSUE TITLE
[BUG] 'wmic' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by wlucha** [compodoc/compodoc#925]
##### **Overview of the issue**

starting compodoc 1.1.11 leads to an error

##### **Operating System, Node.js, npm, compodoc version(s)**

Windows 10
Compodoc: 1.1.11
TypeScript version used by Compodoc : 2.9.1
TypeScript version of current project : 3.7.5
Node.js version : v10.17.0

##### **Angular configuration, a `package.json` file in the root folder**

    "@angular/animations": "9.0.5",
    "@angular/cdk": "9.1.0",
    "@angular/common": "9.0.5",
    "@angular/compiler": "9.0.5",
    "@angular/core": "9.0.5",
    "@angular/forms": "9.0.5",
  

##### **Compodoc installed globally or locally ?**

locally

##### **If possible your terminal logs before the error**

\node_modules\execa\index.js:347
                throw err;
                ^

Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.

##### **Reproduce the error**

npx compodoc -p src/tsconfig.app.json

**Comment by mgalante** [comment]
To solve this issue in my computer i added  C:\Windows\System32\wbem to the PATH
