### ISSUE TITLE
[FEATURE] Support Typedoc directory structure

### ISSUE THREAD

**Issue by zpydee** [compodoc/compodoc#93]
Hi Vincent,

I am finding the need to use both compodoc and typedoc for various features, and can't do becuase the resultant generated directory structure is different.

Because of the large typedoc user base, it may be a good strategy for you to support their direcory structure, specifically:
- all classes go in the `/classes` dir
- all interfaces go in the '/interfaces` dir
- user assets go in the `/media` dir

Your thoughts?

**Comment by vogloblinsky** [comment]
> all classes/interfaces go in the /classes /interfaces dir

Compodoc puts them in that directory.

> I am finding the need to use both compodoc and typedoc for various features

What are the missing features ?

**Comment by vogloblinsky** [comment]
@zpydee any news ?

**Comment by vogloblinsky** [comment]
Closing it, if any news, feel free to discuss here @zpydee
