### ISSUE TITLE
[BUG] Inputs declared in the Component/Directive decorator are ignored

### ISSUE THREAD

**Issue by twittwer** [compodoc/compodoc#941]
##### **Overview of the issue**

When inputs are declared with the inputs array in the Component/Directive decorator, they are not show in the documentation. [Angular docs about inputs array](https://angular.io/api/core/Directive#inputs)

##### **Version(s)**

Compodoc: 1.1.11
Angular: 9.1.0

##### **Use Case**

To use mixins, like done in Angular Material, you have to declare mixed in inputs via the inputs array in the Component decorator.
These inputs should be documented as well, like the inputs declared via Input decorator. Otherwise, it would not be possible to see, that a component can be e.g. disabled after the mixin was applied.

Use Cases: Standalone Compodoc & Compodoc with Storybook

Sample from Angular Material:
* [Mixin definition](https://github.com/angular/components/blob/master/src/material/core/common-behaviors/color.ts#L29)
* [Mixin usage for a button](https://github.com/angular/components/blob/master/src/material/button/button.ts#L77)

**Comment by pfeileon** [comment]
My team has the exact same issue.
Btw, there was a related feature request which was closed due to inactivity: https://github.com/compodoc/compodoc/issues/881

**Comment by twittwer** [comment]
@vogloblinsky can you say something about the issue?

**Comment by twittwer** [comment]
@vogloblinsky can you say something about the issue?

**Comment by twittwer** [comment]
@vogloblinsky can you say something about the issue?
