### ISSUE TITLE
[BUG] Modules and components no detected in Angular 9

### ISSUE THREAD

**Issue by dloprodu** [compodoc/compodoc#951]
##### **Overview of the issue**

The documentation isn't been generated for modules, components, in Angular 9.

##### **Operating System, Node.js, npm, compodoc version(s)**

Node: 12.16.1
Angular: 9.1.2
Compodoc: 1.1.11

##### **Angular configuration, a `package.json` file in the root folder**

script: compodoc -p src/tsconfig.app.json

##### **Compodoc installed globally or locally ?**

Locally

**Comment by chekit** [comment]
There is some kind of a small workaround here: [compodoc/issues/927](https://github.com/compodoc/compodoc/issues/927#issuecomment-603690089)

**Comment by gultyaev** [comment]
@chekit In my case I have a monorepo Angular workspace. I want my docs to be split per project. This usage doesn't allow to do that
