### ISSUE TITLE
[BUG] Live-server warning

### ISSUE THREAD

**Issue by hmendezm** [compodoc/compodoc#964]
Hi guys, 

I just want to report the following warnings from yarn

```
 @compodoc/compodoc > live-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @compodoc/compodoc > live-server > opn@6.0.0: The package has been renamed to `open`
warning @compodoc/compodoc > @compodoc/ngd-transformer > viz.js@1.8.2: no longer supported
warning @compodoc/compodoc > ts-simple-ast@12.4.0: NOTICE: ts-simple-ast has been renamed to ts-morph and version reset to 1.0.0. Switch at your leisure...
```

best,
hmendezm

**Comment by kylemeenehan** [comment]
It looks like live-server hasn't been updated in 2 years. The simplest fix for that warning for now would be to fork and update live-server. Unless there's a planned change for live reloading in the roadmap @vogloblinsky ?

If the strategy is to fork, update and maintain, there would probably be more of a general uptake if it was housed in a respected organization such as compodoc. @vogloblinsky , let me know if you want to fork and publish as @compodoc/live-server and I can do the update to the dependencies.

Will try look at the other warnings soon.

**Comment by hmendezm** [comment]
Thanks, Kylemeenehan.

**Comment by vogloblinsky** [comment]
I will try to find an updated alternative to live-server
