### ISSUE TITLE
[FEATURE] Custom Menu Items

### ISSUE THREAD

**Issue by MikeMatusz** [compodoc/compodoc#966]
#601 (and #944)

**Comment by alonewarrior** [comment]
This appears to also be related to my desired feature #960 

+1

**Comment by alonewarrior** [comment]
Bump

**Comment by alonewarrior** [comment]
Bump

**Comment by MikeMatusz** [comment]
Bump

**Comment by MikeMatusz** [comment]
.

**Comment by MikeMatusz** [comment]
.

**Comment by MikeMatusz** [comment]
Bumping again.  At some point I wouldn't mind taking as tab at a PR for this at some point in the future, assuming we're still using Compodoc at that time.
