### ISSUE TITLE
[BUG] Left navigation is missing in Internet Explorer 11

### ISSUE THREAD

**Issue by ricardosaracino** [compodoc/compodoc#988]
##### **Overview of the issue**

JS Error running demo in IE, this problem also exists in my deployment

![image](https://user-images.githubusercontent.com/759253/92468712-96305500-f1a1-11ea-8b90-681028e73be7.png)

##### **Angular configuration, a `package.json` file in the root folder**

 "dependencies": {
    "@angular/animations": "^10.0.14",
    "@angular/common": "^10.0.14",
    "@angular/compiler": "^10.0.14",
    "@angular/core": "^10.0.14",
    "@angular/forms": "^10.0.14",
    "@angular/localize": "^10.0.14",
    "@angular/platform-browser": "^10.0.14",
    "@angular/platform-browser-dynamic": "^10.0.14",
    "@angular/router": "^10.0.14",
    "@coreui/angular": "^2.9.4",
    "@coreui/coreui": "^2.1.16",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@ngx-loading-bar/core": "^5.1.0",
    "@ngx-loading-bar/http-client": "^5.1.0",
    "@ngx-loading-bar/router": "^5.1.0",
    "class-transformer": "^0.2.3",
    "core-js": "^3.6.4",
    "font-awesome": "^4.7.0",
    "ngx-cookie-service": "^2.2.0",
    "ngx-loading-bar": "0.0.9",
    "ngx-toastr": "^13.0.0",
    "rxjs": "~6.6.2",
    "tslib": "^2.0.1",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.8",
    "@angular/cli": "^10.0.8",
    "@angular/compiler-cli": "^10.0.14",
    "@angular/language-service": "^10.0.14",
    "@compodoc/compodoc": "^1.1.11",
    "@ngx-i18nsupport/ngx-i18nsupport": "^1.1.6",
    "@ngx-i18nsupport/tooling": "^8.0.3",
    "@types/jasmine": "~3.4.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.12.54",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "karma-junit-reporter": "^2.0.1",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "^6.1.3",
    "typescript": "~3.9.7"
  }
##### **Compodoc installed globally or locally ?**
locally

##### **If possible sourcecode of the file where it breaks**

_**menu-wc.js (4,40)**_

```js
customElements.define('compodoc-menu', class extends HTMLElement {
    constructor() {
        super();
        this.isNormalMode = this.getAttribute('mode') === 'normal';
    }

    connectedCallback() {
        this.render(this.isNormalMode);
    }
```

##### **Motivation for or Use Case**

I realize IE is a relic, but Angular does support it and i feel like you should as well

##### **Reproduce the error**

the bug exists on the Demo site provided by Compodoc

https://compodoc.github.io/compodoc-demo-todomvc-angular/

**Comment by vogloblinsky** [comment]
Fixed in https://github.com/compodoc/compodoc/commit/8c509f0c130fb7cfc63f470a16e2fce73ddca092
Coming soon in next release.
