### ISSUE TITLE
[BUG] TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by AnggaraAng** [compodoc/compodoc#990]
[10:30:20] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sinta-frontend@1.5.2 compodoc: `npx compodoc -p tsconfig.json -w -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sinta-frontend@1.5.2 compodoc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Anggi Anggara CTI\AppData\Roaming\npm-cache\_logs\2020-10-02T03_30_20_990Z-debug.log

**Comment by vogloblinsky** [comment]
Could you give us in which file Compodoc breaks ?

**Comment by AnggaraAng** [comment]
> Could you give us in which file Compodoc breaks ?

Finally I solved the problem by installing compodoc version 1.1.1. because my corner project is version 6.x.x.
