### ISSUE TITLE
Height too small for the generated graph for a grand size project, also zoom +- has limitations.

### ISSUE THREAD

**Issue by dssagar93** [compodoc/compodoc#999]
Overview of the issue : Graph generated is extremely small and can't zoom in to the top level node.
Operating System, Node.js, npm, compodoc version(s) - Windows 10, Node - 12.18.3, NPM - 6.14.6, Compodoc - 1.1.11
Angular configuration, a package.json file in the root folder
Compodoc installed globally or locally ? - locally
If possible sourcecode of the file where it breaks
If possible your terminal logs before the error
Motivation for or Use Case
Reproduce the error - Can only be reproduced where the project size is extremely large.
Related issues
Suggest a Fix  -A temporary fix  that I did was to increase the scale from (1,1) to (5,5). Not sure if it's the right way but it did work temporarily with zoom restrictions.

**Comment by AlvaroP95** [comment]
same here! i cannot see anything, impossible to distinguish letters, classes, modules, etc

**Comment by andreasciamanna** [comment]
Please reopen it.

#234 won't fix this problem.

Compodoc generates a `div.module-graph-svg` 250px high: it's pretty much unusable.
